import { useState } from "react";
import { CheckCircle2, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { acknowledgeFactoryCustomerSuccess, approveFactoryCustomerSuccess, createFactoryCustomerSuccess, handoffFactoryCustomerSuccess, listFactoryCustomerSuccess, reviewFactoryCustomerSuccess, type FactoryCustomerSuccessHandoff, type FactoryCustomerSuccessReview } from "@/lib/factory-customer-success-api";
import type { FactoryCustomerAsset } from "@/lib/factory-customer-asset-api";

export function CustomerSuccessGovernance({ projectId, assets }: { projectId: number; assets: FactoryCustomerAsset[] }) {
  const [reviews, setReviews] = useState<FactoryCustomerSuccessReview[]>([]); const [handoffs, setHandoffs] = useState<FactoryCustomerSuccessHandoff[]>([]); const [summary, setSummary] = useState("服务结果、保修窗口和下一步续费价值已核验，建议进入续费经营。"); const [reference, setReference] = useState("CS-REVIEW-001"); const [note, setNote] = useState("跨角色复核：资产来源、服务证据和客户价值判断一致。");
  const replace = (item: FactoryCustomerSuccessReview) => setReviews((rows) => rows.map((row) => row.id === item.id ? item : row));
  const load = async () => { try { const data = await listFactoryCustomerSuccess(projectId); setReviews(data.reviews); setHandoffs(data.handoffs); } catch (error) { toast.error(error instanceof Error ? error.message : "客户成功工作台载入失败"); } };
  const create = async (assetId: string) => { try { const item = await createFactoryCustomerSuccess(projectId, { asset_id: assetId, success_summary: summary }); setReviews((rows) => [item, ...rows]); toast.success("成功复核草稿已从受控资产快照创建"); } catch (error) { toast.error(error instanceof Error ? error.message : "创建失败"); } };
  const advance = async (item: FactoryCustomerSuccessReview) => { try { if (item.lifecycle_status === "draft") replace(await reviewFactoryCustomerSuccess(projectId, item.id, { expected_revision: item.revision, reference, note })); else if (item.lifecycle_status === "reviewed") replace(await approveFactoryCustomerSuccess(projectId, item.id, { expected_revision: item.revision, reference, note })); else if (item.lifecycle_status === "approved") { const data = await handoffFactoryCustomerSuccess(projectId, item.id, { expected_revision: item.revision, release_reference: reference }); replace(data.review); setHandoffs((rows) => [data.handoff, ...rows]); } } catch (error) { toast.error(error instanceof Error ? error.message : "推进失败，请刷新后重试"); await load(); } };
  const acknowledge = async (item: FactoryCustomerSuccessHandoff) => { try { const value = await acknowledgeFactoryCustomerSuccess(projectId, item.id, { expected_revision: item.revision, receipt_reference: reference }); setHandoffs((rows) => rows.map((row) => row.id === item.id ? value : row)); } catch (error) { toast.error(error instanceof Error ? error.message : "签收失败"); } };
  return <section className="space-y-3" data-customer-success-page><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-base font-bold"><ShieldCheck className="h-4 w-4" />客户成功复核与续费交接</h2><Button size="sm" variant="outline" onClick={() => void load()}><RefreshCw className="mr-1 h-4 w-4" />载入复核</Button></div><Card><CardContent className="grid gap-2 pt-6 md:grid-cols-3"><Input aria-label="客户成功摘要" value={summary} onChange={(e) => setSummary(e.target.value)} /><Input aria-label="客户成功证据编号" value={reference} onChange={(e) => setReference(e.target.value)} /><Input aria-label="客户成功复核说明" value={note} onChange={(e) => setNote(e.target.value)} /></CardContent></Card><div className="grid gap-3 xl:grid-cols-2">{assets.filter((asset) => asset.status === "active" && asset.renewal_status === "action-required").map((asset) => <Card key={asset.id}><CardHeader className="pb-2"><CardTitle className="text-sm">{asset.asset_number} · {asset.serial_number}</CardTitle></CardHeader><CardContent><Button data-customer-success-create size="sm" onClick={() => void create(asset.id)}>创建成功复核</Button></CardContent></Card>)}</div><div className="grid gap-3 xl:grid-cols-2">{reviews.map((item) => <Card key={item.id} data-customer-success-review={item.id} data-success-status={item.lifecycle_status}><CardHeader className="pb-2"><CardTitle className="flex justify-between gap-2 text-sm"><span>{item.review_number} · {item.asset_number}</span><Badge>{item.lifecycle_status}</Badge></CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p>健康分 {item.health_score} · 风险 {item.risk_level}</p><p>{item.success_summary}</p>{item.lifecycle_status !== "handed-off" ? <Button data-customer-success-advance={item.lifecycle_status} size="sm" onClick={() => void advance(item)}>{item.lifecycle_status === "approved" ? <Send className="mr-1 h-4 w-4" /> : <CheckCircle2 className="mr-1 h-4 w-4" />}{item.lifecycle_status === "draft" ? "独立复核" : item.lifecycle_status === "reviewed" ? "独立批准" : "交接续费经营"}</Button> : null}</CardContent></Card>)}</div><div className="grid gap-3 xl:grid-cols-2">{handoffs.map((item) => <Card key={item.id} data-customer-success-handoff={item.id}><CardContent className="flex items-center justify-between gap-2 pt-6 text-sm"><span>{item.handoff_number} · {item.status}</span>{item.status === "pending" ? <Button data-customer-success-acknowledge size="sm" variant="outline" onClick={() => void acknowledge(item)}>独立签收</Button> : <span className="text-emerald-600">已签收</span>}</CardContent></Card>)}</div></section>;
}
