"""Tenant-authorized immutable CDP data-product APIs."""
from core.database import get_db
from dependencies.auth import get_current_user
from fastapi import APIRouter,Depends,HTTPException,Request
from pydantic import BaseModel,Field
from schemas.auth import UserResponse
from services.audit import record_audit_event
from services.factory_cdp import FactoryCdpService
from services.tenant_access import require_project_access,require_project_permission
from sqlalchemy.ext.asyncio import AsyncSession
router=APIRouter(prefix="/api/v1/factory-platform/projects/{project_id}/cdp",tags=["factory-platform-cdp"])
CREATE="factory.portrait.cdp.create";APPROVE="factory.portrait.cdp.approve";PUBLISH="factory.portrait.cdp.publish";ACK="factory.portrait.cdp.acknowledge"
class Create(BaseModel):product_key:str=Field(min_length=1,max_length=96);profile_version_id:str=Field(min_length=1,max_length=100);timeline_version_id:str=Field(min_length=1,max_length=100);segment_version_id:str=Field(min_length=1,max_length=100)
class Revision(BaseModel):expected_revision:int=Field(gt=0);reference:str=Field(min_length=1,max_length=255)
class Publish(Revision):consumers:list[str]=Field(min_length=1,max_length=4)
async def run(db,r,u,p,permission,action,target,method,context=False,**kwargs):
 resolved=await require_project_permission(db,current_user=u,project_id=p,permission=permission)
 try:result=await method(project_id=p,actor=u.id,**({"context":resolved.context} if context else {}),**kwargs)
 except KeyError as e:raise HTTPException(404,detail=str(e)) from e
 except ValueError as e:raise HTTPException(409,detail=str(e)) from e
 item=result.get("product",result) if isinstance(result,dict) else result;record_audit_event(db,action=action,actor_user_id=u.id,project_id=p,target_type=target,target_id=str(item["id"]),ip_address=r.client.host if r.client else None,detail={"revision":item.get("revision"),"status":item.get("status")});await db.commit();return result
@router.get("")
async def workspace(project_id:int,current_user:UserResponse=Depends(get_current_user),db:AsyncSession=Depends(get_db)):
 await require_project_access(db,current_user=current_user,project_id=project_id);return await FactoryCdpService(db).list_workspace(project_id=project_id)
@router.post("/products")
async def create(project_id:int,payload:Create,request:Request,current_user:UserResponse=Depends(get_current_user),db:AsyncSession=Depends(get_db)):
 return await run(db,request,current_user,project_id,CREATE,"factory_cdp_product_created","cdp-data-product",FactoryCdpService(db).create_product,True,**payload.model_dump())
@router.post("/products/{product_id}/approve")
async def approve(project_id:int,product_id:str,payload:Revision,request:Request,current_user:UserResponse=Depends(get_current_user),db:AsyncSession=Depends(get_db)):
 return await run(db,request,current_user,project_id,APPROVE,"factory_cdp_product_approved","cdp-data-product",FactoryCdpService(db).approve_product,product_id=product_id,**payload.model_dump())
@router.post("/products/{product_id}/publish")
async def publish(project_id:int,product_id:str,payload:Publish,request:Request,current_user:UserResponse=Depends(get_current_user),db:AsyncSession=Depends(get_db)):
 # `reference` is accepted uniformly by the revision payload used in the
 # shared action UI, but publication evidence is generated by the immutable
 # product/publication events themselves and the service intentionally has no
 # mutable release-reference field.
 return await run(db,request,current_user,project_id,PUBLISH,"factory_cdp_product_released","cdp-data-product",FactoryCdpService(db).publish_product,True,product_id=product_id,**payload.model_dump(exclude={"reference"}))
@router.post("/publications/{publication_id}/acknowledge")
async def acknowledge(project_id:int,publication_id:str,payload:Revision,request:Request,current_user:UserResponse=Depends(get_current_user),db:AsyncSession=Depends(get_db)):
 return await run(db,request,current_user,project_id,ACK,"factory_cdp_publication_acknowledged","cdp-publication",FactoryCdpService(db).acknowledge_publication,publication_id=publication_id,**payload.model_dump())
