"""Consent-bound dynamic segments with immutable activations."""
from __future__ import annotations
from datetime import datetime,timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_customer_timeline import FactoryCustomerTimeline,FactoryCustomerTimelineEvent,FactoryCustomerTimelineVersion
from models.factory_identity_resolution import FactoryIdentityConsent,FactoryIdentitySignal
from models.factory_segments_consent import FactoryAudienceActivation,FactoryAudienceEvidence,FactoryAudienceMembership,FactoryAudienceSegment,FactoryAudienceSegmentRule,FactoryAudienceSegmentVersion
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
CONSUMERS={"crm","marketing","ads","service"};SOURCE_TYPES={"marketing-touchpoint","inquiry-flow","cpq-quote","fulfillment-order","service-ticket"}
SEGMENT=("id","segment_number","segment_code","segment_name","business_purpose","allowed_channels_json","status","authored_by","published_by","revision");RULE=("id","rule_number","segment_id","segment_number","rule_code","rule_name","minimum_high_intent_events","required_source_types_json","required_consent_purposes_json","definition_hash","status","authored_by","approved_by","revision");MEMBER=("id","membership_number","segment_id","segment_number","rule_id","rule_number","rule_definition_hash","account_reference","contact_signal_id","contact_signal_number","contact_hash","contact_hint","contact_revision","contact_fingerprint","consent_id","consent_number","consent_revision","consent_event_hash","consent_expires_at","timeline_version_id","timeline_version_reference","timeline_manifest_hash","high_intent_event_count","source_types_json","status","evaluated_by","verified_by","revision");VERSION=("id","version_reference","segment_id","segment_number","version_number","manifest_hash","member_count","status","published_by");ACTIVATION=("id","activation_number","segment_id","version_id","version_reference","consumer","manifest_hash","delivery_reference","consumer_mutated","status","created_by","acknowledged_by","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _number(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _context(c,pid):return {"project_id":pid,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{pid}"}
def _same(x):return {k:getattr(x,k) for k in ("project_id","agent_path","tenant_id","client_id","plan_id")}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _serialize(x,f):return {k:getattr(x,k) for k in f}
def _aware(x):return x if x.tzinfo else x.replace(tzinfo=timezone.utc)
class FactorySegmentsConsentService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  segments=await rows(FactoryAudienceSegment,FactoryAudienceSegment.created_at);rules=await rows(FactoryAudienceSegmentRule,FactoryAudienceSegmentRule.created_at);members=await rows(FactoryAudienceMembership,FactoryAudienceMembership.created_at);versions=await rows(FactoryAudienceSegmentVersion,FactoryAudienceSegmentVersion.published_at);activations=await rows(FactoryAudienceActivation,FactoryAudienceActivation.created_at);evidence=await rows(FactoryAudienceEvidence,FactoryAudienceEvidence.recorded_at);verified=[x for x in members if x.status=="verified"];ack=[x for x in activations if x.status=="acknowledged"]
  return {"segments":[_serialize(x,SEGMENT) for x in segments],"rules":[_serialize(x,RULE) for x in rules],"memberships":[_serialize(x,MEMBER) for x in members],"versions":[_serialize(x,VERSION) for x in versions],"activations":[_serialize(x,ACTIVATION) for x in activations],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._source_options(project_id),"metrics":{"active_segments":len([x for x in segments if x.status=="published"]),"verified_members":len(verified),"consent_eligible_percent":round(len(verified)*100/max(1,len(members)),2),"high_intent_members":len([x for x in verified if x.high_intent_event_count>0]),"published_versions":len(versions),"activation_acknowledgement_percent":round(len(ack)*100/max(1,len(activations)),2)},"contract":{"source_records_copied":False,"raw_identifier_stored":False,"active_consent_required":True,"consent_revocation_excludes_membership":True,"timeline_version_pinned":True,"rule_definition_pinned":True,"ai_autonomous_segmentation":False,"membership_self_verification":False,"segment_author_self_publish":False,"published_versions_mutable":False,"consumer_system_mutated":False,"acknowledgement_required":True}}
 async def create_segment(self,*,project_id:int,context:TenantContext,actor:str,segment_code:str,segment_name:str,business_purpose:str,allowed_channels:list[str]):
  channels=sorted(set(allowed_channels))
  if not segment_code.strip() or not segment_name.strip() or not business_purpose.strip() or not channels or any(x not in CONSUMERS for x in channels):raise ValueError("Segment requires code, name, purpose and supported channels")
  now=datetime.now(timezone.utc);x=FactoryAudienceSegment(id=_id("segment"),**_context(context,project_id),segment_number=_number("SEG",project_id),segment_code=segment_code.strip()[:64],segment_name=segment_name.strip()[:180],business_purpose=business_purpose.strip()[:255],allowed_channels_json=channels,status="draft",authored_by=str(actor),revision=1,created_at=now,updated_at=now);self.db.add(x);await self._event(x,"segment","segment-created",segment_code,"Created governed purpose-bound segment",actor);await self.db.flush();return _serialize(x,SEGMENT)
 async def create_rule(self,segment_id:str,*,project_id:int,context:TenantContext,actor:str,rule_code:str,rule_name:str,minimum_high_intent_events:int,required_source_types:list[str],required_consent_purposes:list[str]):
  segment=await self._get(FactoryAudienceSegment,segment_id,project_id,"Audience segment");sources=sorted(set(required_source_types));purposes=sorted(set(required_consent_purposes));definition={"minimum_high_intent_events":minimum_high_intent_events,"required_source_types":sources,"required_consent_purposes":purposes}
  if segment.status!="draft" or not rule_code.strip() or not rule_name.strip() or minimum_high_intent_events<0 or not sources or any(x not in SOURCE_TYPES for x in sources) or not purposes:raise ValueError("Segment rule requires valid intent threshold, source types and consent purposes")
  now=datetime.now(timezone.utc);x=FactoryAudienceSegmentRule(id=_id("segment-rule"),**_context(context,project_id),rule_number=_number("SGR",project_id),segment_id=segment.id,segment_number=segment.segment_number,rule_code=rule_code.strip()[:64],rule_name=rule_name.strip()[:180],minimum_high_intent_events=minimum_high_intent_events,required_source_types_json=sources,required_consent_purposes_json=purposes,definition_hash=_hash(definition),status="draft",authored_by=str(actor),revision=1,created_at=now);self.db.add(x);await self._event(x,"rule","rule-created",rule_code,"Pinned explicit deterministic segment rule",actor);await self.db.flush();return _serialize(x,RULE)
 async def approve_rule(self,rule_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAudienceSegmentRule,rule_id,project_id,"Segment rule");self._revision(x,expected_revision)
  if x.status!="draft" or x.authored_by==str(actor) or not reference.strip() or x.definition_hash!=_hash(self._rule_definition(x)):raise ValueError("Rule requires independent approval and stable definition")
  x.status="approved";x.approved_by=str(actor);x.approved_at=datetime.now(timezone.utc);x.approval_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"rule","rule-approved",reference,"Independently approved deterministic segment rule",actor);await self.db.flush();return _serialize(x,RULE)
 async def evaluate_membership(self,segment_id:str,*,project_id:int,context:TenantContext,actor:str,rule_id:str,contact_signal_id:str):
  segment=await self._get(FactoryAudienceSegment,segment_id,project_id,"Audience segment");rule=await self._get(FactoryAudienceSegmentRule,rule_id,project_id,"Segment rule");candidate=await self._candidate(contact_signal_id,project_id)
  if segment.status!="draft" or rule.segment_id!=segment.id or rule.status!="approved":raise ValueError("Membership requires approved rule in draft segment")
  purposes=set(candidate["consent_purposes"]);source_types=set(candidate["source_types"]);passed=candidate["high_intent_event_count"]>=rule.minimum_high_intent_events and set(rule.required_source_types_json)<=source_types and set(rule.required_consent_purposes_json)<=purposes
  if not passed:raise ValueError("Candidate does not satisfy intent, source or consent rule")
  evaluation={"intent":candidate["high_intent_event_count"],"source_types":sorted(source_types),"consent_purposes":sorted(purposes),"passed":True};now=datetime.now(timezone.utc);x=FactoryAudienceMembership(id=_id("membership"),**_context(context,project_id),membership_number=_number("SGM",project_id),segment_id=segment.id,segment_number=segment.segment_number,rule_id=rule.id,rule_number=rule.rule_number,rule_definition_hash=rule.definition_hash,account_reference=candidate["account_reference"],contact_signal_id=candidate["contact_signal_id"],contact_signal_number=candidate["contact_signal_number"],contact_hash=candidate["contact_hash"],contact_hint=candidate["contact_hint"],contact_revision=candidate["contact_revision"],contact_fingerprint=candidate["contact_fingerprint"],consent_id=candidate["consent_id"],consent_number=candidate["consent_number"],consent_revision=candidate["consent_revision"],consent_event_hash=candidate["consent_event_hash"],consent_expires_at=candidate["consent_expires_at"],timeline_version_id=candidate["timeline_version_id"],timeline_version_reference=candidate["timeline_version_reference"],timeline_manifest_hash=candidate["timeline_manifest_hash"],high_intent_event_count=candidate["high_intent_event_count"],source_types_json=sorted(source_types),evaluation_json=evaluation,status="pending",evaluated_by=str(actor),revision=1,created_at=now);self.db.add(x);await self._event(x,"membership","membership-evaluated",rule.rule_number,"Evaluated consent-bound hashed contact without raw identifier",actor);await self.db.flush();return _serialize(x,MEMBER)
 async def verify_membership(self,membership_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAudienceMembership,membership_id,project_id,"Audience membership");self._revision(x,expected_revision)
  if x.status!="pending" or x.evaluated_by==str(actor) or not reference.strip():raise ValueError("Membership requires independent verification evidence")
  await self._validate_member(x);x.status="verified";x.verified_by=str(actor);x.verified_at=datetime.now(timezone.utc);x.verification_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"membership","membership-verified",reference,"Independently verified consent, timeline and rule",actor);await self.db.flush();return _serialize(x,MEMBER)
 async def publish_segment(self,segment_id:str,*,project_id:int,context:TenantContext,actor:str,expected_revision:int,consumers:list[str],delivery_reference_prefix:str):
  segment=await self._get(FactoryAudienceSegment,segment_id,project_id,"Audience segment");self._revision(segment,expected_revision);requested=sorted(set(consumers));members=(await self.db.execute(select(FactoryAudienceMembership).where(FactoryAudienceMembership.segment_id==segment.id))).scalars().all();rules=(await self.db.execute(select(FactoryAudienceSegmentRule).where(FactoryAudienceSegmentRule.segment_id==segment.id))).scalars().all()
  if segment.status!="draft" or segment.authored_by==str(actor) or not requested or any(x not in segment.allowed_channels_json for x in requested) or not delivery_reference_prefix.strip():raise ValueError("Segment requires independent publisher and purpose-approved channels")
  if not rules or any(x.status!="approved" for x in rules) or not members or any(x.status!="verified" for x in members):raise ValueError("Segment requires approved rules and independently verified members")
  for x in members:await self._validate_member(x)
  manifest={"segment_number":segment.segment_number,"purpose":segment.business_purpose,"channels":segment.allowed_channels_json,"rules":sorted([{"rule_number":x.rule_number,"definition_hash":x.definition_hash} for x in rules],key=lambda x:x["rule_number"]),"members":sorted([{"membership_number":x.membership_number,"account_reference":x.account_reference,"contact_hash":x.contact_hash,"consent_event_hash":x.consent_event_hash,"timeline_manifest_hash":x.timeline_manifest_hash} for x in members],key=lambda x:x["membership_number"])};mh=_hash(manifest);current=await self.db.scalar(select(FactoryAudienceSegmentVersion.version_number).where(FactoryAudienceSegmentVersion.segment_id==segment.id).order_by(FactoryAudienceSegmentVersion.version_number.desc()).limit(1)) or 0;now=datetime.now(timezone.utc);v=FactoryAudienceSegmentVersion(id=_id("segment-version"),**_context(context,project_id),version_reference=_number("SGV",project_id),segment_id=segment.id,segment_number=segment.segment_number,version_number=int(current)+1,manifest_json=manifest,manifest_hash=mh,member_count=len(members),status="published",published_by=str(actor),published_at=now);self.db.add(v);acts=[]
  for consumer in requested:
   a=FactoryAudienceActivation(id=_id("segment-activation"),**_context(context,project_id),activation_number=_number("SGA",project_id),segment_id=segment.id,version_id=v.id,version_reference=v.version_reference,consumer=consumer,manifest_hash=mh,delivery_reference=f"{delivery_reference_prefix.strip()[:180]}:{consumer}",consumer_mutated=False,status="pending",created_by=str(actor),created_at=now,revision=1);self.db.add(a);acts.append(a);await self._event(a,"activation","activation-created",a.delivery_reference,"Created explicit acknowledgement for exact segment hash",actor)
  segment.status="published";segment.published_by=str(actor);segment.published_at=now;segment.revision+=1;segment.updated_at=now;await self._event(segment,"segment","segment-published",v.version_reference,"Published immutable consent-bound segment",actor);await self.db.flush();return {"segment":_serialize(segment,SEGMENT),"version":_serialize(v,VERSION),"activations":[_serialize(x,ACTIVATION) for x in acts]}
 async def acknowledge_activation(self,activation_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAudienceActivation,activation_id,project_id,"Audience activation");self._revision(x,expected_revision)
  if x.status!="pending" or x.created_by==str(actor) or not reference.strip():raise ValueError("Activation acknowledgement must be independent and evidenced")
  v=await self._get(FactoryAudienceSegmentVersion,x.version_id,project_id,"Segment version")
  if v.status!="published" or v.manifest_hash!=x.manifest_hash or _hash(v.manifest_json)!=x.manifest_hash:raise ValueError("Published segment changed")
  x.status="acknowledged";x.acknowledged_by=str(actor);x.acknowledged_at=datetime.now(timezone.utc);x.acknowledgement_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"activation","activation-acknowledged",reference,"Consumer acknowledged exact consent-bound segment hash",actor);await self.db.flush();return _serialize(x,ACTIVATION)
 async def _candidate(self,signal_id,pid):
  s=await self._get(FactoryIdentitySignal,signal_id,pid,"Identity signal");c=await self._get(FactoryIdentityConsent,s.consent_id,pid,"Identity consent")
  if s.status!="verified" or s.signal_type not in {"contact","email","phone"} or c.status!="active" or _aware(c.expires_at)<=datetime.now(timezone.utc) or s.source_revision!=c.revision or s.source_fingerprint!=c.source_event_hash:raise ValueError("Candidate requires verified contact and active pinned consent")
  timeline=await self.db.scalar(select(FactoryCustomerTimeline).where(FactoryCustomerTimeline.project_id==pid,FactoryCustomerTimeline.account_reference==s.account_reference,FactoryCustomerTimeline.status=="published"))
  if not timeline:raise ValueError("Candidate requires published customer timeline")
  v=await self.db.scalar(select(FactoryCustomerTimelineVersion).where(FactoryCustomerTimelineVersion.timeline_id==timeline.id,FactoryCustomerTimelineVersion.status=="published").order_by(FactoryCustomerTimelineVersion.version_number.desc()).limit(1))
  if not v or _hash(v.manifest_json)!=v.manifest_hash:raise ValueError("Customer timeline version is missing or changed")
  types={x.source_type for x in (await self.db.execute(select(FactoryCustomerTimelineEvent).where(FactoryCustomerTimelineEvent.timeline_id==timeline.id,FactoryCustomerTimelineEvent.status=="verified"))).scalars().all()};return {"account_reference":s.account_reference,"contact_signal_id":s.id,"contact_signal_number":s.signal_number,"contact_hash":s.identifier_hash,"contact_hint":s.display_hint,"contact_revision":s.revision,"contact_fingerprint":s.source_fingerprint,"consent_id":c.id,"consent_number":c.consent_number,"consent_revision":c.revision,"consent_event_hash":c.source_event_hash,"consent_expires_at":c.expires_at,"consent_purposes":c.purposes_json,"timeline_version_id":v.id,"timeline_version_reference":v.version_reference,"timeline_manifest_hash":v.manifest_hash,"high_intent_event_count":v.high_intent_event_count,"source_types":sorted(types)}
 async def _source_options(self,pid):
  out=[]
  for s in (await self.db.execute(select(FactoryIdentitySignal).where(FactoryIdentitySignal.project_id==pid,FactoryIdentitySignal.status=="verified"))).scalars().all():
   try:out.append(await self._candidate(s.id,pid))
   except ValueError:pass
  return out
 async def _validate_member(self,x):
  r=await self._get(FactoryAudienceSegmentRule,x.rule_id,x.project_id,"Segment rule");c=await self._candidate(x.contact_signal_id,x.project_id)
  if r.status!="approved" or r.definition_hash!=x.rule_definition_hash or r.definition_hash!=_hash(self._rule_definition(r)) or c["contact_signal_number"]!=x.contact_signal_number or c["contact_hash"]!=x.contact_hash or c["contact_revision"]!=x.contact_revision or c["contact_fingerprint"]!=x.contact_fingerprint or c["consent_id"]!=x.consent_id or c["consent_revision"]!=x.consent_revision or c["consent_event_hash"]!=x.consent_event_hash or c["timeline_version_id"]!=x.timeline_version_id or c["timeline_manifest_hash"]!=x.timeline_manifest_hash:raise ValueError("Segment membership consent, rule or timeline source drifted")
  if x.high_intent_event_count<r.minimum_high_intent_events or not set(r.required_source_types_json)<=set(c["source_types"]) or not set(r.required_consent_purposes_json)<=set(c["consent_purposes"]):raise ValueError("Segment membership no longer satisfies rule")
 @staticmethod
 def _rule_definition(x):return {"minimum_high_intent_events":x.minimum_high_intent_events,"required_source_types":x.required_source_types_json,"required_consent_purposes":x.required_consent_purposes_json}
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _revision(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("segment_number","rule_number","membership_number","version_reference","activation_number") if getattr(x,z,None)),str(x.id));self.db.add(FactoryAudienceEvidence(id=_id("audience-evidence"),**_same(x),evidence_number=_number("SGX",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc)))
