"""Governed RFQ requirements, sampling cost and customer feedback."""
from datetime import date,datetime,timezone
from decimal import Decimal
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_revenue import FactoryRevenueFlowRun
from models.factory_rfq_sample import FactoryRfqCase,FactoryRfqEvidence,FactoryRfqRequirement,FactorySampleFeedback,FactorySampleTask
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
STAGES=["product-selected","inquiry-created","qualified-inquiry","quote-submitted","quote-accepted","order-confirmed","invoice-issued","payment-received"];OUTCOMES={"accepted","revise","rejected"};CASE=("id","rfq_number","source_flow_id","source_correlation_id","source_revision","source_stage","source_fingerprint","account_reference_hash","product_reference","objective","status","created_by","revision");REQ=("id","requirement_number","case_id","rfq_number","requirement_code","requirement_name","specification","quantity","target_date","critical","status","authored_by","approved_by","approval_reference","revision");SAMPLE=("id","sample_number","case_id","rfq_number","sample_code","requirement_ids_json","quantity","unit_cost","currency","promised_at","status","created_by","approved_by","approval_reference","shipping_reference","dispatched_by","revision");FEEDBACK=("id","feedback_number","case_id","sample_id","sample_number","outcome","quality_score","feedback_note","conversion_intent","feedback_hash","status","recorded_by","acknowledged_by","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _num(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _ctx(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _same(x):return {k:getattr(x,k) for k in ("project_id","agent_path","tenant_id","client_id","plan_id")}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _ser(x,f):
 d={k:getattr(x,k) for k in f}
 for k,v in list(d.items()):
  if isinstance(v,Decimal):d[k]=str(v)
 return d
class FactoryRfqSampleService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  cases=await rows(FactoryRfqCase,FactoryRfqCase.created_at);reqs=await rows(FactoryRfqRequirement,FactoryRfqRequirement.created_at);samples=await rows(FactorySampleTask,FactorySampleTask.created_at);feedback=await rows(FactorySampleFeedback,FactorySampleFeedback.recorded_at);evidence=await rows(FactoryRfqEvidence,FactoryRfqEvidence.recorded_at);approved=[x for x in reqs if x.status=="approved"];acks=[x for x in feedback if x.status=="acknowledged"]
  return {"cases":[_ser(x,CASE) for x in cases],"requirements":[_ser(x,REQ) for x in reqs],"samples":[_ser(x,SAMPLE) for x in samples],"feedback":[_ser(x,FEEDBACK) for x in feedback],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._sources(project_id),"metrics":{"rfq_cases":len(cases),"requirement_review_percent":round(len(approved)*100/max(1,len(reqs)),2),"approved_samples":len([x for x in samples if x.status in {"approved","dispatched","received"}]),"dispatched_samples":len([x for x in samples if x.status in {"dispatched","received"}]),"accepted_feedback":len([x for x in feedback if x.outcome=="accepted" and x.status=="acknowledged"]),"feedback_acknowledgement_percent":round(len(acks)*100/max(1,len(feedback)),2)},"contract":{"source_records_copied":False,"inquiry_source_pinned":True,"authoritative_source_revalidated":True,"requirement_self_approval":False,"sample_self_approval":False,"sample_cost_posts_finance":False,"feedback_mutates_order":False,"raw_customer_identifier_stored":False,"customer_feedback_acknowledgement_required":True}}
 async def create_case(self,*,project_id:int,context:TenantContext,actor:str,source_flow_id:str,objective:str):
  flow,snap=await self._source(source_flow_id,project_id)
  if not objective.strip():raise ValueError("RFQ objective is required")
  now=datetime.now(timezone.utc);x=FactoryRfqCase(id=_id("rfq-case"),**_ctx(context,project_id),rfq_number=_num("RFQ",project_id),source_flow_id=flow.id,source_correlation_id=flow.correlation_id,source_revision=flow.revision,source_stage=flow.current_stage,source_snapshot_json=snap,source_fingerprint=_hash(snap),account_reference_hash=_hash(flow.account_reference),product_reference=flow.product_reference,objective=objective.strip()[:255],status="clarifying",created_by=str(actor),created_at=now,updated_at=now,revision=1);self.db.add(x);await self._event(x,"rfq","rfq-created",flow.correlation_id,"Pinned authoritative inquiry flow without copying or mutating it",actor);await self.db.flush();return _ser(x,CASE)
 async def add_requirement(self,case_id:str,*,project_id:int,context:TenantContext,actor:str,requirement_code:str,requirement_name:str,specification:str,quantity:int,target_date:date,critical:bool):
  case=await self._get(FactoryRfqCase,case_id,project_id,"RFQ case");await self._validate_case(case)
  if case.status!="clarifying" or not requirement_code.strip() or not requirement_name.strip() or not specification.strip() or int(quantity)<=0 or target_date<date.today():raise ValueError("RFQ requirement requires future target, specification and positive quantity")
  x=FactoryRfqRequirement(id=_id("rfq-requirement"),**_ctx(context,project_id),requirement_number=_num("RQR",project_id),case_id=case.id,rfq_number=case.rfq_number,requirement_code=requirement_code.strip()[:64],requirement_name=requirement_name.strip()[:180],specification=specification.strip(),quantity=int(quantity),target_date=target_date,critical=critical,status="pending-review",authored_by=str(actor),revision=1,created_at=datetime.now(timezone.utc));self.db.add(x);await self._event(x,"requirement","requirement-authored",requirement_code,"Submitted technical requirement for independent review",actor);await self.db.flush();return _ser(x,REQ)
 async def approve_requirement(self,requirement_id:str,*,project_id:int,actor:str,expected_revision:int,approval_reference:str):
  x=await self._get(FactoryRfqRequirement,requirement_id,project_id,"RFQ requirement");self._rev(x,expected_revision);case=await self._get(FactoryRfqCase,x.case_id,project_id,"RFQ case");await self._validate_case(case)
  if x.status!="pending-review" or x.authored_by==str(actor) or not approval_reference.strip():raise ValueError("RFQ requirement requires independent technical approval")
  x.status="approved";x.approved_by=str(actor);x.approved_at=datetime.now(timezone.utc);x.approval_reference=approval_reference.strip()[:255];x.revision+=1;await self._event(x,"requirement","requirement-approved",approval_reference,"Independently approved requirement scope",actor);await self.db.flush();return _ser(x,REQ)
 async def create_sample(self,case_id:str,*,project_id:int,context:TenantContext,actor:str,sample_code:str,requirement_ids:list[str],quantity:int,unit_cost:Decimal,currency:str,promised_at:datetime):
  case=await self._get(FactoryRfqCase,case_id,project_id,"RFQ case");await self._validate_case(case);reqs=(await self.db.execute(select(FactoryRfqRequirement).where(FactoryRfqRequirement.case_id==case.id))).scalars().all();selected=set(requirement_ids)
  if not sample_code.strip() or not reqs or any(x.status!="approved" for x in reqs) or selected!={x.id for x in reqs} or int(quantity)<=0 or Decimal(unit_cost)<0 or not currency.strip() or promised_at<=datetime.now(timezone.utc):raise ValueError("Sample requires all approved requirements, cost, quantity and future promise")
  now=datetime.now(timezone.utc);x=FactorySampleTask(id=_id("sample-task"),**_ctx(context,project_id),sample_number=_num("SMP",project_id),case_id=case.id,rfq_number=case.rfq_number,sample_code=sample_code.strip()[:64],requirement_ids_json=sorted(selected),quantity=int(quantity),unit_cost=Decimal(unit_cost),currency=currency.upper()[:8],promised_at=promised_at,status="pending-approval",created_by=str(actor),revision=1,created_at=now);self.db.add(x);case.status="sample-planned";case.updated_at=now;case.revision+=1;await self._event(x,"sample","sample-created",sample_code,"Planned traceable sample and management cost only",actor);await self.db.flush();return _ser(x,SAMPLE)
 async def approve_sample(self,sample_id:str,*,project_id:int,actor:str,expected_revision:int,approval_reference:str):
  x=await self._get(FactorySampleTask,sample_id,project_id,"Sample task");self._rev(x,expected_revision);case=await self._get(FactoryRfqCase,x.case_id,project_id,"RFQ case");await self._validate_case(case)
  if x.status!="pending-approval" or x.created_by==str(actor) or not approval_reference.strip():raise ValueError("Sample requires independent cost and scope approval")
  x.status="approved";x.approved_by=str(actor);x.approval_reference=approval_reference.strip()[:255];x.revision+=1;await self._event(x,"sample","sample-approved",approval_reference,"Independently approved sample scope and management cost",actor);await self.db.flush();return _ser(x,SAMPLE)
 async def dispatch_sample(self,sample_id:str,*,project_id:int,actor:str,expected_revision:int,shipping_reference:str):
  x=await self._get(FactorySampleTask,sample_id,project_id,"Sample task");self._rev(x,expected_revision);case=await self._get(FactoryRfqCase,x.case_id,project_id,"RFQ case");await self._validate_case(case)
  if x.status!="approved" or not shipping_reference.strip():raise ValueError("Approved sample and shipping evidence are required")
  x.status="dispatched";x.shipping_reference=shipping_reference.strip()[:255];x.dispatched_by=str(actor);x.dispatched_at=datetime.now(timezone.utc);x.revision+=1;case.status="sample-dispatched";case.updated_at=datetime.now(timezone.utc);case.revision+=1;await self._event(x,"sample","sample-dispatched",shipping_reference,"Recorded shipment reference without mutating logistics",actor);await self.db.flush();return _ser(x,SAMPLE)
 async def record_feedback(self,sample_id:str,*,project_id:int,context:TenantContext,actor:str,outcome:str,quality_score:int,feedback_note:str,conversion_intent:bool):
  x=await self._get(FactorySampleTask,sample_id,project_id,"Sample task");case=await self._get(FactoryRfqCase,x.case_id,project_id,"RFQ case");await self._validate_case(case)
  if x.status!="dispatched" or x.dispatched_by==str(actor) or outcome not in OUTCOMES or not 1<=int(quality_score)<=100 or not feedback_note.strip():raise ValueError("Customer feedback requires dispatched sample, independent actor, outcome and score")
  payload={"sample_number":x.sample_number,"shipping_reference":x.shipping_reference,"outcome":outcome,"quality_score":int(quality_score),"feedback_note":feedback_note.strip(),"conversion_intent":bool(conversion_intent)};now=datetime.now(timezone.utc);f=FactorySampleFeedback(id=_id("sample-feedback"),**_ctx(context,project_id),feedback_number=_num("SMF",project_id),case_id=case.id,sample_id=x.id,sample_number=x.sample_number,outcome=outcome,quality_score=int(quality_score),feedback_note=feedback_note.strip(),conversion_intent=bool(conversion_intent),feedback_hash=_hash(payload),status="pending-acknowledgement",recorded_by=str(actor),recorded_at=now,revision=1);self.db.add(f);x.status="received";x.received_at=now;x.revision+=1;case.status="feedback-pending";case.updated_at=now;case.revision+=1;await self._event(f,"feedback","feedback-recorded",f.feedback_hash,"Customer recorded immutable sample feedback",actor);await self.db.flush();return _ser(f,FEEDBACK)
 async def acknowledge_feedback(self,feedback_id:str,*,project_id:int,actor:str,expected_revision:int,acknowledgement_reference:str):
  f=await self._get(FactorySampleFeedback,feedback_id,project_id,"Sample feedback");self._rev(f,expected_revision);case=await self._get(FactoryRfqCase,f.case_id,project_id,"RFQ case");await self._validate_case(case);sample=await self._get(FactorySampleTask,f.sample_id,project_id,"Sample task");payload={"sample_number":sample.sample_number,"shipping_reference":sample.shipping_reference,"outcome":f.outcome,"quality_score":f.quality_score,"feedback_note":f.feedback_note,"conversion_intent":f.conversion_intent}
  if f.status!="pending-acknowledgement" or f.recorded_by==str(actor) or not acknowledgement_reference.strip() or f.feedback_hash!=_hash(payload):raise ValueError("Sample feedback requires independent acknowledgement of unchanged evidence")
  f.status="acknowledged";f.acknowledged_by=str(actor);f.acknowledged_at=datetime.now(timezone.utc);f.acknowledgement_reference=acknowledgement_reference.strip()[:255];f.revision+=1;case.status="sample-accepted" if f.outcome=="accepted" else "sample-revision" if f.outcome=="revise" else "sample-rejected";case.updated_at=datetime.now(timezone.utc);case.revision+=1;await self._event(f,"feedback","feedback-acknowledged",acknowledgement_reference,"Sales acknowledged customer feedback without order mutation",actor);await self.db.flush();return _ser(f,FEEDBACK)
 async def _sources(self,pid):
  used=set((await self.db.execute(select(FactoryRfqCase.source_flow_id).where(FactoryRfqCase.project_id==pid))).scalars().all());flows=(await self.db.execute(select(FactoryRevenueFlowRun).where(FactoryRevenueFlowRun.project_id==pid).order_by(FactoryRevenueFlowRun.created_at.desc()))).scalars().all();return [{"source_flow_id":x.id,"correlation_id":x.correlation_id,"product_reference":x.product_reference,"source_stage":x.current_stage,"account_reference_hash":_hash(x.account_reference)} for x in flows if x.id not in used and STAGES.index(x.current_stage)>=STAGES.index("inquiry-created")]
 async def _source(self,i,pid):
  x=await self._get(FactoryRevenueFlowRun,i,pid,"Inquiry flow")
  if x.current_stage not in STAGES or STAGES.index(x.current_stage)<STAGES.index("inquiry-created"):raise ValueError("RFQ requires an authoritative inquiry-stage revenue flow")
  snap={"correlation_id":x.correlation_id,"product_reference":x.product_reference,"account_reference_hash":_hash(x.account_reference),"currency":x.currency,"quoted_amount":str(x.quoted_amount),"current_stage":x.current_stage,"revision":x.revision};return x,snap
 async def _validate_case(self,case):
  flow,snap=await self._source(case.source_flow_id,case.project_id)
  if case.source_correlation_id!=flow.correlation_id or case.source_revision!=flow.revision or case.source_stage!=flow.current_stage or case.source_snapshot_json!=snap or case.source_fingerprint!=_hash(snap) or case.account_reference_hash!=_hash(flow.account_reference) or case.product_reference!=flow.product_reference:raise ValueError("Authoritative inquiry source changed; RFQ is blocked")
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _rev(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("rfq_number","requirement_number","sample_number","feedback_number") if getattr(x,z,None)),str(x.id));self.db.add(FactoryRfqEvidence(id=_id("rfq-evidence"),**_same(x),evidence_number=_num("RQE",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc)))
