"""Consent-governed opportunity buying committees and influence paths."""
from __future__ import annotations
from datetime import datetime,timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_buying_committee import FactoryBuyingCommittee,FactoryBuyingCommitteeEvidence,FactoryBuyingCommitteeMember,FactoryBuyingCommitteePublication,FactoryBuyingCommitteeVersion,FactoryBuyingInfluenceEdge
from models.factory_cpq import FactoryCpqQuote
from models.factory_icp import FactoryIcpBuyingRole,FactoryIcpProfile,FactoryIcpVersion
from models.factory_identity_resolution import FactoryIdentityConsent,FactoryIdentitySignal
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

CONSUMERS={"crm","sales","marketing","service"};COMMITTEE=("id","committee_number","committee_name","account_reference","opportunity_source_type","opportunity_source_id","opportunity_source_number","opportunity_source_revision","opportunity_source_status","opportunity_fingerprint","icp_profile_id","icp_profile_number","icp_profile_revision","icp_definition_hash","status","authored_by","published_by","revision");MEMBER=("id","member_number","committee_id","committee_number","account_reference","role_id","role_number","role_code","role_name","influence_type","role_fingerprint","contact_signal_id","contact_signal_number","contact_hash","contact_hint","contact_source_revision","contact_source_fingerprint","influence_score","relationship_strength","stance","preferred_channel","evidence_reference","status","created_by","verified_by","revision");EDGE=("id","edge_number","committee_id","committee_number","from_member_id","from_member_number","to_member_id","to_member_number","influence_direction","strength","evidence_reference","endpoint_manifest_hash","status","created_by","verified_by","revision");VERSION=("id","version_reference","committee_id","committee_number","version_number","manifest_json","manifest_hash","required_role_count","member_count","influence_edge_count","status","published_by");PUBLICATION=("id","publication_number","committee_id","version_id","version_reference","consumer","manifest_hash","delivery_reference","consumer_mutated","status","created_by","acknowledged_by","revision")
def _id(kind):return f"{kind}-{secrets.token_urlsafe(18)}"
def _number(prefix,pid):return f"{prefix}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _context(context,pid):return {"project_id":pid,"agent_path":context.agent_path,"tenant_id":context.tenant_id,"client_id":context.client_id,"plan_id":context.plan_id or f"plan-{pid}"}
def _same(x):return {k:getattr(x,k) for k in ("project_id","agent_path","tenant_id","client_id","plan_id")}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _serialize(x,fields):return {k:getattr(x,k) for k in fields}
def _aware(x):return x if x.tzinfo else x.replace(tzinfo=timezone.utc)

class FactoryBuyingCommitteeService:
    def __init__(self,db:AsyncSession):self.db=db
    async def list_workspace(self,*,project_id:int):
        async def rows(model,order):return (await self.db.execute(select(model).where(model.project_id==project_id).order_by(order.desc()).limit(500))).scalars().all()
        committees=await rows(FactoryBuyingCommittee,FactoryBuyingCommittee.created_at);members=await rows(FactoryBuyingCommitteeMember,FactoryBuyingCommitteeMember.created_at);edges=await rows(FactoryBuyingInfluenceEdge,FactoryBuyingInfluenceEdge.created_at);versions=await rows(FactoryBuyingCommitteeVersion,FactoryBuyingCommitteeVersion.published_at);publications=await rows(FactoryBuyingCommitteePublication,FactoryBuyingCommitteePublication.created_at);evidence=await rows(FactoryBuyingCommitteeEvidence,FactoryBuyingCommitteeEvidence.recorded_at);verified=[x for x in members if x.status=="verified"];verified_edges=[x for x in edges if x.status=="verified"];multi=0;coverage=[]
        for committee in committees:
            roles=await self._roles(committee.icp_profile_id);filled={x.role_id for x in verified if x.committee_id==committee.id};coverage.append(len(filled)*100/max(1,len(roles)));multi+=int(len([x for x in verified if x.committee_id==committee.id])>=3)
        ack=[x for x in publications if x.status=="acknowledged"]
        return {"committees":[_serialize(x,COMMITTEE) for x in committees],"members":[_serialize(x,MEMBER) for x in members],"influence_edges":[_serialize(x,EDGE) for x in edges],"versions":[_serialize(x,VERSION) for x in versions],"publications":[_serialize(x,PUBLICATION) for x in publications],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._source_options(project_id),"metrics":{"verified_members":len(verified),"role_coverage_percent":round(max(coverage,default=0),2),"multi_threaded_opportunities":multi,"verified_influence_edges":len(verified_edges),"published_versions":len(versions),"handoff_acknowledgement_percent":round(len(ack)*100/max(1,len(publications)),2)},"contract":{"source_records_copied":False,"consented_contacts_only":True,"opportunity_revision_pinned":True,"icp_role_definition_pinned":True,"member_self_verification":False,"influence_self_verification":False,"incomplete_committee_publishable":False,"committee_author_self_publish":False,"published_versions_mutable":False,"consumer_system_mutated":False,"acknowledgement_required":True}}
    async def create_committee(self,*,project_id:int,context:TenantContext,actor:str,committee_name:str,opportunity_source_id:str,icp_profile_id:str):
        quote,snapshot=await self._opportunity(opportunity_source_id,project_id);profile,version=await self._profile(icp_profile_id,project_id);now=datetime.now(timezone.utc)
        if not committee_name.strip():raise ValueError("Buying committee name is required")
        item=FactoryBuyingCommittee(id=_id("buying-committee"),**_context(context,project_id),committee_number=_number("BCM",project_id),committee_name=committee_name.strip()[:180],account_reference=quote.account_reference[:180],opportunity_source_type="cpq-quote",opportunity_source_id=quote.id,opportunity_source_number=quote.quote_number,opportunity_source_revision=quote.revision,opportunity_source_status=quote.status,opportunity_fingerprint=_hash(snapshot),opportunity_snapshot_json=snapshot,icp_profile_id=profile.id,icp_profile_number=profile.profile_number,icp_profile_revision=profile.revision,icp_definition_hash=version.definition_hash,status="draft",authored_by=str(actor),revision=1,created_at=now,updated_at=now);self.db.add(item);await self._event(item,"committee","committee-created",quote.quote_number,"Pinned opportunity and active ICP role definition",actor);await self.db.flush();return _serialize(item,COMMITTEE)
    async def add_member(self,committee_id:str,*,project_id:int,context:TenantContext,actor:str,role_id:str,contact_signal_id:str,influence_score:float,relationship_strength:str,stance:str,preferred_channel:str,evidence_reference:str):
        committee=await self._get(FactoryBuyingCommittee,committee_id,project_id,"Buying committee");await self._validate_committee_sources(committee);role=await self._get(FactoryIcpBuyingRole,role_id,project_id,"ICP buying role");signal,consent=await self._contact(contact_signal_id,project_id)
        if committee.status!="draft" or role.profile_id!=committee.icp_profile_id or signal.account_reference!=committee.account_reference or not 0<=influence_score<=100 or relationship_strength not in {"weak","medium","strong"} or stance not in {"supportive","neutral","blocking"} or preferred_channel not in {"email","phone","meeting","wechat","whatsapp"} or not evidence_reference.strip():raise ValueError("Committee member requires matching opportunity account, ICP role, consented contact and evidence")
        role_snapshot=self._role_snapshot(role);now=datetime.now(timezone.utc);item=FactoryBuyingCommitteeMember(id=_id("buying-member"),**_context(context,project_id),member_number=_number("BCM-M",project_id),committee_id=committee.id,committee_number=committee.committee_number,account_reference=committee.account_reference,role_id=role.id,role_number=role.role_number,role_code=role.role_code,role_name=role.role_name,influence_type=role.influence_type,role_fingerprint=_hash(role_snapshot),contact_signal_id=signal.id,contact_signal_number=signal.signal_number,contact_hash=signal.identifier_hash,contact_hint=signal.display_hint,contact_source_revision=signal.revision,contact_source_fingerprint=signal.source_fingerprint,influence_score=influence_score,relationship_strength=relationship_strength,stance=stance,preferred_channel=preferred_channel,evidence_reference=evidence_reference.strip()[:255],status="pending",created_by=str(actor),revision=1,created_at=now);self.db.add(item);await self._event(item,"member","member-created",evidence_reference,"Mapped consented contact hash to pinned ICP buying role",actor);await self.db.flush();return _serialize(item,MEMBER)
    async def verify_member(self,member_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
        item=await self._get(FactoryBuyingCommitteeMember,member_id,project_id,"Committee member");self._revision(item,expected_revision)
        if item.status!="pending" or item.created_by==str(actor) or not reference.strip():raise ValueError("Committee member requires independent verification evidence")
        await self._validate_member(item);item.status="verified";item.verified_by=str(actor);item.verified_at=datetime.now(timezone.utc);item.verification_reference=reference.strip()[:255];item.revision+=1;await self._event(item,"member","member-verified",reference,"Independently verified contact consent, role and opportunity account",actor);await self.db.flush();return _serialize(item,MEMBER)
    async def add_influence(self,committee_id:str,*,project_id:int,context:TenantContext,actor:str,from_member_id:str,to_member_id:str,influence_direction:str,strength:str,evidence_reference:str):
        committee=await self._get(FactoryBuyingCommittee,committee_id,project_id,"Buying committee");left=await self._get(FactoryBuyingCommitteeMember,from_member_id,project_id,"From member");right=await self._get(FactoryBuyingCommitteeMember,to_member_id,project_id,"To member")
        if committee.status!="draft" or left.committee_id!=committee.id or right.committee_id!=committee.id or left.id==right.id or left.status!="verified" or right.status!="verified" or influence_direction not in {"influences","approves","advises","blocks"} or strength not in {"weak","medium","strong"} or not evidence_reference.strip():raise ValueError("Influence path requires distinct verified committee members and evidence")
        await self._validate_member(left);await self._validate_member(right);manifest=self._edge_manifest(left,right,influence_direction);now=datetime.now(timezone.utc);item=FactoryBuyingInfluenceEdge(id=_id("buying-influence"),**_context(context,project_id),edge_number=_number("BCE",project_id),committee_id=committee.id,committee_number=committee.committee_number,from_member_id=left.id,from_member_number=left.member_number,to_member_id=right.id,to_member_number=right.member_number,influence_direction=influence_direction,strength=strength,evidence_reference=evidence_reference.strip()[:255],endpoint_manifest_hash=_hash(manifest),status="pending",created_by=str(actor),revision=1,created_at=now);self.db.add(item);await self._event(item,"influence","influence-created",evidence_reference,"Recorded evidenced influence path without mutating contacts",actor);await self.db.flush();return _serialize(item,EDGE)
    async def verify_influence(self,edge_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
        item=await self._get(FactoryBuyingInfluenceEdge,edge_id,project_id,"Influence edge");self._revision(item,expected_revision)
        if item.status!="pending" or item.created_by==str(actor) or not reference.strip():raise ValueError("Influence path requires independent verification evidence")
        left=await self._get(FactoryBuyingCommitteeMember,item.from_member_id,project_id,"From member");right=await self._get(FactoryBuyingCommitteeMember,item.to_member_id,project_id,"To member");await self._validate_member(left);await self._validate_member(right)
        if _hash(self._edge_manifest(left,right,item.influence_direction))!=item.endpoint_manifest_hash:raise ValueError("Influence endpoint manifest drifted")
        item.status="verified";item.verified_by=str(actor);item.verified_at=datetime.now(timezone.utc);item.verification_reference=reference.strip()[:255];item.revision+=1;await self._event(item,"influence","influence-verified",reference,"Independently verified buying influence path",actor);await self.db.flush();return _serialize(item,EDGE)
    async def publish_committee(self,committee_id:str,*,project_id:int,context:TenantContext,actor:str,expected_revision:int,consumers:list[str],delivery_reference_prefix:str):
        committee=await self._get(FactoryBuyingCommittee,committee_id,project_id,"Buying committee");self._revision(committee,expected_revision);requested=sorted(set(consumers))
        if committee.status!="draft" or committee.authored_by==str(actor) or not requested or any(x not in CONSUMERS for x in requested) or not delivery_reference_prefix.strip():raise ValueError("Buying committee requires independent publisher, consumers and delivery reference")
        await self._validate_committee_sources(committee);roles=await self._roles(committee.icp_profile_id);members=(await self.db.execute(select(FactoryBuyingCommitteeMember).where(FactoryBuyingCommitteeMember.committee_id==committee.id))).scalars().all();edges=(await self.db.execute(select(FactoryBuyingInfluenceEdge).where(FactoryBuyingInfluenceEdge.committee_id==committee.id))).scalars().all()
        if len(members)!=len(roles) or {x.role_id for x in members}!={x.id for x in roles} or any(x.status!="verified" for x in members):raise ValueError("All required ICP buying roles must be independently verified")
        if len(edges)<max(1,len(members)-1) or any(x.status!="verified" for x in edges) or {x.id for e in edges for x in members if x.id in {e.from_member_id,e.to_member_id}}!={x.id for x in members}:raise ValueError("Verified influence paths must connect every committee member")
        for member in members:await self._validate_member(member)
        manifest={"committee_number":committee.committee_number,"account_reference":committee.account_reference,"opportunity":{"number":committee.opportunity_source_number,"revision":committee.opportunity_source_revision,"fingerprint":committee.opportunity_fingerprint},"icp":{"profile_number":committee.icp_profile_number,"definition_hash":committee.icp_definition_hash},"members":sorted([{"member_number":x.member_number,"role_code":x.role_code,"contact_hash":x.contact_hash,"influence_score":x.influence_score,"strength":x.relationship_strength,"stance":x.stance,"channel":x.preferred_channel} for x in members],key=lambda x:x["role_code"]),"influence_paths":sorted([{"edge_number":x.edge_number,"from":x.from_member_number,"direction":x.influence_direction,"to":x.to_member_number,"strength":x.strength,"endpoint_manifest_hash":x.endpoint_manifest_hash} for x in edges],key=lambda x:x["edge_number"])};manifest_hash=_hash(manifest);current=await self.db.scalar(select(FactoryBuyingCommitteeVersion.version_number).where(FactoryBuyingCommitteeVersion.committee_id==committee.id).order_by(FactoryBuyingCommitteeVersion.version_number.desc()).limit(1)) or 0;now=datetime.now(timezone.utc);version=FactoryBuyingCommitteeVersion(id=_id("buying-version"),**_context(context,project_id),version_reference=_number("BCV",project_id),committee_id=committee.id,committee_number=committee.committee_number,version_number=int(current)+1,manifest_json=manifest,manifest_hash=manifest_hash,required_role_count=len(roles),member_count=len(members),influence_edge_count=len(edges),status="published",published_by=str(actor),published_at=now);self.db.add(version);publications=[]
        for consumer in requested:
            publication=FactoryBuyingCommitteePublication(id=_id("buying-publication"),**_context(context,project_id),publication_number=_number("BCP",project_id),committee_id=committee.id,version_id=version.id,version_reference=version.version_reference,consumer=consumer,manifest_hash=manifest_hash,delivery_reference=f"{delivery_reference_prefix.strip()[:180]}:{consumer}",consumer_mutated=False,status="pending",created_by=str(actor),created_at=now,revision=1);self.db.add(publication);publications.append(publication);await self._event(publication,"publication","handoff-created",publication.delivery_reference,"Created explicit consumer acknowledgement for exact committee hash",actor)
        committee.status="published";committee.published_by=str(actor);committee.published_at=now;committee.revision+=1;committee.updated_at=now;await self._event(committee,"committee","committee-published",version.version_reference,"Published immutable complete buying committee",actor);await self.db.flush();return {"committee":_serialize(committee,COMMITTEE),"version":_serialize(version,VERSION),"publications":[_serialize(x,PUBLICATION) for x in publications]}
    async def acknowledge_publication(self,publication_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
        item=await self._get(FactoryBuyingCommitteePublication,publication_id,project_id,"Committee publication");self._revision(item,expected_revision)
        if item.status!="pending" or item.created_by==str(actor) or not reference.strip():raise ValueError("Committee handoff acknowledgement must be independent and evidenced")
        version=await self._get(FactoryBuyingCommitteeVersion,item.version_id,project_id,"Committee version")
        if version.status!="published" or version.manifest_hash!=item.manifest_hash or _hash(version.manifest_json)!=item.manifest_hash:raise ValueError("Published buying committee changed")
        item.status="acknowledged";item.acknowledged_by=str(actor);item.acknowledged_at=datetime.now(timezone.utc);item.acknowledgement_reference=reference.strip()[:255];item.revision+=1;await self._event(item,"publication","handoff-acknowledged",reference,"Consumer acknowledged exact immutable committee hash",actor);await self.db.flush();return _serialize(item,PUBLICATION)
    async def _source_options(self,project_id):
        opportunities=[]
        for q in (await self.db.execute(select(FactoryCpqQuote).where(FactoryCpqQuote.project_id==project_id).order_by(FactoryCpqQuote.created_at.desc()))).scalars().all():
            try:_,snap=await self._opportunity(q.id,project_id)
            except ValueError:continue
            opportunities.append({"id":q.id,"number":q.quote_number,"account_reference":q.account_reference,"status":q.status,"revision":q.revision,"fingerprint":_hash(snap)})
        profiles=[]
        for p in (await self.db.execute(select(FactoryIcpProfile).where(FactoryIcpProfile.project_id==project_id,FactoryIcpProfile.status=="active"))).scalars().all():
            try:_,v=await self._profile(p.id,project_id)
            except ValueError:continue
            profiles.append({"id":p.id,"number":p.profile_number,"name":p.profile_name,"revision":p.revision,"definition_hash":v.definition_hash,"roles":[{"id":r.id,"number":r.role_number,"code":r.role_code,"name":r.role_name,"influence_type":r.influence_type,"fingerprint":_hash(self._role_snapshot(r))} for r in await self._roles(p.id)]})
        contacts=[]
        for s in (await self.db.execute(select(FactoryIdentitySignal).where(FactoryIdentitySignal.project_id==project_id,FactoryIdentitySignal.status=="verified"))).scalars().all():
            try:signal,_=await self._contact(s.id,project_id)
            except ValueError:continue
            contacts.append({"id":signal.id,"number":signal.signal_number,"account_reference":signal.account_reference,"signal_type":signal.signal_type,"hint":signal.display_hint,"hash":signal.identifier_hash,"revision":signal.revision})
        return {"opportunities":opportunities,"profiles":profiles,"contacts":contacts}
    async def _opportunity(self,item_id,pid):
        q=await self._get(FactoryCpqQuote,item_id,pid,"CPQ opportunity");snap={"quote_number":q.quote_number,"account_reference":q.account_reference,"currency":q.currency,"subtotal":str(q.subtotal),"status":q.status,"revision":q.revision}
        if q.status in {"rejected","expired","cancelled","void"}:raise ValueError("Inactive CPQ opportunity cannot create buying committee")
        return q,snap
    async def _profile(self,item_id,pid):
        p=await self._get(FactoryIcpProfile,item_id,pid,"ICP profile");v=await self.db.scalar(select(FactoryIcpVersion).where(FactoryIcpVersion.profile_id==p.id,FactoryIcpVersion.version_number==p.current_version,FactoryIcpVersion.status=="active"))
        if p.status!="active" or not v or not await self._roles(p.id):raise ValueError("Buying committee requires active ICP profile, version and roles")
        return p,v
    async def _roles(self,profile_id):return (await self.db.execute(select(FactoryIcpBuyingRole).where(FactoryIcpBuyingRole.profile_id==profile_id).order_by(FactoryIcpBuyingRole.role_code.asc()))).scalars().all()
    @staticmethod
    def _role_snapshot(r):return {"role_number":r.role_number,"role_code":r.role_code,"role_name":r.role_name,"influence_type":r.influence_type,"pains":r.pains_json,"proof_requirements":r.proof_requirements_json,"preferred_channels":r.preferred_channels_json}
    async def _contact(self,item_id,pid):
        s=await self._get(FactoryIdentitySignal,item_id,pid,"Contact signal");c=await self._get(FactoryIdentityConsent,s.consent_id,pid,"Identity consent")
        if s.status!="verified" or s.signal_type not in {"contact","email","phone"} or c.status!="active" or _aware(c.expires_at)<=datetime.now(timezone.utc) or s.source_revision!=c.revision or s.source_fingerprint!=c.source_event_hash:raise ValueError("Buying member requires verified contact and active pinned consent")
        return s,c
    async def _validate_committee_sources(self,c):
        q,snap=await self._opportunity(c.opportunity_source_id,c.project_id);p,v=await self._profile(c.icp_profile_id,c.project_id)
        if c.opportunity_source_number!=q.quote_number or c.opportunity_source_revision!=q.revision or c.opportunity_source_status!=q.status or c.opportunity_fingerprint!=_hash(snap) or c.opportunity_snapshot_json!=snap or c.icp_profile_number!=p.profile_number or c.icp_profile_revision!=p.revision or c.icp_definition_hash!=v.definition_hash:raise ValueError("Buying committee opportunity or ICP definition drifted")
    async def _validate_member(self,m):
        committee=await self._get(FactoryBuyingCommittee,m.committee_id,m.project_id,"Buying committee");await self._validate_committee_sources(committee);role=await self._get(FactoryIcpBuyingRole,m.role_id,m.project_id,"ICP role");signal,_=await self._contact(m.contact_signal_id,m.project_id)
        if role.profile_id!=committee.icp_profile_id or m.role_number!=role.role_number or m.role_fingerprint!=_hash(self._role_snapshot(role)) or signal.account_reference!=committee.account_reference or m.contact_signal_number!=signal.signal_number or m.contact_hash!=signal.identifier_hash or m.contact_source_revision!=signal.revision or m.contact_source_fingerprint!=signal.source_fingerprint:raise ValueError("Buying committee member source or role drifted")
    @staticmethod
    def _edge_manifest(l,r,d):return {"from":{"id":l.id,"revision":l.revision,"role_fingerprint":l.role_fingerprint,"contact_hash":l.contact_hash},"direction":d,"to":{"id":r.id,"revision":r.revision,"role_fingerprint":r.role_fingerprint,"contact_hash":r.contact_hash}}
    async def _get(self,model,item_id,pid,label):
        x=await self.db.scalar(select(model).where(model.id==item_id,model.project_id==pid))
        if not x:raise KeyError(f"{label} not found")
        return x
    @staticmethod
    def _revision(x,e):
        if int(x.revision)!=int(e):raise ValueError("Revision conflict")
    async def _event(self,x,subject_type,evidence_type,reference,note,actor):
        number=next((getattr(x,k,None) for k in ("committee_number","member_number","edge_number","version_reference","publication_number") if getattr(x,k,None)),str(x.id));self.db.add(FactoryBuyingCommitteeEvidence(id=_id("buying-evidence"),**_same(x),evidence_number=_number("BCX",x.project_id),subject_type=subject_type,subject_id=x.id,subject_number=number,evidence_type=evidence_type,evidence_reference=str(reference)[:255],note=note,recorded_by=str(actor),recorded_at=datetime.now(timezone.utc)))
