"""Evidence-pinned AI SDR recommendations with mandatory human review."""
from datetime import datetime,timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_ai_sdr import FactoryAiSdrEvidence,FactoryAiSdrHandoff,FactoryAiSdrLead,FactoryAiSdrRecommendation
from models.factory_icp import FactoryIcpAccountEvidence,FactoryIcpFitAssessment,FactoryIcpProfile,FactoryIcpVersion
from services.factory_icp import FactoryIcpService
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
PROPOSALS={"qualified","nurture","disqualify"};LEAD=("id","lead_number","assessment_id","assessment_number","profile_id","profile_number","profile_version","definition_hash","account_reference_hash","fit_tier","fit_score","status","created_by","revision");REC=("id","recommendation_number","lead_id","lead_number","sequence_number","model_reference","prompt_hash","enrichment_summary","intent_score","qualification_proposal","reply_subject","reply_body","next_action","output_hash","status","generated_by","reviewed_by","review_reference","review_note","revision");HANDOFF=("id","handoff_number","lead_id","recommendation_id","recommendation_number","owner_team","sla_minutes","manifest_hash","delivery_reference","crm_mutated","status","created_by","acknowledged_by","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _num(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _ctx(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _ser(x,fields):return {k:getattr(x,k) for k in fields}
class FactoryAiSdrService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  leads=await rows(FactoryAiSdrLead,FactoryAiSdrLead.created_at);recs=await rows(FactoryAiSdrRecommendation,FactoryAiSdrRecommendation.created_at);handoffs=await rows(FactoryAiSdrHandoff,FactoryAiSdrHandoff.created_at);evidence=await rows(FactoryAiSdrEvidence,FactoryAiSdrEvidence.recorded_at);reviewed=[x for x in recs if x.status in {"approved","rejected"}];ack=[x for x in handoffs if x.status=="acknowledged"]
  return {"leads":[_ser(x,LEAD) for x in leads],"recommendations":[_ser(x,REC) for x in recs],"handoffs":[_ser(x,HANDOFF) for x in handoffs],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._source_options(project_id),"metrics":{"sdr_leads":len(leads),"human_review_percent":round(len(reviewed)*100/max(1,len(recs)),2),"qualified_leads":len([x for x in recs if x.status=="approved" and x.qualification_proposal=="qualified"]),"average_intent_score":round(sum(x.intent_score for x in recs)/max(1,len(recs)),2),"sales_handoffs":len(handoffs),"handoff_acknowledgement_percent":round(len(ack)*100/max(1,len(handoffs)),2)},"contract":{"source_records_copied":False,"verified_icp_assessment_required":True,"authoritative_source_revalidated":True,"ai_output_direct_qualification":False,"ai_output_direct_reply":False,"recommendation_self_review":False,"raw_contact_identifier_stored":False,"prompt_content_stored":False,"crm_writeback":False,"immutable_handoff_manifest":True,"acknowledgement_required":True}}
 async def create_lead(self,*,project_id:int,context:TenantContext,actor:str,assessment_id:str):
  src=await self._source(assessment_id,project_id);a=src["assessment"];e=src["evidence"];now=datetime.now(timezone.utc);snapshot={"assessment_number":a.assessment_number,"profile_number":src["profile"].profile_number,"profile_version":a.profile_version,"definition_hash":a.definition_hash,"fit_tier":a.fit_tier,"fit_score":str(a.total_score),"account_reference_hash":_hash(a.account_reference),"evidence_number":e.evidence_number,"source_type":e.source_type,"source_number":e.source_number,"source_revision":e.source_revision};x=FactoryAiSdrLead(id=_id("ai-sdr-lead"),**_ctx(context,project_id),lead_number=_num("SDRL",project_id),assessment_id=a.id,assessment_number=a.assessment_number,profile_id=a.profile_id,profile_number=src["profile"].profile_number,profile_version=a.profile_version,definition_hash=a.definition_hash,account_reference=a.account_reference,account_reference_hash=_hash(a.account_reference),source_snapshot_json=snapshot,fit_tier=a.fit_tier,fit_score=str(a.total_score),status="draft",created_by=str(actor),created_at=now,updated_at=now,revision=1);self.db.add(x);await self._event(x,"lead","lead-created",a.assessment_number,"Pinned independently verified ICP fit without copying source",actor);await self.db.flush();return _ser(x,LEAD)
 async def generate_recommendation(self,lead_id:str,*,project_id:int,context:TenantContext,actor:str,model_reference:str,prompt_reference:str,enrichment_summary:str,intent_score:int,qualification_proposal:str,reply_subject:str,reply_body:str,next_action:str):
  lead=await self._get(FactoryAiSdrLead,lead_id,project_id,"AI SDR lead");await self._validate_lead(lead)
  if lead.status not in {"draft","reviewed"} or not model_reference.strip() or not prompt_reference.strip() or not enrichment_summary.strip() or not reply_subject.strip() or not reply_body.strip() or not next_action.strip() or not 0<=int(intent_score)<=100 or qualification_proposal not in PROPOSALS:raise ValueError("AI SDR recommendation requires provenance, explicit content, score and supported proposal")
  seq=(await self.db.scalar(select(FactoryAiSdrRecommendation.sequence_number).where(FactoryAiSdrRecommendation.lead_id==lead.id).order_by(FactoryAiSdrRecommendation.sequence_number.desc()).limit(1)) or 0)+1;payload={"lead_number":lead.lead_number,"model_reference":model_reference.strip(),"prompt_hash":_hash(prompt_reference.strip()),"enrichment_summary":enrichment_summary.strip(),"intent_score":int(intent_score),"qualification_proposal":qualification_proposal,"reply_subject":reply_subject.strip(),"reply_body":reply_body.strip(),"next_action":next_action.strip()};x=FactoryAiSdrRecommendation(id=_id("ai-sdr-recommendation"),**_ctx(context,project_id),recommendation_number=_num("SDRA",project_id),lead_id=lead.id,lead_number=lead.lead_number,sequence_number=seq,model_reference=model_reference.strip()[:255],prompt_hash=payload["prompt_hash"],enrichment_summary=enrichment_summary.strip(),intent_score=int(intent_score),qualification_proposal=qualification_proposal,reply_subject=reply_subject.strip()[:180],reply_body=reply_body.strip(),next_action=next_action.strip()[:255],output_hash=_hash(payload),status="pending-review",generated_by=str(actor),created_at=datetime.now(timezone.utc),revision=1);self.db.add(x);lead.status="pending-review";lead.updated_at=datetime.now(timezone.utc);lead.revision+=1;await self._event(x,"recommendation","recommendation-generated",x.output_hash,"Generated suggestion only; no qualification, reply or CRM mutation",actor);await self.db.flush();return _ser(x,REC)
 async def review_recommendation(self,recommendation_id:str,*,project_id:int,actor:str,expected_revision:int,decision:str,review_reference:str,review_note:str):
  x=await self._get(FactoryAiSdrRecommendation,recommendation_id,project_id,"AI SDR recommendation");self._rev(x,expected_revision);lead=await self._get(FactoryAiSdrLead,x.lead_id,project_id,"AI SDR lead");await self._validate_recommendation(x,lead)
  if x.status!="pending-review" or x.generated_by==str(actor) or decision not in {"approve","reject"} or not review_reference.strip() or not review_note.strip():raise ValueError("AI SDR recommendation requires independent documented human review")
  x.status="approved" if decision=="approve" else "rejected";x.reviewed_by=str(actor);x.reviewed_at=datetime.now(timezone.utc);x.review_reference=review_reference.strip()[:255];x.review_note=review_note.strip();x.revision+=1;lead.status={"qualified":"qualified","nurture":"nurture","disqualify":"disqualified"}[x.qualification_proposal] if decision=="approve" else "reviewed";lead.updated_at=datetime.now(timezone.utc);lead.revision+=1;await self._event(x,"recommendation","recommendation-reviewed",review_reference,f"Human decision: {decision}; {review_note}",actor);await self.db.flush();return _ser(x,REC)
 async def create_handoff(self,recommendation_id:str,*,project_id:int,context:TenantContext,actor:str,owner_team:str,sla_minutes:int,delivery_reference:str):
  x=await self._get(FactoryAiSdrRecommendation,recommendation_id,project_id,"AI SDR recommendation");lead=await self._get(FactoryAiSdrLead,x.lead_id,project_id,"AI SDR lead");await self._validate_recommendation(x,lead)
  if x.status!="approved" or x.qualification_proposal not in {"qualified","nurture"} or x.generated_by==str(actor) or not owner_team.strip() or not 5<=int(sla_minutes)<=10080 or not delivery_reference.strip():raise ValueError("Sales handoff requires approved human-reviewed lead, owner, SLA and delivery evidence")
  manifest={"lead_number":lead.lead_number,"assessment_number":lead.assessment_number,"definition_hash":lead.definition_hash,"account_reference_hash":lead.account_reference_hash,"fit_tier":lead.fit_tier,"recommendation_number":x.recommendation_number,"output_hash":x.output_hash,"human_review_reference":x.review_reference,"proposal":x.qualification_proposal,"owner_team":owner_team.strip(),"sla_minutes":int(sla_minutes)};mh=_hash(manifest);now=datetime.now(timezone.utc);h=FactoryAiSdrHandoff(id=_id("ai-sdr-handoff"),**_ctx(context,project_id),handoff_number=_num("SDRH",project_id),lead_id=lead.id,recommendation_id=x.id,recommendation_number=x.recommendation_number,owner_team=owner_team.strip()[:64],sla_minutes=int(sla_minutes),manifest_json=manifest,manifest_hash=mh,delivery_reference=delivery_reference.strip()[:255],crm_mutated=False,status="pending",created_by=str(actor),created_at=now,revision=1);self.db.add(h);await self._event(h,"handoff","handoff-created",delivery_reference,"Published immutable sales payload without CRM writeback",actor);await self.db.flush();return _ser(h,HANDOFF)
 async def acknowledge_handoff(self,handoff_id:str,*,project_id:int,actor:str,expected_revision:int,acknowledgement_reference:str):
  h=await self._get(FactoryAiSdrHandoff,handoff_id,project_id,"AI SDR handoff");self._rev(h,expected_revision)
  if h.status!="pending" or h.created_by==str(actor) or not acknowledgement_reference.strip() or h.manifest_hash!=_hash(h.manifest_json) or h.crm_mutated:raise ValueError("Sales handoff requires independent acknowledgement of unchanged manifest")
  h.status="acknowledged";h.acknowledged_by=str(actor);h.acknowledged_at=datetime.now(timezone.utc);h.acknowledgement_reference=acknowledgement_reference.strip()[:255];h.revision+=1;await self._event(h,"handoff","handoff-acknowledged",acknowledgement_reference,"Sales owner acknowledged exact immutable payload",actor);await self.db.flush();return _ser(h,HANDOFF)
 async def _source_options(self,pid):
  out=[];assessments=(await self.db.execute(select(FactoryIcpFitAssessment).where(FactoryIcpFitAssessment.project_id==pid,FactoryIcpFitAssessment.status=="verified").order_by(FactoryIcpFitAssessment.verified_at.desc()))).scalars().all();used=set((await self.db.execute(select(FactoryAiSdrLead.assessment_id).where(FactoryAiSdrLead.project_id==pid))).scalars().all())
  for a in assessments:
   if a.id in used:continue
   try:s=await self._source(a.id,pid)
   except (KeyError,ValueError):continue
   out.append({"assessment_id":a.id,"assessment_number":a.assessment_number,"profile_number":s["profile"].profile_number,"fit_tier":a.fit_tier,"fit_score":str(a.total_score),"account_reference_hash":_hash(a.account_reference)})
  return out
 async def _source(self,assessment_id,pid):
  a=await self._get(FactoryIcpFitAssessment,assessment_id,pid,"Verified ICP assessment");profile=await self._get(FactoryIcpProfile,a.profile_id,pid,"ICP profile");version=await self.db.scalar(select(FactoryIcpVersion).where(FactoryIcpVersion.profile_id==profile.id,FactoryIcpVersion.version_number==a.profile_version));evidence=await self._get(FactoryIcpAccountEvidence,a.account_evidence_id,pid,"ICP evidence")
  if a.status!="verified" or a.disqualified or profile.status!="active" or not version or version.status!="active" or version.definition_hash!=a.definition_hash or evidence.verification_status!="verified":raise ValueError("AI SDR requires active unchanged ICP and independently verified fit assessment")
  source,_=await FactoryIcpService(self.db)._source(evidence.source_type,evidence.source_id,pid)
  if int(source.revision)!=int(evidence.source_revision):raise ValueError("Authoritative lead source changed; AI SDR is blocked")
  return {"assessment":a,"profile":profile,"version":version,"evidence":evidence,"source":source}
 async def _validate_lead(self,lead):
  s=await self._source(lead.assessment_id,lead.project_id);a=s["assessment"];e=s["evidence"];snap={"assessment_number":a.assessment_number,"profile_number":s["profile"].profile_number,"profile_version":a.profile_version,"definition_hash":a.definition_hash,"fit_tier":a.fit_tier,"fit_score":str(a.total_score),"account_reference_hash":_hash(a.account_reference),"evidence_number":e.evidence_number,"source_type":e.source_type,"source_number":e.source_number,"source_revision":e.source_revision}
  if lead.assessment_number!=a.assessment_number or lead.profile_version!=a.profile_version or lead.definition_hash!=a.definition_hash or lead.account_reference_hash!=_hash(a.account_reference) or lead.source_snapshot_json!=snap:raise ValueError("Pinned AI SDR lead source drifted")
  return s
 async def _validate_recommendation(self,x,lead):
  await self._validate_lead(lead);payload={"lead_number":lead.lead_number,"model_reference":x.model_reference,"prompt_hash":x.prompt_hash,"enrichment_summary":x.enrichment_summary,"intent_score":x.intent_score,"qualification_proposal":x.qualification_proposal,"reply_subject":x.reply_subject,"reply_body":x.reply_body,"next_action":x.next_action}
  if x.output_hash!=_hash(payload) or not x.prompt_hash or not x.model_reference:raise ValueError("AI SDR recommendation provenance or output changed")
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _rev(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("lead_number","recommendation_number","handoff_number") if getattr(x,z,None)),str(x.id));self.db.add(FactoryAiSdrEvidence(id=_id("ai-sdr-evidence"),**{q:getattr(x,q) for q in ("project_id","agent_path","tenant_id","client_id","plan_id")},evidence_number=_num("SDRE",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc)))
