"""Consent-safe enterprise targeting and coordinated ABM plays."""
from __future__ import annotations
from datetime import datetime,timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_abm import FactoryAbmActivation,FactoryAbmEvidence,FactoryAbmProgram,FactoryAbmRolePlay,FactoryAbmTargetAccount,FactoryAbmVersion
from models.factory_buying_committee import FactoryBuyingCommittee,FactoryBuyingCommitteeMember,FactoryBuyingCommitteeVersion
from models.factory_segments_consent import FactoryAudienceMembership,FactoryAudienceSegment,FactoryAudienceSegmentVersion
from services.factory_buying_committee import FactoryBuyingCommitteeService
from services.factory_segments_consent import FactorySegmentsConsentService
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
CONSUMERS={"crm","marketing","ads","sales"};TEAMS={"marketing","sales","revops"};CHANNELS={"email","phone","meeting","wechat","whatsapp","display","social"}
PROGRAM=("id","program_number","program_code","program_name","business_objective","allowed_consumers_json","status","authored_by","published_by","revision");TARGET=("id","target_number","program_id","program_number","account_reference","priority_tier","fit_score","audience_segment_id","audience_version_id","audience_version_reference","audience_manifest_hash","consented_member_count","buying_committee_id","buying_version_id","buying_version_reference","buying_manifest_hash","opportunity_number","required_role_count","source_fingerprint","status","created_by","verified_by","revision");PLAY=("id","play_number","program_id","target_id","target_number","account_reference","committee_member_id","committee_member_number","role_code","role_name","contact_hash","member_fingerprint","owner_team","channel","action_code","message_intent","success_signal","sequence_order","definition_hash","status","authored_by","approved_by","revision");VERSION=("id","version_reference","program_id","program_number","version_number","manifest_hash","target_count","role_play_count","role_coverage_percent","status","published_by");ACTIVATION=("id","activation_number","program_id","version_id","version_reference","consumer","manifest_hash","delivery_reference","consumer_mutated","status","created_by","acknowledged_by","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _number(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _context(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _serialize(x,f):return {k:getattr(x,k) for k in f}
class FactoryAbmService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  programs=await rows(FactoryAbmProgram,FactoryAbmProgram.created_at);targets=await rows(FactoryAbmTargetAccount,FactoryAbmTargetAccount.created_at);plays=await rows(FactoryAbmRolePlay,FactoryAbmRolePlay.created_at);versions=await rows(FactoryAbmVersion,FactoryAbmVersion.published_at);acts=await rows(FactoryAbmActivation,FactoryAbmActivation.created_at);evidence=await rows(FactoryAbmEvidence,FactoryAbmEvidence.recorded_at);approved=[x for x in plays if x.status=="approved"];ack=[x for x in acts if x.status=="acknowledged"]
  return {"programs":[_serialize(x,PROGRAM) for x in programs],"targets":[_serialize(x,TARGET) for x in targets],"plays":[_serialize(x,PLAY) for x in plays],"versions":[_serialize(x,VERSION) for x in versions],"activations":[_serialize(x,ACTIVATION) for x in acts],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._source_options(project_id),"metrics":{"active_programs":len([x for x in programs if x.status=="published"]),"verified_accounts":len([x for x in targets if x.status=="verified"]),"role_coverage_percent":round(len(approved)*100/max(1,sum(x.required_role_count for x in targets)),2),"approved_role_plays":len(approved),"published_versions":len(versions),"activation_acknowledgement_percent":round(len(ack)*100/max(1,len(acts)),2)},"contract":{"source_records_copied":False,"audience_version_pinned":True,"buying_committee_version_pinned":True,"active_consent_revalidated":True,"complete_role_coverage_required":True,"target_account_self_verification":False,"role_play_self_approval":False,"ai_autonomous_targeting":False,"program_author_self_publish":False,"published_versions_mutable":False,"consumer_system_mutated":False,"acknowledgement_required":True}}
 async def create_program(self,*,project_id:int,context:TenantContext,actor:str,program_code:str,program_name:str,business_objective:str,allowed_consumers:list[str]):
  consumers=sorted(set(allowed_consumers))
  if not program_code.strip() or not program_name.strip() or not business_objective.strip() or not consumers or any(x not in CONSUMERS for x in consumers):raise ValueError("ABM program requires code, name, objective and supported consumers")
  now=datetime.now(timezone.utc);x=FactoryAbmProgram(id=_id("abm-program"),**_context(context,project_id),program_number=_number("ABM",project_id),program_code=program_code.strip()[:64],program_name=program_name.strip()[:180],business_objective=business_objective.strip()[:255],allowed_consumers_json=consumers,status="draft",authored_by=str(actor),revision=1,created_at=now,updated_at=now);self.db.add(x);await self._event(x,"program","program-created",program_code,"Created governed enterprise targeting program",actor);await self.db.flush();return _serialize(x,PROGRAM)
 async def add_target(self,program_id:str,*,project_id:int,context:TenantContext,actor:str,audience_segment_id:str,buying_committee_id:str,priority_tier:str,fit_score:float):
  program=await self._get(FactoryAbmProgram,program_id,project_id,"ABM program");bundle=await self._bundle(audience_segment_id,buying_committee_id,project_id)
  if program.status!="draft" or priority_tier not in {"tier-1","tier-2","tier-3"} or not 0<=fit_score<=100:raise ValueError("Target account requires draft program, valid priority and fit score")
  snap=self._bundle_snapshot(bundle);now=datetime.now(timezone.utc);x=FactoryAbmTargetAccount(id=_id("abm-target"),**_context(context,project_id),target_number=_number("ABT",project_id),program_id=program.id,program_number=program.program_number,account_reference=bundle["committee"].account_reference,priority_tier=priority_tier,fit_score=fit_score,audience_segment_id=bundle["segment"].id,audience_version_id=bundle["audience_version"].id,audience_version_reference=bundle["audience_version"].version_reference,audience_manifest_hash=bundle["audience_version"].manifest_hash,consented_member_count=len(bundle["memberships"]),buying_committee_id=bundle["committee"].id,buying_version_id=bundle["buying_version"].id,buying_version_reference=bundle["buying_version"].version_reference,buying_manifest_hash=bundle["buying_version"].manifest_hash,opportunity_number=bundle["committee"].opportunity_source_number,required_role_count=len(bundle["committee_members"]),source_snapshot_json=snap,source_fingerprint=_hash(snap),status="pending",created_by=str(actor),revision=1,created_at=now);self.db.add(x);await self._event(x,"target","target-added",x.account_reference,"Pinned consented audience and complete buying committee",actor);await self.db.flush();return _serialize(x,TARGET)
 async def verify_target(self,target_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAbmTargetAccount,target_id,project_id,"ABM target account");self._revision(x,expected_revision)
  if x.status!="pending" or x.created_by==str(actor) or not reference.strip():raise ValueError("Target account requires independent verification")
  await self._validate_target(x);x.status="verified";x.verified_by=str(actor);x.verified_at=datetime.now(timezone.utc);x.verification_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"target","target-verified",reference,"Independently verified audience, consent and buying committee",actor);await self.db.flush();return _serialize(x,TARGET)
 async def add_role_play(self,target_id:str,*,project_id:int,context:TenantContext,actor:str,committee_member_id:str,owner_team:str,channel:str,action_code:str,message_intent:str,success_signal:str,sequence_order:int):
  target=await self._get(FactoryAbmTargetAccount,target_id,project_id,"ABM target account");program=await self._get(FactoryAbmProgram,target.program_id,project_id,"ABM program");await self._validate_target(target);member=await self._get(FactoryBuyingCommitteeMember,committee_member_id,project_id,"Buying committee member")
  if program.status!="draft" or target.status!="verified" or member.committee_id!=target.buying_committee_id or member.status!="verified" or owner_team not in TEAMS or channel not in CHANNELS or not action_code.strip() or not message_intent.strip() or not success_signal.strip() or sequence_order<1:raise ValueError("Role play requires verified target, committee member and explicit human-authored action")
  mf=_hash(self._member_manifest(member));definition={"member_fingerprint":mf,"owner_team":owner_team,"channel":channel,"action_code":action_code.strip(),"message_intent":message_intent.strip(),"success_signal":success_signal.strip(),"sequence_order":sequence_order};now=datetime.now(timezone.utc);x=FactoryAbmRolePlay(id=_id("abm-play"),**_context(context,project_id),play_number=_number("ABP",project_id),program_id=program.id,target_id=target.id,target_number=target.target_number,account_reference=target.account_reference,committee_member_id=member.id,committee_member_number=member.member_number,role_code=member.role_code,role_name=member.role_name,contact_hash=member.contact_hash,member_fingerprint=mf,owner_team=owner_team,channel=channel,action_code=action_code.strip()[:64],message_intent=message_intent.strip()[:255],success_signal=success_signal.strip()[:180],sequence_order=sequence_order,definition_hash=_hash(definition),status="draft",authored_by=str(actor),revision=1,created_at=now);self.db.add(x);await self._event(x,"play","role-play-created",action_code,"Authored explicit buying-role coordinated play",actor);await self.db.flush();return _serialize(x,PLAY)
 async def approve_role_play(self,play_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAbmRolePlay,play_id,project_id,"ABM role play");self._revision(x,expected_revision)
  if x.status!="draft" or x.authored_by==str(actor) or not reference.strip():raise ValueError("Role play requires independent approval")
  await self._validate_play(x);x.status="approved";x.approved_by=str(actor);x.approved_at=datetime.now(timezone.utc);x.approval_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"play","role-play-approved",reference,"Independently approved role-specific ABM play",actor);await self.db.flush();return _serialize(x,PLAY)
 async def publish_program(self,program_id:str,*,project_id:int,context:TenantContext,actor:str,expected_revision:int,consumers:list[str],delivery_reference_prefix:str):
  program=await self._get(FactoryAbmProgram,program_id,project_id,"ABM program");self._revision(program,expected_revision);requested=sorted(set(consumers));targets=(await self.db.execute(select(FactoryAbmTargetAccount).where(FactoryAbmTargetAccount.program_id==program.id))).scalars().all();plays=(await self.db.execute(select(FactoryAbmRolePlay).where(FactoryAbmRolePlay.program_id==program.id))).scalars().all()
  if program.status!="draft" or program.authored_by==str(actor) or not requested or any(x not in program.allowed_consumers_json for x in requested) or not delivery_reference_prefix.strip():raise ValueError("ABM program requires independent publisher and approved consumers")
  if not targets or any(x.status!="verified" for x in targets) or not plays or any(x.status!="approved" for x in plays):raise ValueError("ABM program requires verified targets and approved role plays")
  for target in targets:
   bundle=await self._validate_target(target);expected={x.id for x in bundle["committee_members"]};actual={x.committee_member_id for x in plays if x.target_id==target.id}
   if actual!=expected:raise ValueError("Every verified buying committee role requires one approved ABM play")
  for play in plays:await self._validate_play(play)
  manifest={"program_number":program.program_number,"objective":program.business_objective,"consumers":program.allowed_consumers_json,"targets":sorted([{"target_number":x.target_number,"account_reference":x.account_reference,"priority_tier":x.priority_tier,"fit_score":x.fit_score,"source_fingerprint":x.source_fingerprint} for x in targets],key=lambda x:x["target_number"]),"role_plays":sorted([{"play_number":x.play_number,"target_number":x.target_number,"role_code":x.role_code,"contact_hash":x.contact_hash,"owner_team":x.owner_team,"channel":x.channel,"action_code":x.action_code,"success_signal":x.success_signal,"definition_hash":x.definition_hash} for x in plays],key=lambda x:x["play_number"])};mh=_hash(manifest);current=await self.db.scalar(select(FactoryAbmVersion.version_number).where(FactoryAbmVersion.program_id==program.id).order_by(FactoryAbmVersion.version_number.desc()).limit(1)) or 0;coverage=round(len(plays)*100/sum(x.required_role_count for x in targets),2);now=datetime.now(timezone.utc);v=FactoryAbmVersion(id=_id("abm-version"),**_context(context,project_id),version_reference=_number("ABV",project_id),program_id=program.id,program_number=program.program_number,version_number=int(current)+1,manifest_json=manifest,manifest_hash=mh,target_count=len(targets),role_play_count=len(plays),role_coverage_percent=coverage,status="published",published_by=str(actor),published_at=now);self.db.add(v);acts=[]
  for consumer in requested:
   a=FactoryAbmActivation(id=_id("abm-activation"),**_context(context,project_id),activation_number=_number("ABA",project_id),program_id=program.id,version_id=v.id,version_reference=v.version_reference,consumer=consumer,manifest_hash=mh,delivery_reference=f"{delivery_reference_prefix.strip()[:180]}:{consumer}",consumer_mutated=False,status="pending",created_by=str(actor),created_at=now,revision=1);self.db.add(a);acts.append(a);await self._event(a,"activation","activation-created",a.delivery_reference,"Created explicit acknowledgement for exact ABM plan hash",actor)
  program.status="published";program.published_by=str(actor);program.published_at=now;program.revision+=1;program.updated_at=now;await self._event(program,"program","program-published",v.version_reference,"Published immutable consent-safe enterprise targeting program",actor);await self.db.flush();return {"program":_serialize(program,PROGRAM),"version":_serialize(v,VERSION),"activations":[_serialize(x,ACTIVATION) for x in acts]}
 async def acknowledge_activation(self,activation_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryAbmActivation,activation_id,project_id,"ABM activation");self._revision(x,expected_revision)
  if x.status!="pending" or x.created_by==str(actor) or not reference.strip():raise ValueError("ABM activation acknowledgement must be independent")
  v=await self._get(FactoryAbmVersion,x.version_id,project_id,"ABM version")
  if v.status!="published" or v.manifest_hash!=x.manifest_hash or _hash(v.manifest_json)!=x.manifest_hash:raise ValueError("Published ABM version changed")
  x.status="acknowledged";x.acknowledged_by=str(actor);x.acknowledged_at=datetime.now(timezone.utc);x.acknowledgement_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"activation","activation-acknowledged",reference,"Consumer acknowledged exact ABM plan hash",actor);await self.db.flush();return _serialize(x,ACTIVATION)
 async def _source_options(self,pid):
  out=[]
  for committee in (await self.db.execute(select(FactoryBuyingCommittee).where(FactoryBuyingCommittee.project_id==pid,FactoryBuyingCommittee.status=="published"))).scalars().all():
   for segment in (await self.db.execute(select(FactoryAudienceSegment).where(FactoryAudienceSegment.project_id==pid,FactoryAudienceSegment.status=="published"))).scalars().all():
    try:b=await self._bundle(segment.id,committee.id,pid)
    except ValueError:continue
    out.append({"account_reference":committee.account_reference,"audience_segment_id":segment.id,"audience_segment_number":segment.segment_number,"audience_version_reference":b["audience_version"].version_reference,"consented_member_count":len(b["memberships"]),"buying_committee_id":committee.id,"buying_committee_number":committee.committee_number,"buying_version_reference":b["buying_version"].version_reference,"opportunity_number":committee.opportunity_source_number,"required_role_count":len(b["committee_members"]),"members":[{"id":x.id,"number":x.member_number,"role_code":x.role_code,"role_name":x.role_name,"channel":x.preferred_channel,"contact_hint":x.contact_hint} for x in b["committee_members"]]})
  return out
 async def _bundle(self,segment_id,committee_id,pid):
  segment=await self._get(FactoryAudienceSegment,segment_id,pid,"Audience segment");committee=await self._get(FactoryBuyingCommittee,committee_id,pid,"Buying committee")
  if segment.status!="published" or committee.status!="published":raise ValueError("ABM source requires published segment and buying committee")
  av=await self.db.scalar(select(FactoryAudienceSegmentVersion).where(FactoryAudienceSegmentVersion.segment_id==segment.id,FactoryAudienceSegmentVersion.status=="published").order_by(FactoryAudienceSegmentVersion.version_number.desc()).limit(1));bv=await self.db.scalar(select(FactoryBuyingCommitteeVersion).where(FactoryBuyingCommitteeVersion.committee_id==committee.id,FactoryBuyingCommitteeVersion.status=="published").order_by(FactoryBuyingCommitteeVersion.version_number.desc()).limit(1))
  if not av or not bv or _hash(av.manifest_json)!=av.manifest_hash or _hash(bv.manifest_json)!=bv.manifest_hash:raise ValueError("ABM source version missing or changed")
  memberships=(await self.db.execute(select(FactoryAudienceMembership).where(FactoryAudienceMembership.segment_id==segment.id,FactoryAudienceMembership.account_reference==committee.account_reference,FactoryAudienceMembership.status=="verified"))).scalars().all();members=(await self.db.execute(select(FactoryBuyingCommitteeMember).where(FactoryBuyingCommitteeMember.committee_id==committee.id,FactoryBuyingCommitteeMember.status=="verified"))).scalars().all()
  if not memberships or not members or {x.contact_hash for x in members}-{x.contact_hash for x in memberships}:raise ValueError("Buying committee roles must be covered by consented segment members")
  segsvc=FactorySegmentsConsentService(self.db);buysvc=FactoryBuyingCommitteeService(self.db);await buysvc._validate_committee_sources(committee)
  for x in memberships:await segsvc._validate_member(x)
  for x in members:await buysvc._validate_member(x)
  return {"segment":segment,"audience_version":av,"memberships":memberships,"committee":committee,"buying_version":bv,"committee_members":members}
 def _bundle_snapshot(self,b):return {"account_reference":b["committee"].account_reference,"audience":{"segment_number":b["segment"].segment_number,"version_reference":b["audience_version"].version_reference,"manifest_hash":b["audience_version"].manifest_hash,"consented_member_hashes":sorted(x.contact_hash for x in b["memberships"])},"buying_committee":{"committee_number":b["committee"].committee_number,"version_reference":b["buying_version"].version_reference,"manifest_hash":b["buying_version"].manifest_hash,"opportunity_number":b["committee"].opportunity_source_number,"member_hashes":sorted(x.contact_hash for x in b["committee_members"])}}
 async def _validate_target(self,x):
  b=await self._bundle(x.audience_segment_id,x.buying_committee_id,x.project_id);snap=self._bundle_snapshot(b)
  if x.account_reference!=b["committee"].account_reference or x.audience_version_id!=b["audience_version"].id or x.audience_manifest_hash!=b["audience_version"].manifest_hash or x.buying_version_id!=b["buying_version"].id or x.buying_manifest_hash!=b["buying_version"].manifest_hash or x.consented_member_count!=len(b["memberships"]) or x.required_role_count!=len(b["committee_members"]) or x.source_snapshot_json!=snap or x.source_fingerprint!=_hash(snap):raise ValueError("ABM target audience, consent or buying committee source drifted")
  return b
 @staticmethod
 def _member_manifest(m):return {"member_number":m.member_number,"role_code":m.role_code,"role_name":m.role_name,"contact_hash":m.contact_hash,"role_fingerprint":m.role_fingerprint,"contact_source_revision":m.contact_source_revision,"contact_source_fingerprint":m.contact_source_fingerprint,"preferred_channel":m.preferred_channel,"revision":m.revision}
 def _play_definition(self,x):return {"member_fingerprint":x.member_fingerprint,"owner_team":x.owner_team,"channel":x.channel,"action_code":x.action_code,"message_intent":x.message_intent,"success_signal":x.success_signal,"sequence_order":x.sequence_order}
 async def _validate_play(self,x):
  target=await self._get(FactoryAbmTargetAccount,x.target_id,x.project_id,"ABM target account");await self._validate_target(target);member=await self._get(FactoryBuyingCommitteeMember,x.committee_member_id,x.project_id,"Buying committee member")
  if member.committee_id!=target.buying_committee_id or x.committee_member_number!=member.member_number or x.contact_hash!=member.contact_hash or x.member_fingerprint!=_hash(self._member_manifest(member)) or x.definition_hash!=_hash(self._play_definition(x)):raise ValueError("ABM role play source or definition drifted")
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _revision(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("program_number","target_number","play_number","activation_number") if getattr(x,z,None)),str(x.id));e=FactoryAbmEvidence(id=_id("abm-evidence"),**{q:getattr(x,q) for q in ("project_id","agent_path","tenant_id","client_id","plan_id")},evidence_number=_number("ABE",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc));self.db.add(e)
