"""Rights-safe, role-specific and human-reviewed creative center."""
from datetime import datetime,timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_abm import FactoryAbmProgram,FactoryAbmRolePlay,FactoryAbmVersion
from models.factory_creative import FactoryCreativeActivation,FactoryCreativeBrief,FactoryCreativeEvidence,FactoryCreativeVariant,FactoryCreativeVersion
from models.factory_dam_localization import FactoryCountryContentPack
from services.factory_dam_localization import FactoryDamLocalizationService
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
CONSUMERS={"ads","marketing","sales","web"};BRIEF=("id","brief_number","brief_code","brief_name","objective","abm_program_id","abm_version_id","abm_version_reference","abm_manifest_hash","country_pack_id","country_pack_number","country_pack_manifest_hash","target_market","target_locale","allowed_consumers_json","status","authored_by","published_by","revision");VARIANT=("id","variant_number","brief_id","brief_number","abm_play_id","abm_play_number","role_code","role_name","channel","headline","message_body","call_to_action","source_pack_hash","play_definition_hash","ai_assisted","model_reference","prompt_hash","content_hash","status","created_by","approved_by","revision");VERSION=("id","version_reference","brief_id","brief_number","version_number","manifest_hash","variant_count","role_coverage_percent","status","published_by");ACTIVATION=("id","activation_number","brief_id","version_id","version_reference","consumer","manifest_hash","delivery_reference","consumer_mutated","status","created_by","acknowledged_by","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _number(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _context(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _serialize(x,f):return {k:getattr(x,k) for k in f}
class FactoryCreativeService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  briefs=await rows(FactoryCreativeBrief,FactoryCreativeBrief.created_at);variants=await rows(FactoryCreativeVariant,FactoryCreativeVariant.created_at);versions=await rows(FactoryCreativeVersion,FactoryCreativeVersion.published_at);acts=await rows(FactoryCreativeActivation,FactoryCreativeActivation.created_at);evidence=await rows(FactoryCreativeEvidence,FactoryCreativeEvidence.recorded_at);approved=[x for x in variants if x.status=="approved"];ack=[x for x in acts if x.status=="acknowledged"]
  return {"briefs":[_serialize(x,BRIEF) for x in briefs],"variants":[_serialize(x,VARIANT) for x in variants],"versions":[_serialize(x,VERSION) for x in versions],"activations":[_serialize(x,ACTIVATION) for x in acts],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in evidence],"sources":await self._source_options(project_id),"metrics":{"published_briefs":len([x for x in briefs if x.status=="published"]),"approved_variants":len(approved),"role_coverage_percent":round(len(approved)*100/max(1,sum(x.variant_count for x in versions) or len(approved)),2),"ai_review_percent":round(len([x for x in approved if x.ai_assisted])*100/max(1,len([x for x in variants if x.ai_assisted])),2),"published_versions":len(versions),"activation_acknowledgement_percent":round(len(ack)*100/max(1,len(acts)),2)},"contract":{"source_records_copied":False,"abm_version_pinned":True,"country_pack_rights_revalidated":True,"complete_role_coverage_required":True,"ai_output_direct_publish":False,"variant_self_approval":False,"brief_author_self_publish":False,"raw_customer_identifier_stored":False,"published_versions_mutable":False,"consumer_system_mutated":False,"acknowledgement_required":True}}
 async def create_brief(self,*,project_id:int,context:TenantContext,actor:str,brief_code:str,brief_name:str,objective:str,abm_version_id:str,country_pack_id:str,allowed_consumers:list[str]):
  src=await self._source(abm_version_id,country_pack_id,project_id);consumers=sorted(set(allowed_consumers))
  if not brief_code.strip() or not brief_name.strip() or not objective.strip() or not consumers or any(x not in CONSUMERS for x in consumers):raise ValueError("Creative brief requires code, name, objective and supported consumers")
  now=datetime.now(timezone.utc);v=src["version"];p=src["pack"];x=FactoryCreativeBrief(id=_id("creative-brief"),**_context(context,project_id),brief_number=_number("CRB",project_id),brief_code=brief_code.strip()[:64],brief_name=brief_name.strip()[:180],objective=objective.strip()[:255],abm_program_id=v.program_id,abm_version_id=v.id,abm_version_reference=v.version_reference,abm_manifest_hash=v.manifest_hash,country_pack_id=p.id,country_pack_number=p.pack_number,country_pack_manifest_hash=p.manifest_hash,target_market=p.target_market,target_locale=p.target_locale,allowed_consumers_json=consumers,status="draft",authored_by=str(actor),revision=1,created_at=now,updated_at=now);self.db.add(x);await self._event(x,"brief","brief-created",brief_code,"Pinned ABM plan and rights-cleared country content pack",actor);await self.db.flush();return _serialize(x,BRIEF)
 async def create_variant(self,brief_id:str,*,project_id:int,context:TenantContext,actor:str,abm_play_id:str,channel:str,headline:str,message_body:str,call_to_action:str,ai_assisted:bool,model_reference:str|None,prompt_reference:str|None):
  brief=await self._get(FactoryCreativeBrief,brief_id,project_id,"Creative brief");src=await self._validate_brief(brief);play=await self._get(FactoryAbmRolePlay,abm_play_id,project_id,"ABM role play")
  if brief.status!="draft" or play.program_id!=brief.abm_program_id or play.status!="approved" or channel not in {"display","social","email","web","video"} or not all(str(x).strip() for x in (headline,message_body,call_to_action)) or (ai_assisted and (not model_reference or not prompt_reference)):raise ValueError("Creative variant requires approved role play, explicit content and AI provenance")
  content={"headline":headline.strip(),"message_body":message_body.strip(),"call_to_action":call_to_action.strip(),"channel":channel};now=datetime.now(timezone.utc);x=FactoryCreativeVariant(id=_id("creative-variant"),**_context(context,project_id),variant_number=_number("CRV",project_id),brief_id=brief.id,brief_number=brief.brief_number,abm_play_id=play.id,abm_play_number=play.play_number,role_code=play.role_code,role_name=play.role_name,channel=channel,headline=headline.strip()[:180],message_body=message_body.strip(),call_to_action=call_to_action.strip()[:128],source_pack_hash=brief.country_pack_manifest_hash,play_definition_hash=play.definition_hash,ai_assisted=ai_assisted,model_reference=model_reference.strip()[:255] if model_reference else None,prompt_hash=_hash(prompt_reference.strip()) if prompt_reference else None,content_hash=_hash(content),status="review",created_by=str(actor),revision=1,created_at=now);self.db.add(x);await self._event(x,"variant","variant-created",play.play_number,"Created traceable role-specific creative candidate",actor);await self.db.flush();return _serialize(x,VARIANT)
 async def approve_variant(self,variant_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryCreativeVariant,variant_id,project_id,"Creative variant");self._revision(x,expected_revision)
  if x.status!="review" or x.created_by==str(actor) or not reference.strip():raise ValueError("Creative variant requires independent human approval")
  await self._validate_variant(x);x.status="approved";x.approved_by=str(actor);x.approved_at=datetime.now(timezone.utc);x.approval_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"variant","variant-approved",reference,"Human approved rights-safe role-specific creative",actor);await self.db.flush();return _serialize(x,VARIANT)
 async def publish_brief(self,brief_id:str,*,project_id:int,context:TenantContext,actor:str,expected_revision:int,consumers:list[str],delivery_reference_prefix:str):
  brief=await self._get(FactoryCreativeBrief,brief_id,project_id,"Creative brief");self._revision(brief,expected_revision);src=await self._validate_brief(brief);requested=sorted(set(consumers));variants=(await self.db.execute(select(FactoryCreativeVariant).where(FactoryCreativeVariant.brief_id==brief.id))).scalars().all();plays=src["plays"]
  if brief.status!="draft" or brief.authored_by==str(actor) or not requested or any(x not in brief.allowed_consumers_json for x in requested) or not delivery_reference_prefix.strip():raise ValueError("Creative brief requires independent publisher and approved consumers")
  if not variants or any(x.status!="approved" for x in variants) or {x.abm_play_id for x in variants}!={x.id for x in plays}:raise ValueError("Every approved ABM role play requires one human-approved creative variant")
  for x in variants:await self._validate_variant(x)
  manifest={"brief_number":brief.brief_number,"objective":brief.objective,"abm":{"version_reference":brief.abm_version_reference,"manifest_hash":brief.abm_manifest_hash},"country_pack":{"pack_number":brief.country_pack_number,"manifest_hash":brief.country_pack_manifest_hash},"variants":sorted([{"variant_number":x.variant_number,"play_number":x.abm_play_number,"role_code":x.role_code,"channel":x.channel,"content_hash":x.content_hash,"ai_assisted":x.ai_assisted,"prompt_hash":x.prompt_hash} for x in variants],key=lambda x:x["variant_number"])};mh=_hash(manifest);current=await self.db.scalar(select(FactoryCreativeVersion.version_number).where(FactoryCreativeVersion.brief_id==brief.id).order_by(FactoryCreativeVersion.version_number.desc()).limit(1)) or 0;now=datetime.now(timezone.utc);v=FactoryCreativeVersion(id=_id("creative-version"),**_context(context,project_id),version_reference=_number("CRX",project_id),brief_id=brief.id,brief_number=brief.brief_number,version_number=int(current)+1,manifest_json=manifest,manifest_hash=mh,variant_count=len(variants),role_coverage_percent=100,status="published",published_by=str(actor),published_at=now);self.db.add(v);acts=[]
  for consumer in requested:
   a=FactoryCreativeActivation(id=_id("creative-activation"),**_context(context,project_id),activation_number=_number("CRA",project_id),brief_id=brief.id,version_id=v.id,version_reference=v.version_reference,consumer=consumer,manifest_hash=mh,delivery_reference=f"{delivery_reference_prefix.strip()[:180]}:{consumer}",consumer_mutated=False,status="pending",created_by=str(actor),created_at=now,revision=1);self.db.add(a);acts.append(a);await self._event(a,"activation","activation-created",a.delivery_reference,"Created explicit acknowledgement for exact creative hash",actor)
  brief.status="published";brief.published_by=str(actor);brief.published_at=now;brief.revision+=1;brief.updated_at=now;await self._event(brief,"brief","brief-published",v.version_reference,"Published immutable human-reviewed creative set",actor);await self.db.flush();return {"brief":_serialize(brief,BRIEF),"version":_serialize(v,VERSION),"activations":[_serialize(x,ACTIVATION) for x in acts]}
 async def acknowledge_activation(self,activation_id:str,*,project_id:int,actor:str,expected_revision:int,reference:str):
  x=await self._get(FactoryCreativeActivation,activation_id,project_id,"Creative activation");self._revision(x,expected_revision)
  if x.status!="pending" or x.created_by==str(actor) or not reference.strip():raise ValueError("Creative activation acknowledgement must be independent")
  v=await self._get(FactoryCreativeVersion,x.version_id,project_id,"Creative version")
  if v.status!="published" or v.manifest_hash!=x.manifest_hash or _hash(v.manifest_json)!=x.manifest_hash:raise ValueError("Published creative version changed")
  x.status="acknowledged";x.acknowledged_by=str(actor);x.acknowledged_at=datetime.now(timezone.utc);x.acknowledgement_reference=reference.strip()[:255];x.revision+=1;await self._event(x,"activation","activation-acknowledged",reference,"Consumer acknowledged exact creative version hash",actor);await self.db.flush();return _serialize(x,ACTIVATION)
 async def _source(self,version_id,pack_id,pid):
  v=await self._get(FactoryAbmVersion,version_id,pid,"ABM version");program=await self._get(FactoryAbmProgram,v.program_id,pid,"ABM program");pack=await self._get(FactoryCountryContentPack,pack_id,pid,"Country content pack")
  if v.status!="published" or program.status!="published" or _hash(v.manifest_json)!=v.manifest_hash or pack.status!="published":raise ValueError("Creative source requires published unchanged ABM and country pack")
  await FactoryDamLocalizationService(self.db)._validate_pack(pack);plays=(await self.db.execute(select(FactoryAbmRolePlay).where(FactoryAbmRolePlay.program_id==program.id,FactoryAbmRolePlay.status=="approved"))).scalars().all()
  if not plays or len(plays)!=v.role_play_count:raise ValueError("Creative source requires complete approved ABM role plays")
  return {"version":v,"program":program,"pack":pack,"plays":plays}
 async def _source_options(self,pid):
  out=[];versions=(await self.db.execute(select(FactoryAbmVersion).where(FactoryAbmVersion.project_id==pid,FactoryAbmVersion.status=="published"))).scalars().all();packs=(await self.db.execute(select(FactoryCountryContentPack).where(FactoryCountryContentPack.project_id==pid,FactoryCountryContentPack.status=="published"))).scalars().all()
  for v in versions:
   for p in packs:
    try:s=await self._source(v.id,p.id,pid)
    except ValueError:continue
    out.append({"abm_version_id":v.id,"abm_version_reference":v.version_reference,"abm_program_number":s["program"].program_number,"role_play_count":len(s["plays"]),"country_pack_id":p.id,"country_pack_number":p.pack_number,"target_market":p.target_market,"target_locale":p.target_locale,"plays":[{"id":x.id,"number":x.play_number,"role_code":x.role_code,"role_name":x.role_name,"channel":x.channel} for x in s["plays"]]})
  return out
 async def _validate_brief(self,x):
  s=await self._source(x.abm_version_id,x.country_pack_id,x.project_id)
  if x.abm_program_id!=s["program"].id or x.abm_version_reference!=s["version"].version_reference or x.abm_manifest_hash!=s["version"].manifest_hash or x.country_pack_number!=s["pack"].pack_number or x.country_pack_manifest_hash!=s["pack"].manifest_hash or x.target_market!=s["pack"].target_market or x.target_locale!=s["pack"].target_locale:raise ValueError("Creative ABM or country-pack source drifted")
  return s
 async def _validate_variant(self,x):
  brief=await self._get(FactoryCreativeBrief,x.brief_id,x.project_id,"Creative brief");await self._validate_brief(brief);play=await self._get(FactoryAbmRolePlay,x.abm_play_id,x.project_id,"ABM role play");content={"headline":x.headline,"message_body":x.message_body,"call_to_action":x.call_to_action,"channel":x.channel}
  if play.status!="approved" or play.program_id!=brief.abm_program_id or x.play_definition_hash!=play.definition_hash or x.source_pack_hash!=brief.country_pack_manifest_hash or x.content_hash!=_hash(content) or (x.ai_assisted and (not x.model_reference or not x.prompt_hash)):raise ValueError("Creative content, provenance or source drifted")
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _revision(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("brief_number","variant_number","activation_number") if getattr(x,z,None)),str(x.id));self.db.add(FactoryCreativeEvidence(id=_id("creative-evidence"),**{q:getattr(x,q) for q in ("project_id","agent_path","tenant_id","client_id","plan_id")},evidence_number=_number("CRE",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc)))
