"""Brand strategy governance: reusable guidance, never an automatic website overwrite."""
from datetime import datetime, timezone
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_brand import FactoryBrandClaim,FactoryBrandEvidence,FactoryBrandProfile,FactoryBrandRelease,FactoryBrandVersion
from models.factory_contract import FactoryCoreEventContract,FactoryCoreObjectContract
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
APPLICATION_ID="identity.brand"; EVIDENCE=("customer_trial_reference","role_training_reference","issue_closure_reference","monitoring_reference","rollback_reference")
def _id(p):return f"{p}-{secrets.token_urlsafe(18)}"
def _num(p,x):return f"{p}-{x}-{datetime.now(timezone.utc):%Y%m%d%H%M%S%f}-{secrets.token_hex(3).upper()}"
def _hash(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _ctx(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _same(x):return {k:getattr(x,k) for k in ("project_id","agent_path","tenant_id","client_id","plan_id")}
def _ser(x,fields):return {k:getattr(x,k) for k in fields}
PROFILE=("id","profile_number","brand_name","market_scope","audience","positioning","value_promise","tone","status","current_version","authored_by","approved_by","revision")
CLAIM=("id","claim_number","profile_id","profile_number","claim_type","claim_text","evidence_reference","evidence_hash","status","recorded_by","verified_by","revision")
VERSION=("id","profile_id","profile_number","version_number","visual_tokens_json","messaging_json","definition_hash","status")
RELEASE=("id","release_number","profile_id","profile_number","profile_version","definition_hash","release_version","manifest_hash","support_until",*EVIDENCE,"status","available","prepared_by","approved_by","revision")
class FactoryBrandService:
 def __init__(self,db):self.db=db
 async def workspace(self,*,project_id):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  profiles=await rows(FactoryBrandProfile,FactoryBrandProfile.created_at);claims=await rows(FactoryBrandClaim,FactoryBrandClaim.recorded_at);versions=await rows(FactoryBrandVersion,FactoryBrandVersion.created_at);releases=await rows(FactoryBrandRelease,FactoryBrandRelease.prepared_at);events=await rows(FactoryBrandEvidence,FactoryBrandEvidence.recorded_at);active=[x for x in releases if x.available and x.status=="available" and self._utc(x.support_until)>datetime.now(timezone.utc)]
  return {"profiles":[_ser(x,PROFILE) for x in profiles],"claims":[_ser(x,CLAIM) for x in claims],"versions":[_ser(x,VERSION) for x in versions],"releases":[_ser(x,RELEASE) for x in releases],"evidence":[{"id":x.id,"subject_type":x.subject_type,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference} for x in events],"metrics":{"brand_profiles":len(profiles),"verified_claim_percent":round(len([x for x in claims if x.status=="verified"])*100/max(1,len(claims)),2),"active_profiles":len([x for x in profiles if x.status=="active"]),"available_releases":len(active)},"availability":{"application_id":APPLICATION_ID,"status":"available" if active else "pilot","release_version":active[0].release_version if active else None,"support_until":active[0].support_until if active else None},"contract":{"website_published":False,"protected_brand_configuration_overwritten":False,"claim_self_verification":False,"profile_self_approval":False,"release_self_approval":False,"minimum_verified_claims":2}}
 async def create_profile(self,*,project_id,context,actor,brand_name,market_scope,audience,positioning,value_promise,tone,visual_tokens,messaging):
  values=[brand_name,market_scope,audience,positioning,value_promise,tone]
  if not all(str(x).strip() for x in values) or not isinstance(visual_tokens,dict) or not isinstance(messaging,dict):raise ValueError("Brand profile needs market, audience, positioning, promise, tone, visual and message guidance")
  now=datetime.now(timezone.utc);profile=FactoryBrandProfile(id=_id("brand-profile"),**_ctx(context,project_id),profile_number=_num("BRD",project_id),brand_name=brand_name.strip(),market_scope=market_scope.strip(),audience=audience.strip(),positioning=positioning.strip(),value_promise=value_promise.strip(),tone=tone.strip(),status="draft",current_version=1,authored_by=str(actor),created_at=now,updated_at=now,revision=1);payload={"brand_name":profile.brand_name,"market_scope":profile.market_scope,"audience":profile.audience,"positioning":profile.positioning,"value_promise":profile.value_promise,"tone":profile.tone,"visual_tokens":visual_tokens,"messaging":messaging};version=FactoryBrandVersion(id=_id("brand-version"),**_same(profile),profile_id=profile.id,profile_number=profile.profile_number,version_number=1,visual_tokens_json=visual_tokens,messaging_json=messaging,definition_hash=_hash(payload),status="draft",created_by=str(actor),created_at=now);self.db.add_all([profile,version]);await self._event(profile,"profile","profile-authored",version.definition_hash,"Brand strategy draft created; no website configuration changed",actor);await self.db.flush();return {"profile":_ser(profile,PROFILE),"version":_ser(version,VERSION)}
 async def add_claim(self,profile_id,*,project_id,context,actor,claim_type,claim_text,evidence_reference):
  p=await self._get(FactoryBrandProfile,profile_id,project_id,"Brand profile")
  if p.status!="draft" or not all(str(x).strip() for x in (claim_type,claim_text,evidence_reference)):raise ValueError("Brand claim requires a draft profile and evidence reference")
  now=datetime.now(timezone.utc);payload={"profile_number":p.profile_number,"claim_type":claim_type.strip(),"claim_text":claim_text.strip(),"evidence_reference":evidence_reference.strip()};x=FactoryBrandClaim(id=_id("brand-claim"),**_same(p),claim_number=_num("BRC",project_id),profile_id=p.id,profile_number=p.profile_number,claim_type=payload["claim_type"],claim_text=payload["claim_text"],evidence_reference=payload["evidence_reference"],evidence_hash=_hash(payload),status="pending-verification",recorded_by=str(actor),recorded_at=now,revision=1);self.db.add(x);await self._event(x,"claim","claim-recorded",x.evidence_hash,"Brand claim evidence pinned",actor);await self.db.flush();return _ser(x,CLAIM)
 async def verify_claim(self,claim_id,*,project_id,actor,expected_revision,verification_reference):
  x=await self._get(FactoryBrandClaim,claim_id,project_id,"Brand claim");self._rev(x,expected_revision);payload={"profile_number":x.profile_number,"claim_type":x.claim_type,"claim_text":x.claim_text,"evidence_reference":x.evidence_reference}
  if x.status!="pending-verification" or x.recorded_by==str(actor) or not verification_reference.strip() or x.evidence_hash!=_hash(payload):raise ValueError("Brand claim requires independent verification of unchanged evidence")
  x.status="verified";x.verified_by=str(actor);x.verified_at=datetime.now(timezone.utc);x.verification_reference=verification_reference.strip()[:255];x.revision+=1;await self._event(x,"claim","claim-verified",verification_reference,"Independent brand-claim verification completed",actor);await self.db.flush();return _ser(x,CLAIM)
 async def approve_profile(self,profile_id,*,project_id,actor,expected_revision,approval_reference):
  p=await self._get(FactoryBrandProfile,profile_id,project_id,"Brand profile");self._rev(p,expected_revision);claims=await self._claims(p.id,project_id);v=await self._version(p.id,project_id)
  if p.status!="draft" or p.authored_by==str(actor) or len([x for x in claims if x.status=="verified"])<2 or not approval_reference.strip() or not v:raise ValueError("Brand activation requires two independently verified claims and independent approval")
  now=datetime.now(timezone.utc);p.status="active";p.approved_by=str(actor);p.approved_at=now;p.approval_reference=approval_reference.strip()[:255];p.updated_at=now;p.revision+=1;v.status="active";v.activated_by=str(actor);v.activated_at=now;await self._event(p,"profile","profile-activated",approval_reference,"Brand version activated without publishing a website",actor);await self.db.flush();return _ser(p,PROFILE)
 async def prepare_release(self,profile_id,*,project_id,context,actor,release_version,support_owner,support_until,**evidence):
  p=await self._get(FactoryBrandProfile,profile_id,project_id,"Brand profile");v=await self._version(p.id,project_id);clean={k:str(evidence.get(k,"")).strip()[:255] for k in EVIDENCE};end=self._utc(support_until)
  if p.status!="active" or not v or v.status!="active" or not release_version.strip() or not support_owner.strip() or not all(clean.values()) or end<=datetime.now(timezone.utc):raise ValueError("Brand release requires active immutable profile, evidence and future support")
  manifest={"application_id":APPLICATION_ID,"profile_number":p.profile_number,"profile_version":v.version_number,"definition_hash":v.definition_hash,"release_version":release_version.strip(),"support_owner":support_owner.strip(),"support_until":end.isoformat(),"evidence":clean,"website_published":False,"protected_brand_configuration_overwritten":False};x=FactoryBrandRelease(id=_id("brand-release"),**_ctx(context,project_id),release_number=_num("BRR",project_id),application_id=APPLICATION_ID,profile_id=p.id,profile_number=p.profile_number,profile_version=v.version_number,definition_hash=v.definition_hash,release_version=manifest["release_version"],manifest_json=manifest,manifest_hash=_hash(manifest),support_owner=manifest["support_owner"],support_until=end,**clean,status="pending-approval",available=False,prepared_by=str(actor),prepared_at=datetime.now(timezone.utc),revision=1);self.db.add(x);await self._event(x,"release","availability-prepared",x.manifest_hash,"Brand release evidence pinned; no site publish",actor);await self.db.flush();return _ser(x,RELEASE)
 async def approve_release(self,release_id,*,project_id,actor,expected_revision,approval_reference):
  x=await self._get(FactoryBrandRelease,release_id,project_id,"Brand release");self._rev(x,expected_revision);p=await self._get(FactoryBrandProfile,x.profile_id,project_id,"Brand profile");v=await self._version(p.id,project_id);obj=await self.db.scalar(select(FactoryCoreObjectContract).where(FactoryCoreObjectContract.id=="brand-profile",FactoryCoreObjectContract.lifecycle_status=="frozen"));event=await self.db.scalar(select(FactoryCoreEventContract).where(FactoryCoreEventContract.id=="brand-released",FactoryCoreEventContract.lifecycle_status=="frozen"))
  if x.status!="pending-approval" or x.prepared_by==str(actor) or not approval_reference.strip() or x.manifest_hash!=_hash(x.manifest_json) or self._utc(x.support_until)<=datetime.now(timezone.utc) or not obj or not event or p.status!="active" or not v or v.definition_hash!=x.definition_hash:raise ValueError("Brand availability requires independent approval, unchanged active version, support and frozen contracts")
  x.status="available";x.available=True;x.approved_by=str(actor);x.approved_at=datetime.now(timezone.utc);x.approval_reference=approval_reference.strip()[:255];x.revision+=1;await self._event(x,"release","brand-released",approval_reference,"Commercial brand guidance release approved",actor);await self.db.flush();return _ser(x,RELEASE)
 async def _get(self,m,id,p,label):
  x=await self.db.scalar(select(m).where(m.id==id,m.project_id==p))
  if not x:raise KeyError(f"{label} not found in this tenant plan")
  return x
 async def _claims(self,id,p):return (await self.db.execute(select(FactoryBrandClaim).where(FactoryBrandClaim.profile_id==id,FactoryBrandClaim.project_id==p))).scalars().all()
 async def _version(self,id,p):return await self.db.scalar(select(FactoryBrandVersion).where(FactoryBrandVersion.profile_id==id,FactoryBrandVersion.project_id==p,FactoryBrandVersion.status.in_(("draft","active"))).order_by(FactoryBrandVersion.version_number.desc()))
 @staticmethod
 def _rev(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 @staticmethod
 def _utc(x):return x.replace(tzinfo=timezone.utc) if x.tzinfo is None else x.astimezone(timezone.utc)
 async def _event(self,x,subject_type,evidence_type,ref,note,actor):
  number=next((getattr(x,k,None) for k in ("profile_number","claim_number","release_number") if getattr(x,k,None)),str(x.id));self.db.add(FactoryBrandEvidence(id=_id("brand-evidence"),**_same(x),evidence_number=_num("BRE",x.project_id),subject_type=subject_type,subject_id=x.id,subject_number=number,evidence_type=evidence_type,evidence_reference=str(ref)[:255],note=note,recorded_by=str(actor),recorded_at=datetime.now(timezone.utc)))
