"""Search-performance observations through independent verification and bounded analysis handoff."""
from datetime import datetime,timezone
import hashlib,json,secrets
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from models.factory_contract import FactoryCoreEventContract,FactoryCoreObjectContract
from models.factory_search_share import FactorySearchShareDataset,FactorySearchShareSnapshot,FactorySearchShareRelease,FactorySearchShareEvidence
APPLICATION_ID="trust.search-share";FORBIDDEN={"password","secret","token","api_key","credential","customer_email","customer_phone"};DATASET=("id","dataset_number","source_reference","market","search_engine","device","observed_from","observed_to","status","revision");SNAPSHOT=("id","snapshot_number","dataset_id","dataset_number","manifest_hash","status","captured_by","verified_by","revision");RELEASE=("id","release_number","dataset_id","snapshot_id","snapshot_number","target","status","available","consumer_receipt_reference","revision")
def _id(x):return f"{x}-{secrets.token_urlsafe(18)}"
def _no(x,p):return f"{x}-{p}-{datetime.now(timezone.utc):%Y%m%d%H%M%S%f}-{secrets.token_hex(3).upper()}"
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _ctx(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _same(x):return {n:getattr(x,n) for n in("project_id","agent_path","tenant_id","client_id","plan_id")}
def _pick(x,n):return {k:getattr(x,k) for k in n}
def _unsafe(v):
 if isinstance(v,dict):return any(str(k).casefold() in FORBIDDEN or _unsafe(i) for k,i in v.items())
 if isinstance(v,list):return any(_unsafe(i) for i in v)
 return isinstance(v,str) and ("<script" in v.casefold() or "javascript:" in v.casefold())
class FactorySearchShareService:
 def __init__(self,db:AsyncSession):self.db=db
 async def workspace(self,*,project_id):
  async def rows(m,o):return list((await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all())
  datasets=await rows(FactorySearchShareDataset,FactorySearchShareDataset.created_at);snapshots=await rows(FactorySearchShareSnapshot,FactorySearchShareSnapshot.captured_at);releases=await rows(FactorySearchShareRelease,FactorySearchShareRelease.prepared_at);evidence=await rows(FactorySearchShareEvidence,FactorySearchShareEvidence.recorded_at);ready=[x for x in releases if x.status=="available" and x.available]
  return {"datasets":[_pick(x,DATASET) for x in datasets],"snapshots":[_pick(x,SNAPSHOT) for x in snapshots],"releases":[_pick(x,RELEASE) for x in releases],"evidence":[{"id":x.id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference} for x in evidence],"metrics":{"source_datasets":len(datasets),"verified_snapshots":sum(x.status=="verified" for x in snapshots),"acknowledged_analyses":len(ready),"evidence_records":len(evidence)},"availability":{"application_id":APPLICATION_ID,"status":"available" if ready else "pilot","release_version":ready[0].snapshot_number if ready else None},"contract":{"source_dataset_mutated_directly":False,"ranking_guaranteed":False,"single_action_causality_claimed":False,"automatic_site_or_ad_change":False,"snapshot_self_verification":False,"release_self_approval":False,"consumer_handoff_required":True}}
 async def create_dataset(self,*,project_id,context,actor,source_reference,market,search_engine,device,observed_from,observed_to):
  if not all(str(v).strip() for v in(source_reference,market,search_engine,device,observed_from,observed_to)) or observed_from>observed_to:raise ValueError("Dataset requires source, market, engine, device and valid observation window")
  x=FactorySearchShareDataset(id=_id("search-share-dataset"),**_ctx(context,project_id),dataset_number=_no("SSD",project_id),source_reference=source_reference.strip()[:255],market=market.strip()[:80],search_engine=search_engine.strip()[:40],device=device.strip()[:40],observed_from=observed_from.strip()[:32],observed_to=observed_to.strip()[:32],status="active",created_by=str(actor),created_at=datetime.now(timezone.utc),revision=1);self.db.add(x);await self._event(x,"dataset","search-performance-source-registered",x.source_reference,"Source is referenced; no search ranking or causal result is promised",actor);await self.db.flush();return _pick(x,DATASET)
 async def capture_snapshot(self,dataset_id,*,project_id,context,actor,performance_manifest):
  d=await self._get(FactorySearchShareDataset,dataset_id,project_id,"Search performance dataset")
  if d.status!="active" or not performance_manifest or _unsafe(performance_manifest):raise ValueError("Snapshot requires active dataset and safe performance manifest")
  payload={"dataset_number":d.dataset_number,"source_reference":d.source_reference,"market":d.market,"search_engine":d.search_engine,"device":d.device,"observed_from":d.observed_from,"observed_to":d.observed_to,"performance_manifest":performance_manifest};x=FactorySearchShareSnapshot(id=_id("search-share-snapshot"),**_same(d),snapshot_number=_no("SSS",project_id),dataset_id=d.id,dataset_number=d.dataset_number,performance_manifest_json=performance_manifest,manifest_hash=_hash(payload),status="captured",captured_by=str(actor),captured_at=datetime.now(timezone.utc),revision=1);self.db.add(x);await self._event(x,"snapshot","search-performance-snapshot-captured",x.manifest_hash,"Snapshot is immutable observation evidence, not a causal ranking claim",actor);await self.db.flush();return _pick(x,SNAPSHOT)
 async def verify_snapshot(self,snapshot_id,*,project_id,actor,expected_revision,verification_reference):
  x=await self._get(FactorySearchShareSnapshot,snapshot_id,project_id,"Search performance snapshot");self._rev(x,expected_revision);d=await self._get(FactorySearchShareDataset,x.dataset_id,project_id,"Search performance dataset");expected=_hash({"dataset_number":d.dataset_number,"source_reference":d.source_reference,"market":d.market,"search_engine":d.search_engine,"device":d.device,"observed_from":d.observed_from,"observed_to":d.observed_to,"performance_manifest":x.performance_manifest_json})
  if x.status!="captured" or x.captured_by==str(actor) or not verification_reference.strip() or x.manifest_hash!=expected:raise ValueError("Snapshot requires independent verification of unchanged observed data")
  x.status="verified";x.verified_by=str(actor);x.verified_at=datetime.now(timezone.utc);x.verification_reference=verification_reference.strip()[:255];x.revision+=1;await self._event(x,"snapshot","search-performance-snapshot-verified",x.verification_reference,"Independent verifier accepted data quality and provenance",actor);await self.db.flush();return _pick(x,SNAPSHOT)
 async def prepare_release(self,snapshot_id,*,project_id,context,actor,target,analysis_manifest,rollback_reference):
  s=await self._get(FactorySearchShareSnapshot,snapshot_id,project_id,"Search performance snapshot");d=await self._get(FactorySearchShareDataset,s.dataset_id,project_id,"Search performance dataset")
  if s.status!="verified" or target not in {"marketing-owner","executive-owner","seo-operations"} or not analysis_manifest or _unsafe(analysis_manifest) or not rollback_reference.strip():raise ValueError("Analysis handoff requires verified snapshot, safe analysis, allowed target and rollback reference")
  m={"application_id":APPLICATION_ID,"dataset_number":d.dataset_number,"snapshot_number":s.snapshot_number,"source_manifest_hash":s.manifest_hash,"source_reference":d.source_reference,"market":d.market,"search_engine":d.search_engine,"device":d.device,"observed_from":d.observed_from,"observed_to":d.observed_to,"target":target,"analysis_manifest":analysis_manifest,"automatic_site_or_ad_change":False,"ranking_guaranteed":False,"single_action_causality_claimed":False,"consumer_receipt_required":True,"rollback_reference":rollback_reference.strip()};x=FactorySearchShareRelease(id=_id("search-share-release"),**_ctx(context,project_id),release_number=_no("SSR",project_id),dataset_id=d.id,snapshot_id=s.id,snapshot_number=s.snapshot_number,target=target,analysis_manifest_json=m,manifest_hash=_hash(m),rollback_reference=rollback_reference.strip()[:255],status="pending-approval",prepared_by=str(actor),available=False,prepared_at=datetime.now(timezone.utc),revision=1);self.db.add(x);await self._event(x,"release","search-share-analysis-prepared",x.manifest_hash,"Handoff reports bounded trend/correlation; it does not change ads, site or content",actor);await self.db.flush();return _pick(x,RELEASE)
 async def approve_release(self,release_id,*,project_id,actor,expected_revision,approval_reference):
  x=await self._get(FactorySearchShareRelease,release_id,project_id,"Search share analysis handoff");self._rev(x,expected_revision);s=await self._get(FactorySearchShareSnapshot,x.snapshot_id,project_id,"Search performance snapshot");o=await self.db.scalar(select(FactoryCoreObjectContract).where(FactoryCoreObjectContract.id=="search-share-performance-snapshot",FactoryCoreObjectContract.lifecycle_status=="frozen"));e=await self.db.scalar(select(FactoryCoreEventContract).where(FactoryCoreEventContract.id=="search-share-analysis-released",FactoryCoreEventContract.lifecycle_status=="frozen"))
  if x.status!="pending-approval" or x.prepared_by==str(actor) or not approval_reference.strip() or x.manifest_hash!=_hash(x.analysis_manifest_json) or s.status!="verified" or not o or not e:raise ValueError("Analysis requires independent approval, frozen contracts and unchanged verified snapshot")
  x.status="approved";x.approved_by=str(actor);x.approval_reference=approval_reference.strip()[:255];x.revision+=1;await self._event(x,"release","search-share-analysis-approved",x.approval_reference,"Awaiting customer receipt; no outcome is guaranteed",actor);await self.db.flush();return _pick(x,RELEASE)
 async def acknowledge_release(self,release_id,*,project_id,actor,expected_revision,consumer_receipt_reference):
  x=await self._get(FactorySearchShareRelease,release_id,project_id,"Search share analysis handoff");self._rev(x,expected_revision)
  if x.status!="approved" or x.approved_by==str(actor) or not consumer_receipt_reference.strip():raise ValueError("Consumer acknowledgement requires independently approved analysis handoff")
  x.status="available";x.available=True;x.consumer_receipt_reference=consumer_receipt_reference.strip()[:255];x.acknowledged_at=datetime.now(timezone.utc);x.revision+=1;await self._event(x,"release","search-share-analysis-released",x.consumer_receipt_reference,"Consumer accepted the bounded performance analysis",actor);await self.db.flush();return _pick(x,RELEASE)
 async def _get(self,m,item_id,project_id,label):
  x=await self.db.scalar(select(m).where(m.id==item_id,m.project_id==project_id))
  if not x:raise KeyError(f"{label} not found in this tenant plan")
  return x
 @staticmethod
 def _rev(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,subject_type,evidence_type,reference,note,actor):
  n=next((getattr(x,k,None) for k in("dataset_number","snapshot_number","release_number") if getattr(x,k,None)),str(x.id));self.db.add(FactorySearchShareEvidence(id=_id("search-share-evidence"),**_same(x),evidence_number=_no("SSE",x.project_id),subject_type=subject_type,subject_id=x.id,subject_number=n,evidence_type=evidence_type,evidence_reference=str(reference)[:255],note=note,recorded_by=str(actor),recorded_at=datetime.now(timezone.utc)))
