"""Governed B2B ordering and B2C checkout without payment/order fabrication."""
from datetime import datetime,timezone
from decimal import Decimal
import hashlib,json,secrets
from core.tenant_context import TenantContext
from models.factory_channel_feed import FactoryChannelListing
from models.factory_commerce import FactoryCommerceAcceptance,FactoryCommerceCheckout,FactoryCommerceEvidence,FactoryCommerceHandoff,FactoryCommercePayment
from models.factory_cpq import FactoryCpqQuote
from models.factory_fulfillment import FactoryFulfillmentOrder
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

C=("id","checkout_number","commerce_mode","source_type","source_id","source_number","source_revision","source_hash","buyer_reference_hash","currency","subtotal","quantity","status","created_by","revision");A=("id","acceptance_number","checkout_id","checkout_number","terms_version","locale","destination_country","fulfillment_mode","purchase_reference_hash","acceptance_reference_hash","acceptance_hash","status","recorded_by","reviewed_by","review_reference","review_note","revision");P=("id","payment_number","checkout_id","acceptance_id","method","amount","currency","processor_reference_hash","status","initiated_by","verified_by","verification_reference","revision");H=("id","handoff_number","checkout_id","payment_id","order_intent_id","manifest_hash","consumer_mutated","status","created_by","acknowledged_by","decision","authority_system","authority_reference","authoritative_order_id","revision")
def _id(k):return f"{k}-{secrets.token_urlsafe(18)}"
def _num(p,pid):return f"{p}-{pid}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S%f')}-{secrets.token_hex(3).upper()}"
def _ctx(c,p):return {"project_id":p,"agent_path":c.agent_path,"tenant_id":c.tenant_id,"client_id":c.client_id,"plan_id":c.plan_id or f"plan-{p}"}
def _same(x):return {k:getattr(x,k) for k in ("project_id","agent_path","tenant_id","client_id","plan_id")}
def _hash(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def _ser(x,f):
 d={k:getattr(x,k) for k in f}
 for k,v in list(d.items()):
  if isinstance(v,Decimal):d[k]=str(v)
 return d
def _lines(x):
 try:return json.loads(x or "[]")
 except (TypeError,ValueError):return []

class FactoryCommerceService:
 def __init__(self,db:AsyncSession):self.db=db
 async def list_workspace(self,*,project_id:int):
  async def rows(m,o):return (await self.db.execute(select(m).where(m.project_id==project_id).order_by(o.desc()).limit(500))).scalars().all()
  cs=await rows(FactoryCommerceCheckout,FactoryCommerceCheckout.created_at);aa=await rows(FactoryCommerceAcceptance,FactoryCommerceAcceptance.recorded_at);pp=await rows(FactoryCommercePayment,FactoryCommercePayment.initiated_at);hh=await rows(FactoryCommerceHandoff,FactoryCommerceHandoff.created_at);ee=await rows(FactoryCommerceEvidence,FactoryCommerceEvidence.recorded_at)
  return {"checkouts":[_ser(x,C) for x in cs],"acceptances":[_ser(x,A) for x in aa],"payments":[_ser(x,P) for x in pp],"handoffs":[_ser(x,H) for x in hh],"evidence":[{"id":x.id,"subject_type":x.subject_type,"subject_id":x.subject_id,"evidence_type":x.evidence_type,"evidence_reference":x.evidence_reference,"recorded_by":x.recorded_by} for x in ee],"sources":await self._sources(project_id),"metrics":{"checkouts":len(cs),"b2b_checkouts":len([x for x in cs if x.commerce_mode=="b2b"]),"b2c_checkouts":len([x for x in cs if x.commerce_mode=="b2c"]),"terms_review_percent":round(len([x for x in aa if x.status=="approved"])*100/max(1,len(aa)),2),"payment_verification_percent":round(len([x for x in pp if x.status=="verified"])*100/max(1,len(pp)),2),"order_confirmation_percent":round(len([x for x in hh if x.status=="confirmed"])*100/max(1,len(hh)),2)},"contract":{"source_records_copied":False,"authoritative_commercial_source_pinned":True,"source_revalidated_before_each_action":True,"raw_buyer_identifier_stored":False,"payment_secret_stored":False,"payment_charge_created":False,"checkout_direct_order_confirmation":False,"terms_self_review":False,"payment_self_verification":False,"immutable_order_intent_manifest":True,"oms_acknowledgement_required":True}}
 async def create_checkout(self,*,project_id:int,context:TenantContext,actor:str,commerce_mode:str,source_id:str,buyer_reference:str,quantity:Decimal):
  if commerce_mode not in {"b2b","b2c"} or not buyer_reference.strip():raise ValueError("Checkout requires B2B/B2C mode and buyer reference")
  source,snap=await self._source(commerce_mode,source_id,project_id,quantity);now=datetime.now(timezone.utc);x=FactoryCommerceCheckout(id=_id("commerce-checkout"),**_ctx(context,project_id),checkout_number=_num("CHK",project_id),commerce_mode=commerce_mode,source_type="cpq-quote" if commerce_mode=="b2b" else "channel-listing",source_id=source.id,source_number=snap["source_number"],source_revision=source.revision,source_snapshot_json=snap,source_hash=_hash(snap),buyer_reference_hash=_hash(buyer_reference.strip()),currency=snap["currency"],subtotal=Decimal(snap["subtotal"]),quantity=Decimal(snap["quantity"]),status="draft",created_by=str(actor),created_at=now,updated_at=now,revision=1);self.db.add(x);await self._event(x,"checkout","checkout-created",x.source_hash,"Pinned commercial facts without raw buyer identity",actor);await self.db.flush();return _ser(x,C)
 async def accept_terms(self,checkout_id:str,*,project_id:int,context:TenantContext,actor:str,terms_version:str,locale:str,destination_country:str,fulfillment_mode:str,purchase_reference:str,acceptance_reference:str):
  x=await self._get(FactoryCommerceCheckout,checkout_id,project_id,"Checkout");await self._validate(x)
  if x.status!="draft" or x.created_by==str(actor) or not all(v.strip() for v in (terms_version,locale,destination_country,fulfillment_mode,purchase_reference,acceptance_reference)):raise ValueError("Buyer terms require complete evidence and independent actor")
  payload={"checkout_number":x.checkout_number,"source_hash":x.source_hash,"terms_version":terms_version.strip(),"locale":locale.strip(),"destination_country":destination_country.strip().upper(),"fulfillment_mode":fulfillment_mode.strip(),"purchase_reference_hash":_hash(purchase_reference.strip()),"acceptance_reference_hash":_hash(acceptance_reference.strip())};now=datetime.now(timezone.utc);a=FactoryCommerceAcceptance(id=_id("commerce-acceptance"),**_ctx(context,project_id),acceptance_number=_num("CTA",project_id),checkout_id=x.id,checkout_number=x.checkout_number,terms_version=payload["terms_version"],locale=payload["locale"],destination_country=payload["destination_country"],fulfillment_mode=payload["fulfillment_mode"],purchase_reference_hash=payload["purchase_reference_hash"],acceptance_reference_hash=payload["acceptance_reference_hash"],acceptance_hash=_hash(payload),status="pending-review",recorded_by=str(actor),recorded_at=now,revision=1);self.db.add(a);x.status="terms-pending";x.updated_at=now;x.revision+=1;await self._event(a,"acceptance","terms-accepted",a.acceptance_hash,"Hashed buyer acceptance and purchase reference",actor);await self.db.flush();return _ser(a,A)
 async def review_terms(self,acceptance_id:str,*,project_id:int,actor:str,expected_revision:int,decision:str,review_reference:str,review_note:str):
  a=await self._get(FactoryCommerceAcceptance,acceptance_id,project_id,"Terms acceptance");self._rev(a,expected_revision);x=await self._get(FactoryCommerceCheckout,a.checkout_id,project_id,"Checkout");await self._validate(x)
  if a.status!="pending-review" or a.recorded_by==str(actor) or decision not in {"approve","reject"} or not review_reference.strip() or not review_note.strip():raise ValueError("Buyer terms require independent documented review")
  a.status="approved" if decision=="approve" else "rejected";a.reviewed_by=str(actor);a.reviewed_at=datetime.now(timezone.utc);a.review_reference=review_reference.strip()[:255];a.review_note=review_note.strip();a.revision+=1;x.status="terms-approved" if decision=="approve" else "terms-rejected";x.updated_at=datetime.now(timezone.utc);x.revision+=1;await self._event(a,"acceptance","terms-reviewed",review_reference,"Independently reviewed unchanged acceptance",actor);await self.db.flush();return _ser(a,A)
 async def initiate_payment(self,checkout_id:str,*,project_id:int,context:TenantContext,actor:str,method:str,processor_reference:str):
  x=await self._get(FactoryCommerceCheckout,checkout_id,project_id,"Checkout");await self._validate(x);a=await self.db.scalar(select(FactoryCommerceAcceptance).where(FactoryCommerceAcceptance.checkout_id==x.id,FactoryCommerceAcceptance.status=="approved"))
  if x.status!="terms-approved" or not a or method not in {"purchase-order","bank-transfer","card-token"} or not processor_reference.strip():raise ValueError("Approved terms and tokenized payment method are required")
  now=datetime.now(timezone.utc);p=FactoryCommercePayment(id=_id("commerce-payment"),**_ctx(context,project_id),payment_number=_num("PAY",project_id),checkout_id=x.id,acceptance_id=a.id,method=method,amount=x.subtotal,currency=x.currency,processor_reference_hash=_hash(processor_reference.strip()),status="pending-verification",initiated_by=str(actor),initiated_at=now,revision=1);self.db.add(p);x.status="payment-pending";x.updated_at=now;x.revision+=1;await self._event(p,"payment","payment-intent-created",p.processor_reference_hash,"Stored token hash; no charge or finance posting",actor);await self.db.flush();return _ser(p,P)
 async def verify_payment(self,payment_id:str,*,project_id:int,actor:str,expected_revision:int,verification_reference:str):
  p=await self._get(FactoryCommercePayment,payment_id,project_id,"Payment intent");self._rev(p,expected_revision);x=await self._get(FactoryCommerceCheckout,p.checkout_id,project_id,"Checkout");await self._validate(x)
  if p.status!="pending-verification" or p.initiated_by==str(actor) or not verification_reference.strip() or Decimal(p.amount)!=Decimal(x.subtotal) or p.currency!=x.currency:raise ValueError("Payment requires independent verification of exact totals")
  p.status="verified";p.verified_by=str(actor);p.verified_at=datetime.now(timezone.utc);p.verification_reference=verification_reference.strip()[:255];p.revision+=1;x.status="payment-verified";x.updated_at=datetime.now(timezone.utc);x.revision+=1;await self._event(p,"payment","payment-verified",verification_reference,"Verified external evidence without charging",actor);await self.db.flush();return _ser(p,P)
 async def submit_order(self,checkout_id:str,*,project_id:int,context:TenantContext,actor:str,delivery_reference:str):
  x=await self._get(FactoryCommerceCheckout,checkout_id,project_id,"Checkout");await self._validate(x);a=await self.db.scalar(select(FactoryCommerceAcceptance).where(FactoryCommerceAcceptance.checkout_id==x.id,FactoryCommerceAcceptance.status=="approved"));p=await self.db.scalar(select(FactoryCommercePayment).where(FactoryCommercePayment.checkout_id==x.id,FactoryCommercePayment.status=="verified"))
  if x.status!="payment-verified" or not a or not p or not delivery_reference.strip():raise ValueError("Order intent requires approved terms and verified payment evidence")
  source=await self._get(FactoryCpqQuote if x.commerce_mode=="b2b" else FactoryChannelListing,x.source_id,project_id,"Commerce source");intent=source.order_intent_id if x.commerce_mode=="b2b" else _id("commerce-order-intent");manifest={"checkout_number":x.checkout_number,"commerce_mode":x.commerce_mode,"source_type":x.source_type,"source_id":x.source_id,"source_number":x.source_number,"source_revision":x.source_revision,"source_hash":x.source_hash,"buyer_reference_hash":x.buyer_reference_hash,"acceptance_hash":a.acceptance_hash,"payment_number":p.payment_number,"payment_method":p.method,"amount":str(p.amount),"currency":p.currency,"order_intent_id":intent};now=datetime.now(timezone.utc);h=FactoryCommerceHandoff(id=_id("commerce-handoff"),**_ctx(context,project_id),handoff_number=_num("COH",project_id),checkout_id=x.id,payment_id=p.id,order_intent_id=intent,manifest_json=manifest,manifest_hash=_hash(manifest),consumer_mutated=False,status="pending-acknowledgement",created_by=str(actor),created_at=now,revision=1);self.db.add(h);x.status="order-submitted";x.updated_at=now;x.revision+=1;await self._event(h,"handoff","order-intent-submitted",delivery_reference,"Immutable intent; checkout did not confirm order",actor);await self.db.flush();return _ser(h,H)
 async def acknowledge_order(self,handoff_id:str,*,project_id:int,actor:str,expected_revision:int,decision:str,authority_system:str,authority_reference:str,authoritative_order_id:str|None=None):
  h=await self._get(FactoryCommerceHandoff,handoff_id,project_id,"Order handoff");self._rev(h,expected_revision);x=await self._get(FactoryCommerceCheckout,h.checkout_id,project_id,"Checkout");await self._validate(x)
  if h.status!="pending-acknowledgement" or h.created_by==str(actor) or decision not in {"confirmed","rejected"} or not authority_system.strip() or not authority_reference.strip() or h.manifest_hash!=_hash(h.manifest_json):raise ValueError("OMS decision requires independent acknowledgement of unchanged intent")
  if decision=="confirmed" and x.commerce_mode=="b2b":
   order=await self._get(FactoryFulfillmentOrder,authoritative_order_id or "",project_id,"Authoritative order")
   if order.order_intent_id!=h.order_intent_id or order.quote_id!=x.source_id or order.status!="confirmed" or Decimal(order.order_total)!=Decimal(x.subtotal) or order.currency!=x.currency:raise ValueError("B2B confirmation requires exact confirmed OMS order")
  h.status=decision;h.acknowledged_by=str(actor);h.acknowledged_at=datetime.now(timezone.utc);h.decision=decision;h.authority_system=authority_system.strip()[:64];h.authority_reference=authority_reference.strip()[:255];h.authoritative_order_id=authoritative_order_id;h.revision+=1;x.status=f"order-{decision}";x.updated_at=datetime.now(timezone.utc);x.revision+=1;await self._event(h,"handoff","order-decision-acknowledged",authority_reference,"Recorded authority decision without order mutation",actor);await self.db.flush();return _ser(h,H)
 async def _sources(self,pid):
  used={(a,b) for a,b in (await self.db.execute(select(FactoryCommerceCheckout.source_type,FactoryCommerceCheckout.source_id).where(FactoryCommerceCheckout.project_id==pid))).all()};qs=(await self.db.execute(select(FactoryCpqQuote).where(FactoryCpqQuote.project_id==pid,FactoryCpqQuote.status=="accepted").order_by(FactoryCpqQuote.created_at.desc()))).scalars().all();ls=(await self.db.execute(select(FactoryChannelListing).where(FactoryChannelListing.project_id==pid,FactoryChannelListing.status=="validated",FactoryChannelListing.price_mode=="connector-reference").order_by(FactoryChannelListing.created_at.desc()))).scalars().all();return [{"commerce_mode":"b2b","source_id":x.id,"source_number":x.quote_number,"currency":x.currency,"subtotal":str(x.subtotal)} for x in qs if ("cpq-quote",x.id) not in used]+[{"commerce_mode":"b2c","source_id":x.id,"source_number":x.listing_number,"currency":x.currency,"subtotal":str(x.price_amount)} for x in ls if ("channel-listing",x.id) not in used and x.availability_status!="out_of_stock"]
 async def _source(self,mode,i,pid,q):
  if Decimal(q)<=0:raise ValueError("Checkout quantity must be positive")
  if mode=="b2b":
   x=await self._get(FactoryCpqQuote,i,pid,"Accepted quote")
   if x.status!="accepted" or not x.order_intent_id:raise ValueError("B2B checkout requires accepted CPQ quote intent")
   lines=[{k:v for k,v in y.items() if k!="unit_cost"} for y in _lines(x.lines_json)];qty=sum(Decimal(str(y.get("quantity",0))) for y in lines);return x,{"source_number":x.quote_number,"status":x.status,"order_intent_id":x.order_intent_id,"currency":x.currency,"subtotal":str(x.subtotal),"quantity":str(qty),"lines":lines,"revision":x.revision}
  x=await self._get(FactoryChannelListing,i,pid,"Validated listing")
  if x.status!="validated" or x.price_mode!="connector-reference" or not x.price_reference or not x.inventory_reference or x.availability_status=="out_of_stock":raise ValueError("B2C checkout requires validated available connector facts")
  quantity=Decimal(q).normalize();return x,{"source_number":x.listing_number,"status":x.status,"product_identifier":x.product_identifier,"source_product_hash":x.source_product_hash,"external_sku":x.external_sku,"price_reference":x.price_reference,"inventory_reference":x.inventory_reference,"availability_status":x.availability_status,"currency":x.currency,"unit_price":str(x.price_amount),"subtotal":str((Decimal(x.price_amount)*quantity).quantize(Decimal("0.01"))),"quantity":str(quantity),"revision":x.revision}
 async def _validate(self,x):
  source,snap=await self._source(x.commerce_mode,x.source_id,x.project_id,x.quantity)
  if source.revision!=x.source_revision or snap!=x.source_snapshot_json or _hash(snap)!=x.source_hash:raise ValueError("Authoritative commerce source changed; checkout is blocked")
 async def _get(self,m,i,p,l):
  x=await self.db.scalar(select(m).where(m.id==i,m.project_id==p))
  if not x:raise KeyError(f"{l} not found")
  return x
 @staticmethod
 def _rev(x,e):
  if int(x.revision)!=int(e):raise ValueError("Revision conflict")
 async def _event(self,x,t,k,r,n,a):
  num=next((getattr(x,z,None) for z in ("checkout_number","acceptance_number","payment_number","handoff_number") if getattr(x,z,None)),str(x.id));self.db.add(FactoryCommerceEvidence(id=_id("commerce-evidence"),**_same(x),evidence_number=_num("COE",x.project_id),subject_type=t,subject_id=x.id,subject_number=num,evidence_type=k,evidence_reference=str(r)[:255],note=n,recorded_by=str(a),recorded_at=datetime.now(timezone.utc)))
