import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/use-toast";
import { acknowledgeCompanyProfilePublication, approveCompanyProfilePublication, createCompanyProfile, draftCompanyProfileVersion, listCompanyProfileWorkspace, prepareCompanyProfilePublication, verifyCompanyProfileVersion, type CompanyProfileWorkspace } from "@/lib/factory-company-profile-api";

const empty: CompanyProfileWorkspace = { profiles: [], versions: [], publications: [], evidence: [], metrics: {}, availability: { application_id: "content.company", status: "pilot", release_version: null }, contract: {} };

export function CompanyProfileGovernance({ profileManifest }: { profileManifest: object }) {
  const [workspace, setWorkspace] = useState(empty); const [mode, setMode] = useState("loading"); const [project, setProject] = useState(1);
  const load = async () => { try { setMode("loading"); setWorkspace(await listCompanyProfileWorkspace(project)); setMode("live"); } catch (error) { setMode("error"); toast({ variant: "destructive", title: error instanceof Error ? error.message : "企业资料治理加载失败" }); } };
  useEffect(() => { void load(); }, [project]);
  const run = async (action: () => Promise<unknown>, message: string) => { try { await action(); toast({ title: message }); await load(); } catch (error) { toast({ variant: "destructive", title: error instanceof Error ? error.message : "企业资料治理操作失败" }); await load(); } };
  const ref = (prefix: string, revision: number) => ({ expected_revision: revision, reference: `${prefix}-${Date.now()}` });
  const profile = workspace.profiles[0]; const draft = workspace.versions.find((item) => item.profile_id === profile?.id && item.status === "draft"); const verified = workspace.versions.find((item) => item.profile_id === profile?.id && item.status === "verified"); const publication = workspace.publications.find((item) => item.profile_id === profile?.id);
  return <Card data-company-profile-governance data-company-profile-mode={mode} data-company-profile-availability={workspace.availability.status} className="border-primary/20">
    <CardHeader className="gap-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle className="text-base">企业资料受控发布</CardTitle><CardDescription>将当前本地编辑内容固化为可追溯版本；需独立核验、批准及下游回执，绝不覆盖本地草稿或源系统。</CardDescription></div><Input className="w-20" aria-label="企业资料项目编号" value={project} onChange={(event) => setProject(Number(event.target.value) || 1)} /></div><div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{Object.entries(workspace.metrics).map(([key, value]) => <span key={key} data-company-profile-metric>{key}: <b>{value}</b></span>)}</div></CardHeader>
    <CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button size="sm" data-company-profile-create disabled={Boolean(profile)} onClick={() => void run(() => createCompanyProfile(project, { profile_key: "corporate-profile", display_name: "企业资料主档" }), "企业资料主档已建立")}>建立资料主档</Button><Button size="sm" data-company-profile-draft disabled={!profile || Boolean(draft) || Boolean(verified)} onClick={() => profile && void run(() => draftCompanyProfileVersion(project, profile.id, { locale: "zh-CN", profile_manifest: structuredClone(profileManifest) as Record<string, unknown>, source_reference: `COMPANY-EDITOR-${Date.now()}` }), "当前资料已固化为待核验版本")}>固化当前资料</Button><Button size="sm" data-company-profile-verify disabled={!draft} onClick={() => draft && void run(() => verifyCompanyProfileVersion(project, draft.id, ref("COMPANY-VERIFY", draft.revision)), "资料版本已独立核验")}>独立核验</Button><Button size="sm" data-company-profile-publication-prepare disabled={!verified || Boolean(publication)} onClick={() => verified && void run(() => prepareCompanyProfilePublication(project, verified.id, { target: "website-content", rollback_reference: `COMPANY-ROLLBACK-${Date.now()}` }), "下游资料交接已准备")}>准备交接</Button><Button size="sm" data-company-profile-publication-approve disabled={!publication || publication.status !== "pending-approval"} onClick={() => publication && void run(() => approveCompanyProfilePublication(project, publication.id, ref("COMPANY-APPROVE", publication.revision)), "资料交接已独立批准")}>独立批准</Button><Button size="sm" data-company-profile-publication-acknowledge disabled={!publication || publication.status !== "approved"} onClick={() => publication && void run(() => acknowledgeCompanyProfilePublication(project, publication.id, ref("COMPANY-RECEIPT", publication.revision)), "下游资料回执已登记")}>登记回执</Button></div>
      {profile ? <div data-company-profile-record data-company-profile-status={profile.status} className="rounded border p-2 text-sm"><b>{profile.profile_number}</b><Badge className="ml-2">{profile.status}</Badge></div> : null}
      {[...workspace.versions, ...workspace.publications].map((item) => <div key={item.id} data-company-profile-record data-company-profile-status={item.status} className="rounded border p-2 text-sm"><b>{"version_number" in item ? item.version_number : item.publication_number}</b><Badge className="ml-2">{"available" in item && item.available ? "正式可用" : item.status}</Badge></div>)}
    </CardContent>
  </Card>;
}
