import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/use-toast";
import { acknowledgeHomepageDesignPublication, approveHomepageDesignPublication, createHomepageDesign, draftHomepageDesignVersion, listHomepageDesignWorkspace, prepareHomepageDesignPublication, validateHomepageDesignVersion, type HomepageDesignWorkspace } from "@/lib/factory-homepage-design-api";

const empty: HomepageDesignWorkspace = { designs: [], versions: [], publications: [], evidence: [], metrics: {}, availability: { application_id: "content.homepage", status: "pilot", release_version: null }, contract: {} };
export function HomepageDesignGovernance({ compositionManifest }: { compositionManifest: object }) {
  const [workspace, setWorkspace] = useState(empty); const [mode, setMode] = useState("loading"); const [project, setProject] = useState(1);
  const load = async () => { try { setMode("loading"); setWorkspace(await listHomepageDesignWorkspace(project)); setMode("live"); } catch (error) { setMode("error"); toast({ variant: "destructive", title: error instanceof Error ? error.message : "首页设计治理加载失败" }); } };
  useEffect(() => { void load(); }, [project]);
  const run = async (action: () => Promise<unknown>, message: string) => { try { await action(); toast({ title: message }); await load(); } catch (error) { toast({ variant: "destructive", title: error instanceof Error ? error.message : "首页设计治理操作失败" }); await load(); } };
  const ref = (prefix: string, revision: number) => ({ expected_revision: revision, reference: `${prefix}-${Date.now()}` });
  const design = workspace.designs[0]; const draft = workspace.versions.find((item) => item.design_id === design?.id && item.status === "draft"); const validated = workspace.versions.find((item) => item.design_id === design?.id && item.status === "validated"); const publication = workspace.publications.find((item) => item.design_id === design?.id);
  return <Card data-homepage-design-governance data-homepage-design-mode={mode} data-homepage-design-availability={workspace.availability.status} className="border-primary/20">
    <CardHeader className="gap-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle className="text-base">首页与落地页受控发布</CardTitle><CardDescription>将当前导航、Banner 与推荐组合固化为可审计版本；独立校验、批准和下游回执后才可对接，不覆盖站点或页面锁定。</CardDescription></div><Input className="w-20" aria-label="首页设计项目编号" value={project} onChange={(event) => setProject(Number(event.target.value) || 1)} /></div><div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{Object.entries(workspace.metrics).map(([key, value]) => <span key={key} data-homepage-design-metric>{key}: <b>{value}</b></span>)}</div></CardHeader>
    <CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button size="sm" data-homepage-design-create disabled={Boolean(design)} onClick={() => void run(() => createHomepageDesign(project, { design_key: "homepage-composition", display_name: "首页与落地页组合" }), "页面组合主档已建立")}>建立组合主档</Button><Button size="sm" data-homepage-design-draft disabled={!design || Boolean(draft) || Boolean(validated)} onClick={() => design && void run(() => draftHomepageDesignVersion(project, design.id, { locale: "zh-CN", composition_manifest: structuredClone(compositionManifest) as Record<string, unknown>, source_reference: `HOMEPAGE-EDITOR-${Date.now()}` }), "当前页面组合已固化")}>固化页面组合</Button><Button size="sm" data-homepage-design-validate disabled={!draft} onClick={() => draft && void run(() => validateHomepageDesignVersion(project, draft.id, ref("HOMEPAGE-VALIDATE", draft.revision)), "页面组合已独立校验")}>独立校验</Button><Button size="sm" data-homepage-design-publication-prepare disabled={!validated || Boolean(publication)} onClick={() => validated && void run(() => prepareHomepageDesignPublication(project, validated.id, { target: "website-homepage", rollback_reference: `HOMEPAGE-ROLLBACK-${Date.now()}` }), "页面交接已准备")}>准备交接</Button><Button size="sm" data-homepage-design-publication-approve disabled={!publication || publication.status !== "pending-approval"} onClick={() => publication && void run(() => approveHomepageDesignPublication(project, publication.id, ref("HOMEPAGE-APPROVE", publication.revision)), "页面交接已独立批准")}>独立批准</Button><Button size="sm" data-homepage-design-publication-acknowledge disabled={!publication || publication.status !== "approved"} onClick={() => publication && void run(() => acknowledgeHomepageDesignPublication(project, publication.id, ref("HOMEPAGE-RECEIPT", publication.revision)), "下游页面回执已登记")}>登记回执</Button></div>
      {design ? <div data-homepage-design-record data-homepage-design-status={design.status} className="rounded border p-2 text-sm"><b>{design.design_number}</b><Badge className="ml-2">{design.status}</Badge></div> : null}
      {[...workspace.versions, ...workspace.publications].map((item) => <div key={item.id} data-homepage-design-record data-homepage-design-status={item.status} className="rounded border p-2 text-sm"><b>{"version_number" in item ? item.version_number : item.publication_number}</b><Badge className="ml-2">{"available" in item && item.available ? "正式可用" : item.status}</Badge></div>)}
    </CardContent>
  </Card>;
}
