import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/use-toast";
import { acknowledgeProductContentPublication, approveProductContentPublication, createProductContentAsset, draftProductContentVersion, listProductContentWorkspace, prepareProductContentPublication, reviewProductContentVersion, type ProductContentWorkspace } from "@/lib/factory-product-content-api";

const empty: ProductContentWorkspace = { assets: [], versions: [], publications: [], evidence: [], metrics: {}, availability: { application_id: "content.product", status: "pilot", release_version: null }, contract: {} };
export function ProductContentGovernance({ contentDocument }: { contentDocument: object }) {
  const [workspace, setWorkspace] = useState(empty); const [mode, setMode] = useState("loading"); const [project, setProject] = useState(1);
  const load = async () => { try { setMode("loading"); setWorkspace(await listProductContentWorkspace(project)); setMode("live"); } catch (error) { setMode("error"); toast({ variant: "destructive", title: error instanceof Error ? error.message : "产品内容治理加载失败" }); } };
  useEffect(() => { void load(); }, [project]);
  const run = async (action: () => Promise<unknown>, message: string) => { try { await action(); toast({ title: message }); await load(); } catch (error) { toast({ variant: "destructive", title: error instanceof Error ? error.message : "产品内容治理操作失败" }); await load(); } };
  const ref = (prefix: string, revision: number) => ({ expected_revision: revision, reference: `${prefix}-${Date.now()}` });
  const asset = workspace.assets[0]; const draft = workspace.versions.find((item) => item.asset_id === asset?.id && item.status === "draft"); const reviewed = workspace.versions.find((item) => item.asset_id === asset?.id && item.status === "reviewed"); const publication = workspace.publications.find((item) => item.asset_id === asset?.id);
  return <Card data-product-content-governance data-product-content-mode={mode} data-product-content-availability={workspace.availability.status} className="border-primary/20">
    <CardHeader className="gap-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><CardTitle className="text-base">产品内容受控发布</CardTitle><CardDescription>把当前编辑器中的产品内容固化为引用产品事实的渠道版本；异人复核、批准和下游回执后才可交接，不回写产品主档、工程、BOM、库存或成本。</CardDescription></div><Input className="w-20" aria-label="产品内容项目编号" value={project} onChange={(event) => setProject(Number(event.target.value) || 1)} /></div><div className="flex flex-wrap gap-2 text-xs text-muted-foreground">{Object.entries(workspace.metrics).map(([key, value]) => <span key={key} data-product-content-metric>{key}: <b>{value}</b></span>)}</div></CardHeader>
    <CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button size="sm" data-product-content-create disabled={Boolean(asset)} onClick={() => void run(() => createProductContentAsset(project, { product_reference: "PRODUCT-EDITOR-PUBLISHED", display_name: "已发布产品内容" }), "产品内容主档已建立")}>建立内容主档</Button><Button size="sm" data-product-content-draft disabled={!asset || Boolean(draft) || Boolean(reviewed)} onClick={() => asset && void run(() => draftProductContentVersion(project, asset.id, { locale: "zh-CN", content_document: structuredClone(contentDocument) as Record<string, unknown>, product_fact_reference: "PRODUCT-MASTER-APPROVED-REFERENCE" }), "当前产品内容已固化")}>固化内容版本</Button><Button size="sm" data-product-content-review disabled={!draft} onClick={() => draft && void run(() => reviewProductContentVersion(project, draft.id, ref("PRODUCT-CONTENT-REVIEW", draft.revision)), "产品内容已独立复核")}>独立复核</Button><Button size="sm" data-product-content-publication-prepare disabled={!reviewed || Boolean(publication)} onClick={() => reviewed && void run(() => prepareProductContentPublication(project, reviewed.id, { target: "website-product", rollback_reference: `PRODUCT-CONTENT-ROLLBACK-${Date.now()}` }), "产品内容交接已准备")}>准备交接</Button><Button size="sm" data-product-content-publication-approve disabled={!publication || publication.status !== "pending-approval"} onClick={() => publication && void run(() => approveProductContentPublication(project, publication.id, ref("PRODUCT-CONTENT-APPROVE", publication.revision)), "产品内容交接已独立批准")}>独立批准</Button><Button size="sm" data-product-content-publication-acknowledge disabled={!publication || publication.status !== "approved"} onClick={() => publication && void run(() => acknowledgeProductContentPublication(project, publication.id, ref("PRODUCT-CONTENT-RECEIPT", publication.revision)), "下游产品内容回执已登记")}>登记回执</Button></div>
      {asset ? <div data-product-content-record data-product-content-status={asset.status} className="rounded border p-2 text-sm"><b>{asset.asset_number}</b><Badge className="ml-2">{asset.status}</Badge></div> : null}
      {[...workspace.versions, ...workspace.publications].map((item) => <div key={item.id} data-product-content-record data-product-content-status={item.status} className="rounded border p-2 text-sm"><b>{"version_number" in item ? item.version_number : item.publication_number}</b><Badge className="ml-2">{"available" in item && item.available ? "正式可用" : item.status}</Badge></div>)}
    </CardContent>
  </Card>;
}
