import { useEffect, useState } from "react";
import { CheckCircle2, RefreshCw, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { advanceFactoryCrmOpportunity, createFactoryCrmAccount, createFactoryCrmOpportunity, listFactoryCrm, verifyFactoryCrmAccount, type CrmAccount, type CrmOpportunity } from "@/lib/factory-crm-api";

const opportunityTimestamp = () => Date.now();

export function CrmGovernance({ projectId }: { projectId: number }) {
  const [accounts,setAccounts]=useState<CrmAccount[]>([]);const [opportunities,setOpportunities]=useState<CrmOpportunity[]>([]);const [reference,setReference]=useState("CRM-EVIDENCE-001");const [note,setNote]=useState("经独立核验的客户经营证据与阶段判断一致。");
  const load=async()=>{try{const data=await listFactoryCrm(projectId);setAccounts(data.accounts);setOpportunities(data.opportunities)}catch(error){toast.error(error instanceof Error?error.message:"CRM 治理数据加载失败")}};
  useEffect(()=>{void load()},[projectId]);
  const createAccount=async()=>{try{const item=await createFactoryCrmAccount(projectId,{account_reference:`ACCOUNT-${Date.now()}`,account_name:"工厂目标客户",market:"overseas"});setAccounts(rows=>[item,...rows]);toast.success("CRM 客户草稿已建立") }catch(error){toast.error(error instanceof Error?error.message:"客户创建失败")}};
  const verify=async(item:CrmAccount)=>{try{const value=await verifyFactoryCrmAccount(projectId,item.id,{expected_revision:item.revision,reference,note});setAccounts(rows=>rows.map(row=>row.id===item.id?value:row));toast.success("客户已由独立角色核验")}catch(error){toast.error(error instanceof Error?error.message:"客户核验失败")}};
  const createOpportunity=async(item:CrmAccount)=>{try{const value=await createFactoryCrmOpportunity(projectId,{account_id:item.id,opportunity_key:`OPP-${opportunityTimestamp()}`,title:"工厂采购项目",currency:"USD",amount_cents:250000,owner_team:"sales"});setOpportunities(rows=>[value,...rows]);toast.success("CRM 商机已建立") }catch(error){toast.error(error instanceof Error?error.message:"商机创建失败")}};
  const advance=async(item:CrmOpportunity)=>{const stage=item.stage==="qualified"?"proposal":"won";try{const value=await advanceFactoryCrmOpportunity(projectId,item.id,{expected_revision:item.revision,stage,reference,note});setOpportunities(rows=>rows.map(row=>row.id===item.id?value:row));toast.success(stage==="proposal"?"商机已进入方案阶段":"商机已按证据完成成交") }catch(error){toast.error(error instanceof Error?error.message:"商机推进失败")}};
  return <section className="space-y-3" data-factory-crm-governance><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="flex items-center gap-2 text-base font-bold"><TrendingUp className="h-4 w-4"/>受控 CRM 客户经营台</h2><p className="mt-1 text-xs text-slate-500">租户隔离的客户、商机与证据；不保存个人联系方式，客户核验必须异人完成。</p></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>刷新</Button></div><Card><CardContent className="grid gap-2 pt-6 md:grid-cols-3"><Input aria-label="CRM 证据编号" value={reference} onChange={event=>setReference(event.target.value)}/><Input aria-label="CRM 证据说明" className="md:col-span-2" value={note} onChange={event=>setNote(event.target.value)}/></CardContent></Card><Button data-factory-crm-create-account size="sm" onClick={()=>void createAccount()}>创建客户草稿</Button><div className="grid gap-3 xl:grid-cols-2">{accounts.map(item=><Card key={item.id} data-factory-crm-account={item.id}><CardHeader className="pb-2"><CardTitle className="flex justify-between gap-2 text-sm"><span>{item.account_number} · {item.account_name}</span><Badge>{item.status}</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2 text-sm"><span>{item.market} · {item.account_reference}</span>{item.status==="draft"?<Button data-factory-crm-verify size="sm" onClick={()=>void verify(item)}><CheckCircle2 className="mr-1 h-4 w-4"/>独立核验</Button>:<Button data-factory-crm-create-opportunity size="sm" onClick={()=>void createOpportunity(item)}>建立商机</Button>}</CardContent></Card>)}</div><div className="grid gap-3 xl:grid-cols-2">{opportunities.map(item=><Card key={item.id} data-factory-crm-opportunity={item.id}><CardContent className="flex flex-wrap items-center justify-between gap-2 pt-6 text-sm"><span>{item.opportunity_number} · {item.title} · {item.currency} {(item.amount_cents/100).toLocaleString()}</span><Badge>{item.stage}</Badge>{["qualified","proposal"].includes(item.stage)?<Button data-factory-crm-advance size="sm" onClick={()=>void advance(item)}>{item.stage==="qualified"?"进入方案":"按证据成交"}</Button>:null}</CardContent></Card>)}</div></section>;
}
