"""factory channel feed and listing center

Revision ID: 1b5d8f3a0c72
Revises: 0a4c7e2d9f61
Create Date: 2026-08-03

Rollback removes only channel account references, catalog projections, listing
validations, immutable feed releases, publications, evidence and permissions.
It never deletes or modifies structured-data releases, product masters, price or
inventory masters, credential vault entries, or remote channel records. Export
published payload hashes and channel acknowledgements first.
"""
import json
from alembic import op
import sqlalchemy as sa

revision="1b5d8f3a0c72";down_revision="0a4c7e2d9f61";branch_labels=None;depends_on=None
PERMISSIONS=("factory.recommend.channel.account.manage","factory.recommend.channel.account.approve","factory.recommend.channel.catalog.manage","factory.recommend.channel.listing.validate","factory.recommend.channel.feed.execute","factory.recommend.channel.publish","factory.recommend.channel.handoff.acknowledge")
TABLES=("factory_channel_catalogs","factory_channel_accounts","factory_channel_listings","factory_channel_feed_runs","factory_channel_feed_releases","factory_channel_publications","factory_channel_evidence")

def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})

def upgrade():
    op.create_table("factory_channel_catalogs",*tenant(),sa.Column("catalog_number",sa.String(96),nullable=False),sa.Column("catalog_code",sa.String(64),nullable=False),sa.Column("catalog_name",sa.String(180),nullable=False),sa.Column("source_release_id",sa.String(100),nullable=False),sa.Column("source_release_number",sa.String(96),nullable=False),sa.Column("source_release_version",sa.Integer(),nullable=False),sa.Column("source_document_hash",sa.String(64),nullable=False),sa.Column("default_locale",sa.String(16),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("catalog_number",name="uq_factory_channel_catalog_number"),sa.UniqueConstraint("project_id","catalog_code",name="uq_factory_channel_project_catalog"));indexes("factory_channel_catalogs",("catalog_number","source_release_id","status"))
    op.create_table("factory_channel_accounts",*tenant(),sa.Column("account_number",sa.String(96),nullable=False),sa.Column("platform",sa.String(40),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("credential_reference",sa.String(255),nullable=False),sa.Column("territory",sa.String(16),nullable=False),sa.Column("locale",sa.String(16),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("requested_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("account_number",name="uq_factory_channel_account_number"),sa.UniqueConstraint("project_id","platform","account_reference",name="uq_factory_channel_platform_account"));indexes("factory_channel_accounts",("account_number","platform","status"))
    op.create_table("factory_channel_listings",*tenant(),sa.Column("listing_number",sa.String(96),nullable=False),sa.Column("catalog_id",sa.String(100),nullable=False),sa.Column("catalog_number",sa.String(96),nullable=False),sa.Column("account_id",sa.String(100),nullable=False),sa.Column("account_number",sa.String(96),nullable=False),sa.Column("external_sku",sa.String(120),nullable=False),sa.Column("product_name",sa.String(255),nullable=False),sa.Column("product_identifier",sa.String(180),nullable=False),sa.Column("source_product_hash",sa.String(64),nullable=False),sa.Column("price_mode",sa.String(32),nullable=False),sa.Column("price_amount",sa.Numeric(18,2)),sa.Column("currency",sa.String(3)),sa.Column("price_reference",sa.String(255)),sa.Column("inventory_mode",sa.String(32),nullable=False),sa.Column("availability_status",sa.String(32),nullable=False),sa.Column("inventory_reference",sa.String(255)),sa.Column("channel_attributes_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("validated_by",sa.String(128)),sa.Column("validated_at",sa.DateTime(timezone=True)),sa.Column("validation_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("listing_number",name="uq_factory_channel_listing_number"),sa.UniqueConstraint("catalog_id","account_id","external_sku",name="uq_factory_channel_catalog_account_sku"));indexes("factory_channel_listings",("listing_number","catalog_id","account_id","status"))
    op.create_table("factory_channel_feed_runs",*tenant(),sa.Column("run_number",sa.String(96),nullable=False),sa.Column("catalog_id",sa.String(100),nullable=False),sa.Column("catalog_number",sa.String(96),nullable=False),sa.Column("source_document_hash",sa.String(64),nullable=False),sa.Column("listing_count",sa.Integer(),nullable=False),sa.Column("error_count",sa.Integer(),nullable=False),sa.Column("warning_count",sa.Integer(),nullable=False),sa.Column("report_json",sa.JSON(),nullable=False),sa.Column("payload_json",sa.JSON(),nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("executed_by",sa.String(128),nullable=False),sa.Column("executed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("run_number",name="uq_factory_channel_run_number"));indexes("factory_channel_feed_runs",("run_number","catalog_id","status"))
    op.create_table("factory_channel_feed_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("catalog_id",sa.String(100),nullable=False),sa.Column("catalog_number",sa.String(96),nullable=False),sa.Column("run_id",sa.String(100),nullable=False),sa.Column("run_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("payload_json",sa.JSON(),nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.Column("channel_count",sa.Integer(),nullable=False),sa.Column("listing_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("release_number",name="uq_factory_channel_release_number"),sa.UniqueConstraint("catalog_id","version_number",name="uq_factory_channel_catalog_version"));indexes("factory_channel_feed_releases",("release_number","catalog_id","run_id","status"))
    op.create_table("factory_channel_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("catalog_id",sa.String(100),nullable=False),sa.Column("release_id",sa.String(100),nullable=False),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("account_id",sa.String(100),nullable=False),sa.Column("account_number",sa.String(96),nullable=False),sa.Column("payload_hash",sa.String(64),nullable=False),sa.Column("remote_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_channel_publication_number"),sa.UniqueConstraint("release_id","account_id",name="uq_factory_channel_release_account"));indexes("factory_channel_publications",("publication_number","catalog_id","release_id","account_id","status"))
    op.create_table("factory_channel_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_channel_evidence_number"));indexes("factory_channel_evidence",("evidence_number","subject_type","subject_id"));permissions(False)

def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
