"""consent-governed identity resolution and golden profiles

Revision ID: 2c6e9a4b1d83
Revises: 1b5d8f3a0c72
Create Date: 2026-08-03

Rollback removes only identity consent references, irreversible signal hashes,
match decisions, golden-profile projections, immutable versions, handoff
acknowledgements, evidence and permissions. It never deletes or modifies CRM,
CDP, legal-party, contact, account, device, email or phone source records. Export
published manifest hashes and downstream acknowledgements before rollback.
"""
import json
from alembic import op
import sqlalchemy as sa

revision="2c6e9a4b1d83";down_revision="1b5d8f3a0c72";branch_labels=None;depends_on=None
PERMISSIONS=("factory.portrait.identity.consent.manage","factory.portrait.identity.consent.approve","factory.portrait.identity.signal.manage","factory.portrait.identity.signal.verify","factory.portrait.identity.match.propose","factory.portrait.identity.match.decide","factory.portrait.identity.profile.publish","factory.portrait.identity.handoff.acknowledge")
TABLES=("factory_identity_consents","factory_identity_signals","factory_identity_match_cases","factory_golden_profiles","factory_golden_profile_versions","factory_identity_publications","factory_identity_evidence")

def tenant(): return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras): op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try: values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError): values=[]
        if not isinstance(values,list): values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})

def upgrade():
    op.create_table("factory_identity_consents",*tenant(),sa.Column("consent_number",sa.String(96),nullable=False),sa.Column("subject_reference",sa.String(180),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("consent_reference",sa.String(255),nullable=False),sa.Column("lawful_basis",sa.String(40),nullable=False),sa.Column("purposes_json",sa.JSON(),nullable=False),sa.Column("source_event_hash",sa.String(64),nullable=False),sa.Column("valid_from",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("requested_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("revoked_by",sa.String(128)),sa.Column("revoked_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("consent_number",name="uq_factory_identity_consent_number"),sa.UniqueConstraint("project_id","consent_reference",name="uq_factory_identity_project_consent_reference"));indexes("factory_identity_consents",("consent_number","subject_reference","account_reference","status"))
    op.create_table("factory_identity_signals",*tenant(),sa.Column("signal_number",sa.String(96),nullable=False),sa.Column("consent_id",sa.String(100),nullable=False),sa.Column("consent_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("signal_type",sa.String(32),nullable=False),sa.Column("identifier_hash",sa.String(64),nullable=False),sa.Column("display_hint",sa.String(32),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("source_revision",sa.Integer(),nullable=False),sa.Column("source_fingerprint",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("captured_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("signal_number",name="uq_factory_identity_signal_number"),sa.UniqueConstraint("project_id","signal_type","identifier_hash",name="uq_factory_identity_project_signal_hash"));indexes("factory_identity_signals",("signal_number","consent_id","account_reference","signal_type","identifier_hash","status"))
    op.create_table("factory_identity_match_cases",*tenant(),sa.Column("case_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("signal_ids_json",sa.JSON(),nullable=False),sa.Column("signal_manifest_hash",sa.String(64),nullable=False),sa.Column("match_method",sa.String(32),nullable=False),sa.Column("match_score",sa.Float(),nullable=False),sa.Column("reasons_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="proposed"),sa.Column("proposed_by",sa.String(128),nullable=False),sa.Column("decided_by",sa.String(128)),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.Column("decision_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("case_number",name="uq_factory_identity_case_number"));indexes("factory_identity_match_cases",("case_number","account_reference","status"))
    op.create_table("factory_golden_profiles",*tenant(),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("match_case_id",sa.String(100),nullable=False),sa.Column("match_case_number",sa.String(96),nullable=False),sa.Column("member_signal_ids_json",sa.JSON(),nullable=False),sa.Column("source_manifest_json",sa.JSON(),nullable=False),sa.Column("source_manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("profile_number",name="uq_factory_identity_profile_number"),sa.UniqueConstraint("project_id","account_reference",name="uq_factory_identity_project_golden_account"));indexes("factory_golden_profiles",("profile_number","account_reference","match_case_id","status"))
    op.create_table("factory_golden_profile_versions",*tenant(),sa.Column("version_number_ref",sa.String(96),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_number_ref",name="uq_factory_identity_version_number_ref"),sa.UniqueConstraint("profile_id","version_number",name="uq_factory_identity_profile_version"));indexes("factory_golden_profile_versions",("version_number_ref","profile_id","status"))
    op.create_table("factory_identity_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number_ref",sa.String(96),nullable=False),sa.Column("consumer_system",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("remote_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_identity_publication_number"),sa.UniqueConstraint("version_id","consumer_system",name="uq_factory_identity_version_consumer"));indexes("factory_identity_publications",("publication_number","profile_id","version_id","consumer_system","status"))
    op.create_table("factory_identity_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_identity_evidence_number"));indexes("factory_identity_evidence",("evidence_number","subject_type","subject_id"));permissions(False)

def downgrade():
    permissions(True)
    for table in reversed(TABLES): op.drop_table(table)
