"""controlled company profile releases

Revision ID: 2d7f4a9b3c16
Revises: 1c6f4a8b2d95

Rollback removes only this tenant-scoped profile governance projection, its
permissions and contracts. It never changes local editor drafts or source facts.
"""
import json
from alembic import op
import sqlalchemy as sa

revision = "2d7f4a9b3c16"; down_revision = "1c6f4a8b2d95"; branch_labels = None; depends_on = None
PERMISSIONS = ("factory.content.company.profile.manage", "factory.content.company.version.verify", "factory.content.company.publication.approve", "factory.content.company.handoff.acknowledge")
TABLES = ("factory_company_profiles", "factory_company_profile_versions", "factory_company_profile_publications", "factory_company_profile_evidence")
def tenant_columns(): return [sa.Column("id", sa.String(100), primary_key=True), sa.Column("project_id", sa.Integer(), nullable=False), sa.Column("agent_path", sa.String(255), nullable=False), sa.Column("tenant_id", sa.String(128), nullable=False), sa.Column("client_id", sa.String(128), nullable=False), sa.Column("plan_id", sa.String(128), nullable=False)]
def indexes(table, *extra):
    for column in ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", *extra): op.create_index(f"ix_{table}_{column}", table, [column])
def permissions(remove=False):
    bind = op.get_bind(); rows = bind.execute(sa.text("SELECT id, permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try: values = json.loads(row["permissions_json"] or "[]")
        except (TypeError, ValueError): values = []
        values = [x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values, *PERMISSIONS])); bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:permissions WHERE id=:id"), {"permissions": json.dumps(values, ensure_ascii=False), "id": row["id"]})
def upgrade():
    op.create_table("factory_company_profiles", *tenant_columns(), sa.Column("profile_number", sa.String(96), nullable=False), sa.Column("profile_key", sa.String(80), nullable=False), sa.Column("display_name", sa.String(200), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="active"), sa.Column("created_by", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("profile_number", name="uq_factory_company_profile_number"), sa.UniqueConstraint("project_id", "profile_key", name="uq_factory_company_profile_key")); indexes("factory_company_profiles", "profile_number", "status")
    op.create_table("factory_company_profile_versions", *tenant_columns(), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("profile_number", sa.String(96), nullable=False), sa.Column("locale", sa.String(16), nullable=False), sa.Column("profile_manifest_json", sa.JSON(), nullable=False), sa.Column("manifest_hash", sa.String(64), nullable=False), sa.Column("source_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="draft"), sa.Column("authored_by", sa.String(128), nullable=False), sa.Column("verified_by", sa.String(128)), sa.Column("verified_at", sa.DateTime(timezone=True)), sa.Column("verification_reference", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("version_number", name="uq_factory_company_profile_version_number"), sa.UniqueConstraint("profile_id", "version_number", name="uq_factory_company_profile_version")); indexes("factory_company_profile_versions", "version_number", "profile_id", "status")
    op.create_table("factory_company_profile_publications", *tenant_columns(), sa.Column("publication_number", sa.String(96), nullable=False), sa.Column("profile_id", sa.String(100), nullable=False), sa.Column("profile_version_id", sa.String(100), nullable=False), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("target", sa.String(32), nullable=False), sa.Column("release_manifest_json", sa.JSON(), nullable=False), sa.Column("manifest_hash", sa.String(64), nullable=False), sa.Column("rollback_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="pending-approval"), sa.Column("prepared_by", sa.String(128), nullable=False), sa.Column("approved_by", sa.String(128)), sa.Column("approval_reference", sa.String(255)), sa.Column("consumer_receipt_reference", sa.String(255)), sa.Column("available", sa.Boolean(), nullable=False, server_default="0"), sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("publication_number", name="uq_factory_company_profile_publication_number"), sa.UniqueConstraint("profile_version_id", "target", name="uq_factory_company_profile_publication_target")); indexes("factory_company_profile_publications", "publication_number", "profile_id", "profile_version_id", "status", "available")
    op.create_table("factory_company_profile_evidence", *tenant_columns(), sa.Column("evidence_number", sa.String(96), nullable=False), sa.Column("subject_type", sa.String(40), nullable=False), sa.Column("subject_id", sa.String(100), nullable=False), sa.Column("subject_number", sa.String(96), nullable=False), sa.Column("evidence_type", sa.String(64), nullable=False), sa.Column("evidence_reference", sa.String(255), nullable=False), sa.Column("note", sa.Text()), sa.Column("recorded_by", sa.String(128), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("evidence_number", name="uq_factory_company_profile_evidence_number")); indexes("factory_company_profile_evidence", "evidence_number", "subject_type", "subject_id")
    bind = op.get_bind(); bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'company-profile-version',29,'Company profile version','content','tenant, profile and version','[\"tenantId\",\"profileId\",\"versionId\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='company-profile-version')")); bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'company-profile-released',21,'Company profile released','company-profile-version','content','[\"site\",\"sales\",\"trust\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='company-profile-released')")); permissions()
def downgrade():
    permissions(True); bind = op.get_bind(); bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='company-profile-released'")); bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='company-profile-version'"));
    for table in reversed(TABLES): op.drop_table(table)
