"""governed B2B account relationship graph

Revision ID: 3d7f0b5c2e94
Revises: 2c6e9a4b1d83
Create Date: 2026-08-03

Rollback removes only account-graph projections, verified relationship edges,
immutable versions, handoff acknowledgements, evidence and permissions. It
never deletes or modifies legal parties, identity profiles/signals, CPQ quotes,
orders, CRM/CDP records or downstream systems. Export published manifest hashes
and acknowledgements first.
"""
import json
from alembic import op
import sqlalchemy as sa

revision="3d7f0b5c2e94";down_revision="2c6e9a4b1d83";branch_labels=None;depends_on=None
PERMISSIONS=("factory.portrait.account.graph.manage","factory.portrait.account.node.verify","factory.portrait.account.relation.manage","factory.portrait.account.relation.verify","factory.portrait.account.publish","factory.portrait.account.handoff.acknowledge")
TABLES=("factory_account_graphs","factory_account_graph_nodes","factory_account_graph_edges","factory_account_graph_versions","factory_account_graph_publications","factory_account_graph_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_account_graphs",*tenant(),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("graph_code",sa.String(64),nullable=False),sa.Column("graph_name",sa.String(180),nullable=False),sa.Column("scope",sa.String(32),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("graph_number",name="uq_factory_account_graph_number"),sa.UniqueConstraint("project_id","graph_code",name="uq_factory_account_graph_project_code"));indexes("factory_account_graphs",("graph_number","status"))
    op.create_table("factory_account_graph_nodes",*tenant(),sa.Column("node_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("node_type",sa.String(32),nullable=False),sa.Column("node_key",sa.String(180),nullable=False),sa.Column("display_name",sa.String(255),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("country_code",sa.String(8)),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("source_number",sa.String(100),nullable=False),sa.Column("source_revision",sa.Integer(),nullable=False),sa.Column("source_status",sa.String(32),nullable=False),sa.Column("source_fingerprint",sa.String(64),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("node_number",name="uq_factory_account_graph_node_number"),sa.UniqueConstraint("graph_id","source_type","source_id",name="uq_factory_account_graph_source_node"));indexes("factory_account_graph_nodes",("node_number","graph_id","node_type","account_reference","source_type","source_id","status"))
    op.create_table("factory_account_graph_edges",*tenant(),sa.Column("edge_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("from_node_id",sa.String(100),nullable=False),sa.Column("from_node_number",sa.String(96),nullable=False),sa.Column("to_node_id",sa.String(100),nullable=False),sa.Column("to_node_number",sa.String(96),nullable=False),sa.Column("relation_type",sa.String(40),nullable=False),sa.Column("strength",sa.String(16),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("endpoint_manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("edge_number",name="uq_factory_account_graph_edge_number"),sa.UniqueConstraint("graph_id","from_node_id","relation_type","to_node_id",name="uq_factory_account_graph_relation"));indexes("factory_account_graph_edges",("edge_number","graph_id","from_node_id","to_node_id","relation_type","status"))
    op.create_table("factory_account_graph_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("node_count",sa.Integer(),nullable=False),sa.Column("edge_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_account_graph_version_reference"),sa.UniqueConstraint("graph_id","version_number",name="uq_factory_account_graph_version"));indexes("factory_account_graph_versions",("version_reference","graph_id","status"))
    op.create_table("factory_account_graph_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_account_graph_publication_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_account_graph_version_consumer"));indexes("factory_account_graph_publications",("publication_number","graph_id","version_id","consumer","status"))
    op.create_table("factory_account_graph_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_account_graph_evidence_number"));indexes("factory_account_graph_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
