"""controlled homepage composition releases

Revision ID: 3e8a1c5d7f92
Revises: 2d7f4a9b3c16

Rollback removes only the tenant-scoped composition governance projection,
permissions and contracts. It never modifies customer pages or plugin locks.
"""
import json
from alembic import op
import sqlalchemy as sa

revision = "3e8a1c5d7f92"; down_revision = "2d7f4a9b3c16"; branch_labels = None; depends_on = None
PERMISSIONS = ("factory.content.homepage.design.manage", "factory.content.homepage.version.validate", "factory.content.homepage.publication.approve", "factory.content.homepage.handoff.acknowledge")
TABLES = ("factory_homepage_designs", "factory_homepage_design_versions", "factory_homepage_design_publications", "factory_homepage_design_evidence")
def tenant_columns(): return [sa.Column("id", sa.String(100), primary_key=True), sa.Column("project_id", sa.Integer(), nullable=False), sa.Column("agent_path", sa.String(255), nullable=False), sa.Column("tenant_id", sa.String(128), nullable=False), sa.Column("client_id", sa.String(128), nullable=False), sa.Column("plan_id", sa.String(128), nullable=False)]
def indexes(table, *extra):
    for column in ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", *extra): op.create_index(f"ix_{table}_{column}", table, [column])
def permissions(remove=False):
    bind = op.get_bind(); rows = bind.execute(sa.text("SELECT id, permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try: values = json.loads(row["permissions_json"] or "[]")
        except (TypeError, ValueError): values = []
        values = [x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values, *PERMISSIONS])); bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:permissions WHERE id=:id"), {"permissions": json.dumps(values, ensure_ascii=False), "id": row["id"]})
def upgrade():
    op.create_table("factory_homepage_designs", *tenant_columns(), sa.Column("design_number", sa.String(96), nullable=False), sa.Column("design_key", sa.String(80), nullable=False), sa.Column("display_name", sa.String(200), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="active"), sa.Column("created_by", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("design_number", name="uq_factory_homepage_design_number"), sa.UniqueConstraint("project_id", "design_key", name="uq_factory_homepage_design_key")); indexes("factory_homepage_designs", "design_number", "status")
    op.create_table("factory_homepage_design_versions", *tenant_columns(), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("design_id", sa.String(100), nullable=False), sa.Column("design_number", sa.String(96), nullable=False), sa.Column("locale", sa.String(16), nullable=False), sa.Column("composition_manifest_json", sa.JSON(), nullable=False), sa.Column("manifest_hash", sa.String(64), nullable=False), sa.Column("source_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="draft"), sa.Column("authored_by", sa.String(128), nullable=False), sa.Column("validated_by", sa.String(128)), sa.Column("validated_at", sa.DateTime(timezone=True)), sa.Column("validation_reference", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("version_number", name="uq_factory_homepage_design_version_number"), sa.UniqueConstraint("design_id", "version_number", name="uq_factory_homepage_design_version")); indexes("factory_homepage_design_versions", "version_number", "design_id", "status")
    op.create_table("factory_homepage_design_publications", *tenant_columns(), sa.Column("publication_number", sa.String(96), nullable=False), sa.Column("design_id", sa.String(100), nullable=False), sa.Column("design_version_id", sa.String(100), nullable=False), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("target", sa.String(32), nullable=False), sa.Column("release_manifest_json", sa.JSON(), nullable=False), sa.Column("manifest_hash", sa.String(64), nullable=False), sa.Column("rollback_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="pending-approval"), sa.Column("prepared_by", sa.String(128), nullable=False), sa.Column("approved_by", sa.String(128)), sa.Column("approval_reference", sa.String(255)), sa.Column("consumer_receipt_reference", sa.String(255)), sa.Column("available", sa.Boolean(), nullable=False, server_default="0"), sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("publication_number", name="uq_factory_homepage_design_publication_number"), sa.UniqueConstraint("design_version_id", "target", name="uq_factory_homepage_design_publication_target")); indexes("factory_homepage_design_publications", "publication_number", "design_id", "design_version_id", "status", "available")
    op.create_table("factory_homepage_design_evidence", *tenant_columns(), sa.Column("evidence_number", sa.String(96), nullable=False), sa.Column("subject_type", sa.String(40), nullable=False), sa.Column("subject_id", sa.String(100), nullable=False), sa.Column("subject_number", sa.String(96), nullable=False), sa.Column("evidence_type", sa.String(64), nullable=False), sa.Column("evidence_reference", sa.String(255), nullable=False), sa.Column("note", sa.Text()), sa.Column("recorded_by", sa.String(128), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("evidence_number", name="uq_factory_homepage_design_evidence_number")); indexes("factory_homepage_design_evidence", "evidence_number", "subject_type", "subject_id")
    bind = op.get_bind(); bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'homepage-composition-version',30,'Homepage composition version','content','tenant, design and version','[\"tenantId\",\"designId\",\"versionId\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='homepage-composition-version')")); bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'homepage-composition-released',22,'Homepage composition released','homepage-composition-version','content','[\"site\",\"recommend\",\"lead\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='homepage-composition-released')")); permissions()
def downgrade():
    permissions(True); bind = op.get_bind(); bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='homepage-composition-released'")); bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='homepage-composition-version'"));
    for table in reversed(TABLES): op.drop_table(table)
