"""controlled product content releases

Revision ID: 4d9e2b7c1f83
Revises: 3e8a1c5d7f92

Rollback removes only product-content governance projections, permissions and
contracts. It never deletes product masters, engineering facts, local drafts,
or already delivered consumer content.
"""
import json
from alembic import op
import sqlalchemy as sa

revision = "4d9e2b7c1f83"; down_revision = "3e8a1c5d7f92"; branch_labels = None; depends_on = None
PERMISSIONS = ("factory.content.product.asset.manage", "factory.content.product.version.review", "factory.content.product.publication.approve", "factory.content.product.handoff.acknowledge")
TABLES = ("factory_product_content_assets", "factory_product_content_versions", "factory_product_content_publications", "factory_product_content_evidence")
def tenant_columns(): return [sa.Column("id", sa.String(100), primary_key=True), sa.Column("project_id", sa.Integer(), nullable=False), sa.Column("agent_path", sa.String(255), nullable=False), sa.Column("tenant_id", sa.String(128), nullable=False), sa.Column("client_id", sa.String(128), nullable=False), sa.Column("plan_id", sa.String(128), nullable=False)]
def indexes(table, *extra):
    for column in ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", *extra): op.create_index(f"ix_{table}_{column}", table, [column])
def permissions(remove=False):
    bind = op.get_bind(); rows = bind.execute(sa.text("SELECT id, permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try: values = json.loads(row["permissions_json"] or "[]")
        except (TypeError, ValueError): values = []
        values = [x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values, *PERMISSIONS])); bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:permissions WHERE id=:id"), {"permissions": json.dumps(values, ensure_ascii=False), "id": row["id"]})
def upgrade():
    op.create_table("factory_product_content_assets", *tenant_columns(), sa.Column("asset_number", sa.String(96), nullable=False), sa.Column("product_reference", sa.String(160), nullable=False), sa.Column("display_name", sa.String(200), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="active"), sa.Column("created_by", sa.String(128), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("asset_number", name="uq_factory_product_content_asset_number"), sa.UniqueConstraint("project_id", "product_reference", name="uq_factory_product_content_product")); indexes("factory_product_content_assets", "asset_number", "status")
    op.create_table("factory_product_content_versions", *tenant_columns(), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("asset_id", sa.String(100), nullable=False), sa.Column("asset_number", sa.String(96), nullable=False), sa.Column("locale", sa.String(16), nullable=False), sa.Column("content_document_json", sa.JSON(), nullable=False), sa.Column("document_hash", sa.String(64), nullable=False), sa.Column("product_fact_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="draft"), sa.Column("authored_by", sa.String(128), nullable=False), sa.Column("reviewed_by", sa.String(128)), sa.Column("reviewed_at", sa.DateTime(timezone=True)), sa.Column("review_reference", sa.String(255)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("version_number", name="uq_factory_product_content_version_number"), sa.UniqueConstraint("asset_id", "version_number", name="uq_factory_product_content_version")); indexes("factory_product_content_versions", "version_number", "asset_id", "status")
    op.create_table("factory_product_content_publications", *tenant_columns(), sa.Column("publication_number", sa.String(96), nullable=False), sa.Column("asset_id", sa.String(100), nullable=False), sa.Column("content_version_id", sa.String(100), nullable=False), sa.Column("version_number", sa.String(96), nullable=False), sa.Column("target", sa.String(40), nullable=False), sa.Column("release_manifest_json", sa.JSON(), nullable=False), sa.Column("manifest_hash", sa.String(64), nullable=False), sa.Column("rollback_reference", sa.String(255), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="pending-approval"), sa.Column("prepared_by", sa.String(128), nullable=False), sa.Column("approved_by", sa.String(128)), sa.Column("approval_reference", sa.String(255)), sa.Column("consumer_receipt_reference", sa.String(255)), sa.Column("available", sa.Boolean(), nullable=False, server_default="0"), sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.UniqueConstraint("publication_number", name="uq_factory_product_content_publication_number"), sa.UniqueConstraint("content_version_id", "target", name="uq_factory_product_content_publication_target")); indexes("factory_product_content_publications", "publication_number", "asset_id", "content_version_id", "status", "available")
    op.create_table("factory_product_content_evidence", *tenant_columns(), sa.Column("evidence_number", sa.String(96), nullable=False), sa.Column("subject_type", sa.String(40), nullable=False), sa.Column("subject_id", sa.String(100), nullable=False), sa.Column("subject_number", sa.String(96), nullable=False), sa.Column("evidence_type", sa.String(64), nullable=False), sa.Column("evidence_reference", sa.String(255), nullable=False), sa.Column("note", sa.Text()), sa.Column("recorded_by", sa.String(128), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("evidence_number", name="uq_factory_product_content_evidence_number")); indexes("factory_product_content_evidence", "evidence_number", "subject_type", "subject_id")
    bind = op.get_bind(); bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'product-content-version',31,'Product content version','content','tenant, product reference and version','[\"tenantId\",\"productReference\",\"versionId\",\"documentHash\",\"productFactReference\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='product-content-version')")); bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'product-content-released',23,'Product content released','product-content-version','content','[\"site\",\"seo\",\"sales\",\"channel\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='product-content-released')")); permissions()
def downgrade():
    permissions(True); bind = op.get_bind(); bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='product-content-released'")); bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='product-content-version'"))
    for table in reversed(TABLES): op.drop_table(table)
