"""governed buying committee and influence paths

Revision ID: 4e8a1c6d3f05
Revises: 3d7f0b5c2e94
Create Date: 2026-08-03

Rollback removes only buying-committee projections, consented contact hashes,
verified influence paths, immutable versions, handoff acknowledgements,
evidence and permissions. It never deletes or modifies ICP definitions, consent
records, identity signals, CPQ opportunities or downstream CRM/sales records.
Export published manifest hashes and acknowledgements first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="4e8a1c6d3f05";down_revision="3d7f0b5c2e94";branch_labels=None;depends_on=None
PERMISSIONS=("factory.portrait.buying.committee.manage","factory.portrait.buying.member.verify","factory.portrait.buying.influence.manage","factory.portrait.buying.influence.verify","factory.portrait.buying.publish","factory.portrait.buying.handoff.acknowledge")
TABLES=("factory_buying_committees","factory_buying_committee_members","factory_buying_influence_edges","factory_buying_committee_versions","factory_buying_committee_publications","factory_buying_committee_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_buying_committees",*tenant(),sa.Column("committee_number",sa.String(96),nullable=False),sa.Column("committee_name",sa.String(180),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("opportunity_source_type",sa.String(40),nullable=False),sa.Column("opportunity_source_id",sa.String(100),nullable=False),sa.Column("opportunity_source_number",sa.String(100),nullable=False),sa.Column("opportunity_source_revision",sa.Integer(),nullable=False),sa.Column("opportunity_source_status",sa.String(32),nullable=False),sa.Column("opportunity_fingerprint",sa.String(64),nullable=False),sa.Column("opportunity_snapshot_json",sa.JSON(),nullable=False),sa.Column("icp_profile_id",sa.String(100),nullable=False),sa.Column("icp_profile_number",sa.String(96),nullable=False),sa.Column("icp_profile_revision",sa.Integer(),nullable=False),sa.Column("icp_definition_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("committee_number",name="uq_factory_buying_committee_number"),sa.UniqueConstraint("project_id","opportunity_source_type","opportunity_source_id",name="uq_factory_buying_project_opportunity"));indexes("factory_buying_committees",("committee_number","account_reference","opportunity_source_id","icp_profile_id","status"))
    op.create_table("factory_buying_committee_members",*tenant(),sa.Column("member_number",sa.String(96),nullable=False),sa.Column("committee_id",sa.String(100),nullable=False),sa.Column("committee_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("role_id",sa.String(100),nullable=False),sa.Column("role_number",sa.String(96),nullable=False),sa.Column("role_code",sa.String(64),nullable=False),sa.Column("role_name",sa.String(128),nullable=False),sa.Column("influence_type",sa.String(32),nullable=False),sa.Column("role_fingerprint",sa.String(64),nullable=False),sa.Column("contact_signal_id",sa.String(100),nullable=False),sa.Column("contact_signal_number",sa.String(96),nullable=False),sa.Column("contact_hash",sa.String(64),nullable=False),sa.Column("contact_hint",sa.String(32),nullable=False),sa.Column("contact_source_revision",sa.Integer(),nullable=False),sa.Column("contact_source_fingerprint",sa.String(64),nullable=False),sa.Column("influence_score",sa.Float(),nullable=False),sa.Column("relationship_strength",sa.String(16),nullable=False),sa.Column("stance",sa.String(16),nullable=False),sa.Column("preferred_channel",sa.String(32),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("member_number",name="uq_factory_buying_member_number"),sa.UniqueConstraint("committee_id","role_id",name="uq_factory_buying_committee_role"),sa.UniqueConstraint("committee_id","contact_signal_id",name="uq_factory_buying_committee_contact"));indexes("factory_buying_committee_members",("member_number","committee_id","account_reference","role_id","contact_signal_id","status"))
    op.create_table("factory_buying_influence_edges",*tenant(),sa.Column("edge_number",sa.String(96),nullable=False),sa.Column("committee_id",sa.String(100),nullable=False),sa.Column("committee_number",sa.String(96),nullable=False),sa.Column("from_member_id",sa.String(100),nullable=False),sa.Column("from_member_number",sa.String(96),nullable=False),sa.Column("to_member_id",sa.String(100),nullable=False),sa.Column("to_member_number",sa.String(96),nullable=False),sa.Column("influence_direction",sa.String(24),nullable=False),sa.Column("strength",sa.String(16),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("endpoint_manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("edge_number",name="uq_factory_buying_edge_number"),sa.UniqueConstraint("committee_id","from_member_id","to_member_id",name="uq_factory_buying_influence_path"));indexes("factory_buying_influence_edges",("edge_number","committee_id","from_member_id","to_member_id","status"))
    op.create_table("factory_buying_committee_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("committee_id",sa.String(100),nullable=False),sa.Column("committee_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("required_role_count",sa.Integer(),nullable=False),sa.Column("member_count",sa.Integer(),nullable=False),sa.Column("influence_edge_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_buying_version_reference"),sa.UniqueConstraint("committee_id","version_number",name="uq_factory_buying_committee_version"));indexes("factory_buying_committee_versions",("version_reference","committee_id","status"))
    op.create_table("factory_buying_committee_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("committee_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_buying_publication_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_buying_version_consumer"));indexes("factory_buying_committee_publications",("publication_number","committee_id","version_id","consumer","status"))
    op.create_table("factory_buying_committee_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_buying_evidence_number"));indexes("factory_buying_committee_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
