"""complete legacy application schema

Revision ID: 52f927590325
Revises: f3a92d1b7c10
Create Date: 2026-07-28 08:51:41.244788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f927590325'
down_revision: Union[str, Sequence[str], None] = 'f3a92d1b7c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_snapshot_backups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_id', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('backup_kind', sa.String(length=50), nullable=False),
    sa.Column('program_path', sa.String(length=1000), nullable=True),
    sa.Column('database_path', sa.String(length=1000), nullable=True),
    sa.Column('backup_path', sa.String(length=1000), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backup_id', name='uq_template_snapshot_backups_backup_id')
    )
    op.create_index(op.f('ix_template_snapshot_backups_backup_id'), 'template_snapshot_backups', ['backup_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_backups_backup_kind'), 'template_snapshot_backups', ['backup_kind'], unique=False)
    op.create_index(op.f('ix_template_snapshot_backups_id'), 'template_snapshot_backups', ['id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_backups_target_id'), 'template_snapshot_backups', ['target_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_backups_target_type'), 'template_snapshot_backups', ['target_type'], unique=False)
    op.create_index(op.f('ix_template_snapshot_backups_version'), 'template_snapshot_backups', ['version'], unique=False)
    op.create_table('template_snapshot_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instance_id', sa.String(length=100), nullable=False),
    sa.Column('instance_type', sa.String(length=50), nullable=False),
    sa.Column('owner_scope', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_template_id', sa.String(length=100), nullable=True),
    sa.Column('base_template_version', sa.String(length=50), nullable=True),
    sa.Column('snapshot_config_json', sa.Text(), nullable=False),
    sa.Column('override_config_json', sa.Text(), nullable=False),
    sa.Column('is_detached', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', name='uq_template_snapshot_instances_instance_id')
    )
    op.create_index(op.f('ix_template_snapshot_instances_base_template_id'), 'template_snapshot_instances', ['base_template_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_base_template_version'), 'template_snapshot_instances', ['base_template_version'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_id'), 'template_snapshot_instances', ['id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_instance_id'), 'template_snapshot_instances', ['instance_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_instance_type'), 'template_snapshot_instances', ['instance_type'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_owner_id'), 'template_snapshot_instances', ['owner_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_owner_scope'), 'template_snapshot_instances', ['owner_scope'], unique=False)
    op.create_index(op.f('ix_template_snapshot_instances_parent_id'), 'template_snapshot_instances', ['parent_id'], unique=False)
    op.create_table('template_snapshot_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('owner_scope', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latest_version', sa.String(length=50), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', name='uq_template_snapshot_templates_template_id')
    )
    op.create_index(op.f('ix_template_snapshot_templates_id'), 'template_snapshot_templates', ['id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_templates_owner_id'), 'template_snapshot_templates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_templates_owner_scope'), 'template_snapshot_templates', ['owner_scope'], unique=False)
    op.create_index(op.f('ix_template_snapshot_templates_template_id'), 'template_snapshot_templates', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_templates_template_type'), 'template_snapshot_templates', ['template_type'], unique=False)
    op.create_table('template_snapshot_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('changelog', sa.String(length=1000), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version', name='uq_template_snapshot_versions_template_version')
    )
    op.create_index(op.f('ix_template_snapshot_versions_id'), 'template_snapshot_versions', ['id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_versions_template_id'), 'template_snapshot_versions', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_snapshot_versions_version'), 'template_snapshot_versions', ['version'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('root_org_id', sa.Integer(), nullable=True),
    sa.Column('root_agency_id', sa.Integer(), nullable=True),
    sa.Column('agent_level', sa.Integer(), nullable=True),
    sa.Column('lineage_path', sa.String(length=1000), nullable=True),
    sa.Column('owner_user_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('commission_mode', sa.String(length=50), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('first_order_commission_rate', sa.Float(), nullable=True),
    sa.Column('renewal_commission_rate', sa.Float(), nullable=True),
    sa.Column('package_commission_rate', sa.Float(), nullable=True),
    sa.Column('discount_rate', sa.Float(), nullable=True),
    sa.Column('invite_code', sa.String(length=100), nullable=True),
    sa.Column('invite_url', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['root_agency_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['root_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_organizations_code')
    )
    op.create_index(op.f('ix_organizations_agent_level'), 'organizations', ['agent_level'], unique=False)
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_invite_code'), 'organizations', ['invite_code'], unique=False)
    op.create_index(op.f('ix_organizations_org_type'), 'organizations', ['org_type'], unique=False)
    op.create_index(op.f('ix_organizations_owner_user_id'), 'organizations', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_organizations_parent_id'), 'organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_organizations_root_agency_id'), 'organizations', ['root_agency_id'], unique=False)
    op.create_index(op.f('ix_organizations_root_org_id'), 'organizations', ['root_org_id'], unique=False)
    op.create_table('ai_provider_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('default_model', sa.String(length=255), nullable=True),
    sa.Column('api_key_env', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider_key', name='uq_ai_provider_org_key')
    )
    op.create_index(op.f('ix_ai_provider_configs_id'), 'ai_provider_configs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_provider_configs_org_id'), 'ai_provider_configs', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_provider_configs_provider_key'), 'ai_provider_configs', ['provider_key'], unique=False)
    op.create_table('data_backups_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('backup_type', sa.String(length=50), server_default='manual', nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_backups_platform_id'), 'data_backups_platform', ['id'], unique=False)
    op.create_index(op.f('ix_data_backups_platform_org_id'), 'data_backups_platform', ['org_id'], unique=False)
    op.create_table('local_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_local_accounts_email')
    )
    op.create_index(op.f('ix_local_accounts_email'), 'local_accounts', ['email'], unique=False)
    op.create_index(op.f('ix_local_accounts_id'), 'local_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_local_accounts_org_id'), 'local_accounts', ['org_id'], unique=False)
    op.create_index(op.f('ix_local_accounts_user_id'), 'local_accounts', ['user_id'], unique=False)
    op.create_table('projects_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('owner_user_id', sa.String(length=255), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_org_id', 'code', name='uq_projects_client_code')
    )
    op.create_index(op.f('ix_projects_platform_client_org_id'), 'projects_platform', ['client_org_id'], unique=False)
    op.create_index(op.f('ix_projects_platform_code'), 'projects_platform', ['code'], unique=False)
    op.create_index(op.f('ix_projects_platform_id'), 'projects_platform', ['id'], unique=False)
    op.create_index(op.f('ix_projects_platform_owner_user_id'), 'projects_platform', ['owner_user_id'], unique=False)
    op.create_table('roles_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('permissions_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_roles_org_name')
    )
    op.create_index(op.f('ix_roles_platform_id'), 'roles_platform', ['id'], unique=False)
    op.create_index(op.f('ix_roles_platform_org_id'), 'roles_platform', ['org_id'], unique=False)
    op.create_index(op.f('ix_roles_platform_scope'), 'roles_platform', ['scope'], unique=False)
    op.create_table('ai_app_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('app_key', sa.String(length=100), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=255), nullable=True),
    sa.Column('primary_provider_id', sa.Integer(), nullable=True),
    sa.Column('primary_model', sa.String(length=255), nullable=True),
    sa.Column('backup_provider_id', sa.Integer(), nullable=True),
    sa.Column('backup_model', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['backup_provider_id'], ['ai_provider_configs.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['primary_provider_id'], ['ai_provider_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'app_key', name='uq_ai_assignment_org_app')
    )
    op.create_index(op.f('ix_ai_app_assignments_app_key'), 'ai_app_assignments', ['app_key'], unique=False)
    op.create_index(op.f('ix_ai_app_assignments_backup_provider_id'), 'ai_app_assignments', ['backup_provider_id'], unique=False)
    op.create_index(op.f('ix_ai_app_assignments_id'), 'ai_app_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_ai_app_assignments_org_id'), 'ai_app_assignments', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_app_assignments_primary_provider_id'), 'ai_app_assignments', ['primary_provider_id'], unique=False)
    op.create_table('audit_logs_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects_platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_platform_action'), 'audit_logs_platform', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_platform_actor_user_id'), 'audit_logs_platform', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_platform_id'), 'audit_logs_platform', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_platform_org_id'), 'audit_logs_platform', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_platform_project_id'), 'audit_logs_platform', ['project_id'], unique=False)
    op.create_table('memberships_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects_platform.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles_platform.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', 'project_id', name='uq_membership_user_org_project')
    )
    op.create_index(op.f('ix_memberships_platform_id'), 'memberships_platform', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_platform_org_id'), 'memberships_platform', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_platform_project_id'), 'memberships_platform', ['project_id'], unique=False)
    op.create_index(op.f('ix_memberships_platform_role_id'), 'memberships_platform', ['role_id'], unique=False)
    op.create_index(op.f('ix_memberships_platform_user_id'), 'memberships_platform', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memberships_platform_user_id'), table_name='memberships_platform')
    op.drop_index(op.f('ix_memberships_platform_role_id'), table_name='memberships_platform')
    op.drop_index(op.f('ix_memberships_platform_project_id'), table_name='memberships_platform')
    op.drop_index(op.f('ix_memberships_platform_org_id'), table_name='memberships_platform')
    op.drop_index(op.f('ix_memberships_platform_id'), table_name='memberships_platform')
    op.drop_table('memberships_platform')
    op.drop_index(op.f('ix_audit_logs_platform_project_id'), table_name='audit_logs_platform')
    op.drop_index(op.f('ix_audit_logs_platform_org_id'), table_name='audit_logs_platform')
    op.drop_index(op.f('ix_audit_logs_platform_id'), table_name='audit_logs_platform')
    op.drop_index(op.f('ix_audit_logs_platform_actor_user_id'), table_name='audit_logs_platform')
    op.drop_index(op.f('ix_audit_logs_platform_action'), table_name='audit_logs_platform')
    op.drop_table('audit_logs_platform')
    op.drop_index(op.f('ix_ai_app_assignments_primary_provider_id'), table_name='ai_app_assignments')
    op.drop_index(op.f('ix_ai_app_assignments_org_id'), table_name='ai_app_assignments')
    op.drop_index(op.f('ix_ai_app_assignments_id'), table_name='ai_app_assignments')
    op.drop_index(op.f('ix_ai_app_assignments_backup_provider_id'), table_name='ai_app_assignments')
    op.drop_index(op.f('ix_ai_app_assignments_app_key'), table_name='ai_app_assignments')
    op.drop_table('ai_app_assignments')
    op.drop_index(op.f('ix_roles_platform_scope'), table_name='roles_platform')
    op.drop_index(op.f('ix_roles_platform_org_id'), table_name='roles_platform')
    op.drop_index(op.f('ix_roles_platform_id'), table_name='roles_platform')
    op.drop_table('roles_platform')
    op.drop_index(op.f('ix_projects_platform_owner_user_id'), table_name='projects_platform')
    op.drop_index(op.f('ix_projects_platform_id'), table_name='projects_platform')
    op.drop_index(op.f('ix_projects_platform_code'), table_name='projects_platform')
    op.drop_index(op.f('ix_projects_platform_client_org_id'), table_name='projects_platform')
    op.drop_table('projects_platform')
    op.drop_index(op.f('ix_local_accounts_user_id'), table_name='local_accounts')
    op.drop_index(op.f('ix_local_accounts_org_id'), table_name='local_accounts')
    op.drop_index(op.f('ix_local_accounts_id'), table_name='local_accounts')
    op.drop_index(op.f('ix_local_accounts_email'), table_name='local_accounts')
    op.drop_table('local_accounts')
    op.drop_index(op.f('ix_data_backups_platform_org_id'), table_name='data_backups_platform')
    op.drop_index(op.f('ix_data_backups_platform_id'), table_name='data_backups_platform')
    op.drop_table('data_backups_platform')
    op.drop_index(op.f('ix_ai_provider_configs_provider_key'), table_name='ai_provider_configs')
    op.drop_index(op.f('ix_ai_provider_configs_org_id'), table_name='ai_provider_configs')
    op.drop_index(op.f('ix_ai_provider_configs_id'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    op.drop_index(op.f('ix_organizations_root_org_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_root_agency_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_parent_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_owner_user_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_org_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_invite_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_agent_level'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_template_snapshot_versions_version'), table_name='template_snapshot_versions')
    op.drop_index(op.f('ix_template_snapshot_versions_template_id'), table_name='template_snapshot_versions')
    op.drop_index(op.f('ix_template_snapshot_versions_id'), table_name='template_snapshot_versions')
    op.drop_table('template_snapshot_versions')
    op.drop_index(op.f('ix_template_snapshot_templates_template_type'), table_name='template_snapshot_templates')
    op.drop_index(op.f('ix_template_snapshot_templates_template_id'), table_name='template_snapshot_templates')
    op.drop_index(op.f('ix_template_snapshot_templates_owner_scope'), table_name='template_snapshot_templates')
    op.drop_index(op.f('ix_template_snapshot_templates_owner_id'), table_name='template_snapshot_templates')
    op.drop_index(op.f('ix_template_snapshot_templates_id'), table_name='template_snapshot_templates')
    op.drop_table('template_snapshot_templates')
    op.drop_index(op.f('ix_template_snapshot_instances_parent_id'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_owner_scope'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_owner_id'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_instance_type'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_instance_id'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_id'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_base_template_version'), table_name='template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_instances_base_template_id'), table_name='template_snapshot_instances')
    op.drop_table('template_snapshot_instances')
    op.drop_index(op.f('ix_template_snapshot_backups_version'), table_name='template_snapshot_backups')
    op.drop_index(op.f('ix_template_snapshot_backups_target_type'), table_name='template_snapshot_backups')
    op.drop_index(op.f('ix_template_snapshot_backups_target_id'), table_name='template_snapshot_backups')
    op.drop_index(op.f('ix_template_snapshot_backups_id'), table_name='template_snapshot_backups')
    op.drop_index(op.f('ix_template_snapshot_backups_backup_kind'), table_name='template_snapshot_backups')
    op.drop_index(op.f('ix_template_snapshot_backups_backup_id'), table_name='template_snapshot_backups')
    op.drop_table('template_snapshot_backups')
    # ### end Alembic commands ###

