"""governed customer behavior timeline

Revision ID: 5f9b2d7e4a16
Revises: 4e8a1c6d3f05
Create Date: 2026-08-03

Rollback removes only timeline projections, checkpoints, immutable versions,
handoff acknowledgements, evidence and permissions. It never deletes or
modifies touchpoints, inquiries, CPQ quotes, OMS orders, customer assets,
service tickets or downstream CRM/CDP records. Export manifests first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="5f9b2d7e4a16";down_revision="4e8a1c6d3f05";branch_labels=None;depends_on=None
PERMISSIONS=("factory.portrait.timeline.manage","factory.portrait.timeline.event.verify","factory.portrait.timeline.checkpoint.manage","factory.portrait.timeline.publish","factory.portrait.timeline.handoff.acknowledge")
TABLES=("factory_customer_timelines","factory_customer_timeline_events","factory_customer_timeline_versions","factory_customer_timeline_publications","factory_customer_timeline_checkpoints","factory_customer_timeline_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_customer_timelines",*tenant(),sa.Column("timeline_number",sa.String(96),nullable=False),sa.Column("timeline_name",sa.String(180),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("scope",sa.String(40),nullable=False,server_default="customer-360"),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("timeline_number",name="uq_factory_timeline_number"),sa.UniqueConstraint("project_id","account_reference",name="uq_factory_timeline_project_account"));indexes("factory_customer_timelines",("timeline_number","account_reference","status"))
    op.create_table("factory_customer_timeline_events",*tenant(),sa.Column("event_number",sa.String(96),nullable=False),sa.Column("timeline_id",sa.String(100),nullable=False),sa.Column("timeline_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("event_type",sa.String(48),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("intent_level",sa.String(16),nullable=False),sa.Column("source_type",sa.String(48),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("source_number",sa.String(100),nullable=False),sa.Column("source_revision",sa.Integer(),nullable=False),sa.Column("source_status",sa.String(40),nullable=False),sa.Column("source_fingerprint",sa.String(64),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("event_number",name="uq_factory_timeline_event_number"),sa.UniqueConstraint("timeline_id","source_type","source_id",name="uq_factory_timeline_source_event"));indexes("factory_customer_timeline_events",("event_number","timeline_id","account_reference","event_type","occurred_at","intent_level","source_type","source_id","status"))
    op.create_table("factory_customer_timeline_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("timeline_id",sa.String(100),nullable=False),sa.Column("timeline_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("event_count",sa.Integer(),nullable=False),sa.Column("source_type_count",sa.Integer(),nullable=False),sa.Column("high_intent_event_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_timeline_version_reference"),sa.UniqueConstraint("timeline_id","version_number",name="uq_factory_timeline_version"));indexes("factory_customer_timeline_versions",("version_reference","timeline_id","status"))
    op.create_table("factory_customer_timeline_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("timeline_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_timeline_publication_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_timeline_version_consumer"));indexes("factory_customer_timeline_publications",("publication_number","timeline_id","version_id","consumer","status"))
    op.create_table("factory_customer_timeline_checkpoints",*tenant(),sa.Column("checkpoint_number",sa.String(96),nullable=False),sa.Column("timeline_id",sa.String(100),nullable=False),sa.Column("checkpoint_code",sa.String(48),nullable=False),sa.Column("event_id",sa.String(100),nullable=False),sa.Column("event_number",sa.String(96),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("note",sa.Text()),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("checkpoint_number",name="uq_factory_timeline_checkpoint_number"),sa.UniqueConstraint("timeline_id","checkpoint_code",name="uq_factory_timeline_checkpoint"));indexes("factory_customer_timeline_checkpoints",("checkpoint_number","timeline_id","event_id"))
    op.create_table("factory_customer_timeline_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_timeline_evidence_number"));indexes("factory_customer_timeline_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
