"""consent-bound audience segments and activations

Revision ID: 6a0c3e8f5b27
Revises: 5f9b2d7e4a16
Create Date: 2026-08-03

Rollback removes only segment definitions, consent-bound membership projections,
immutable versions, activations, evidence and permissions. It never deletes or
modifies identity consent, signals, customer timelines or downstream systems.
Export manifests and acknowledgements first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="6a0c3e8f5b27";down_revision="5f9b2d7e4a16";branch_labels=None;depends_on=None
PERMISSIONS=("factory.portrait.segment.manage","factory.portrait.segment.rule.approve","factory.portrait.segment.membership.evaluate","factory.portrait.segment.membership.verify","factory.portrait.segment.publish","factory.portrait.segment.activation.acknowledge")
TABLES=("factory_audience_segments","factory_audience_segment_rules","factory_audience_memberships","factory_audience_segment_versions","factory_audience_activations","factory_audience_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_audience_segments",*tenant(),sa.Column("segment_number",sa.String(96),nullable=False),sa.Column("segment_code",sa.String(64),nullable=False),sa.Column("segment_name",sa.String(180),nullable=False),sa.Column("business_purpose",sa.String(255),nullable=False),sa.Column("allowed_channels_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("segment_number",name="uq_factory_segment_number"),sa.UniqueConstraint("project_id","segment_code",name="uq_factory_segment_project_code"));indexes("factory_audience_segments",("segment_number","segment_code","status"))
    op.create_table("factory_audience_segment_rules",*tenant(),sa.Column("rule_number",sa.String(96),nullable=False),sa.Column("segment_id",sa.String(100),nullable=False),sa.Column("segment_number",sa.String(96),nullable=False),sa.Column("rule_code",sa.String(64),nullable=False),sa.Column("rule_name",sa.String(180),nullable=False),sa.Column("minimum_high_intent_events",sa.Integer(),nullable=False),sa.Column("required_source_types_json",sa.JSON(),nullable=False),sa.Column("required_consent_purposes_json",sa.JSON(),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("rule_number",name="uq_factory_segment_rule_number"),sa.UniqueConstraint("segment_id","rule_code",name="uq_factory_segment_rule_code"));indexes("factory_audience_segment_rules",("rule_number","segment_id","status"))
    op.create_table("factory_audience_memberships",*tenant(),sa.Column("membership_number",sa.String(96),nullable=False),sa.Column("segment_id",sa.String(100),nullable=False),sa.Column("segment_number",sa.String(96),nullable=False),sa.Column("rule_id",sa.String(100),nullable=False),sa.Column("rule_number",sa.String(96),nullable=False),sa.Column("rule_definition_hash",sa.String(64),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("contact_signal_id",sa.String(100),nullable=False),sa.Column("contact_signal_number",sa.String(96),nullable=False),sa.Column("contact_hash",sa.String(64),nullable=False),sa.Column("contact_hint",sa.String(32),nullable=False),sa.Column("contact_revision",sa.Integer(),nullable=False),sa.Column("contact_fingerprint",sa.String(64),nullable=False),sa.Column("consent_id",sa.String(100),nullable=False),sa.Column("consent_number",sa.String(96),nullable=False),sa.Column("consent_revision",sa.Integer(),nullable=False),sa.Column("consent_event_hash",sa.String(64),nullable=False),sa.Column("consent_expires_at",sa.DateTime(timezone=True),nullable=False),sa.Column("timeline_version_id",sa.String(100),nullable=False),sa.Column("timeline_version_reference",sa.String(96),nullable=False),sa.Column("timeline_manifest_hash",sa.String(64),nullable=False),sa.Column("high_intent_event_count",sa.Integer(),nullable=False),sa.Column("source_types_json",sa.JSON(),nullable=False),sa.Column("evaluation_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("evaluated_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("membership_number",name="uq_factory_segment_membership_number"),sa.UniqueConstraint("segment_id","contact_signal_id",name="uq_factory_segment_contact"));indexes("factory_audience_memberships",("membership_number","segment_id","rule_id","account_reference","contact_signal_id","consent_id","timeline_version_id","status"))
    op.create_table("factory_audience_segment_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("segment_id",sa.String(100),nullable=False),sa.Column("segment_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("member_count",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_segment_version_reference"),sa.UniqueConstraint("segment_id","version_number",name="uq_factory_segment_version"));indexes("factory_audience_segment_versions",("version_reference","segment_id","status"))
    op.create_table("factory_audience_activations",*tenant(),sa.Column("activation_number",sa.String(96),nullable=False),sa.Column("segment_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("activation_number",name="uq_factory_segment_activation_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_segment_version_consumer"));indexes("factory_audience_activations",("activation_number","segment_id","version_id","consumer","status"))
    op.create_table("factory_audience_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_audience_evidence_number"));indexes("factory_audience_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
