"""authorized proof-content releases

Revision ID: 6b4e1d9a2f70
Revises: 4d9e2b7c1f83

Rollback removes only authorized-proof governance records, permissions and
contracts; it never deletes source editor content, assets, authorization files
or consumer-owned publication copies.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="6b4e1d9a2f70";down_revision="4d9e2b7c1f83";branch_labels=None;depends_on=None
PERMISSIONS=("factory.content.proof.asset.manage","factory.content.proof.version.verify","factory.content.proof.publication.approve","factory.content.proof.handoff.acknowledge");TABLES=("factory_content_proof_assets","factory_content_proof_versions","factory_content_proof_publications","factory_content_proof_evidence")
def tenant(): return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(t,*xs):
 for x in ("project_id","agent_path","tenant_id","client_id","plan_id",*xs):op.create_index(f"ix_{t}_{x}",t,[x])
def permissions(remove=False):
 b=op.get_bind();rows=b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for r in rows:
  try:v=json.loads(r["permissions_json"] or "[]")
  except (TypeError,ValueError):v=[]
  v=[x for x in v if x not in PERMISSIONS] if remove else list(dict.fromkeys([*v,*PERMISSIONS]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_content_proof_assets",*tenant(),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("content_type",sa.String(16),nullable=False),sa.Column("content_reference",sa.String(160),nullable=False),sa.Column("display_name",sa.String(200),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("authorization_reference",sa.String(255),nullable=False),sa.Column("public_scope",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="active"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("asset_number",name="uq_factory_content_proof_asset_number"),sa.UniqueConstraint("project_id","content_type","content_reference",name="uq_factory_content_proof_reference"));indexes("factory_content_proof_assets","asset_number","content_type","status")
 op.create_table("factory_content_proof_versions",*tenant(),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("locale",sa.String(16),nullable=False),sa.Column("content_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("version_number",name="uq_factory_content_proof_version_number"),sa.UniqueConstraint("asset_id","version_number",name="uq_factory_content_proof_version"));indexes("factory_content_proof_versions","version_number","asset_id","status")
 op.create_table("factory_content_proof_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("proof_version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("release_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_content_proof_publication_number"),sa.UniqueConstraint("proof_version_id","target",name="uq_factory_content_proof_publication_target"));indexes("factory_content_proof_publications","publication_number","asset_id","proof_version_id","status","available")
 op.create_table("factory_content_proof_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_content_proof_evidence_number"));indexes("factory_content_proof_evidence","evidence_number","subject_type","subject_id")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'authorized-proof-content-version',32,'Authorized proof content version','content','tenant, asset and version','[\"tenantId\",\"assetId\",\"versionId\",\"authorizationReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='authorized-proof-content-version')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'authorized-proof-content-released',24,'Authorized proof content released','authorized-proof-content-version','content','[\"site\",\"seo\",\"sales\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='authorized-proof-content-released')"));permissions()
def downgrade():
 permissions(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='authorized-proof-content-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='authorized-proof-content-version'"))
 for t in reversed(TABLES):op.drop_table(t)
