"""governed enterprise targeting and ABM

Revision ID: 7b1d4f9a6c38
Revises: 6a0c3e8f5b27
Create Date: 2026-08-03

Rollback removes only ABM programs, source-pinned target projections, role
plays, immutable versions, activations, evidence and permissions. It never
deletes or modifies consent segments, identity records, buying committees,
ICP/CPQ records or downstream systems. Export manifests and receipts first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="7b1d4f9a6c38";down_revision="6a0c3e8f5b27";branch_labels=None;depends_on=None
PERMISSIONS=("factory.lead.abm.manage","factory.lead.abm.target.verify","factory.lead.abm.play.approve","factory.lead.abm.publish","factory.lead.abm.activation.acknowledge")
TABLES=("factory_abm_programs","factory_abm_target_accounts","factory_abm_role_plays","factory_abm_versions","factory_abm_activations","factory_abm_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
 for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
 bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for row in rows:
  try:values=json.loads(row["permissions_json"] or "[]")
  except (TypeError,ValueError):values=[]
  if not isinstance(values,list):values=[]
  values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
 op.create_table("factory_abm_programs",*tenant(),sa.Column("program_number",sa.String(96),nullable=False),sa.Column("program_code",sa.String(64),nullable=False),sa.Column("program_name",sa.String(180),nullable=False),sa.Column("business_objective",sa.String(255),nullable=False),sa.Column("allowed_consumers_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("program_number",name="uq_factory_abm_program_number"),sa.UniqueConstraint("project_id","program_code",name="uq_factory_abm_project_code"));indexes("factory_abm_programs",("program_number","program_code","status"))
 op.create_table("factory_abm_target_accounts",*tenant(),sa.Column("target_number",sa.String(96),nullable=False),sa.Column("program_id",sa.String(100),nullable=False),sa.Column("program_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("priority_tier",sa.String(16),nullable=False),sa.Column("fit_score",sa.Float(),nullable=False),sa.Column("audience_segment_id",sa.String(100),nullable=False),sa.Column("audience_version_id",sa.String(100),nullable=False),sa.Column("audience_version_reference",sa.String(96),nullable=False),sa.Column("audience_manifest_hash",sa.String(64),nullable=False),sa.Column("consented_member_count",sa.Integer(),nullable=False),sa.Column("buying_committee_id",sa.String(100),nullable=False),sa.Column("buying_version_id",sa.String(100),nullable=False),sa.Column("buying_version_reference",sa.String(96),nullable=False),sa.Column("buying_manifest_hash",sa.String(64),nullable=False),sa.Column("opportunity_number",sa.String(100),nullable=False),sa.Column("required_role_count",sa.Integer(),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("source_fingerprint",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("target_number",name="uq_factory_abm_target_number"),sa.UniqueConstraint("program_id","account_reference",name="uq_factory_abm_program_account"));indexes("factory_abm_target_accounts",("target_number","program_id","account_reference","audience_segment_id","audience_version_id","buying_committee_id","buying_version_id","status"))
 op.create_table("factory_abm_role_plays",*tenant(),sa.Column("play_number",sa.String(96),nullable=False),sa.Column("program_id",sa.String(100),nullable=False),sa.Column("target_id",sa.String(100),nullable=False),sa.Column("target_number",sa.String(96),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("committee_member_id",sa.String(100),nullable=False),sa.Column("committee_member_number",sa.String(96),nullable=False),sa.Column("role_code",sa.String(64),nullable=False),sa.Column("role_name",sa.String(128),nullable=False),sa.Column("contact_hash",sa.String(64),nullable=False),sa.Column("member_fingerprint",sa.String(64),nullable=False),sa.Column("owner_team",sa.String(24),nullable=False),sa.Column("channel",sa.String(32),nullable=False),sa.Column("action_code",sa.String(64),nullable=False),sa.Column("message_intent",sa.String(255),nullable=False),sa.Column("success_signal",sa.String(180),nullable=False),sa.Column("sequence_order",sa.Integer(),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("play_number",name="uq_factory_abm_play_number"),sa.UniqueConstraint("target_id","committee_member_id",name="uq_factory_abm_target_member_play"));indexes("factory_abm_role_plays",("play_number","program_id","target_id","account_reference","committee_member_id","status"))
 op.create_table("factory_abm_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("program_id",sa.String(100),nullable=False),sa.Column("program_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("target_count",sa.Integer(),nullable=False),sa.Column("role_play_count",sa.Integer(),nullable=False),sa.Column("role_coverage_percent",sa.Float(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_abm_version_reference"),sa.UniqueConstraint("program_id","version_number",name="uq_factory_abm_program_version"));indexes("factory_abm_versions",("version_reference","program_id","status"))
 op.create_table("factory_abm_activations",*tenant(),sa.Column("activation_number",sa.String(96),nullable=False),sa.Column("program_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("activation_number",name="uq_factory_abm_activation_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_abm_version_consumer"));indexes("factory_abm_activations",("activation_number","program_id","version_id","consumer","status"))
 op.create_table("factory_abm_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_abm_evidence_number"));indexes("factory_abm_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
 permissions(True)
 for table in reversed(TABLES):op.drop_table(table)
