"""controlled technical SEO audit and remediation handoff

Revision ID: 7c5e2f9a1d84
Revises: 6b4e1d9a2f70

Rollback removes only this tenant-scoped SEO evidence projection, permissions
and frozen contracts. It never deletes website content, robots, sitemap,
search-platform settings, crawler credentials or consumer-owned work records.
"""
import json
from alembic import op
import sqlalchemy as sa

revision="7c5e2f9a1d84"; down_revision="6b4e1d9a2f70"; branch_labels=None; depends_on=None
PERMISSIONS=("factory.trust.technical-seo.audit.manage","factory.trust.technical-seo.snapshot.verify","factory.trust.technical-seo.release.approve","factory.trust.technical-seo.handoff.acknowledge")
TABLES=("factory_technical_seo_audits","factory_technical_seo_snapshots","factory_technical_seo_releases","factory_technical_seo_evidence")
def tenant(): return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,*fields):
 for field in ("project_id","agent_path","tenant_id","client_id","plan_id",*fields): op.create_index(f"ix_{table}_{field}",table,[field])
def permissions(remove=False):
 bind=op.get_bind(); rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for row in rows:
  try: values=json.loads(row["permissions_json"] or "[]")
  except (TypeError,ValueError): values=[]
  values=[value for value in values if value not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS])); bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(values,ensure_ascii=False),"i":row["id"]})
def upgrade():
 op.create_table("factory_technical_seo_audits",*tenant(),sa.Column("audit_number",sa.String(96),nullable=False),sa.Column("site_reference",sa.String(255),nullable=False),sa.Column("audit_reference",sa.String(255),nullable=False),sa.Column("public_scope",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="active"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("audit_number",name="uq_factory_technical_seo_audit_number"),sa.UniqueConstraint("project_id","site_reference","audit_reference",name="uq_factory_technical_seo_audit")); indexes("factory_technical_seo_audits","audit_number","status")
 op.create_table("factory_technical_seo_snapshots",*tenant(),sa.Column("snapshot_number",sa.String(96),nullable=False),sa.Column("audit_id",sa.String(100),nullable=False),sa.Column("audit_number",sa.String(96),nullable=False),sa.Column("evidence_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("captured_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("captured_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("snapshot_number",name="uq_factory_technical_seo_snapshot_number"),sa.UniqueConstraint("audit_id","snapshot_number",name="uq_factory_technical_seo_snapshot")); indexes("factory_technical_seo_snapshots","snapshot_number","audit_id","status")
 op.create_table("factory_technical_seo_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("audit_id",sa.String(100),nullable=False),sa.Column("snapshot_id",sa.String(100),nullable=False),sa.Column("snapshot_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("remediation_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number",name="uq_factory_technical_seo_release_number"),sa.UniqueConstraint("snapshot_id","target",name="uq_factory_technical_seo_release")); indexes("factory_technical_seo_releases","release_number","audit_id","snapshot_id","status","available")
 op.create_table("factory_technical_seo_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_technical_seo_evidence_number")); indexes("factory_technical_seo_evidence","evidence_number","subject_type","subject_id")
 bind=op.get_bind(); bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'technical-seo-evidence-snapshot',33,'Technical SEO evidence snapshot','seo','tenant, audit and snapshot','[\"tenantId\",\"auditId\",\"snapshotId\",\"siteReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='technical-seo-evidence-snapshot')")); bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'technical-seo-remediation-released',25,'Technical SEO remediation released','technical-seo-evidence-snapshot','trust','[\"site-owner\",\"web-team\",\"seo-operations\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='technical-seo-remediation-released')")); permissions()
def downgrade():
 permissions(True); bind=op.get_bind(); bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='technical-seo-remediation-released'")); bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='technical-seo-evidence-snapshot'"))
 for table in reversed(TABLES): op.drop_table(table)
