"""governed creative center

Revision ID: 8c2e5a0b7d49
Revises: 7b1d4f9a6c38
Create Date: 2026-08-03

Rollback removes only creative briefs, variants, immutable versions,
activations, evidence and permissions. It never deletes or modifies ABM,
DAM, rights, source files or downstream systems. Export hashes first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="8c2e5a0b7d49";down_revision="7b1d4f9a6c38";branch_labels=None;depends_on=None
PERMISSIONS=("factory.lead.creative.manage","factory.lead.creative.variant.approve","factory.lead.creative.publish","factory.lead.creative.activation.acknowledge");TABLES=("factory_creative_briefs","factory_creative_variants","factory_creative_versions","factory_creative_activations","factory_creative_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def idx(t,extra=()):
 for c in ("project_id","agent_path","tenant_id","client_id","plan_id",*extra):op.create_index(f"ix_{t}_{c}",t,[c])
def perms(remove):
 b=op.get_bind()
 for r in b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all():
  try:v=json.loads(r["permissions_json"] or "[]")
  except (TypeError,ValueError):v=[]
  v=[x for x in v if x not in PERMISSIONS] if remove else list(dict.fromkeys([*v,*PERMISSIONS]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(v,ensure_ascii=False),"id":r["id"]})
def upgrade():
 op.create_table("factory_creative_briefs",*tenant(),sa.Column("brief_number",sa.String(96),nullable=False),sa.Column("brief_code",sa.String(64),nullable=False),sa.Column("brief_name",sa.String(180),nullable=False),sa.Column("objective",sa.String(255),nullable=False),sa.Column("abm_program_id",sa.String(100),nullable=False),sa.Column("abm_version_id",sa.String(100),nullable=False),sa.Column("abm_version_reference",sa.String(96),nullable=False),sa.Column("abm_manifest_hash",sa.String(64),nullable=False),sa.Column("country_pack_id",sa.String(100),nullable=False),sa.Column("country_pack_number",sa.String(96),nullable=False),sa.Column("country_pack_manifest_hash",sa.String(64),nullable=False),sa.Column("target_market",sa.String(64),nullable=False),sa.Column("target_locale",sa.String(16),nullable=False),sa.Column("allowed_consumers_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("brief_number",name="uq_factory_creative_brief_number"),sa.UniqueConstraint("project_id","brief_code",name="uq_factory_creative_project_code"));idx("factory_creative_briefs",("brief_number","brief_code","abm_program_id","abm_version_id","country_pack_id","status"))
 op.create_table("factory_creative_variants",*tenant(),sa.Column("variant_number",sa.String(96),nullable=False),sa.Column("brief_id",sa.String(100),nullable=False),sa.Column("brief_number",sa.String(96),nullable=False),sa.Column("abm_play_id",sa.String(100),nullable=False),sa.Column("abm_play_number",sa.String(96),nullable=False),sa.Column("role_code",sa.String(64),nullable=False),sa.Column("role_name",sa.String(128),nullable=False),sa.Column("channel",sa.String(32),nullable=False),sa.Column("headline",sa.String(180),nullable=False),sa.Column("message_body",sa.Text(),nullable=False),sa.Column("call_to_action",sa.String(128),nullable=False),sa.Column("source_pack_hash",sa.String(64),nullable=False),sa.Column("play_definition_hash",sa.String(64),nullable=False),sa.Column("ai_assisted",sa.Boolean(),nullable=False,server_default="0"),sa.Column("model_reference",sa.String(255)),sa.Column("prompt_hash",sa.String(64)),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="review"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("variant_number",name="uq_factory_creative_variant_number"),sa.UniqueConstraint("brief_id","abm_play_id",name="uq_factory_creative_brief_play"));idx("factory_creative_variants",("variant_number","brief_id","abm_play_id","role_code","status"))
 op.create_table("factory_creative_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("brief_id",sa.String(100),nullable=False),sa.Column("brief_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("variant_count",sa.Integer(),nullable=False),sa.Column("role_coverage_percent",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_creative_version_reference"),sa.UniqueConstraint("brief_id","version_number",name="uq_factory_creative_brief_version"));idx("factory_creative_versions",("version_reference","brief_id","status"))
 op.create_table("factory_creative_activations",*tenant(),sa.Column("activation_number",sa.String(96),nullable=False),sa.Column("brief_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("activation_number",name="uq_factory_creative_activation_number"),sa.UniqueConstraint("version_id","consumer",name="uq_factory_creative_version_consumer"));idx("factory_creative_activations",("activation_number","brief_id","version_id","consumer","status"))
 op.create_table("factory_creative_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_creative_evidence_number"));idx("factory_creative_evidence",("evidence_number","subject_type","subject_id"));perms(False)
def downgrade():
 perms(True)
 for t in reversed(TABLES):op.drop_table(t)
