"""controlled source-dated keyword topic maps

Revision ID: 8d6f3a2b1c95
Revises: 7c5e2f9a1d84

Rollback removes only keyword-map governance records, permissions and contracts;
it never deletes source datasets, customer content, search-platform settings or consumer work.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="8d6f3a2b1c95";down_revision="7c5e2f9a1d84";branch_labels=None;depends_on=None
P=("factory.trust.keyword-map.study.manage","factory.trust.keyword-map.version.verify","factory.trust.keyword-map.release.approve","factory.trust.keyword-map.handoff.acknowledge");T=("factory_keyword_map_studies","factory_keyword_map_versions","factory_keyword_map_releases","factory_keyword_map_evidence")
def tenant():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(t,*x):
 for n in("project_id","agent_path","tenant_id","client_id","plan_id",*x):op.create_index(f"ix_{t}_{n}",t,[n])
def perms(remove=False):
 b=op.get_bind();rows=b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for r in rows:
  try:v=json.loads(r["permissions_json"]or"[]")
  except(TypeError,ValueError):v=[]
  v=[z for z in v if z not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_keyword_map_studies",*tenant(),sa.Column("study_number",sa.String(96),nullable=False),sa.Column("market",sa.String(80),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("observed_on",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="active"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("study_number"),sa.UniqueConstraint("project_id","market","source_reference",name="uq_factory_keyword_map_study"));ix("factory_keyword_map_studies","study_number","status")
 op.create_table("factory_keyword_map_versions",*tenant(),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("study_id",sa.String(100),nullable=False),sa.Column("study_number",sa.String(96),nullable=False),sa.Column("topic_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("version_number"));ix("factory_keyword_map_versions","version_number","study_id","status")
 op.create_table("factory_keyword_map_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("study_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("activation_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number"));ix("factory_keyword_map_releases","release_number","study_id","version_id","status","available")
 op.create_table("factory_keyword_map_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_keyword_map_evidence","evidence_number","subject_type","subject_id")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'keyword-topic-map-version',34,'Keyword topic map version','trust','tenant, study and version','[\"tenantId\",\"studyId\",\"versionId\",\"sourceReference\",\"observedOn\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='keyword-topic-map-version')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'keyword-topic-map-released',26,'Keyword topic map released','keyword-topic-map-version','trust','[\"content\",\"seo\",\"sales\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='keyword-topic-map-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='keyword-topic-map-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='keyword-topic-map-version'"))
 for t in reversed(T):op.drop_table(t)
