"""human-governed AI SDR

Revision ID: 9d3f6b1c8e50
Revises: 8c2e5a0b7d49
Create Date: 2026-08-03

Rollback removes only AI SDR projections, recommendations, handoffs, evidence
and permissions. It never changes ICP evidence, inquiry/CPQ sources, CRM or
customer identifiers. Export manifests and acknowledgements before rollback.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="9d3f6b1c8e50";down_revision="8c2e5a0b7d49";branch_labels=None;depends_on=None
PERMISSIONS=("factory.convert.ai-sdr.manage","factory.convert.ai-sdr.review","factory.convert.ai-sdr.handoff","factory.convert.ai-sdr.handoff.acknowledge");TABLES=("factory_ai_sdr_leads","factory_ai_sdr_recommendations","factory_ai_sdr_handoffs","factory_ai_sdr_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def idx(t,extra=()):
 for c in ("project_id","agent_path","tenant_id","client_id","plan_id",*extra):op.create_index(f"ix_{t}_{c}",t,[c])
def perms(remove):
 b=op.get_bind()
 for r in b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all():
  try:v=json.loads(r["permissions_json"] or "[]")
  except (TypeError,ValueError):v=[]
  v=[x for x in v if x not in PERMISSIONS] if remove else list(dict.fromkeys([*v,*PERMISSIONS]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(v,ensure_ascii=False),"id":r["id"]})
def upgrade():
 op.create_table("factory_ai_sdr_leads",*tenant(),sa.Column("lead_number",sa.String(96),nullable=False),sa.Column("assessment_id",sa.String(100),nullable=False),sa.Column("assessment_number",sa.String(96),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("profile_version",sa.Integer(),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("account_reference",sa.String(180),nullable=False),sa.Column("account_reference_hash",sa.String(64),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("fit_tier",sa.String(16),nullable=False),sa.Column("fit_score",sa.String(16),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("lead_number",name="uq_factory_ai_sdr_lead_number"),sa.UniqueConstraint("project_id","assessment_id",name="uq_factory_ai_sdr_project_assessment"));idx("factory_ai_sdr_leads",("lead_number","assessment_id","profile_id","account_reference","status"))
 op.create_table("factory_ai_sdr_recommendations",*tenant(),sa.Column("recommendation_number",sa.String(96),nullable=False),sa.Column("lead_id",sa.String(100),nullable=False),sa.Column("lead_number",sa.String(96),nullable=False),sa.Column("sequence_number",sa.Integer(),nullable=False),sa.Column("model_reference",sa.String(255),nullable=False),sa.Column("prompt_hash",sa.String(64),nullable=False),sa.Column("enrichment_summary",sa.Text(),nullable=False),sa.Column("intent_score",sa.Integer(),nullable=False),sa.Column("qualification_proposal",sa.String(24),nullable=False),sa.Column("reply_subject",sa.String(180),nullable=False),sa.Column("reply_body",sa.Text(),nullable=False),sa.Column("next_action",sa.String(255),nullable=False),sa.Column("output_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending-review"),sa.Column("generated_by",sa.String(128),nullable=False),sa.Column("reviewed_by",sa.String(128)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_reference",sa.String(255)),sa.Column("review_note",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("recommendation_number",name="uq_factory_ai_sdr_recommendation_number"),sa.UniqueConstraint("lead_id","sequence_number",name="uq_factory_ai_sdr_lead_sequence"));idx("factory_ai_sdr_recommendations",("recommendation_number","lead_id","status"))
 op.create_table("factory_ai_sdr_handoffs",*tenant(),sa.Column("handoff_number",sa.String(96),nullable=False),sa.Column("lead_id",sa.String(100),nullable=False),sa.Column("recommendation_id",sa.String(100),nullable=False),sa.Column("recommendation_number",sa.String(96),nullable=False),sa.Column("owner_team",sa.String(64),nullable=False),sa.Column("sla_minutes",sa.Integer(),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("crm_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("handoff_number",name="uq_factory_ai_sdr_handoff_number"),sa.UniqueConstraint("recommendation_id",name="uq_factory_ai_sdr_recommendation_handoff"));idx("factory_ai_sdr_handoffs",("handoff_number","lead_id","recommendation_id","status"))
 op.create_table("factory_ai_sdr_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_ai_sdr_evidence_number"));idx("factory_ai_sdr_evidence",("evidence_number","subject_type","subject_id"));perms(False)
def downgrade():
 perms(True)
 for t in reversed(TABLES):op.drop_table(t)
