"""controlled page SEO recommendation handoffs

Revision ID: 9e7a3c2d1b86
Revises: 8d6f3a2b1c95

Rollback removes only page-SEO governance records, permissions and contracts;
it never deletes source pages, content, CMS settings or consumer work.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="9e7a3c2d1b86";down_revision="8d6f3a2b1c95";branch_labels=None;depends_on=None
P=("factory.trust.onpage.page.manage","factory.trust.onpage.version.review","factory.trust.onpage.release.approve","factory.trust.onpage.handoff.acknowledge");T=("factory_onpage_seo_pages","factory_onpage_seo_versions","factory_onpage_seo_releases","factory_onpage_seo_evidence")
def tenant():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(t,*x):
 for n in("project_id","agent_path","tenant_id","client_id","plan_id",*x):op.create_index(f"ix_{t}_{n}",t,[n])
def perms(remove=False):
 b=op.get_bind();rows=b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for r in rows:
  try:v=json.loads(r["permissions_json"]or"[]")
  except(TypeError,ValueError):v=[]
  v=[z for z in v if z not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_onpage_seo_pages",*tenant(),sa.Column("page_number",sa.String(96),nullable=False),sa.Column("page_reference",sa.String(255),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("locale",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="active"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("page_number"),sa.UniqueConstraint("project_id","page_reference","source_reference",name="uq_factory_onpage_seo_page"));ix("factory_onpage_seo_pages","page_number","status")
 op.create_table("factory_onpage_seo_versions",*tenant(),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("page_id",sa.String(100),nullable=False),sa.Column("page_number",sa.String(96),nullable=False),sa.Column("suggestion_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("reviewed_by",sa.String(128)),sa.Column("review_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("version_number"));ix("factory_onpage_seo_versions","version_number","page_id","status")
 op.create_table("factory_onpage_seo_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("page_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("handoff_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number"));ix("factory_onpage_seo_releases","release_number","page_id","version_id","status","available")
 op.create_table("factory_onpage_seo_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_onpage_seo_evidence","evidence_number","subject_type","subject_id")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'onpage-seo-suggestion-version',35,'On-page SEO suggestion version','trust','tenant, page and version','[\"tenantId\",\"pageId\",\"versionId\",\"sourceReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='onpage-seo-suggestion-version')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'onpage-seo-handoff-released',27,'On-page SEO handoff released','onpage-seo-suggestion-version','trust','[\"content\",\"seo\",\"web\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='onpage-seo-handoff-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='onpage-seo-handoff-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='onpage-seo-suggestion-version'"))
 for t in reversed(T):op.drop_table(t)
