"""factory governed recruiting and structured interview center

Revision ID: a2e84b0c3df1
Revises: f1d73a9b2ce0
Create Date: 2026-08-02

Rollback removes only recruiting-owned requisitions, candidate references,
applications, interviews, offers, HR handoffs, evidence and permissions. It
never removes HR employees, contracts, payroll, CRM contacts or marketing data.
Export active applications and accepted-offer handoffs before production rollback.
"""

from __future__ import annotations
import json
from alembic import op
import sqlalchemy as sa

revision="a2e84b0c3df1"; down_revision="f1d73a9b2ce0"; branch_labels=None; depends_on=None
PERMISSIONS=("factory.operations.recruiting.requisition.manage","factory.operations.recruiting.requisition.approve","factory.operations.recruiting.candidate.manage","factory.operations.recruiting.application.manage","factory.operations.recruiting.interview.manage","factory.operations.recruiting.interview.assess","factory.operations.recruiting.decision.make","factory.operations.recruiting.offer.manage","factory.operations.recruiting.offer.approve","factory.operations.recruiting.handoff.manage")
INDEXES={
"factory_recruiting_requisitions":("project_id","agent_path","tenant_id","client_id","plan_id","requisition_number","requisition_reference","position_id","position_number","employment_type","target_start_date","status","authored_by","approved_by","closed_by","updated_by"),
"factory_recruiting_candidates":("project_id","agent_path","tenant_id","client_id","plan_id","candidate_number","candidate_reference","email","country_code","source_type","retention_until","status","created_by","updated_by"),
"factory_recruiting_applications":("project_id","agent_path","tenant_id","client_id","plan_id","application_number","requisition_id","requisition_number","candidate_id","candidate_number","application_reference","current_stage","status","submitted_by","final_decision","decided_by","updated_by"),
"factory_recruiting_interviews":("project_id","agent_path","tenant_id","client_id","plan_id","interview_number","application_id","application_number","interview_type","scheduled_at","status","scheduled_by","completed_by","updated_by"),
"factory_recruiting_assessments":("project_id","agent_path","tenant_id","client_id","plan_id","assessment_number","interview_id","interview_number","application_id","ai_assisted","assessed_by"),
"factory_recruiting_offers":("project_id","agent_path","tenant_id","client_id","plan_id","offer_number","application_id","application_number","position_id","candidate_id","offer_reference","proposed_start_date","compensation_band","status","authored_by","approved_by","sent_by","responded_by","updated_by"),
"factory_recruiting_onboarding_handoffs":("project_id","agent_path","tenant_id","client_id","plan_id","handoff_number","offer_id","offer_number","candidate_id","candidate_number","position_id","position_number","status","created_by","consumed_employee_id","consumed_by"),
"factory_recruiting_evidence":("project_id","agent_path","tenant_id","client_id","plan_id","evidence_number","subject_type","subject_id","subject_number","evidence_type","recorded_by")}

def tenant(): return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(500),nullable=False),sa.Column("tenant_id",sa.String(100),nullable=False),sa.Column("client_id",sa.String(100),nullable=False),sa.Column("plan_id",sa.String(100),nullable=False)]
def indexes(table):
    for column in INDEXES[table]: op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind(); rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try: values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError): values=[]
        if not isinstance(values,list): values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]))
        bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})

def upgrade():
    op.create_table("factory_recruiting_requisitions",*tenant(),sa.Column("requisition_number",sa.String(100),nullable=False),sa.Column("requisition_reference",sa.String(255),nullable=False),sa.Column("position_id",sa.String(100),nullable=False),sa.Column("position_number",sa.String(100),nullable=False),sa.Column("opening_count",sa.Integer(),nullable=False),sa.Column("employment_type",sa.String(30),nullable=False),sa.Column("work_location",sa.String(255),nullable=False),sa.Column("target_start_date",sa.Date(),nullable=False),sa.Column("hiring_reason",sa.Text(),nullable=False),sa.Column("rubric_version",sa.String(40),nullable=False),sa.Column("rubric_json",sa.Text(),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(255),nullable=False),sa.Column("approval_reference",sa.String(500)),sa.Column("approved_by",sa.String(255)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("closed_by",sa.String(255)),sa.Column("closed_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("requisition_number",name="uq_factory_recruiting_requisition_number"),sa.UniqueConstraint("tenant_id","requisition_reference",name="uq_factory_recruiting_tenant_requisition_reference")); indexes("factory_recruiting_requisitions")
    op.create_table("factory_recruiting_candidates",*tenant(),sa.Column("candidate_number",sa.String(100),nullable=False),sa.Column("candidate_reference",sa.String(255),nullable=False),sa.Column("display_name",sa.String(255),nullable=False),sa.Column("email",sa.String(320),nullable=False),sa.Column("country_code",sa.String(2),nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("source_reference",sa.String(500),nullable=False),sa.Column("consent_reference",sa.String(500),nullable=False),sa.Column("privacy_notice_reference",sa.String(500),nullable=False),sa.Column("retention_until",sa.Date(),nullable=False),sa.Column("profile_reference",sa.String(500),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("candidate_number",name="uq_factory_recruiting_candidate_number"),sa.UniqueConstraint("tenant_id","candidate_reference",name="uq_factory_recruiting_tenant_candidate_reference"),sa.UniqueConstraint("tenant_id","email",name="uq_factory_recruiting_tenant_candidate_email")); indexes("factory_recruiting_candidates")
    op.create_table("factory_recruiting_applications",*tenant(),sa.Column("application_number",sa.String(100),nullable=False),sa.Column("requisition_id",sa.String(100),nullable=False),sa.Column("requisition_number",sa.String(100),nullable=False),sa.Column("candidate_id",sa.String(100),nullable=False),sa.Column("candidate_number",sa.String(100),nullable=False),sa.Column("application_reference",sa.String(255),nullable=False),sa.Column("submitted_evidence_reference",sa.String(500),nullable=False),sa.Column("current_stage",sa.String(30),nullable=False,server_default="applied"),sa.Column("status",sa.String(30),nullable=False,server_default="active"),sa.Column("submitted_by",sa.String(255),nullable=False),sa.Column("final_decision",sa.String(30)),sa.Column("decision_reason",sa.Text()),sa.Column("decided_by",sa.String(255)),sa.Column("decided_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("application_number",name="uq_factory_recruiting_application_number"),sa.UniqueConstraint("requisition_id","candidate_id",name="uq_factory_recruiting_requisition_candidate")); indexes("factory_recruiting_applications")
    op.create_table("factory_recruiting_interviews",*tenant(),sa.Column("interview_number",sa.String(100),nullable=False),sa.Column("application_id",sa.String(100),nullable=False),sa.Column("application_number",sa.String(100),nullable=False),sa.Column("interview_type",sa.String(30),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("interviewer_reference",sa.String(500),nullable=False),sa.Column("rubric_version",sa.String(40),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="scheduled"),sa.Column("scheduled_by",sa.String(255),nullable=False),sa.Column("completed_by",sa.String(255)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("interview_number",name="uq_factory_recruiting_interview_number")); indexes("factory_recruiting_interviews")
    op.create_table("factory_recruiting_assessments",*tenant(),sa.Column("assessment_number",sa.String(100),nullable=False),sa.Column("interview_id",sa.String(100),nullable=False),sa.Column("interview_number",sa.String(100),nullable=False),sa.Column("application_id",sa.String(100),nullable=False),sa.Column("skills_score",sa.Numeric(5,2),nullable=False),sa.Column("evidence_score",sa.Numeric(5,2),nullable=False),sa.Column("communication_score",sa.Numeric(5,2),nullable=False),sa.Column("integrity_score",sa.Numeric(5,2),nullable=False),sa.Column("overall_score",sa.Numeric(5,2),nullable=False),sa.Column("transcript_reference",sa.String(500),nullable=False),sa.Column("citation_references_json",sa.Text(),nullable=False),sa.Column("assessor_comment",sa.Text(),nullable=False),sa.Column("ai_assisted",sa.Boolean(),nullable=False,server_default="0"),sa.Column("ai_model_reference",sa.String(500)),sa.Column("ai_autonomous_decision",sa.Boolean(),nullable=False,server_default="0"),sa.Column("assessed_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("assessment_number",name="uq_factory_recruiting_assessment_number"),sa.UniqueConstraint("interview_id",name="uq_factory_recruiting_interview_assessment")); indexes("factory_recruiting_assessments")
    op.create_table("factory_recruiting_offers",*tenant(),sa.Column("offer_number",sa.String(100),nullable=False),sa.Column("application_id",sa.String(100),nullable=False),sa.Column("application_number",sa.String(100),nullable=False),sa.Column("position_id",sa.String(100),nullable=False),sa.Column("candidate_id",sa.String(100),nullable=False),sa.Column("offer_reference",sa.String(255),nullable=False),sa.Column("proposed_start_date",sa.Date(),nullable=False),sa.Column("compensation_band",sa.String(100),nullable=False),sa.Column("offer_document_reference",sa.String(500),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(255),nullable=False),sa.Column("approval_reference",sa.String(500)),sa.Column("approved_by",sa.String(255)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("sent_by",sa.String(255)),sa.Column("sent_at",sa.DateTime(timezone=True)),sa.Column("candidate_response_reference",sa.String(500)),sa.Column("responded_by",sa.String(255)),sa.Column("responded_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("offer_number",name="uq_factory_recruiting_offer_number"),sa.UniqueConstraint("application_id",name="uq_factory_recruiting_application_offer")); indexes("factory_recruiting_offers")
    op.create_table("factory_recruiting_onboarding_handoffs",*tenant(),sa.Column("handoff_number",sa.String(100),nullable=False),sa.Column("offer_id",sa.String(100),nullable=False),sa.Column("offer_number",sa.String(100),nullable=False),sa.Column("candidate_id",sa.String(100),nullable=False),sa.Column("candidate_number",sa.String(100),nullable=False),sa.Column("position_id",sa.String(100),nullable=False),sa.Column("position_number",sa.String(100),nullable=False),sa.Column("source_reference",sa.String(500),nullable=False),sa.Column("status",sa.String(30),nullable=False,server_default="ready"),sa.Column("created_by",sa.String(255),nullable=False),sa.Column("consumed_employee_id",sa.String(100)),sa.Column("consumed_by",sa.String(255)),sa.Column("consumed_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("handoff_number",name="uq_factory_recruiting_handoff_number"),sa.UniqueConstraint("offer_id",name="uq_factory_recruiting_offer_handoff")); indexes("factory_recruiting_onboarding_handoffs")
    op.create_table("factory_recruiting_evidence",*tenant(),sa.Column("evidence_number",sa.String(100),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(100),nullable=False),sa.Column("evidence_type",sa.String(50),nullable=False),sa.Column("evidence_reference",sa.String(500),nullable=False),sa.Column("note",sa.Text(),nullable=False),sa.Column("recorded_by",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("evidence_number",name="uq_factory_recruiting_evidence_number")); indexes("factory_recruiting_evidence")
    permissions(False)

def downgrade():
    permissions(True)
    for table in reversed(tuple(INDEXES)):
        for column in reversed(INDEXES[table]): op.drop_index(f"ix_{table}_{column}",table_name=table)
        op.drop_table(table)
