"""controlled search-performance observation and analysis handoffs

Revision ID: a4e7b2c9d106
Revises: 9e7a3c2d1b86

Rollback removes only search-share governance records, permissions and contracts;
it never deletes source performance datasets, customer sites, advertising accounts or downstream work.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="a4e7b2c9d106";down_revision="9e7a3c2d1b86";branch_labels=None;depends_on=None
P=("factory.trust.search-share.dataset.manage","factory.trust.search-share.snapshot.verify","factory.trust.search-share.release.approve","factory.trust.search-share.handoff.acknowledge");T=("factory_search_share_datasets","factory_search_share_snapshots","factory_search_share_releases","factory_search_share_evidence")
def tenant():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(t,*x):
 for n in("project_id","agent_path","tenant_id","client_id","plan_id",*x):op.create_index(f"ix_{t}_{n}",t,[n])
def perms(remove=False):
 b=op.get_bind();rows=b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for r in rows:
  try:v=json.loads(r["permissions_json"]or"[]")
  except(TypeError,ValueError):v=[]
  v=[z for z in v if z not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_search_share_datasets",*tenant(),sa.Column("dataset_number",sa.String(96),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("market",sa.String(80),nullable=False),sa.Column("search_engine",sa.String(40),nullable=False),sa.Column("device",sa.String(40),nullable=False),sa.Column("observed_from",sa.String(32),nullable=False),sa.Column("observed_to",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="active"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("dataset_number"),sa.UniqueConstraint("project_id","source_reference","observed_from","observed_to",name="uq_factory_search_share_dataset"));ix("factory_search_share_datasets","dataset_number","status")
 op.create_table("factory_search_share_snapshots",*tenant(),sa.Column("snapshot_number",sa.String(96),nullable=False),sa.Column("dataset_id",sa.String(100),nullable=False),sa.Column("dataset_number",sa.String(96),nullable=False),sa.Column("performance_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="captured"),sa.Column("captured_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("captured_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("snapshot_number"));ix("factory_search_share_snapshots","snapshot_number","dataset_id","status")
 op.create_table("factory_search_share_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("dataset_id",sa.String(100),nullable=False),sa.Column("snapshot_id",sa.String(100),nullable=False),sa.Column("snapshot_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("analysis_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number"));ix("factory_search_share_releases","release_number","dataset_id","snapshot_id","status","available")
 op.create_table("factory_search_share_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_search_share_evidence","evidence_number","subject_type","subject_id")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'search-share-performance-snapshot',36,'Search share performance snapshot','trust','tenant, dataset and snapshot','[\"tenantId\",\"datasetId\",\"snapshotId\",\"sourceReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='search-share-performance-snapshot')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'search-share-analysis-released',28,'Search share analysis released','search-share-performance-snapshot','trust','[\"marketing\",\"executive\",\"seo\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='search-share-analysis-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='search-share-analysis-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='search-share-performance-snapshot'"))
 for t in reversed(T):op.drop_table(t)
