"""controlled public-mention and reputation response handoffs

Revision ID: b6f8c3d1e207
Revises: a4e7b2c9d106

Rollback removes only reputation governance records, permissions and contracts;
it never deletes public mentions, customer sites, third-party reviews or media records.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="b6f8c3d1e207";down_revision="a4e7b2c9d106";branch_labels=None;depends_on=None
P=("factory.trust.reputation.mention.manage","factory.trust.reputation.assessment.verify","factory.trust.reputation.release.approve","factory.trust.reputation.handoff.acknowledge");T=("factory_reputation_mentions","factory_reputation_assessments","factory_reputation_releases","factory_reputation_evidence")
def tenant():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(t,*x):
 for n in("project_id","agent_path","tenant_id","client_id","plan_id",*x):op.create_index(f"ix_{t}_{n}",t,[n])
def perms(remove=False):
 b=op.get_bind();rows=b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for r in rows:
  try:v=json.loads(r["permissions_json"]or"[]")
  except(TypeError,ValueError):v=[]
  v=[z for z in v if z not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_reputation_mentions",*tenant(),sa.Column("mention_number",sa.String(96),nullable=False),sa.Column("public_reference",sa.String(255),nullable=False),sa.Column("channel",sa.String(48),nullable=False),sa.Column("sentiment",sa.String(24),nullable=False),sa.Column("observed_on",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="registered"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("mention_number"),sa.UniqueConstraint("project_id","public_reference",name="uq_factory_reputation_mention"));ix("factory_reputation_mentions","mention_number","status")
 op.create_table("factory_reputation_assessments",*tenant(),sa.Column("assessment_number",sa.String(96),nullable=False),sa.Column("mention_id",sa.String(100),nullable=False),sa.Column("mention_number",sa.String(96),nullable=False),sa.Column("assessment_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("assessment_number"));ix("factory_reputation_assessments","assessment_number","mention_id","status")
 op.create_table("factory_reputation_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("mention_id",sa.String(100),nullable=False),sa.Column("assessment_id",sa.String(100),nullable=False),sa.Column("assessment_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("response_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number"));ix("factory_reputation_releases","release_number","mention_id","assessment_id","status","available")
 op.create_table("factory_reputation_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_reputation_evidence","evidence_number","subject_type","subject_id")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'reputation-public-mention',37,'Reputation public mention','trust','tenant, mention and assessment','[\"tenantId\",\"mentionId\",\"assessmentId\",\"publicReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='reputation-public-mention')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'reputation-response-released',29,'Reputation response released','reputation-public-mention','trust','[\"marketing\",\"service\",\"pr\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='reputation-response-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='reputation-response-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='reputation-public-mention'"))
 for t in reversed(T):op.drop_table(t)
