"""governed B2B ordering and B2C checkout

Revision ID: be5d8f3a0c72
Revises: ad4c7e2f9b61
Create Date: 2026-08-03

Rollback removes only commerce checkout projections, acceptance proofs,
payment-token hashes, order-intent handoffs, evidence and permissions. It does
not change CPQ, channel, payment, finance, inventory or authoritative OMS data.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="be5d8f3a0c72";down_revision="ad4c7e2f9b61";branch_labels=None;depends_on=None
PERMISSIONS=("factory.convert.commerce.manage","factory.convert.commerce.terms.review","factory.convert.commerce.payment.verify","factory.convert.commerce.order.submit","factory.convert.commerce.order.acknowledge")
TABLES=("factory_commerce_checkouts","factory_commerce_acceptances","factory_commerce_payments","factory_commerce_handoffs","factory_commerce_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def idx(t,extra=()):
 for c in ("project_id","agent_path","tenant_id","client_id","plan_id",*extra):op.create_index(f"ix_{t}_{c}",t,[c])
def perms(remove):
 b=op.get_bind()
 for r in b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all():
  try:v=json.loads(r["permissions_json"] or "[]")
  except (TypeError,ValueError):v=[]
  v=[x for x in v if x not in PERMISSIONS] if remove else list(dict.fromkeys([*v,*PERMISSIONS]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(v,ensure_ascii=False),"id":r["id"]})
def upgrade():
 op.create_table("factory_commerce_checkouts",*tenant(),sa.Column("checkout_number",sa.String(96),nullable=False),sa.Column("commerce_mode",sa.String(8),nullable=False),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("source_number",sa.String(96),nullable=False),sa.Column("source_revision",sa.Integer(),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("source_hash",sa.String(64),nullable=False),sa.Column("buyer_reference_hash",sa.String(64),nullable=False),sa.Column("currency",sa.String(8),nullable=False),sa.Column("subtotal",sa.Numeric(18,2),nullable=False),sa.Column("quantity",sa.Numeric(18,4),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("checkout_number",name="uq_factory_commerce_checkout_number"),sa.UniqueConstraint("project_id","source_type","source_id",name="uq_factory_commerce_project_source"));idx("factory_commerce_checkouts",("checkout_number","commerce_mode","source_id","status"))
 op.create_table("factory_commerce_acceptances",*tenant(),sa.Column("acceptance_number",sa.String(96),nullable=False),sa.Column("checkout_id",sa.String(100),nullable=False),sa.Column("checkout_number",sa.String(96),nullable=False),sa.Column("terms_version",sa.String(64),nullable=False),sa.Column("locale",sa.String(16),nullable=False),sa.Column("destination_country",sa.String(16),nullable=False),sa.Column("fulfillment_mode",sa.String(32),nullable=False),sa.Column("purchase_reference_hash",sa.String(64),nullable=False),sa.Column("acceptance_reference_hash",sa.String(64),nullable=False),sa.Column("acceptance_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending-review"),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("reviewed_by",sa.String(128)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_reference",sa.String(255)),sa.Column("review_note",sa.Text()),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("acceptance_number",name="uq_factory_commerce_acceptance_number"),sa.UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_acceptance"));idx("factory_commerce_acceptances",("acceptance_number","checkout_id","status"))
 op.create_table("factory_commerce_payments",*tenant(),sa.Column("payment_number",sa.String(96),nullable=False),sa.Column("checkout_id",sa.String(100),nullable=False),sa.Column("acceptance_id",sa.String(100),nullable=False),sa.Column("method",sa.String(32),nullable=False),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(8),nullable=False),sa.Column("processor_reference_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-verification"),sa.Column("initiated_by",sa.String(128),nullable=False),sa.Column("initiated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("payment_number",name="uq_factory_commerce_payment_number"),sa.UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_payment"));idx("factory_commerce_payments",("payment_number","checkout_id","status"))
 op.create_table("factory_commerce_handoffs",*tenant(),sa.Column("handoff_number",sa.String(96),nullable=False),sa.Column("checkout_id",sa.String(100),nullable=False),sa.Column("payment_id",sa.String(100),nullable=False),sa.Column("order_intent_id",sa.String(100),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(32),nullable=False,server_default="pending-acknowledgement"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("decision",sa.String(16)),sa.Column("authority_system",sa.String(64)),sa.Column("authority_reference",sa.String(255)),sa.Column("authoritative_order_id",sa.String(100)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("handoff_number",name="uq_factory_commerce_handoff_number"),sa.UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_handoff"),sa.UniqueConstraint("order_intent_id",name="uq_factory_commerce_order_intent"));idx("factory_commerce_handoffs",("handoff_number","checkout_id","order_intent_id","status"))
 op.create_table("factory_commerce_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_commerce_evidence_number"));idx("factory_commerce_evidence",("evidence_number","subject_type","subject_id"));perms(False)
def downgrade():
 perms(True)
 for t in reversed(TABLES):op.drop_table(t)
