"""governed inquiry intake and lead routing

Revision ID: c4e8a1d6f902
Revises: f3d7a9c2b506

Rollback removes only inquiry intake projections, routing rules, assignment
receipts, evidence and permissions. It never removes source-channel messages,
customer accounts or revenue, quote, order and payment records.
"""
import json
from alembic import op
import sqlalchemy as sa

revision = "c4e8a1d6f902"; down_revision = "f3d7a9c2b506"; branch_labels = None; depends_on = None
P = ("factory.convert.inquiry.create", "factory.convert.inquiry.qualify", "factory.convert.inquiry.handoff", "factory.convert.routing.create", "factory.convert.routing.approve", "factory.convert.routing.activate", "factory.convert.routing.route", "factory.convert.routing.acknowledge")
def C(): return [sa.Column("id", sa.String(100), primary_key=True), sa.Column("project_id", sa.Integer(), nullable=False), sa.Column("agent_path", sa.String(255), nullable=False), sa.Column("tenant_id", sa.String(128), nullable=False), sa.Column("client_id", sa.String(128), nullable=False), sa.Column("plan_id", sa.String(128), nullable=False)]
def perms(remove=False):
    bind = op.get_bind()
    for row in bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings():
        try: values = json.loads(row["permissions_json"] or "[]")
        except (TypeError, ValueError): values = []
        values = [x for x in values if x not in P] if remove else list(dict.fromkeys([*values, *P]))
        bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:permissions WHERE id=:id"), {"permissions": json.dumps(values, ensure_ascii=False), "id": row["id"]})
def indexes(table, columns):
    for column in columns: op.create_index(f"ix_{table}_{column}", table, [column])
def upgrade():
    op.create_table("factory_inquiries", *C(), sa.Column("inquiry_number", sa.String(96), nullable=False, unique=True), sa.Column("source_channel", sa.String(32), nullable=False), sa.Column("source_reference_hash", sa.String(64), nullable=False), sa.Column("account_reference", sa.String(180), nullable=False), sa.Column("product_reference", sa.String(180), nullable=False), sa.Column("country_code", sa.String(8), nullable=False), sa.Column("requested_quantity", sa.Integer()), sa.Column("payload_summary", sa.Text()), sa.Column("score", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(24), nullable=False, server_default="received"), sa.Column("qualified_by", sa.String(128)), sa.Column("qualification_reference", sa.String(255)), sa.Column("revenue_flow_id", sa.String(100), unique=True), sa.Column("created_by", sa.String(128), nullable=False), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "source_channel", "source_reference_hash", name="uq_factory_inquiry_source"))
    op.create_table("factory_inquiry_routing_rules", *C(), sa.Column("rule_number", sa.String(96), nullable=False, unique=True), sa.Column("rule_key", sa.String(96), nullable=False), sa.Column("rule_name", sa.String(160), nullable=False), sa.Column("priority", sa.Integer(), nullable=False, server_default="100"), sa.Column("conditions_json", sa.JSON(), nullable=False), sa.Column("assignee_reference", sa.String(128), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="draft"), sa.Column("authored_by", sa.String(128), nullable=False), sa.Column("approved_by", sa.String(128)), sa.Column("approval_reference", sa.String(255)), sa.Column("activated_by", sa.String(128)), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("project_id", "rule_key", name="uq_factory_inquiry_rule_key"))
    op.create_table("factory_inquiry_assignments", *C(), sa.Column("assignment_number", sa.String(96), nullable=False, unique=True), sa.Column("inquiry_id", sa.String(100), nullable=False), sa.Column("inquiry_number", sa.String(96), nullable=False), sa.Column("rule_id", sa.String(100), nullable=False), sa.Column("rule_number", sa.String(96), nullable=False), sa.Column("assignee_reference", sa.String(128), nullable=False), sa.Column("status", sa.String(24), nullable=False, server_default="pending"), sa.Column("routed_by", sa.String(128), nullable=False), sa.Column("acknowledged_by", sa.String(128)), sa.Column("receipt_reference", sa.String(255)), sa.Column("revision", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("acknowledged_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("inquiry_id", name="uq_factory_inquiry_assignment"))
    op.create_table("factory_inquiry_evidence", *C(), sa.Column("evidence_number", sa.String(96), nullable=False, unique=True), sa.Column("subject_id", sa.String(100), nullable=False), sa.Column("event_type", sa.String(48), nullable=False), sa.Column("reference", sa.String(255), nullable=False), sa.Column("note", sa.Text()), sa.Column("recorded_by", sa.String(128), nullable=False), sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False))
    indexes("factory_inquiries", ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", "inquiry_number", "source_channel", "account_reference", "product_reference", "country_code", "status")); indexes("factory_inquiry_routing_rules", ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", "rule_number", "status")); indexes("factory_inquiry_assignments", ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", "assignment_number", "inquiry_id", "assignee_reference", "status")); indexes("factory_inquiry_evidence", ("project_id", "agent_path", "tenant_id", "client_id", "plan_id", "evidence_number", "subject_id", "event_type"))
    bind = op.get_bind(); bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'factory-inquiry',43,'Factory inquiry','convert','tenant and source-channel fingerprint','[\"tenantId\",\"inquiryId\",\"sourceChannel\",\"sourceReferenceHash\",\"accountReference\",\"productReference\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='factory-inquiry')")); bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'inquiry-routed',35,'Inquiry routed','factory-inquiry','convert','[\"care\",\"decision\"]','[\"eventId\",\"tenantId\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='inquiry-routed')")); perms()
def downgrade():
    perms(True); bind = op.get_bind(); bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='inquiry-routed'")); bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='factory-inquiry'"))
    for table, columns in (("factory_inquiry_evidence", ("event_type", "subject_id", "evidence_number", "plan_id", "client_id", "tenant_id", "agent_path", "project_id")), ("factory_inquiry_assignments", ("status", "assignee_reference", "inquiry_id", "assignment_number", "plan_id", "client_id", "tenant_id", "agent_path", "project_id")), ("factory_inquiry_routing_rules", ("status", "rule_number", "plan_id", "client_id", "tenant_id", "agent_path", "project_id")), ("factory_inquiries", ("status", "country_code", "product_reference", "account_reference", "source_channel", "inquiry_number", "plan_id", "client_id", "tenant_id", "agent_path", "project_id"))):
        for column in columns: op.drop_index(f"ix_{table}_{column}", table_name=table)
    op.drop_table("factory_inquiry_evidence"); op.drop_table("factory_inquiry_assignments"); op.drop_table("factory_inquiry_routing_rules"); op.drop_table("factory_inquiries")
