"""verified trust-evidence center and controlled webpage handoffs

Revision ID: c8d1e4f2a309
Revises: b6f8c3d1e207
Rollback removes only proof-center governance projections, permissions and contracts;
it never deletes source files, company profiles, product facts or customer websites.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="c8d1e4f2a309";down_revision="b6f8c3d1e207";branch_labels=None;depends_on=None
P=("factory.trust.proof-center.asset.manage","factory.trust.proof-center.version.verify","factory.trust.proof-center.release.approve","factory.trust.proof-center.handoff.acknowledge");T=("factory_proof_center_assets","factory_proof_center_versions","factory_proof_center_releases","factory_proof_center_evidence")
def t():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(n,*c):
 for x in("project_id","agent_path","tenant_id","client_id","plan_id",*c):op.create_index(f"ix_{n}_{x}",n,[x])
def perms(remove=False):
 b=op.get_bind()
 for r in b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings():
  try:v=json.loads(r["permissions_json"]or"[]")
  except(ValueError,TypeError):v=[]
  v=[x for x in v if x not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_proof_center_assets",*t(),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("asset_type",sa.String(40),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("rights_reference",sa.String(255),nullable=False),sa.Column("market_scope",sa.String(80),nullable=False),sa.Column("valid_until",sa.String(32),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("asset_number"),sa.UniqueConstraint("project_id","source_reference",name="uq_factory_proof_center_asset"));ix("factory_proof_center_assets","asset_number","status")
 op.create_table("factory_proof_center_versions",*t(),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("claim_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("version_number"));ix("factory_proof_center_versions","version_number","asset_id","status")
 op.create_table("factory_proof_center_releases",*t(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("handoff_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approval_reference",sa.String(255)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("release_number"));ix("factory_proof_center_releases","release_number","asset_id","version_id","status","available")
 op.create_table("factory_proof_center_evidence",*t(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_proof_center_evidence","evidence_number","subject_type")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'proof-center-verified-asset',38,'Verified proof asset','trust','tenant, asset and version','[\"tenantId\",\"assetId\",\"versionId\",\"sourceReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='proof-center-verified-asset')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'proof-center-handoff-released',30,'Proof center handoff released','proof-center-verified-asset','trust','[\"marketing\",\"sales\",\"quality\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='proof-center-handoff-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='proof-center-handoff-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='proof-center-verified-asset'"))
 for n in reversed(T):op.drop_table(n)
