"""governed competitive price intelligence

Revision ID: e18ab6d3f205
Revises: d07fa5c2e194
Create Date: 2026-08-05

Rollback removes only competitive-pricing projections, permissions and contracts;
it never changes CPQ quotes, finance price masters or external observations.
"""
import json
from alembic import op
import sqlalchemy as sa

revision="e18ab6d3f205"; down_revision="d07fa5c2e194"; branch_labels=None; depends_on=None
PERMISSIONS=("factory.identity.competitive-pricing.manage","factory.identity.competitive-pricing.offer.verify","factory.identity.competitive-pricing.decision.review","factory.identity.competitive-pricing.release.approve")
TABLES=("factory_competitive_price_watches","factory_competitive_offer_snapshots","factory_competitive_price_decisions","factory_competitive_pricing_releases","factory_competitive_pricing_evidence")
def tenant_columns(): return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extra=()):
    for column in ("project_id","agent_path","tenant_id","client_id","plan_id",*extra):op.create_index(f"ix_{table}_{column}",table,[column])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id, permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_competitive_price_watches",*tenant_columns(),sa.Column("watch_number",sa.String(96),nullable=False),sa.Column("product_reference",sa.String(180),nullable=False),sa.Column("product_name",sa.String(180),nullable=False),sa.Column("market_country",sa.String(8),nullable=False),sa.Column("channel",sa.String(64),nullable=False),sa.Column("currency",sa.String(8),nullable=False),sa.Column("own_reference_price",sa.Numeric(18,4),nullable=False),sa.Column("scope_note",sa.Text(),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="gathering"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("watch_number",name="uq_factory_competitive_watch_number"));indexes("factory_competitive_price_watches",("watch_number","product_reference","market_country","status"))
    op.create_table("factory_competitive_offer_snapshots",*tenant_columns(),sa.Column("snapshot_number",sa.String(96),nullable=False),sa.Column("watch_id",sa.String(100),nullable=False),sa.Column("watch_number",sa.String(96),nullable=False),sa.Column("competitor_name",sa.String(180),nullable=False),sa.Column("competitor_offer_reference",sa.String(180),nullable=False),sa.Column("offer_type",sa.String(24),nullable=False),sa.Column("offer_price",sa.Numeric(18,4),nullable=False),sa.Column("freight_price",sa.Numeric(18,4),nullable=False),sa.Column("landed_price",sa.Numeric(18,4),nullable=False),sa.Column("feature_summary",sa.Text(),nullable=False),sa.Column("source_system",sa.String(64),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("source_revision",sa.String(96),nullable=False),sa.Column("source_observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("source_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-verification"),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("snapshot_number",name="uq_factory_competitive_snapshot_number"));indexes("factory_competitive_offer_snapshots",("snapshot_number","watch_id","status"))
    op.create_table("factory_competitive_price_decisions",*tenant_columns(),sa.Column("decision_number",sa.String(96),nullable=False),sa.Column("watch_id",sa.String(100),nullable=False),sa.Column("watch_number",sa.String(96),nullable=False),sa.Column("input_snapshot_json",sa.JSON(),nullable=False),sa.Column("input_hash",sa.String(64),nullable=False),sa.Column("low_landed_price",sa.Numeric(18,4),nullable=False),sa.Column("median_landed_price",sa.Numeric(18,4),nullable=False),sa.Column("high_landed_price",sa.Numeric(18,4),nullable=False),sa.Column("price_index",sa.Numeric(8,2),nullable=False),sa.Column("recommendation",sa.String(16),nullable=False),sa.Column("boundary_note",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending-review"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("authored_at",sa.DateTime(timezone=True),nullable=False),sa.Column("reviewed_by",sa.String(128)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("review_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("decision_number",name="uq_factory_competitive_decision_number"),sa.UniqueConstraint("watch_id",name="uq_factory_competitive_watch_decision"));indexes("factory_competitive_price_decisions",("decision_number","watch_id","status"))
    op.create_table("factory_competitive_pricing_releases",*tenant_columns(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("application_id",sa.String(100),nullable=False),sa.Column("release_version",sa.String(64),nullable=False),sa.Column("watch_id",sa.String(100),nullable=False),sa.Column("decision_id",sa.String(100),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("support_owner",sa.String(128),nullable=False),sa.Column("support_until",sa.DateTime(timezone=True),nullable=False),sa.Column("customer_trial_reference",sa.String(255),nullable=False),sa.Column("role_training_reference",sa.String(255),nullable=False),sa.Column("issue_closure_reference",sa.String(255),nullable=False),sa.Column("monitoring_reference",sa.String(255),nullable=False),sa.Column("rollback_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending-approval"),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number",name="uq_factory_competitive_release_number"),sa.UniqueConstraint("project_id","release_version",name="uq_factory_competitive_pricing_version"),sa.UniqueConstraint("decision_id",name="uq_factory_competitive_decision_release"));indexes("factory_competitive_pricing_releases",("release_number","application_id","decision_id","status","available"))
    op.create_table("factory_competitive_pricing_evidence",*tenant_columns(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_competitive_evidence_number"));indexes("factory_competitive_pricing_evidence",("evidence_number","subject_type","subject_id"))
    bind=op.get_bind();bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'competitive-price-watch',25,'竞品价格观察','identity','租户、产品、市场和渠道确定情报身份，不产生报价或财务价','[\"tenantId\",\"watchId\",\"productReference\",\"marketCountry\",\"channel\",\"status\",\"version\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='competitive-price-watch')"));bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'competitive-price-released',17,'竞品价格发布','competitive-price-watch','identity','[\"content\",\"lead\",\"decision\"]','[\"eventId\",\"tenantId\",\"eventType\",\"occurredAt\",\"source\",\"subjectId\",\"version\",\"correlationId\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='competitive-price-released')"));permissions(False)
def downgrade():
    permissions(True);bind=op.get_bind();bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='competitive-price-released'"));bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='competitive-price-watch'"))
    for table in reversed(TABLES):op.drop_table(table)
