"""factory DAM and localization

Revision ID: e6c28f4a7bd5
Revises: d5b17e3f6ac4
Create Date: 2026-08-02

Rollback removes only DAM metadata, bounded rights grants, terminology
versions, localization jobs/reviews, country-pack manifests, handoffs and DAM
permissions. It never deletes private source files, product masters, CMS,
social, commerce or regional compliance records. Export published manifests
and acknowledged handoffs before production rollback.
"""

from __future__ import annotations
import json
from alembic import op
import sqlalchemy as sa

revision="e6c28f4a7bd5";down_revision="d5b17e3f6ac4";branch_labels=None;depends_on=None
PERMISSIONS=("factory.content.dam.asset.manage","factory.content.dam.rights.approve","factory.content.dam.glossary.manage","factory.content.dam.glossary.approve","factory.content.dam.localization.manage","factory.content.dam.localization.review","factory.content.dam.pack.publish","factory.content.dam.handoff.acknowledge")
TABLES=("factory_dam_assets","factory_dam_rights_grants","factory_localization_glossaries","factory_localization_glossary_versions","factory_localization_jobs","factory_localized_renditions","factory_localization_reviews","factory_country_content_packs","factory_localization_handoffs","factory_dam_evidence")

def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for col in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{col}",table,[col])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]))
        bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:permissions WHERE id=:id"),{"permissions":json.dumps(values,ensure_ascii=False),"id":row["id"]})

def upgrade():
    op.create_table("factory_dam_assets",*tenant(),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("asset_name",sa.String(255),nullable=False),sa.Column("asset_type",sa.String(32),nullable=False),sa.Column("source_asset_id",sa.String(64),nullable=False),sa.Column("source_display_name",sa.String(500),nullable=False),sa.Column("source_media_type",sa.String(255),nullable=False),sa.Column("source_sha256",sa.String(64),nullable=False),sa.Column("source_size_bytes",sa.Integer(),nullable=False),sa.Column("source_language",sa.String(16),nullable=False),sa.Column("product_references_json",sa.JSON(),nullable=False),sa.Column("brand_reference",sa.String(255),nullable=False),sa.Column("rights_owner_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("activated_by",sa.String(128)),sa.Column("activated_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("updated_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("asset_number",name="uq_factory_dam_asset_number"),sa.UniqueConstraint("project_id","source_asset_id",name="uq_factory_dam_project_source"));indexes("factory_dam_assets",("asset_number","source_asset_id","status"))
    op.create_table("factory_dam_rights_grants",*tenant(),sa.Column("grant_number",sa.String(96),nullable=False),sa.Column("grant_code",sa.String(64),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("territories_json",sa.JSON(),nullable=False),sa.Column("languages_json",sa.JSON(),nullable=False),sa.Column("channels_json",sa.JSON(),nullable=False),sa.Column("valid_from",sa.Date(),nullable=False),sa.Column("valid_until",sa.Date(),nullable=False),sa.Column("license_type",sa.String(32),nullable=False),sa.Column("rights_evidence_reference",sa.String(255),nullable=False),sa.Column("restrictions",sa.Text()),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("requested_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("grant_number",name="uq_factory_dam_grant_number"),sa.UniqueConstraint("asset_id","grant_code",name="uq_factory_dam_asset_grant"));indexes("factory_dam_rights_grants",("grant_number","asset_id","valid_until","status"))
    op.create_table("factory_localization_glossaries",*tenant(),sa.Column("glossary_number",sa.String(96),nullable=False),sa.Column("glossary_code",sa.String(64),nullable=False),sa.Column("glossary_name",sa.String(180),nullable=False),sa.Column("source_locale",sa.String(16),nullable=False),sa.Column("target_locale",sa.String(16),nullable=False),sa.Column("current_version",sa.Integer(),nullable=False,server_default="1"),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("glossary_number",name="uq_factory_localization_glossary_number"),sa.UniqueConstraint("project_id","glossary_code",name="uq_factory_localization_project_glossary"));indexes("factory_localization_glossaries",("glossary_number","status"))
    op.create_table("factory_localization_glossary_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("glossary_id",sa.String(100),nullable=False),sa.Column("glossary_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("terms_json",sa.JSON(),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("activated_by",sa.String(128)),sa.Column("activated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("version_reference",name="uq_factory_localization_version_reference"),sa.UniqueConstraint("glossary_id","version_number",name="uq_factory_localization_glossary_version"));indexes("factory_localization_glossary_versions",("version_reference","glossary_id"))
    op.create_table("factory_localization_jobs",*tenant(),sa.Column("job_number",sa.String(96),nullable=False),sa.Column("asset_id",sa.String(100),nullable=False),sa.Column("asset_number",sa.String(96),nullable=False),sa.Column("source_sha256",sa.String(64),nullable=False),sa.Column("rights_grant_id",sa.String(100),nullable=False),sa.Column("rights_grant_number",sa.String(96),nullable=False),sa.Column("glossary_id",sa.String(100),nullable=False),sa.Column("glossary_number",sa.String(96),nullable=False),sa.Column("glossary_version",sa.Integer(),nullable=False),sa.Column("glossary_hash",sa.String(64),nullable=False),sa.Column("target_market",sa.String(64),nullable=False),sa.Column("target_locale",sa.String(16),nullable=False),sa.Column("channel",sa.String(32),nullable=False),sa.Column("brief",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("job_number",name="uq_factory_localization_job_number"),sa.UniqueConstraint("asset_id","target_market","target_locale","channel",name="uq_factory_localization_asset_target"));indexes("factory_localization_jobs",("job_number","asset_id","rights_grant_id","glossary_id","status"))
    op.create_table("factory_localized_renditions",*tenant(),sa.Column("rendition_number",sa.String(96),nullable=False),sa.Column("job_id",sa.String(100),nullable=False),sa.Column("job_number",sa.String(96),nullable=False),sa.Column("localized_storage_reference",sa.String(500),nullable=False),sa.Column("localized_sha256",sa.String(64),nullable=False),sa.Column("translator_reference",sa.String(255),nullable=False),sa.Column("ai_assisted",sa.Boolean(),nullable=False,server_default="0"),sa.Column("machine_translation_provider_reference",sa.String(255)),sa.Column("status",sa.String(24),nullable=False,server_default="review"),sa.Column("submitted_by",sa.String(128),nullable=False),sa.Column("submitted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("rendition_number",name="uq_factory_localized_rendition_number"),sa.UniqueConstraint("job_id",name="uq_factory_localization_job_rendition"));indexes("factory_localized_renditions",("rendition_number","job_id","status"))
    op.create_table("factory_localization_reviews",*tenant(),sa.Column("review_number",sa.String(96),nullable=False),sa.Column("rendition_id",sa.String(100),nullable=False),sa.Column("rendition_number",sa.String(96),nullable=False),sa.Column("linguistic_score",sa.Integer(),nullable=False),sa.Column("terminology_score",sa.Integer(),nullable=False),sa.Column("brand_score",sa.Integer(),nullable=False),sa.Column("cultural_score",sa.Integer(),nullable=False),sa.Column("findings_json",sa.JSON(),nullable=False),sa.Column("recommendation",sa.String(16),nullable=False),sa.Column("compliance_assessment_reference",sa.String(255),nullable=False),sa.Column("reviewed_by",sa.String(128),nullable=False),sa.Column("reviewed_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("review_number",name="uq_factory_localization_review_number"),sa.UniqueConstraint("rendition_id",name="uq_factory_localization_rendition_review"));indexes("factory_localization_reviews",("review_number","rendition_id"))
    op.create_table("factory_country_content_packs",*tenant(),sa.Column("pack_number",sa.String(96),nullable=False),sa.Column("pack_code",sa.String(64),nullable=False),sa.Column("pack_name",sa.String(180),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False,server_default="1"),sa.Column("target_market",sa.String(64),nullable=False),sa.Column("target_locale",sa.String(16),nullable=False),sa.Column("rendition_ids_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("compliance_assessment_reference",sa.String(255),nullable=False),sa.Column("tax_reviewed",sa.Boolean(),nullable=False,server_default="0"),sa.Column("privacy_reviewed",sa.Boolean(),nullable=False,server_default="0"),sa.Column("market_access_reviewed",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("pack_number",name="uq_factory_country_pack_number"),sa.UniqueConstraint("project_id","pack_code","version_number",name="uq_factory_country_pack_version"));indexes("factory_country_content_packs",("pack_number","status"))
    op.create_table("factory_localization_handoffs",*tenant(),sa.Column("handoff_number",sa.String(96),nullable=False),sa.Column("pack_id",sa.String(100),nullable=False),sa.Column("pack_number",sa.String(96),nullable=False),sa.Column("pack_version",sa.Integer(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("handoff_number",name="uq_factory_localization_handoff_number"),sa.UniqueConstraint("pack_id","consumer",name="uq_factory_country_pack_consumer"));indexes("factory_localization_handoffs",("handoff_number","pack_id","status"))
    op.create_table("factory_dam_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_dam_evidence_number"));indexes("factory_dam_evidence",("evidence_number","subject_type","subject_id"));permissions(False)

def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
