"""governed brand positioning and website style

Revision ID: f31c7a9b2d60
Revises: e18ab6d3f205
Rollback removes only brand strategy projections, permissions and contracts;
it never publishes a site or overwrites protected customer brand configuration.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="f31c7a9b2d60";down_revision="e18ab6d3f205";branch_labels=None;depends_on=None
PERMISSIONS=("factory.identity.brand.manage","factory.identity.brand.claim.verify","factory.identity.brand.profile.approve","factory.identity.brand.release.approve")
TABLES=("factory_brand_profiles","factory_brand_versions","factory_brand_claims","factory_brand_releases","factory_brand_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(t,extra=()):
 for c in ("project_id","agent_path","tenant_id","client_id","plan_id",*extra):op.create_index(f"ix_{t}_{c}",t,[c])
def permissions(remove):
 bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
 for row in rows:
  try:v=json.loads(row["permissions_json"] or "[]")
  except (ValueError,TypeError):v=[]
  v=[x for x in v if x not in PERMISSIONS] if remove else list(dict.fromkeys([*v,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(v,ensure_ascii=False),"id":row["id"]})
def upgrade():
 op.create_table("factory_brand_profiles",*tenant(),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("brand_name",sa.String(180),nullable=False),sa.Column("market_scope",sa.String(64),nullable=False),sa.Column("audience",sa.String(4000),nullable=False),sa.Column("positioning",sa.Text(),nullable=False),sa.Column("value_promise",sa.Text(),nullable=False),sa.Column("tone",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("current_version",sa.Integer(),nullable=False,server_default="1"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("profile_number",name="uq_factory_brand_profile_number"));indexes("factory_brand_profiles",("profile_number","status"))
 op.create_table("factory_brand_versions",*tenant(),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("visual_tokens_json",sa.JSON(),nullable=False),sa.Column("messaging_json",sa.JSON(),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="draft"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("activated_by",sa.String(128)),sa.Column("activated_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("profile_id","version_number",name="uq_factory_brand_profile_version"));indexes("factory_brand_versions",("profile_id","status"))
 op.create_table("factory_brand_claims",*tenant(),sa.Column("claim_number",sa.String(96),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("claim_type",sa.String(64),nullable=False),sa.Column("claim_text",sa.Text(),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("evidence_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False,server_default="pending-verification"),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("claim_number",name="uq_factory_brand_claim_number"));indexes("factory_brand_claims",("claim_number","profile_id","status"))
 op.create_table("factory_brand_releases",*tenant(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("application_id",sa.String(100),nullable=False),sa.Column("profile_id",sa.String(100),nullable=False),sa.Column("profile_number",sa.String(96),nullable=False),sa.Column("profile_version",sa.Integer(),nullable=False),sa.Column("definition_hash",sa.String(64),nullable=False),sa.Column("release_version",sa.String(64),nullable=False),sa.Column("manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("support_owner",sa.String(128),nullable=False),sa.Column("support_until",sa.DateTime(timezone=True),nullable=False),*[sa.Column(x,sa.String(255),nullable=False) for x in ("customer_trial_reference","role_training_reference","issue_closure_reference","monitoring_reference","rollback_reference")],sa.Column("status",sa.String(32),nullable=False,server_default="pending-approval"),sa.Column("available",sa.Boolean(),nullable=False,server_default="0"),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("approval_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("release_number",name="uq_factory_brand_release_number"),sa.UniqueConstraint("profile_id","release_version",name="uq_factory_brand_release_version"));indexes("factory_brand_releases",("release_number","profile_id","status","available"))
 op.create_table("factory_brand_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_brand_evidence_number"));indexes("factory_brand_evidence",("evidence_number","subject_type","subject_id"))
 bind=op.get_bind();bind.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'brand-profile',26,'Brand profile','identity','tenant and brand version','[\"tenantId\",\"profileId\",\"version\",\"status\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='brand-profile')"));bind.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'brand-released',18,'Brand released','brand-profile','identity','[\"content\",\"lead\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='brand-released')"));permissions(False)
def downgrade():
 permissions(True);bind=op.get_bind();bind.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='brand-released'"));bind.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='brand-profile'"))
 for t in reversed(TABLES):op.drop_table(t)
