"""factory enterprise knowledge graph

Revision ID: f7d39a5b8ce6
Revises: e6c28f4a7bd5
Create Date: 2026-08-02

Rollback removes only knowledge-graph projections, immutable graph manifests,
publications, evidence and permissions. It never deletes or modifies legal
parties, product passports, certificates, ICP definitions, DAM assets or any
consumer system. Export published manifests and acknowledgements first.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="f7d39a5b8ce6";down_revision="e6c28f4a7bd5";branch_labels=None;depends_on=None
PERMISSIONS=("factory.recommend.knowledge.graph.manage","factory.recommend.knowledge.entity.verify","factory.recommend.knowledge.relation.manage","factory.recommend.knowledge.relation.verify","factory.recommend.knowledge.publish","factory.recommend.knowledge.handoff.acknowledge")
TABLES=("factory_knowledge_graphs","factory_knowledge_entities","factory_knowledge_relations","factory_knowledge_graph_versions","factory_knowledge_publications","factory_knowledge_evidence")
def tenant():return [sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def indexes(table,extras=()):
    for col in ("project_id","agent_path","tenant_id","client_id","plan_id",*extras):op.create_index(f"ix_{table}_{col}",table,[col])
def permissions(remove):
    bind=op.get_bind();rows=bind.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings().all()
    for row in rows:
        try:values=json.loads(row["permissions_json"] or "[]")
        except (TypeError,ValueError):values=[]
        if not isinstance(values,list):values=[]
        values=[x for x in values if x not in PERMISSIONS] if remove else list(dict.fromkeys([*values,*PERMISSIONS]));bind.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:id"),{"p":json.dumps(values,ensure_ascii=False),"id":row["id"]})
def upgrade():
    op.create_table("factory_knowledge_graphs",*tenant(),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("graph_code",sa.String(64),nullable=False),sa.Column("graph_name",sa.String(180),nullable=False),sa.Column("scope",sa.String(32),nullable=False),sa.Column("default_locale",sa.String(16),nullable=False),sa.Column("objective",sa.Text(),nullable=False),sa.Column("current_version",sa.Integer(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="draft"),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("published_by",sa.String(128)),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("graph_number",name="uq_factory_knowledge_graph_number"),sa.UniqueConstraint("project_id","graph_code",name="uq_factory_knowledge_project_graph"));indexes("factory_knowledge_graphs",("graph_number","status"))
    op.create_table("factory_knowledge_entities",*tenant(),sa.Column("entity_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("entity_key",sa.String(160),nullable=False),sa.Column("entity_type",sa.String(32),nullable=False),sa.Column("canonical_name",sa.String(255),nullable=False),sa.Column("aliases_json",sa.JSON(),nullable=False),sa.Column("properties_json",sa.JSON(),nullable=False),sa.Column("locale",sa.String(16),nullable=False),sa.Column("source_type",sa.String(48),nullable=False),sa.Column("source_id",sa.String(100),nullable=False),sa.Column("source_number",sa.String(100),nullable=False),sa.Column("source_revision",sa.Integer(),nullable=False),sa.Column("source_status",sa.String(32),nullable=False),sa.Column("source_fingerprint",sa.String(64),nullable=False),sa.Column("source_snapshot_json",sa.JSON(),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("verification_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("entity_number",name="uq_factory_knowledge_entity_number"),sa.UniqueConstraint("graph_id","entity_key",name="uq_factory_knowledge_graph_entity"),sa.UniqueConstraint("graph_id","source_type","source_id","entity_type",name="uq_factory_knowledge_graph_source_entity"));indexes("factory_knowledge_entities",("entity_number","graph_id","entity_type","source_type","source_id","status"))
    op.create_table("factory_knowledge_relations",*tenant(),sa.Column("relation_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("subject_entity_id",sa.String(100),nullable=False),sa.Column("subject_entity_number",sa.String(96),nullable=False),sa.Column("predicate",sa.String(100),nullable=False),sa.Column("object_entity_id",sa.String(100),nullable=False),sa.Column("object_entity_number",sa.String(96),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("relation_number",name="uq_factory_knowledge_relation_number"),sa.UniqueConstraint("graph_id","subject_entity_id","predicate","object_entity_id",name="uq_factory_knowledge_relation"));indexes("factory_knowledge_relations",("relation_number","graph_id","subject_entity_id","object_entity_id","status"))
    op.create_table("factory_knowledge_graph_versions",*tenant(),sa.Column("version_reference",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("entity_manifest_json",sa.JSON(),nullable=False),sa.Column("relation_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("entity_type_coverage_json",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False,server_default="published"),sa.Column("published_by",sa.String(128),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("version_reference",name="uq_factory_knowledge_version_reference"),sa.UniqueConstraint("graph_id","version_number",name="uq_factory_knowledge_graph_version"));indexes("factory_knowledge_graph_versions",("version_reference","graph_id","status"))
    op.create_table("factory_knowledge_publications",*tenant(),sa.Column("publication_number",sa.String(96),nullable=False),sa.Column("graph_id",sa.String(100),nullable=False),sa.Column("graph_number",sa.String(96),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.Integer(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("consumer",sa.String(32),nullable=False),sa.Column("delivery_reference",sa.String(255),nullable=False),sa.Column("consumer_mutated",sa.Boolean(),nullable=False,server_default="0"),sa.Column("status",sa.String(24),nullable=False,server_default="pending"),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("acknowledgement_reference",sa.String(255)),sa.Column("revision",sa.Integer(),nullable=False,server_default="1"),sa.UniqueConstraint("publication_number",name="uq_factory_knowledge_publication_number"),sa.UniqueConstraint("graph_id","version_number","consumer",name="uq_factory_knowledge_publication"));indexes("factory_knowledge_publications",("publication_number","graph_id","version_id","status"))
    op.create_table("factory_knowledge_evidence",*tenant(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_type",sa.String(40),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("subject_number",sa.String(96),nullable=False),sa.Column("evidence_type",sa.String(48),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number",name="uq_factory_knowledge_evidence_number"));indexes("factory_knowledge_evidence",("evidence_number","subject_type","subject_id"));permissions(False)
def downgrade():
    permissions(True)
    for table in reversed(TABLES):op.drop_table(table)
