"""source-bound AI-readable fact versions and controlled handoffs

Revision ID: f8a1c3e6b205
Revises: d9e2f5a3b410
Rollback removes only fact-library governance data, permissions and contracts; it never deletes source content, product facts or model observations.
"""
import json
from alembic import op
import sqlalchemy as sa
revision="f8a1c3e6b205";down_revision="d9e2f5a3b410";branch_labels=None;depends_on=None
P=("factory.recommend.fact-library.fact.manage","factory.recommend.fact-library.version.verify","factory.recommend.fact-library.release.approve","factory.recommend.fact-library.handoff.acknowledge");T=("factory_fact_library_facts","factory_fact_library_versions","factory_fact_library_releases","factory_fact_library_evidence")
def t():return[sa.Column("id",sa.String(100),primary_key=True),sa.Column("project_id",sa.Integer(),nullable=False),sa.Column("agent_path",sa.String(255),nullable=False),sa.Column("tenant_id",sa.String(128),nullable=False),sa.Column("client_id",sa.String(128),nullable=False),sa.Column("plan_id",sa.String(128),nullable=False)]
def ix(n,*c):
 for x in("project_id","agent_path","tenant_id","client_id","plan_id",*c):op.create_index(f"ix_{n}_{x}",n,[x])
def perms(remove=False):
 b=op.get_bind()
 for r in b.execute(sa.text("SELECT id,permissions_json FROM roles_platform WHERE is_system=1 AND scope IN ('client','project')")).mappings():
  try:v=json.loads(r["permissions_json"]or"[]")
  except(ValueError,TypeError):v=[]
  v=[x for x in v if x not in P]if remove else list(dict.fromkeys([*v,*P]));b.execute(sa.text("UPDATE roles_platform SET permissions_json=:p WHERE id=:i"),{"p":json.dumps(v,ensure_ascii=False),"i":r["id"]})
def upgrade():
 op.create_table("factory_fact_library_facts",*t(),sa.Column("fact_number",sa.String(96),nullable=False),sa.Column("fact_key",sa.String(160),nullable=False),sa.Column("fact_type",sa.String(40),nullable=False),sa.Column("source_reference",sa.String(255),nullable=False),sa.Column("authority_reference",sa.String(255),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("created_by",sa.String(128),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("fact_number"),sa.UniqueConstraint("project_id","fact_key",name="uq_factory_fact_library_fact"));ix("factory_fact_library_facts","fact_number","status")
 op.create_table("factory_fact_library_versions",*t(),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("fact_id",sa.String(100),nullable=False),sa.Column("fact_number",sa.String(96),nullable=False),sa.Column("fact_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("authored_by",sa.String(128),nullable=False),sa.Column("verified_by",sa.String(128)),sa.Column("verification_reference",sa.String(255)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("verified_at",sa.DateTime(timezone=True)),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("version_number"));ix("factory_fact_library_versions","version_number","fact_id","status")
 op.create_table("factory_fact_library_releases",*t(),sa.Column("release_number",sa.String(96),nullable=False),sa.Column("version_id",sa.String(100),nullable=False),sa.Column("version_number",sa.String(96),nullable=False),sa.Column("target",sa.String(40),nullable=False),sa.Column("handoff_manifest_json",sa.JSON(),nullable=False),sa.Column("manifest_hash",sa.String(64),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("prepared_by",sa.String(128),nullable=False),sa.Column("approved_by",sa.String(128)),sa.Column("consumer_receipt_reference",sa.String(255)),sa.Column("available",sa.Boolean(),nullable=False),sa.Column("prepared_at",sa.DateTime(timezone=True),nullable=False),sa.Column("revision",sa.Integer(),nullable=False),sa.UniqueConstraint("release_number"));ix("factory_fact_library_releases","release_number","version_id","status","available")
 op.create_table("factory_fact_library_evidence",*t(),sa.Column("evidence_number",sa.String(96),nullable=False),sa.Column("subject_id",sa.String(100),nullable=False),sa.Column("evidence_type",sa.String(64),nullable=False),sa.Column("evidence_reference",sa.String(255),nullable=False),sa.Column("note",sa.Text()),sa.Column("recorded_by",sa.String(128),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("evidence_number"));ix("factory_fact_library_evidence","evidence_number")
 b=op.get_bind();b.execute(sa.text("INSERT INTO factory_core_object_contracts (id,sequence,label,system_of_record,identity_rule,minimum_fields_json,lifecycle_status,schema_version,revision,updated_by) SELECT 'ai-readable-fact-version',40,'AI readable fact version','recommend','tenant, fact and version','[\"tenantId\",\"factId\",\"versionId\",\"sourceReference\",\"authorityReference\",\"manifestHash\"]','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_object_contracts WHERE id='ai-readable-fact-version')"));b.execute(sa.text("INSERT INTO factory_core_event_contracts (id,sequence,label,subject_id,producer,consumers_json,required_fields_json,compatibility,lifecycle_status,schema_version,revision,updated_by) SELECT 'ai-readable-fact-released',32,'AI readable fact released','ai-readable-fact-version','recommend','[\"content\",\"geo\",\"structured-data\"]','[\"eventId\",\"tenantId\",\"eventType\",\"subjectId\",\"version\"]','backward','frozen',1,1,'migration' WHERE NOT EXISTS (SELECT 1 FROM factory_core_event_contracts WHERE id='ai-readable-fact-released')"));perms()
def downgrade():
 perms(True);b=op.get_bind();b.execute(sa.text("DELETE FROM factory_core_event_contracts WHERE id='ai-readable-fact-released'"));b.execute(sa.text("DELETE FROM factory_core_object_contracts WHERE id='ai-readable-fact-version'"))
 for n in reversed(T):op.drop_table(n)
