import {useEffect,useState,type ReactNode} from "react";
import {BadgeCheck,Braces,CheckCircle2,RefreshCw,Send,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {acknowledgeStructuredPublication,addStructuredMapping,createStructuredBundle,listStructuredWorkspace,publishStructuredBundle,validateStructuredBundle,verifyStructuredMapping,type StructuredWorkspace} from "@/lib/factory-structured-data-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:StructuredWorkspace={bundles:[],mappings:[],validations:[],releases:[],publications:[],evidence:[],graph_versions:[],graph_entities:[],metrics:{verified_mappings:0,schema_coverage_percent:0,passed_validations:0,validation_pass_percent:0,published_releases:0,publication_acknowledgement_percent:0},contract:{}};
const SPECS=[
  {schema_type:"Organization",entity_type:"organization",target:"name"},
  {schema_type:"Product",entity_type:"product",target:"name"},
  {schema_type:"FAQPage",entity_type:"capability",target:"mainEntity"},
  {schema_type:"Review",entity_type:"case",target:"itemReviewed"},
  {schema_type:"Article",entity_type:"market",target:"headline"},
] as const;
const STATUS:Record<string,string>={draft:"草稿",pending:"待确认",verified:"已验证",passed:"已通过",failed:"未通过",published:"已发布",acknowledged:"已确认"};
const reference=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});

export default function FactoryStructuredData(){
  const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listStructuredWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"结构化数据加载失败")}};
  useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"结构化数据操作失败");await load(true)}};
  const bundle=workspace.bundles[0];const mappings=bundle?workspace.mappings.filter(item=>item.bundle_id===bundle.id):[];const validations=bundle?workspace.validations.filter(item=>item.bundle_id===bundle.id):[];const passed=validations.find(item=>item.status==="passed");
  const addFive=async()=>{if(!bundle)return;for(const spec of SPECS){if(mappings.some(item=>item.schema_type===spec.schema_type))continue;const entity=workspace.graph_entities.find(item=>item.graph_id===bundle.graph_id&&item.entity_type===spec.entity_type);if(!entity)throw new Error(`缺少${spec.entity_type}已验证图谱实体`);await addStructuredMapping(projectId,bundle.id,{schema_type:spec.schema_type,source_entity_id:entity.id,field_map:{[spec.target]:"canonical_name",identifier:"entity_number"},required_fields:[spec.target]})}};
  const verifyFive=async()=>{for(const item of mappings.filter(row=>row.status==="pending"))await verifyStructuredMapping(projectId,item.id,reference(item.revision,"SCHEMA-MAPPING-VERIFY"))};
  return <FactoryPage pageId="client-structured-data" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-structured-data-page data-structured-data-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Braces className="h-5 w-5"/>结构化数据中心</h1><p className="mt-1 text-sm opacity-70">将已发布企业知识图谱映射为可验证的 Organization、Product、FAQ、Review 与 Article JSON-LD，并以不可变哈希交付搜索渠道。</p></div><div className="flex gap-2"><Input aria-label="结构化数据项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={event=>setProjectText(event.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入数据</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="已验证映射" value={workspace.metrics.verified_mappings}/><Metric label="类型覆盖率" value={`${workspace.metrics.schema_coverage_percent}%`}/><Metric label="通过验证" value={workspace.metrics.passed_validations}/><Metric label="验证通过率" value={`${workspace.metrics.validation_pass_percent}%`}/><Metric label="发布版本" value={workspace.metrics.published_releases}/><Metric label="渠道确认" value={`${workspace.metrics.publication_acknowledgement_percent}%`}/></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Braces className="h-4 w-4"/>图谱版本与五类Schema映射</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!bundle||!workspace.graph_versions.length} data-structured-bundle-create onClick={()=>void execute(()=>createStructuredBundle(projectId,{bundle_code:`GLOBAL-SCHEMA-${Date.now()}`,bundle_name:"全球站点结构化数据包",target_site_reference:"CLIENT-SOURCE-WEBSITE",default_locale:"en-US",graph_version_id:workspace.graph_versions[0].id}),"结构化数据包已固定图谱版本")}>建立数据包</Button><Button disabled={!bundle||bundle.status!=="draft"||SPECS.every(spec=>mappings.some(item=>item.schema_type===spec.schema_type))} data-structured-mappings-create onClick={()=>void execute(addFive,"五类Schema映射已建立")}>生成五类映射</Button><Button disabled={!mappings.some(item=>item.status==="pending")} data-structured-mappings-verify onClick={()=>void execute(verifyFive,"映射已由独立角色验证")}>独立验证映射</Button></div>{workspace.bundles.map(item=><Row key={item.id} title={`${item.bundle_number} · ${item.bundle_name}`} status={item.status} detail={`图谱 ${item.graph_number}@v${item.graph_version_number} · ${item.graph_manifest_hash.slice(0,16)}…`}/>)}<div className="grid gap-2 md:grid-cols-2">{mappings.map(item=><Row key={item.id} title={`${item.schema_type} ← ${item.source_entity_type}`} status={item.status} detail={`${item.source_entity_number}@r${item.source_entity_revision} · ${item.source_entity_fingerprint.slice(0,12)}…`}/>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CheckCircle2 className="h-4 w-4"/>JSON-LD生成与规则验证</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!bundle||bundle.status!=="draft"||workspace.metrics.schema_coverage_percent<100} data-structured-validation-run onClick={()=>void execute(()=>validateStructuredBundle(projectId,bundle.id,{expected_revision:bundle.revision,validation_reference:`SCHEMA-VALIDATOR-${Date.now()}`}),"JSON-LD已生成并通过验证")}>运行结构验证</Button>{validations.map(item=><Row key={item.id} title={`${item.validation_number} · ${item.mapping_count}类映射`} status={item.status} detail={`错误 ${item.error_count} · 警告 ${item.warning_count} · ${item.generated_hash.slice(0,16)}…`}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>不可变发布与渠道确认</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!bundle||bundle.status!=="draft"||!passed} data-structured-release-publish onClick={()=>void execute(()=>publishStructuredBundle(projectId,bundle.id,{expected_revision:bundle.revision,validation_id:passed!.id,consumer:"website",deployment_reference:`WEBSITE-SCHEMA-DEPLOY-${Date.now()}`}),"结构化数据已独立发布，未直接改写站点")}>独立发布到站点契约</Button>{workspace.releases.map(item=><Row key={item.id} title={`${item.release_number} · JSON-LD v${item.version_number}`} status={item.status} detail={`${item.schema_types_json.join("/")} · ${item.document_hash.slice(0,16)}…`}/>)}{workspace.publications.map(item=><Row key={item.id} title={`${item.publication_number} · ${item.consumer}`} status={item.status} detail={`消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.document_hash.slice(0,16)}…`} action={item.status==="pending"?<Button size="sm" data-structured-publication-ack onClick={()=>void execute(()=>acknowledgeStructuredPublication(projectId,item.id,reference(item.revision,"WEBSITE-SCHEMA-ACK")),"渠道已确认接收精确JSON-LD哈希")}>渠道确认接收</Button>:null}/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>图谱主数据不复制</Badge><Badge>图谱版本与实体指纹固定</Badge><Badge>映射异人验证</Badge><Badge>无效文档禁止发布</Badge><Badge>作者不能自发布</Badge><Badge>已发布版本不可改</Badge><Badge>不直接改写渠道</Badge><Badge>证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-structured-record data-structured-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge><BadgeCheck className="mr-1 h-3 w-3"/>{STATUS[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
