import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeCheck, FileSignature, Gavel, RefreshCw, ScrollText, ShieldCheck, Stamp, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  approveLegalParty, approveLegalSeal, approveLegalTemplate, completeContractObligation,
  createBusinessContract, createContractObligation, createLegalParty, createLegalTemplate,
  createSignatureEnvelope, listLegalWorkspace, recordLegalSignature, requestLegalSeal,
  reviewBusinessContract, sendSignatureEnvelope, submitBusinessContract, useLegalSeal as consumeLegalSeal,
  waiveContractObligation, type LegalWorkspace,
} from "@/lib/factory-legal-api";

const EMPTY:LegalWorkspace={parties:[],templates:[],template_versions:[],contracts:[],reviews:[],seal_authorizations:[],signature_envelopes:[],obligations:[],eligible_sources:[],evidence:[],metrics:{active_contracts:0,obligation_fulfillment_percent:0,overdue_obligations:0,expiring_90_days:0,duplicate_party_rate_percent:0},contract:{system_of_record:"legal-contract-lifecycle",raw_registration_number_stored:false,template_versions_mutable:false,approval_center_handoff_required:true,source_revision_pinned:true,signature_private_keys_stored:false,seal_self_approval:false,legal_author_self_review:false,signature_completion_activates_contract:true,source_business_record_mutated:false,obligation_evidence_required:true}};
const STATUS:Record<string,string>={draft:"草稿",active:"生效",review:"法务审核",approved:"已批准",rejected:"已驳回",terminated:"已终止","pending-approval":"待审批",used:"已用印",sent:"签署中",open:"待履约",completed:"已完成",waived:"已豁免"};
const sourceLabel=(value:string)=>value==="cpq-quote"?"客户报价":"采购订单";
const evidence=(item:{revision:number},prefix:string)=>({expected_revision:item.revision,evidence_reference:`${prefix}-${Date.now()}`});

export default function FactoryLegalContracts(){
  const [projectText,setProjectText]=useState("1");const projectId=Number(projectText);const [mode,setMode]=useState<"loading"|"live"|"error">("loading");const [workspace,setWorkspace]=useState(EMPTY);
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listLegalWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"合同法务加载失败")}};
  useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"合同法务操作失败");await load(true)}};
  const source=workspace.eligible_sources[0];
  const party=source?workspace.parties.find(x=>x.status==="active"&&((source.source_type==="cpq-quote"&&x.source_id===source.source_id)||(source.source_type==="purchase-order"&&x.source_type==="supplier"&&x.source_id===source.party_source_id))):undefined;
  const template=workspace.templates.find(x=>x.status==="active"&&x.contract_type===(source?.source_type==="purchase-order"?"supplier-purchase":"customer-sales"))??workspace.templates.find(x=>x.status==="active");
  const reviews=useMemo(()=>new Map(workspace.reviews.map(x=>[x.contract_id,x])),[workspace.reviews]);
  const createParty=()=>source&&execute(()=>createLegalParty(projectId,{party_reference:source.party_reference,party_type:source.source_type==="purchase-order"?"supplier":"customer",legal_name:`${source.party_reference} 法律主体`,country_code:"CN",identity_key:`REG-${source.party_reference}-${Date.now()}`,registration_reference:`KYB-REG-${Date.now()}`,tax_profile_reference:`TAX-${Date.now()}`,registered_address_reference:`ADDRESS-${Date.now()}`,source_type:source.party_source_type,source_id:source.party_source_id,kyb_evidence_reference:`KYB-${Date.now()}`,sanctions_screening_reference:`SCREEN-${Date.now()}`}),"法律主体草稿已创建，原始证照号已哈希后丢弃");
  const createTemplate=()=>execute(()=>createLegalTemplate(projectId,{template_code:`LEGAL-${Date.now()}`,template_name:"标准跨境业务合同",contract_type:source?.source_type==="purchase-order"?"supplier-purchase":"customer-sales",language_code:"zh-CN",governing_law:"中华人民共和国法律",dispute_resolution:"双方协商，未果提交约定仲裁机构",clauses:[{title:"标的与范围",body:"合同标的、规格、数量和服务边界以批准业务来源为准。"},{title:"交付与验收",body:"双方依据约定里程碑记录交付证据并完成独立验收。"},{title:"付款与违约",body:"付款节点、违约责任和争议处置依据受控合同文本执行。"}],document_reference:`DOC-TEMPLATE-${Date.now()}`}),"不可变合同模板版本 1 已创建");
  const createContract=()=>source&&party&&template&&execute(()=>{const effective=new Date();const expiry=new Date(effective);expiry.setFullYear(expiry.getFullYear()+1);return createBusinessContract(projectId,{contract_reference:`CONTRACT-${Date.now()}`,party_id:party.id,template_id:template.id,source_type:source.source_type,source_id:source.source_id,approval_handoff_id:source.approval_handoff_id,effective_date:effective.toISOString().slice(0,10),expiry_date:expiry.toISOString().slice(0,10),auto_renew:false,notice_days:30,draft_document_reference:`DRAFT-${Date.now()}`})},"合同草稿已按主体、模板、业务来源和审批交接版本固定");
  return <FactoryPage pageId="client-legal-contracts" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-legal-page data-legal-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Gavel className="h-5 w-5"/>合同法务</h1><p className="mt-1 text-sm opacity-70">以法律合同为唯一权威记录，串联主体核验、不可变模板、独立法审、受控用印、第三方电子签和履约义务。</p></div><div className="flex gap-2"><Input aria-label="合同法务项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入法务</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="生效合同" value={workspace.metrics.active_contracts}/><Metric label="义务履约率" value={`${workspace.metrics.obligation_fulfillment_percent}%`}/><Metric label="逾期义务" value={workspace.metrics.overdue_obligations}/><Metric label="90天内到期" value={workspace.metrics.expiring_90_days}/><Metric label="重复主体率" value={`${workspace.metrics.duplicate_party_rate_percent}%`}/></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UsersRound className="h-4 w-4"/>法律主体与不可变模板</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!source} data-legal-party-create onClick={()=>void createParty()}>从批准来源建立主体</Button><Button data-legal-template-create onClick={()=>void createTemplate()}>建立标准合同模板</Button><span className="self-center text-xs opacity-70">{source?`${sourceLabel(source.source_type)} ${source.source_number} · 版本 ${source.source_revision} · 审批交接 ${source.approval_handoff_number}`:"暂无未建合同的已确认审批来源"}</span></div>
      {workspace.parties.map(item=><Row key={item.id} data="party" title={`${item.party_number} · ${item.legal_name}`} status={item.status} detail={`${item.party_type} · ${item.country_code} · 身份指纹 ${item.identity_fingerprint.slice(0,12)}… · 来源 ${item.source_number}`} action={item.status==="draft"?<Button size="sm" data-legal-party-approve onClick={()=>void execute(()=>approveLegalParty(projectId,item.id,evidence(item,"PARTY-APPROVAL")),"法律主体已由独立人员启用")}>独立启用</Button>:null}/>) }
      {workspace.templates.map(item=><Row key={item.id} data="template" title={`${item.template_number} · ${item.template_name}`} status={item.status} detail={`${item.contract_type} · 不可变版本 ${item.current_version} · 作者 ${item.authored_by}`} action={item.status==="draft"?<Button size="sm" data-legal-template-approve onClick={()=>void execute(()=>approveLegalTemplate(projectId,item.id,evidence(item,"TEMPLATE-APPROVAL")),"合同模板已由独立人员启用")}>独立启用</Button>:null}/>) }
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ScrollText className="h-4 w-4"/>合同拟定与独立法审</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!source||!party||!template} data-legal-contract-create onClick={()=>void createContract()}>生成固定版本合同草稿</Button>{workspace.contracts.map(item=><Row key={item.id} data="contract" title={`${item.contract_number} · ${item.contract_reference}`} status={item.status} detail={`${sourceLabel(item.source_type)} ${item.source_number} v${item.source_revision} · ${item.currency} ${item.contract_value} · ${item.effective_date} 至 ${item.expiry_date}${reviews.get(item.id)?` · 风险 ${reviews.get(item.id)?.risk_level}`:""}`} action={<div className="flex flex-wrap gap-2">{item.status==="draft"?<Button size="sm" data-legal-contract-submit onClick={()=>void execute(()=>submitBusinessContract(projectId,item.id,evidence(item,"CONTRACT-SUBMIT")),"合同已提交独立法审")}>提交法审</Button>:null}{item.status==="review"?<Button size="sm" data-legal-contract-review onClick={()=>void execute(()=>reviewBusinessContract(projectId,item.id,{expected_revision:item.revision,risk_level:"low",deviations:[],recommendation:"approve",legal_comment:"已核验主体、模板、商业来源、审批交接和合同关键条款。",review_evidence_reference:`LEGAL-REVIEW-${Date.now()}`}),"合同已完成独立法审")}>批准合同</Button>:null}</div>}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Stamp className="h-4 w-4"/>受控用印与第三方电子签</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.contracts.filter(x=>x.status==="approved").map(item=><Button key={item.id} size="sm" data-legal-seal-create onClick={()=>void execute(()=>requestLegalSeal(projectId,{contract_id:item.id,seal_type:"contract-seal",document_hash:"a".repeat(64),purpose:"对已完成独立法审的固定合同文档执行单次受控用印。"}),"单文档用印申请已创建")}>为 {item.contract_number} 申请用印</Button>)}{workspace.seal_authorizations.map(item=><Row key={item.id} data="seal" title={`${item.seal_number} · ${item.contract_number}`} status={item.status} detail={`${item.seal_type} · 文档 SHA-256 ${item.document_hash.slice(0,12)}…`} action={<div className="flex flex-wrap gap-2">{item.status==="pending-approval"?<Button size="sm" data-legal-seal-approve onClick={()=>void execute(()=>approveLegalSeal(projectId,item.id,evidence(item,"SEAL-APPROVAL")),"用印已由独立人员批准")}>独立批准</Button>:null}{item.status==="approved"?<Button size="sm" data-legal-seal-use onClick={()=>void execute(()=>consumeLegalSeal(projectId,item.id,evidence(item,"SEAL-USE")),"单次用印授权已核销")}>执行用印</Button>:null}{item.status==="used"&&!workspace.signature_envelopes.some(x=>x.contract_id===item.contract_id)?<Button size="sm" data-legal-signature-create onClick={()=>void execute(()=>createSignatureEnvelope(projectId,{contract_id:item.contract_id,seal_authorization_id:item.id,provider_reference:"trusted-esign-provider",provider_envelope_reference:`ENVELOPE-${Date.now()}`,signers:["factory-signer","counterparty-signer"],signed_document_reference:`SIGNED-DOC-${Date.now()}`}),"第三方签署信封已创建")}>建立签署信封</Button>:null}</div>}/>) }
      {workspace.signature_envelopes.map(item=><Row key={item.id} data="signature" title={`${item.envelope_number} · ${item.provider_reference}`} status={item.status} detail={`第三方信封 ${item.provider_envelope_reference} · 仅保存事件证据，不保存私钥或签章图像`} action={<div className="flex flex-wrap gap-2">{item.status==="draft"?<Button size="sm" data-legal-signature-send onClick={()=>void execute(()=>sendSignatureEnvelope(projectId,item.id,evidence(item,"SIGN-DELIVERY")),"签署信封已发送")}>发送签署</Button>:null}{item.status==="sent"?JSON.parse(item.signers_json).filter((signer:string)=>!JSON.parse(item.signatures_json).some((x:{signer_reference:string})=>x.signer_reference===signer)).map((signer:string)=><Button key={signer} size="sm" data-legal-signature-record onClick={()=>void execute(()=>recordLegalSignature(projectId,item.id,{expected_revision:item.revision,signer_reference:signer,provider_event_reference:`PROVIDER-EVENT-${Date.now()}`,signature_evidence_reference:`SIGNATURE-EVIDENCE-${Date.now()}`}),`${signer} 的第三方签署证据已登记`)}>登记 {signer}</Button>):null}</div>}/>) }
    </CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BadgeCheck className="h-4 w-4"/>合同履约义务</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.contracts.filter(x=>x.status==="active").map(item=><Button key={item.id} size="sm" data-legal-obligation-create onClick={()=>{const due=new Date(item.expiry_date);due.setMonth(due.getMonth()-1);void execute(()=>createContractObligation(projectId,{contract_id:item.id,obligation_reference:`OBL-${Date.now()}`,obligation_type:"delivery",title:"合同交付与验收",description:"按合同里程碑完成交付、客户验收并保存可核验证据。",owner_reference:"contract-owner",due_date:due.toISOString().slice(0,10)}),"合同履约义务已建立")}}>为 {item.contract_number} 建立义务</Button>)}{workspace.obligations.map(item=><Row key={item.id} data="obligation" title={`${item.obligation_number} · ${item.title}`} status={item.status} detail={`${item.obligation_type} · 责任人 ${item.owner_reference} · 到期 ${item.due_date}`} action={item.status==="open"?<div className="flex flex-wrap gap-2"><Button size="sm" data-legal-obligation-complete onClick={()=>void execute(()=>completeContractObligation(projectId,item.id,evidence(item,"OBLIGATION-COMPLETE")),"义务已凭证据完成")}>凭证完成</Button><Button size="sm" variant="outline" data-legal-obligation-waive onClick={()=>void execute(()=>waiveContractObligation(projectId,item.id,evidence(item,"OBLIGATION-WAIVER")),"义务已由独立人员豁免")}>独立豁免</Button></div>:null}/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>主体原始证照号不落库</Badge><Badge>模板版本不可修改</Badge><Badge>审批中心交接必需</Badge><Badge>来源版本固定</Badge><Badge>法务作者自审禁止</Badge><Badge>用印自批禁止</Badge><Badge><FileSignature className="mr-1 h-3 w-3"/>签完才激活</Badge><Badge>业务来源不被合同系统改写</Badge><Badge>履约必须有证据</Badge><Badge>法务证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action,data}:{title:string;status:string;detail:string;action?:ReactNode;data:string}){const statusLabel=status==="completed"?(data==="signature"?"已签完":data==="obligation"?"已履约":"已完成"):(STATUS[status]??status);return <div className="rounded-lg border p-3" data-legal-record={data} data-legal-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{statusLabel}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
