import {useEffect,useMemo,useState,type ReactNode} from "react";
import {BadgeCheck,Network,RefreshCw,Send,ShieldCheck,UsersRound} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {acknowledgeBuyingPublication,addBuyingCommitteeMember,addBuyingInfluence,createBuyingCommittee,listBuyingCommitteeWorkspace,publishBuyingCommittee,verifyBuyingCommitteeMember,verifyBuyingInfluence,type BuyingCommitteeWorkspace} from "@/lib/factory-buying-committee-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:BuyingCommitteeWorkspace={committees:[],members:[],influence_edges:[],versions:[],publications:[],evidence:[],sources:{opportunities:[],profiles:[],contacts:[]},metrics:{verified_members:0,role_coverage_percent:0,multi_threaded_opportunities:0,verified_influence_edges:0,published_versions:0,handoff_acknowledgement_percent:0},contract:{}};
const STATUS:Record<string,string>={draft:"草稿",pending:"待核验",verified:"已核验",published:"已发布",acknowledged:"已回执"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});
export default function FactoryBuyingCommittee(){
 const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
 const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listBuyingCommitteeWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"采购画像加载失败")}};useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"采购画像操作失败");await load(true)}};
 const committee=workspace.committees[0];const members=useMemo(()=>committee?workspace.members.filter(x=>x.committee_id===committee.id):[],[committee,workspace.members]);const edges=useMemo(()=>committee?workspace.influence_edges.filter(x=>x.committee_id===committee.id):[],[committee,workspace.influence_edges]);const profile=workspace.sources.profiles.find(x=>x.id===committee?.icp_profile_id)??workspace.sources.profiles[0];const opportunity=workspace.sources.opportunities[0];
 const create=()=>opportunity&&profile&&execute(()=>createBuyingCommittee(projectId,{committee_name:`${opportunity.account_reference} 全球采购决策委员会`,opportunity_source_id:opportunity.id,icp_profile_id:profile.id}),"采购决策委员会已固定商机和ICP角色定义");
 const addMembers=async()=>{if(!committee||!profile)return;const contacts=workspace.sources.contacts.filter(x=>x.account_reference===committee.account_reference);for(const [index,role] of profile.roles.entries()){if(members.some(x=>x.role_id===role.id))continue;const contact=contacts.find(x=>!members.some(m=>m.contact_signal_id===x.id));if(!contact)throw new Error("该商机缺少足够的已授权、已核验联系人");await addBuyingCommitteeMember(projectId,committee.id,{role_id:role.id,contact_signal_id:contact.id,influence_score:90-index*10,relationship_strength:index===0?"strong":"medium",stance:index===2?"neutral":"supportive",preferred_channel:index===0?"meeting":"email",evidence_reference:`BUYING-ROLE-MAP-${role.code}-${Date.now()}`})}};
 const verifyMembers=async()=>{for(const item of members.filter(x=>x.status==="pending"))await verifyBuyingCommitteeMember(projectId,item.id,ref(item.revision,"BUYING-MEMBER-VERIFY"))};
 const createInfluences=async()=>{if(!committee)return;const verified=members.filter(x=>x.status==="verified");for(let i=0;i<verified.length-1;i++){const left=verified[i],right=verified[i+1];if(edges.some(x=>x.from_member_id===left.id&&x.to_member_id===right.id))continue;await addBuyingInfluence(projectId,committee.id,{from_member_id:left.id,to_member_id:right.id,influence_direction:i===0?"approves":"influences",strength:i===0?"strong":"medium",evidence_reference:`BUYING-INFLUENCE-${Date.now()}-${i}`})}};
 const verifyInfluences=async()=>{for(const item of edges.filter(x=>x.status==="pending"))await verifyBuyingInfluence(projectId,item.id,ref(item.revision,"BUYING-INFLUENCE-VERIFY"))};const acknowledge=async()=>{for(const item of workspace.publications.filter(x=>x.status==="pending"))await acknowledgeBuyingPublication(projectId,item.id,ref(item.revision,"BUYING-CONSUMER-ACK"))};
 return <FactoryPage pageId="client-buying-committee" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-buying-committee-page data-buying-committee-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><UsersRound className="h-5 w-5"/>采购画像与决策委员会</h1><p className="mt-1 text-sm opacity-70">把真实商机、ICP采购角色和已授权联系人组成可核验的多线程决策网络；不复制联系人原文，也不直接改写CRM。</p></div><div className="flex gap-2"><Input aria-label="采购画像项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入画像</Button></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="核验成员" value={workspace.metrics.verified_members}/><Metric label="角色覆盖" value={`${workspace.metrics.role_coverage_percent}%`}/><Metric label="多线程商机" value={workspace.metrics.multi_threaded_opportunities}/><Metric label="影响路径" value={workspace.metrics.verified_influence_edges}/><Metric label="发布版本" value={workspace.metrics.published_versions}/><Metric label="下游回执" value={`${workspace.metrics.handoff_acknowledgement_percent}%`}/></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UsersRound className="h-4 w-4"/>商机、ICP角色与已授权成员</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!committee||!opportunity||!profile} data-buying-committee-create onClick={()=>void create()}>建立决策委员会</Button><Button disabled={!committee||committee.status!=="draft"||!profile||profile.roles.every(r=>members.some(m=>m.role_id===r.id))} data-buying-members-create onClick={()=>void execute(addMembers,"全部ICP采购角色已映射")}>映射采购角色</Button><Button disabled={!members.some(x=>x.status==="pending")} data-buying-members-verify onClick={()=>void execute(verifyMembers,"成员已由独立角色核验")}>独立核验成员</Button></div>{workspace.committees.map(item=><Row key={item.id} title={`${item.committee_number} · ${item.committee_name}`} status={item.status} detail={`${item.account_reference} · ${item.opportunity_source_number}@v${item.opportunity_source_revision} · ${item.icp_profile_number}`}/>)}<div className="grid gap-2 md:grid-cols-2">{members.map(item=><Row key={item.id} title={`${item.role_name} · ${item.contact_hint}`} status={item.status} detail={`${item.member_number} · 影响力 ${item.influence_score} · ${item.relationship_strength}/${item.stance} · 仅保存不可逆联系人哈希`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Network className="h-4 w-4"/>决策影响路径</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!committee||members.filter(x=>x.status==="verified").length<2||committee.status!=="draft"} data-buying-influences-create onClick={()=>void execute(createInfluences,"决策影响路径已提交")}>生成影响路径</Button><Button disabled={!edges.some(x=>x.status==="pending")} data-buying-influences-verify onClick={()=>void execute(verifyInfluences,"影响路径已独立核验")}>独立核验路径</Button></div><div className="grid gap-2 md:grid-cols-2">{edges.map(item=><Row key={item.id} title={`${item.from_member_number} → ${item.influence_direction} → ${item.to_member_number}`} status={item.status} detail={`${item.strength} · ${item.endpoint_manifest_hash.slice(0,18)}…`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>不可变版本与业务系统回执</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!committee||committee.status!=="draft"||workspace.metrics.role_coverage_percent<100||workspace.metrics.verified_influence_edges<Math.max(0,members.length-1)} data-buying-committee-publish onClick={()=>committee&&void execute(()=>publishBuyingCommittee(projectId,committee.id,{expected_revision:committee.revision,consumers:["crm","sales","marketing","service"],delivery_reference_prefix:`BUYING-COMMITTEE-${Date.now()}`}),"完整决策委员会已独立发布")}>独立发布画像</Button><Button disabled={!workspace.publications.some(x=>x.status==="pending")} data-buying-publications-ack onClick={()=>void execute(acknowledge,"全部下游已确认委员会哈希")}>下游批量回执</Button></div>{workspace.versions.map(item=><Row key={item.id} title={`${item.version_reference} · 决策委员会v${item.version_number}`} status={item.status} detail={`${item.member_count}/${item.required_role_count}角色 · ${item.influence_edge_count}条路径 · ${item.manifest_hash.slice(0,20)}…`}/>) }<div className="grid gap-2 md:grid-cols-2">{workspace.publications.map(item=><Row key={item.id} title={`${item.consumer.toUpperCase()} · ${item.publication_number}`} status={item.status} detail={`消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.delivery_reference}`}/>)}</div></CardContent></Card>
  <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>只接收已授权联系人</Badge><Badge>商机与ICP修订固定</Badge><Badge>成员异人核验</Badge><Badge>路径异人核验</Badge><Badge>角色不完整禁止发布</Badge><Badge>版本不可变</Badge><Badge>不改写CRM/销售系统</Badge><Badge>审计证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
 </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-buying-committee-record data-buying-committee-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge><BadgeCheck className="mr-1 h-3 w-3"/>{STATUS[status]??status}</Badge></div><p className="mt-1 break-all text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
