import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeCheck, BrainCircuit, Network, RefreshCw, ShieldCheck, Target, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  acknowledgeIcpActivation, addIcpRole, addIcpScenario, approveIcpProfile, assessIcpFit,
  captureIcpEvidence, createIcpActivation, createIcpProfile, listIcpWorkspace,
  verifyIcpAssessment, verifyIcpEvidence, type IcpWorkspace,
} from "@/lib/factory-icp-api";

const EMPTY:IcpWorkspace={profiles:[],versions:[],buying_roles:[],scenarios:[],account_evidence:[],fit_assessments:[],activations:[],authoritative_sources:[],evidence:[],metrics:{active_icps:0,assessed_accounts:0,high_fit_rate_percent:0,verified_evidence_coverage_percent:0,buying_role_coverage:0,activation_acknowledgement_percent:0},contract:{}};
const statusLabel:Record<string,string>={draft:"草稿",active:"已启用",retired:"已退役",pending:"待复核",verified:"已验证",acknowledged:"已确认"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});

export default function FactoryIcpProfiles(){
  const [projectText,setProjectText]=useState("1");const projectId=Number(projectText);const [mode,setMode]=useState<"loading"|"live"|"error">("loading");const [workspace,setWorkspace]=useState(EMPTY);
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listIcpWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"ICP工作台加载失败")}};
  useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"ICP操作失败");await load(true)}};
  const versions=useMemo(()=>new Map(workspace.versions.map(item=>[item.profile_id,item])),[workspace.versions]);
  const createCompleteDraft=()=>execute(async()=>{
    const stamp=Date.now();const result=await createIcpProfile(projectId,{profile_code:`GLOBAL-ICP-${stamp}`,profile_name:"全球工业自动化高价值客户",market_mode:"global",customer_type:"b2b",objective:"以可核验商业事实识别高价值工业自动化客户，并为获客、内容和销售提供统一标准。",countries:["CN","US","DE"],industries:["industrial-automation","advanced-manufacturing"],company_size_bands:["500-5000","5000+"],product_references:["ROBOT-CELL"],required_roles:["CFO","CTO","plant-manager"],buying_triggers:["capacity-expansion","equipment-renewal"],minimum_potential_value:200000,currency:"USD",scoring_weights:{country:10,industry:15,company_size:10,product:20,role:15,trigger:15,value:15}});
    for(const item of [{code:"CFO",name:"经济决策人",type:"economic-buyer"},{code:"CTO",name:"技术决策人",type:"technical-buyer"},{code:"plant-manager",name:"工厂推动者",type:"champion"}])await addIcpRole(projectId,result.profile.id,{role_code:item.code,role_name:item.name,influence_type:item.type,pains:["产能与投资回报压力"],proof_requirements:["可核验ROI与交付案例"],preferred_channels:["高层研讨会","行业展会"]});
    for(const item of [{code:"expansion",name:"产能扩张",trigger:"capacity-expansion"},{code:"renewal",name:"设备更新",trigger:"equipment-renewal"}])await addIcpScenario(projectId,result.profile.id,{scenario_code:item.code,scenario_name:item.name,job_to_be_done:"在可控投资与交付风险下提升自动化产能和生产稳定性。",buying_trigger:item.trigger,product_references:["ROBOT-CELL"],success_outcomes:["产能提升","回收期可验证"],disqualifiers:["无预算负责人","无明确项目窗口"]});
  },"完整ICP草稿、采购角色和购买场景已建立");
  const active=workspace.profiles.find(item=>item.status==="active");const source=active?workspace.authoritative_sources.find(item=>!item.captured_profile_ids.includes(active.id)):undefined;
  const capture=()=>active&&source&&execute(()=>{const version=versions.get(active.id);return captureIcpEvidence(projectId,active.id,{source_type:source.source_type,source_id:source.source_id,firmographic_country:version?.countries_json[0],firmographic_industry:version?.industries_json[0],firmographic_company_size:version?.company_size_bands_json[0],firmographic_evidence_reference:`FIRMOGRAPHIC-${Date.now()}`,observed_roles:version?.required_roles_json.slice(0,2)??[],observed_triggers:version?.buying_triggers_json.slice(0,1)??[],observed_products:source.products.length?source.products:version?.product_references_json.slice(0,1)??[]})},"权威来源版本与企业特征证据已锁定");
  return <FactoryPage pageId="client-icp-profiles" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-icp-page data-icp-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Target className="h-5 w-5"/>ICP客户定位</h1><p className="mt-1 text-sm opacity-70">用不可变客群标准、采购角色、购买场景和权威业务证据识别真正值得投入的客户；AI只能辅助解释，不能自主判客。</p></div><div className="flex gap-2"><Input aria-label="ICP项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={event=>setProjectText(event.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入ICP</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="启用ICP" value={workspace.metrics.active_icps}/><Metric label="已评估账户" value={workspace.metrics.assessed_accounts}/><Metric label="高匹配率" value={`${workspace.metrics.high_fit_rate_percent}%`}/><Metric label="证据覆盖" value={`${workspace.metrics.verified_evidence_coverage_percent}%`}/><Metric label="采购角色" value={workspace.metrics.buying_role_coverage}/><Metric label="激活确认" value={`${workspace.metrics.activation_acknowledgement_percent}%`}/></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UsersRound className="h-4 w-4"/>客群标准、采购角色与购买场景</CardTitle></CardHeader><CardContent className="space-y-3"><Button data-icp-profile-create onClick={()=>void createCompleteDraft()}>建立完整ICP草稿</Button>{workspace.profiles.map(item=>{const version=versions.get(item.id);const roleCount=workspace.buying_roles.filter(x=>x.profile_id===item.id).length;const scenarioCount=workspace.scenarios.filter(x=>x.profile_id===item.id).length;return <Row key={item.id} data="profile" title={`${item.profile_number} · ${item.profile_name}`} status={item.status} detail={`${item.market_mode.toUpperCase()} · ${item.customer_type.toUpperCase()} · v${item.current_version} · ${roleCount}个采购角色 · ${scenarioCount}个购买场景 · 定义指纹 ${version?.definition_hash.slice(0,12)??"—"}…`} action={item.status==="draft"?<Button size="sm" data-icp-profile-approve onClick={()=>void execute(()=>approveIcpProfile(projectId,item.id,ref(item.revision,"ICP-APPROVAL")),"ICP已由独立人员启用")}>独立审核启用</Button>:null}/>})}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4"/>账户证据与来源版本</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap items-center gap-2"><Button disabled={!active||!source} data-icp-evidence-capture onClick={()=>void capture()}>从权威业务来源采集</Button><span className="text-xs opacity-70">{source?`${source.source_type} ${source.source_number} · ${source.account_reference} · v${source.revision}`:"暂无未采集的报价、订单、装机资产或客户之声"}</span></div>{workspace.account_evidence.map(item=><Row key={item.id} data="account-evidence" title={`${item.evidence_number} · ${item.account_reference}`} status={item.verification_status} detail={`${item.source_type} ${item.source_number} v${item.source_revision} · ${item.currency} ${item.potential_value} · ${item.firmographic_country??"未标国家"} / ${item.firmographic_industry??"未标行业"}`} action={item.verification_status==="pending"?<Button size="sm" data-icp-evidence-verify onClick={()=>void execute(()=>verifyIcpEvidence(projectId,item.id,ref(item.revision,"ICP-EVIDENCE-QA")),"账户证据已由独立人员验证")}>独立验证证据</Button>:null}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BrainCircuit className="h-4 w-4"/>可解释匹配评分</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.account_evidence.filter(item=>item.verification_status==="verified"&&!workspace.fit_assessments.some(x=>x.account_evidence_id===item.id)).map(item=><Button key={item.id} size="sm" data-icp-assess onClick={()=>void execute(()=>assessIcpFit(projectId,item.profile_id,{account_evidence_id:item.id}),"已生成可解释ICP匹配评分")}>评估 {item.account_reference}</Button>)}{workspace.fit_assessments.map(item=><Row key={item.id} data="assessment" title={`${item.assessment_number} · ${item.account_reference}`} status={item.status} detail={`匹配等级 ${item.fit_tier} · ${item.total_score}/100 · ${item.explanation}`} action={item.status==="pending"?<Button size="sm" data-icp-assessment-verify onClick={()=>void execute(()=>verifyIcpAssessment(projectId,item.id,ref(item.revision,"ICP-FIT-QA")),"ICP评分已由独立人员复核")}>独立复核评分</Button>:null}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Network className="h-4 w-4"/>下游应用激活与确认</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.profiles.filter(item=>item.status==="active"&&!workspace.activations.some(x=>x.profile_id===item.id&&x.consumer==="lead-routing")).map(item=><Button key={item.id} size="sm" data-icp-activation-create onClick={()=>void execute(()=>createIcpActivation(projectId,item.id,{consumer:"lead-routing",minimum_fit_tier:"B",delivery_reference:`ICP-ROUTING-PAYLOAD-${Date.now()}`}),"已发布不可变ICP契约，等待线索路由确认")}>发布到线索路由</Button>)}{workspace.activations.map(item=><Row key={item.id} data="activation" title={`${item.activation_number} · ${item.consumer}`} status={item.status} detail={`ICP v${item.profile_version} · 最低匹配 ${item.minimum_fit_tier} · ${item.delivery_reference}`} action={item.status==="pending"?<Button size="sm" data-icp-activation-ack onClick={()=>void execute(()=>acknowledgeIcpActivation(projectId,item.id,ref(item.revision,"ICP-CONSUMER-ACK")),"下游应用已确认接收ICP契约")}>下游确认接收</Button>:null}/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><BadgeCheck className="mr-1 h-3 w-3"/>ICP版本不可变</Badge><Badge>来源版本固定</Badge><Badge>人工企业特征必须有证据</Badge><Badge>作者自审禁止</Badge><Badge>评分者自证禁止</Badge><Badge>AI自主判客禁止</Badge><Badge>不写回CRM客户主档</Badge><Badge>不保存原始联系人</Badge><Badge>下游必须显式确认</Badge><Badge>审计证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action,data}:{title:string;status:string;detail:string;action?:ReactNode;data:string}){return <div className="rounded-lg border p-3" data-icp-record={data} data-icp-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{statusLabel[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
