import { useEffect, useMemo, useState } from "react";
import { Building2, Calculator, Database, RefreshCw, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  approveErpPosting, approveErpUnit, closeErpPeriod, createErpCostCenter, createErpPosting,
  createErpUnit, listErpWorkspace, openErpPeriod, registerErpOrderProject,
  submitErpPeriodClose, submitErpPosting, type ErpPeriod, type ErpPosting,
  type ErpWorkspace,
} from "@/lib/factory-erp-api";

const EMPTY:ErpWorkspace={operating_units:[],cost_centers:[],order_projects:[],periods:[],postings:[],balances:[],evidence:[],eligible_orders:[],contract:{ledger_classification:"management-operating-ledger",formal_financial_general_ledger:false,oms_order_authority:true,order_confirmation_writeback:false,posted_records_mutable:false,historical_recalculation:false,period_close_independent:true}};
const STATUS:Record<string,string>={draft:"草稿",active:"已启用",open:"开放",closing:"待独立关账",closed:"已关账","pending-approval":"待独立审批",posted:"已过账"};
const rev=(item:{revision:number})=>({expected_revision:item.revision,evidence_reference:`ERP-EVIDENCE-${Date.now()}`});

export default function FactoryErp(){
  const [projectText,setProjectText]=useState("1"); const projectId=Number(projectText);
  const [mode,setMode]=useState<"loading"|"live"|"error">("loading"); const [workspace,setWorkspace]=useState<ErpWorkspace>(EMPTY);
  const [unitCode,setUnitCode]=useState("FACTORY-01"); const [unitName,setUnitName]=useState("主营工厂");
  const [manager,setManager]=useState("factory-manager"); const [currency,setCurrency]=useState("USD");
  const [centerCode,setCenterCode]=useState("PROD-01"); const [centerName,setCenterName]=useState("生产成本中心");
  const [periodCode,setPeriodCode]=useState(new Date().toISOString().slice(0,7));
  const [postingCategory,setPostingCategory]=useState("material"); const [direction,setDirection]=useState("outflow");
  const [amount,setAmount]=useState("630"); const [postingDescription,setPostingDescription]=useState("订单项目材料经营成本凭证");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listErpWorkspace(projectId));setMode("live");}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"ERP经营总台加载失败");}};
  useEffect(()=>{void load();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true);}catch(error){toast.error(error instanceof Error?error.message:"ERP治理操作失败");await load(true);}};
  const activeUnit=workspace.operating_units.find(x=>x.status==="active"); const center=workspace.cost_centers.find(x=>x.status==="active");
  const unregisteredOrder=workspace.eligible_orders.find(x=>!x.registered); const orderProject=workspace.order_projects.find(x=>x.status==="open");
  const openPeriod=workspace.periods.find(x=>x.status==="open");
  const postingsByPeriod=useMemo(()=>new Map(workspace.periods.map(period=>[period.id,workspace.postings.filter(x=>x.period_id===period.id)])),[workspace.periods,workspace.postings]);
  const balancesByPeriod=useMemo(()=>new Map(workspace.periods.map(period=>[period.id,workspace.balances.filter(x=>x.period_id===period.id)])),[workspace.periods,workspace.balances]);
  const createUnit=()=>execute(()=>createErpUnit(projectId,{unit_reference:`ERP-UNIT-${Date.now()}`,unit_code:unitCode,unit_name:unitName,unit_type:"factory",base_currency:currency,manager}),"ERP经营组织草稿已建立");
  const createCenter=()=>activeUnit&&execute(()=>createErpCostCenter(projectId,{operating_unit_id:activeUnit.id,center_reference:`ERP-CENTER-${Date.now()}`,center_code:centerCode,center_name:centerName,center_type:"production",owner:"production-owner"}),"成本中心已建立");
  const registerOrder=()=>activeUnit&&unregisteredOrder&&execute(()=>registerErpOrderProject(projectId,{operating_unit_id:activeUnit.id,order_id:unregisteredOrder.id,project_reference:`ERP-PROJECT-${unregisteredOrder.order_number}`}),"已引用OMS确认订单建立经营项目");
  const openPeriodAction=()=>activeUnit&&execute(()=>openErpPeriod(projectId,{operating_unit_id:activeUnit.id,period_reference:`ERP-PERIOD-${periodCode}-${Date.now()}`,period_code:periodCode}),"经营期间已开放");
  const post=()=>openPeriod&&orderProject&&center&&execute(()=>createErpPosting(projectId,{posting_reference:`ERP-POST-${Date.now()}`,period_id:openPeriod.id,order_project_id:orderProject.id,cost_center_id:center.id,posting_date:`${periodCode}-01`,category:postingCategory,direction,amount,description:postingDescription,evidence_reference:`ERP-SOURCE-${Date.now()}`,correction_of_posting_id:null}),"经营记账草稿已建立");
  return <FactoryPage pageId="client-erp" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-erp-page data-erp-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Building2 className="h-5 w-5"/>ERP经营总台</h1><p className="mt-1 text-sm opacity-70">把已确认OMS订单连接到经营组织、成本中心、订单项目和不可变月结底账；不是正式财务总账。</p></div><div className="flex gap-2"><Input aria-label="ERP项目ID" className="w-24" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入ERP</Button></div></div>

    <Card><CardHeader><CardTitle className="text-base">经营组织与成本中心</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-4"><Input aria-label="经营组织代码" value={unitCode} onChange={e=>setUnitCode(e.target.value)}/><Input aria-label="经营组织名称" value={unitName} onChange={e=>setUnitName(e.target.value)}/><Input aria-label="经营组织负责人" value={manager} onChange={e=>setManager(e.target.value)}/><Input aria-label="本位币" value={currency} onChange={e=>setCurrency(e.target.value)}/></div><Button data-erp-unit-create onClick={()=>void createUnit()}><Building2 className="mr-1 h-4 w-4"/>建立经营组织</Button>{workspace.operating_units.map(unit=><div key={unit.id} className="rounded-lg border p-3" data-erp-unit-status={unit.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{unit.unit_number} · {unit.unit_code} · {unit.unit_name}</b><Badge>{STATUS[unit.status]??unit.status}</Badge></div><p className="mt-1 text-xs">{unit.unit_type} · {unit.base_currency} · 负责人 {unit.manager} · 修订 {unit.revision}</p>{unit.status==="draft"?<Button className="mt-2" size="sm" data-erp-unit-approve onClick={()=>void execute(()=>approveErpUnit(projectId,unit.id,rev(unit)),"经营组织已独立审批启用")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批启用</Button>:null}</div>)}{activeUnit?<><div className="grid gap-2 md:grid-cols-3"><Input aria-label="成本中心代码" value={centerCode} onChange={e=>setCenterCode(e.target.value)}/><Input aria-label="成本中心名称" value={centerName} onChange={e=>setCenterName(e.target.value)}/><Button data-erp-center-create onClick={()=>void createCenter()}>建立成本中心</Button></div><div className="grid gap-2 md:grid-cols-2">{workspace.cost_centers.map(item=><div key={item.id} className="rounded bg-muted/40 p-3" data-erp-center={item.id}><b>{item.center_number} · {item.center_code}</b><p className="text-xs">{item.center_name} · {item.center_type} · {item.owner}</p></div>)}</div></>:null}</CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">OMS确认订单与ERP经营项目</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-2">{workspace.eligible_orders.map(order=><div key={order.id} className="rounded-lg border p-3" data-erp-eligible-order data-erp-order-registered={order.registered?"true":"false"}><div className="flex items-center justify-between"><b>{order.order_number}</b><Badge>{order.status}</Badge></div><p className="text-sm">{order.account_reference} · {order.order_total} {order.currency} · OMS修订 {order.revision}</p>{!order.registered&&activeUnit?<Button className="mt-2" size="sm" data-erp-order-register onClick={()=>void registerOrder()}>登记经营项目</Button>:null}</div>)}</div>{workspace.order_projects.map(item=><div key={item.id} className="rounded-lg border p-3" data-erp-order-project><b>{item.erp_project_number} · {item.order_number}</b><p className="text-sm">冻结OMS修订 {item.order_revision} · {item.account_reference} · {item.order_total} {item.currency}</p></div>)}</CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">经营期间、不可变记账与独立月结</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Input aria-label="经营期间" className="w-40" value={periodCode} onChange={e=>setPeriodCode(e.target.value)}/><Button disabled={!activeUnit} data-erp-period-open onClick={()=>void openPeriodAction()}><Database className="mr-1 h-4 w-4"/>开放期间</Button></div>{openPeriod&&orderProject&&center?<div className="grid gap-2 md:grid-cols-5"><select aria-label="经营记账类别" value={postingCategory} onChange={e=>setPostingCategory(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="order-revenue">订单收入</option><option value="material">材料成本</option><option value="labor">人工成本</option><option value="logistics">物流成本</option><option value="service">服务成本</option><option value="overhead">制造费用</option><option value="adjustment">调整</option></select><select aria-label="经营记账方向" value={direction} onChange={e=>setDirection(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="inflow">流入</option><option value="outflow">流出</option></select><Input aria-label="经营记账金额" value={amount} onChange={e=>setAmount(e.target.value)}/><Input aria-label="经营记账说明" value={postingDescription} onChange={e=>setPostingDescription(e.target.value)}/><Button data-erp-posting-create onClick={()=>void post()}><WalletCards className="mr-1 h-4 w-4"/>建立记账</Button></div>:null}{workspace.periods.map(period=><PeriodCard key={period.id} period={period} postings={postingsByPeriod.get(period.id)??[]} balances={balancesByPeriod.get(period.id)??[]} execute={execute} projectId={projectId}/>)}</CardContent></Card>

    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge>{workspace.contract.ledger_classification}</Badge><Badge>正式财务总账：{workspace.contract.formal_financial_general_ledger?"是":"否"}</Badge><Badge>订单权威：OMS</Badge><Badge>确认状态回写：{workspace.contract.order_confirmation_writeback?"允许":"禁止"}</Badge><Badge>已过账可改：{workspace.contract.posted_records_mutable?"允许":"禁止"}</Badge><Badge>历史重算：{workspace.contract.historical_recalculation?"允许":"禁止"}</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function PeriodCard({period,postings,balances,execute,projectId}:{period:ErpPeriod;postings:ErpPosting[];balances:ErpWorkspace["balances"];execute:(operation:()=>Promise<unknown>,message:string)=>Promise<void>;projectId:number}){
  return <div className="rounded-lg border p-3" data-erp-period-status={period.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{period.period_number} · {period.period_code}</b><Badge>{STATUS[period.status]??period.status}</Badge></div><div className="mt-2 grid gap-2 sm:grid-cols-4 text-sm"><p>流入 <b>{period.total_inflow}</b></p><p>流出 <b>{period.total_outflow}</b></p><p>经营净额 <b data-erp-period-net>{period.net_result}</b></p><p>已过账 {period.posting_count} 条</p></div><div className="mt-2 space-y-2">{postings.map(item=><div key={item.id} className="rounded bg-muted/40 p-2" data-erp-posting-status={item.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.posting_number} · {item.category}</b><Badge variant="secondary">{STATUS[item.status]??item.status}</Badge></div><p className="text-xs">{item.direction} · {item.amount} {item.currency} · {item.description}</p><div className="mt-1 flex gap-2">{item.status==="draft"?<Button size="sm" data-erp-posting-submit onClick={()=>void execute(()=>submitErpPosting(projectId,item.id,rev(item)),"经营记账已提交独立审批")}>提交审批</Button>:null}{item.status==="pending-approval"?<Button size="sm" data-erp-posting-approve onClick={()=>void execute(()=>approveErpPosting(projectId,item.id,rev(item)),"经营记账已独立过账")}>独立过账</Button>:null}</div></div>)}</div><div className="mt-2 flex gap-2">{period.status==="open"&&postings.length>0?<Button size="sm" data-erp-period-submit-close onClick={()=>void execute(()=>submitErpPeriodClose(projectId,period.id,rev(period)),"经营期间已对账，等待独立关账")}><Calculator className="mr-1 h-4 w-4"/>提交月结</Button>:null}{period.status==="closing"?<Button size="sm" data-erp-period-close onClick={()=>void execute(()=>closeErpPeriod(projectId,period.id,rev(period)),"经营期间已独立关账冻结")}><ShieldCheck className="mr-1 h-4 w-4"/>独立关账</Button>:null}</div>{balances.map(item=><p key={item.id} className="mt-2 text-xs font-semibold text-emerald-700" data-erp-period-balance>{item.erp_project_number} · {item.center_number} · 流入 {item.inflow} / 流出 {item.outflow} / 净额 {item.net_result}</p>)}</div>;
}
