import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Bot, BriefcaseBusiness, FileCheck2, RefreshCw, Send, ShieldCheck, UserCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  approveRecruitingOffer, approveRecruitingRequisition, completeRecruitingInterview,
  createRecruitingCandidate, createRecruitingOffer, createRecruitingRequisition,
  decideRecruitingApplication, listRecruitingWorkspace, respondRecruitingOffer,
  scheduleRecruitingInterview, sendRecruitingOffer, submitRecruitingApplication,
  type RecruitingWorkspace,
} from "@/lib/factory-recruiting-api";

const EMPTY:RecruitingWorkspace={requisitions:[],candidates:[],applications:[],interviews:[],assessments:[],offers:[],onboarding_handoffs:[],eligible_positions:[],evidence:[],metrics:{open_requisitions:0,active_candidates:0,interviews_completed:0,offers_accepted:0},contract:{system_of_record:"recruiting-ats",candidate_consent_required:true,marketing_contact_import:false,resume_content_stored:false,ai_assistance_allowed:true,ai_autonomous_decision:false,structured_rubric_required:true,human_final_decision_required:true,accepted_offer_hr_handoff_only:true}};
const LABEL:Record<string,string>={draft:"草稿",open:"招聘中",closed:"已关闭",active:"进行中",applied:"已应聘",interview:"面试中",offer:"待Offer",hired:"已录用",scheduled:"已安排",completed:"已评估",approved:"已批准",sent:"已发送",accepted:"已接受",declined:"已拒绝",ready:"待入职",consumed:"已入职",advance:"推进",reject:"淘汰"};
const futureDate=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)};
const futureTime=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString()};
const rev=(item:{revision:number})=>({expected_revision:item.revision,evidence_reference:`REC-EVIDENCE-${Date.now()}`});

export default function FactoryRecruiting(){
  const [projectText,setProjectText]=useState("1"); const projectId=Number(projectText);
  const [mode,setMode]=useState<"loading"|"live"|"error">("loading"); const [workspace,setWorkspace]=useState<RecruitingWorkspace>(EMPTY);
  const [candidateName,setCandidateName]=useState("候选人"); const [candidateEmail,setCandidateEmail]=useState("candidate-auto@example.com");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listRecruitingWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"招聘面试中心加载失败")}};
  useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"招聘治理操作失败");await load(true)}};
  const position=workspace.eligible_positions.find(x=>x.available_openings>0); const req=workspace.requisitions.find(x=>x.status==="open"); const candidate=workspace.candidates.find(x=>x.status==="active");
  const createReq=()=>position&&execute(()=>createRecruitingRequisition(projectId,{requisition_reference:`REQ-${Date.now()}`,position_id:position.id,opening_count:1,employment_type:"full-time",work_location:"Shanghai",target_start_date:futureDate(90),hiring_reason:"依据已批准岗位编制补充全球业务关键人才。",rubric_version:"RUBRIC-2026-V1",rubric:{skills:"专业能力",evidence:"事实证据",communication:"沟通能力",integrity:"诚信合规"}}),"招聘需求草稿已建立");
  const createCandidate=()=>execute(()=>createRecruitingCandidate(projectId,{candidate_reference:`CAN-${Date.now()}`,display_name:candidateName,email:candidateEmail==="candidate-auto@example.com"?`candidate-${Date.now().toString().slice(-6)}@example.com`:candidateEmail,country_code:"CN",source_type:"candidate-direct",source_reference:`CAREERS-${Date.now()}`,consent_reference:`CONSENT-${Date.now()}`,privacy_notice_reference:"CANDIDATE-PRIVACY-V1",retention_until:futureDate(365),profile_reference:`ATS-PROFILE-${Date.now()}`}),"候选人授权档案已建立");
  const apply=()=>req&&candidate&&execute(()=>submitRecruitingApplication(projectId,{requisition_id:req.id,candidate_id:candidate.id,application_reference:`APPLICATION-${Date.now()}`,submitted_evidence_reference:`PORTAL-SUBMISSION-${Date.now()}`}),"候选人已提交应聘");
  const schedule=(applicationId:string)=>execute(()=>scheduleRecruitingInterview(projectId,{application_id:applicationId,interview_type:"structured-ai-assisted",scheduled_at:futureTime(3),interviewer_reference:`PANEL-${Date.now()}`}),"结构化面试已安排");
  const complete=(item:{id:string;revision:number})=>execute(()=>completeRecruitingInterview(projectId,item.id,{expected_revision:item.revision,skills_score:"90",evidence_score:"88",communication_score:"92",integrity_score:"94",transcript_reference:`TRANSCRIPT-${Date.now()}`,citation_references:[`ANSWER-2-${Date.now()}`,`ANSWER-5-${Date.now()}`],assessor_comment:"依据固定量表、访谈记录和回答证据完成结构化评价。",ai_assisted:true,ai_model_reference:"INTERVIEW-MODEL-2026-V1"}),"面试证据和量表评分已登记");
  const createOffer=(applicationId:string)=>execute(()=>createRecruitingOffer(projectId,{application_id:applicationId,offer_reference:`OFFER-${Date.now()}`,proposed_start_date:futureDate(60),compensation_band:"CN-L5-BAND",offer_document_reference:`OFFER-DOC-${Date.now()}`}),"Offer草稿已建立");
  return <FactoryPage pageId="client-recruiting" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-recruiting-page data-recruiting-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><UsersRound className="h-5 w-5"/>招聘面试中心</h1><p className="mt-1 text-sm opacity-70">受岗位编制约束，候选人必须授权；AI只辅助转写和证据评分，最终录用由人类独立决定，接受Offer后才交接HR。</p></div><div className="flex gap-2"><Input aria-label="招聘项目ID" className="w-24" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入招聘</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="开放需求" value={workspace.metrics.open_requisitions}/><Metric label="授权候选人" value={workspace.metrics.active_candidates}/><Metric label="完成面试" value={workspace.metrics.interviews_completed}/><Metric label="接受Offer" value={workspace.metrics.offers_accepted}/></div>
    <Card><CardHeader><CardTitle className="text-base">岗位编制与招聘需求</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-3">{workspace.eligible_positions.map(item=><div key={item.id} className="rounded border p-2 text-xs" data-recruiting-position><b>{item.position_number} · {item.position_title}</b><p>编制 {item.planned_headcount} / 在岗 {item.filled_headcount} / 可招 {item.available_openings}</p></div>)}<Button disabled={!position} data-recruiting-requisition-create onClick={()=>void createReq()}><BriefcaseBusiness className="mr-1 h-4 w-4"/>建立招聘需求</Button></div>{workspace.requisitions.map(item=><Row key={item.id} title={`${item.requisition_number} · ${item.position_number}`} status={item.status} detail={`${item.opening_count}人 · ${item.work_location} · ${item.employment_type} · ${item.rubric_version}`} data="requisition" action={item.status==="draft"?<Button size="sm" data-recruiting-requisition-approve onClick={()=>void execute(()=>approveRecruitingRequisition(projectId,item.id,rev(item)),"招聘需求已独立审批开放")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批开放</Button>:null}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">候选人授权与应聘</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><Input aria-label="候选人姓名" value={candidateName} onChange={e=>setCandidateName(e.target.value)}/><Input aria-label="候选人邮箱" value={candidateEmail} onChange={e=>setCandidateEmail(e.target.value)}/><Button data-recruiting-candidate-create onClick={()=>void createCandidate()}><UserCheck className="mr-1 h-4 w-4"/>登记授权候选人</Button></div>{workspace.candidates.map(item=><Row key={item.id} title={`${item.candidate_number} · ${item.display_name}`} status={item.status} detail={`${item.email} · ${item.source_type} · 保留至 ${item.retention_until}`} data="candidate"/>)}<Button disabled={!req||!candidate} data-recruiting-application-create onClick={()=>void apply()}>提交应聘</Button>{workspace.applications.map(item=><Row key={item.id} title={`${item.application_number} · ${item.candidate_number}`} status={item.current_stage} detail={`${item.requisition_number} · 人工决定 ${item.final_decision?LABEL[item.final_decision]:"未决定"}`} data="application" action={item.current_stage==="applied"?<Button size="sm" data-recruiting-interview-schedule onClick={()=>void schedule(item.id)}>安排结构化面试</Button>:null}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">结构化面试与人工终审</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.interviews.map(item=>{const app=workspace.applications.find(x=>x.id===item.application_id);return <Row key={item.id} title={`${item.interview_number} · ${item.interview_type}`} status={item.status} detail={`${item.rubric_version} · ${item.interviewer_reference}`} data="interview" action={<div className="flex flex-wrap gap-2">{item.status==="scheduled"?<Button size="sm" data-recruiting-interview-complete onClick={()=>void complete(item)}><Bot className="mr-1 h-4 w-4"/>登记AI辅助评估</Button>:null}{item.status==="completed"&&app&&!app.final_decision?<><Button size="sm" data-recruiting-decision-advance onClick={()=>void execute(()=>decideRecruitingApplication(projectId,app.id,{expected_revision:app.revision,decision:"advance",decision_reason:"人类委员会复核面试证据并决定推进Offer。",decision_reference:`HUMAN-DECISION-${Date.now()}`}),"人工终审已决定推进")}>人工推进</Button><Button size="sm" variant="outline" data-recruiting-decision-reject onClick={()=>void execute(()=>decideRecruitingApplication(projectId,app.id,{expected_revision:app.revision,decision:"reject",decision_reason:"人类委员会复核证据后决定本轮不推进。",decision_reference:`HUMAN-DECISION-${Date.now()}`}),"人工终审已决定不推进")}>人工淘汰</Button></>:null}</div>}/>})}{workspace.assessments.map(item=><div key={item.id} className="rounded border p-3 text-sm" data-recruiting-assessment><b>{item.assessment_number} · 综合 {item.overall_score}</b><p>技能 {item.skills_score} / 证据 {item.evidence_score} / 沟通 {item.communication_score} / 诚信 {item.integrity_score}</p><p className="text-xs">AI辅助：{item.ai_assisted?"是":"否"} · AI自主决定：{item.ai_autonomous_decision?"是（违规）":"否"}</p></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">Offer与HR入职交接</CardTitle></CardHeader><CardContent className="space-y-3">{workspace.applications.filter(x=>x.current_stage==="offer"&&!workspace.offers.some(o=>o.application_id===x.id)).map(item=><Button key={item.id} data-recruiting-offer-create onClick={()=>void createOffer(item.id)}><FileCheck2 className="mr-1 h-4 w-4"/>为 {item.application_number} 建立Offer</Button>)}{workspace.offers.map(item=><Row key={item.id} title={`${item.offer_number} · ${item.compensation_band}`} status={item.status} detail={`${item.proposed_start_date} · ${item.offer_reference}`} data="offer" action={<div className="flex flex-wrap gap-2">{item.status==="draft"?<Button size="sm" data-recruiting-offer-approve onClick={()=>void execute(()=>approveRecruitingOffer(projectId,item.id,rev(item)),"Offer已独立审批")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批</Button>:null}{item.status==="approved"?<Button size="sm" data-recruiting-offer-send onClick={()=>void execute(()=>sendRecruitingOffer(projectId,item.id,rev(item)),"Offer已留证发送")}><Send className="mr-1 h-4 w-4"/>发送Offer</Button>:null}{item.status==="sent"?<Button size="sm" data-recruiting-offer-accept onClick={()=>void execute(()=>respondRecruitingOffer(projectId,item.id,{expected_revision:item.revision,response:"accepted",response_reference:`CANDIDATE-ACCEPT-${Date.now()}`}),"候选人接受Offer，HR交接已就绪")}>登记接受</Button>:null}</div>}/>)}{workspace.onboarding_handoffs.map(item=><Row key={item.id} title={`${item.handoff_number} · ${item.offer_number}`} status={item.status} detail={`${item.position_number} · ${item.source_reference} · 员工 ${item.consumed_employee_id??"待建立"}`} data="handoff"/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge>候选人同意：强制</Badge><Badge>营销联系人导入：禁止</Badge><Badge>简历正文：不保存</Badge><Badge>结构量表：强制</Badge><Badge>AI自主决定：禁止</Badge><Badge>人类终审：强制</Badge><Badge>审计证据：{workspace.evidence.length}条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action,data}:{title:string;status:string;detail:string;action?:ReactNode;data:string}){return <div className="rounded-lg border p-3" data-recruiting-record={data} data-recruiting-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{LABEL[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
