import {useEffect,useState,type ReactNode} from "react";
import {BadgeCheck,Boxes,RefreshCw,Send,ShieldCheck,Store} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {acknowledgeChannelPublication,addChannelListing,approveChannelAccount,createChannelAccount,createChannelCatalog,listChannelWorkspace,publishChannelCatalog,runChannelFeed,validateChannelListing,type ChannelWorkspace} from "@/lib/factory-channel-feed-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:ChannelWorkspace={catalogs:[],accounts:[],listings:[],runs:[],releases:[],publications:[],evidence:[],source_releases:[],metrics:{approved_channels:0,channel_coverage_percent:0,validated_listings:0,listing_validation_percent:0,passed_feed_runs:0,publication_acknowledgement_percent:0},contract:{}};
const CHANNELS=[{platform:"google-merchant",label:"Google商品"},{platform:"amazon",label:"Amazon"},{platform:"alibaba",label:"阿里国际"},{platform:"industry-marketplace",label:"行业平台"}] as const;
const STATUS:Record<string,string>={draft:"草稿",pending:"待确认",approved:"已批准",validated:"已验证",passed:"已通过",published:"已发布",acknowledged:"已确认"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});
export default function FactoryChannelFeed(){
 const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
 const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listChannelWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"商品Feed加载失败")}};useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const execute=async(op:()=>Promise<unknown>,message:string)=>{try{await op();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"商品Feed操作失败");await load(true)}};
 const catalog=workspace.catalogs[0];const accounts=workspace.accounts;const listings=catalog?workspace.listings.filter(x=>x.catalog_id===catalog.id):[];const runs=catalog?workspace.runs.filter(x=>x.catalog_id===catalog.id):[];const passed=runs.find(x=>x.status==="passed");const source=workspace.source_releases[0];const product=source?.products[0];
 const createAccounts=async()=>{for(const spec of CHANNELS){if(accounts.some(x=>x.platform===spec.platform))continue;await createChannelAccount(projectId,{platform:spec.platform,account_reference:`${spec.platform.toUpperCase()}-${Date.now()}`,credential_reference:`vault://factory-channel/${spec.platform}/primary`,territory:"GLOBAL",locale:"en-US",currency:"USD"})}};
 const approveAccounts=async()=>{for(const item of accounts.filter(x=>x.status==="pending"))await approveChannelAccount(projectId,item.id,ref(item.revision,"CHANNEL-SECURITY-APPROVAL"))};
 const createListings=async()=>{if(!catalog||!product)return;for(const account of accounts.filter(x=>x.status==="approved")){if(listings.some(x=>x.account_id===account.id))continue;await addChannelListing(projectId,catalog.id,{account_id:account.id,external_sku:`ROBOT-${account.platform.toUpperCase()}`,product_identifier:product.identifier,price_mode:"catalog-only",price_amount:null,currency:null,price_reference:null,inventory_mode:"on-request",availability_status:"on_request",inventory_reference:null,channel_attributes:{category:"industrial-automation",condition:"new"}})}};
 const validateListings=async()=>{for(const item of listings.filter(x=>x.status==="pending"))await validateChannelListing(projectId,item.id,ref(item.revision,"CHANNEL-LISTING-VALIDATE"))};
 const acknowledgeAll=async()=>{for(const item of workspace.publications.filter(x=>x.status==="pending"))await acknowledgeChannelPublication(projectId,item.id,ref(item.revision,"CHANNEL-CONSUMER-ACK"))};
 return <FactoryPage pageId="client-channel-feed" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-channel-feed-page data-channel-feed-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Store className="h-5 w-5"/>商品Feed与平台刊登</h1><p className="mt-1 text-sm opacity-70">将不可变产品JSON-LD投影到搜索、商城和行业平台；渠道只保存凭证引用，价格库存无权威来源时默认询价，不制造虚假事实。</p></div><div className="flex gap-2"><Input aria-label="商品Feed项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入Feed</Button></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="批准渠道" value={workspace.metrics.approved_channels}/><Metric label="渠道覆盖率" value={`${workspace.metrics.channel_coverage_percent}%`}/><Metric label="有效刊登" value={workspace.metrics.validated_listings}/><Metric label="刊登通过率" value={`${workspace.metrics.listing_validation_percent}%`}/><Metric label="通过Feed" value={workspace.metrics.passed_feed_runs}/><Metric label="渠道确认" value={`${workspace.metrics.publication_acknowledgement_percent}%`}/></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Store className="h-4 w-4"/>渠道账户与安全授权</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={CHANNELS.every(spec=>accounts.some(x=>x.platform===spec.platform))} data-channel-accounts-create onClick={()=>void execute(createAccounts,"四类渠道账户引用已建立")}>建立四类渠道</Button><Button disabled={!accounts.some(x=>x.status==="pending")} data-channel-accounts-approve onClick={()=>void execute(approveAccounts,"渠道账户已由独立角色批准")}>独立批准渠道</Button></div><div className="grid gap-2 md:grid-cols-2">{accounts.map(item=><Row key={item.id} title={`${item.platform} · ${item.account_reference}`} status={item.status} detail={`${item.territory}/${item.locale}/${item.currency} · ${item.credential_reference}`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Boxes className="h-4 w-4"/>商品来源与渠道刊登</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!catalog||!source} data-channel-catalog-create onClick={()=>void execute(()=>createChannelCatalog(projectId,{catalog_code:`GLOBAL-FEED-${Date.now()}`,catalog_name:"全球多渠道商品目录",source_release_id:source.id,default_locale:"en-US"}),"商品目录已固定结构化数据版本")}>建立商品目录</Button><Button disabled={!catalog||catalog.status!=="draft"||!product||!accounts.some(x=>x.status==="approved")||accounts.filter(x=>x.status==="approved").every(x=>listings.some(y=>y.account_id===x.id))} data-channel-listings-create onClick={()=>void execute(createListings,"各渠道商品刊登已建立")}>生成渠道刊登</Button><Button disabled={!listings.some(x=>x.status==="pending")} data-channel-listings-validate onClick={()=>void execute(validateListings,"刊登已独立验证")}>独立验证刊登</Button></div>{workspace.catalogs.map(item=><Row key={item.id} title={`${item.catalog_number} · ${item.catalog_name}`} status={item.status} detail={`${item.source_release_number}@v${item.source_release_version} · ${item.source_document_hash.slice(0,16)}…`}/>)}<div className="grid gap-2 md:grid-cols-2">{listings.map(item=><Row key={item.id} title={`${item.external_sku} · ${item.product_name}`} status={item.status} detail={`${item.account_number} · ${item.price_mode}/${item.availability_status} · ${item.source_product_hash.slice(0,12)}…`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>Feed校验、不可变发布与渠道回执</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!catalog||catalog.status!=="draft"||workspace.metrics.listing_validation_percent<100||!listings.length} data-channel-feed-run onClick={()=>void execute(()=>runChannelFeed(projectId,catalog.id,{expected_revision:catalog.revision,reference:`MULTI-CHANNEL-FEED-VALIDATOR-${Date.now()}`}),"多渠道Feed校验通过")}>运行Feed校验</Button><Button disabled={!catalog||catalog.status!=="draft"||!passed} data-channel-feed-publish onClick={()=>void execute(()=>publishChannelCatalog(projectId,catalog.id,{expected_revision:catalog.revision,run_id:passed!.id,remote_reference_prefix:`CHANNEL-DEPLOY-${Date.now()}`}),"不可变Feed已独立发布")}>独立发布Feed</Button><Button disabled={!workspace.publications.some(x=>x.status==="pending")} data-channel-publications-ack onClick={()=>void execute(acknowledgeAll,"全部渠道已确认精确Feed哈希")}>渠道批量确认</Button></div>{runs.map(item=><Row key={item.id} title={`${item.run_number} · ${item.listing_count}条刊登`} status={item.status} detail={`错误 ${item.error_count} · 警告 ${item.warning_count} · ${item.payload_hash.slice(0,16)}…`}/>)}{workspace.releases.map(item=><Row key={item.id} title={`${item.release_number} · Feed v${item.version_number}`} status={item.status} detail={`${item.channel_count}渠道/${item.listing_count}刊登 · ${item.payload_hash.slice(0,16)}…`}/>)}{workspace.publications.map(item=><Row key={item.id} title={`${item.publication_number} · ${item.account_number}`} status={item.status} detail={`消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.remote_reference}`}/>)}</CardContent></Card>
  <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>不保存渠道密钥</Badge><Badge>产品主数据不复制</Badge><Badge>结构化版本与商品哈希固定</Badge><Badge>无来源价格库存禁止刊登</Badge><Badge>刊登异人验证</Badge><Badge>失败Feed禁止发布</Badge><Badge>不直接改写渠道</Badge><Badge>证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
 </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-channel-record data-channel-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge><BadgeCheck className="mr-1 h-3 w-3"/>{STATUS[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
