import {useEffect,useMemo,useState,type ReactNode} from "react";
import {BadgeCheck,Boxes,GitBranch,Network,RefreshCw,Send,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {acknowledgeKnowledgePublication,addKnowledgeEntity,addKnowledgeRelation,createKnowledgeGraph,listKnowledgeWorkspace,publishKnowledgeGraph,verifyKnowledgeEntity,verifyKnowledgeRelation,type KnowledgeEntity,type KnowledgeWorkspace} from "@/lib/factory-knowledge-graph-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:KnowledgeWorkspace={graphs:[],entities:[],relations:[],versions:[],publications:[],evidence:[],source_candidates:[],metrics:{verified_entities:0,entity_type_completeness_percent:0,verified_relations:0,relation_verification_percent:0,published_graph_versions:0,publication_acknowledgement_percent:0},contract:{}};
const TYPES=[{key:"organization",label:"企业主体",props:{role:"manufacturer"}},{key:"product",label:"产品实体",props:{offering:"robot-cell"}},{key:"capability",label:"制造能力",props:{capability:"flexible-assembly"}},{key:"certificate",label:"证书实体",props:{assurance:"verified"}},{key:"case",label:"案例实体",props:{proof:"authorized-content"}},{key:"market",label:"市场实体",props:{segment:"evidence-backed-ICP"}}] as const;
const STATUS:Record<string,string>={draft:"草稿",pending:"待验证",verified:"已验证",published:"已发布",acknowledged:"已确认"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});
export default function FactoryKnowledgeGraph(){
  const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listKnowledgeWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"知识图谱加载失败")}};
  useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(op:()=>Promise<unknown>,message:string)=>{try{await op();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"知识图谱操作失败");await load(true)}};
  const graph=workspace.graphs[0];
  const entities=useMemo(()=>graph?workspace.entities.filter(x=>x.graph_id===graph.id):[],[graph,workspace.entities]);
  const relations=useMemo(()=>graph?workspace.relations.filter(x=>x.graph_id===graph.id):[],[graph,workspace.relations]);
  const byType=useMemo(()=>new Map(entities.map(x=>[x.entity_type,x])),[entities]);
  const addSix=async()=>{if(!graph)return;for(const spec of TYPES){if(byType.has(spec.key))continue;const source=workspace.source_candidates.find(x=>x.allowed_entity_types.includes(spec.key));if(!source)throw new Error(`缺少可用于“${spec.label}”的已发布权威来源`);await addKnowledgeEntity(projectId,graph.id,{entity_key:`${spec.key}-${source.source_number}`,entity_type:spec.key,canonical_name:source.suggested_name,aliases:[],properties:spec.props,locale:"en-US",source_type:source.source_type,source_id:source.source_id,evidence_reference:`SOURCE-PIN-${spec.key}-${Date.now()}`})}};
  const verifyPending=async()=>{for(const item of entities.filter(x=>x.status==="pending"))await verifyKnowledgeEntity(projectId,item.id,ref(item.revision,"ENTITY-VERIFY"))};
  const relationSpecs=()=>{const get=(type:string)=>byType.get(type);return [[get("organization"),"offers",get("product")],[get("product"),"has-capability",get("capability")],[get("product"),"certified-by",get("certificate")],[get("product"),"proven-by",get("case")],[get("market"),"demands",get("product")]] as Array<[KnowledgeEntity|undefined,string,KnowledgeEntity|undefined]>};
  const addFive=async()=>{if(!graph)return;for(const [subject,predicate,object] of relationSpecs()){if(!subject||!object)throw new Error("六类实体尚未完整验证");if(relations.some(x=>x.subject_entity_id===subject.id&&x.predicate===predicate&&x.object_entity_id===object.id))continue;await addKnowledgeRelation(projectId,graph.id,{subject_entity_id:subject.id,predicate,object_entity_id:object.id,evidence_reference:`RELATION-EVIDENCE-${predicate}-${Date.now()}`})}};
  const verifyRelations=async()=>{for(const item of relations.filter(x=>x.status==="pending"))await verifyKnowledgeRelation(projectId,item.id,ref(item.revision,"RELATION-VERIFY"))};
  return <FactoryPage pageId="client-knowledge-graph" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-knowledge-graph-page data-knowledge-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Network className="h-5 w-5"/>企业知识图谱</h1><p className="mt-1 text-sm opacity-70">连接企业、产品、能力、证书、案例和市场；每个实体与关系固定权威来源，异人验证后发布不可变图谱清单。</p></div><div className="flex gap-2"><Input aria-label="知识图谱项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入图谱</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="已验证实体" value={workspace.metrics.verified_entities}/><Metric label="类型完整度" value={`${workspace.metrics.entity_type_completeness_percent}%`}/><Metric label="已验证关系" value={workspace.metrics.verified_relations}/><Metric label="关系验证率" value={`${workspace.metrics.relation_verification_percent}%`}/><Metric label="发布版本" value={workspace.metrics.published_graph_versions}/><Metric label="下游确认" value={`${workspace.metrics.publication_acknowledgement_percent}%`}/></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Boxes className="h-4 w-4"/>图谱身份与六类权威实体</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!graph} data-knowledge-graph-create onClick={()=>void execute(()=>createKnowledgeGraph(projectId,{graph_code:`ENTERPRISE-${Date.now()}`,graph_name:"全球企业事实图谱",scope:"enterprise",default_locale:"zh-CN",objective:"向GEO、结构化数据和AI检索发布可追溯的企业、产品、能力、证书、案例和市场事实。"}),"企业知识图谱草稿已建立")}>建立企业图谱</Button><Button disabled={!graph||graph.status!=="draft"||TYPES.every(x=>byType.has(x.key))} data-knowledge-entities-ingest onClick={()=>void execute(addSix,"六类实体已按权威来源固定")}>引入六类权威实体</Button><Button disabled={!entities.some(x=>x.status==="pending")} data-knowledge-entities-verify onClick={()=>void execute(verifyPending,"待审实体已由异人验证")}>独立验证实体</Button></div>{workspace.graphs.map(item=><Row key={item.id} title={`${item.graph_number} · ${item.graph_name}`} status={item.status} detail={`${item.scope} · ${item.default_locale} · 当前v${item.current_version}`}/>)}<div className="grid gap-2 md:grid-cols-2">{entities.map(item=><Row key={item.id} title={`${item.entity_type} · ${item.canonical_name}`} status={item.status} detail={`${item.source_type}/${item.source_number}@r${item.source_revision} · ${item.source_fingerprint.slice(0,12)}…`}/>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GitBranch className="h-4 w-4"/>证据关系与异人验证</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!graph||workspace.metrics.entity_type_completeness_percent<100||relations.length>=5} data-knowledge-relations-create onClick={()=>void execute(addFive,"五条核心业务关系已建立")}>生成五条证据关系</Button><Button disabled={!relations.some(x=>x.status==="pending")} data-knowledge-relations-verify onClick={()=>void execute(verifyRelations,"关系与两端来源已由异人验证")}>独立验证关系</Button></div>{relations.map(item=><Row key={item.id} title={`${item.subject_entity_number} → ${item.predicate} → ${item.object_entity_number}`} status={item.status} detail={item.evidence_reference}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>不可变版本与下游确认</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!graph||graph.status!=="draft"||workspace.metrics.entity_type_completeness_percent<100||workspace.metrics.verified_relations<5} data-knowledge-graph-publish onClick={()=>void execute(()=>publishKnowledgeGraph(projectId,graph.id,{expected_revision:graph.revision,consumer:"geo",delivery_reference:`GEO-GRAPH-PAYLOAD-${Date.now()}`}),"图谱清单已独立发布，未直接改写GEO")}>独立发布到GEO契约</Button>{workspace.versions.map(item=><Row key={item.id} title={`${item.version_reference} · 图谱v${item.version_number}`} status={item.status} detail={`六类 ${item.entity_type_coverage_json.join("/")} · 清单 ${item.manifest_hash.slice(0,16)}…`}/>)}{workspace.publications.map(item=><Row key={item.id} title={`${item.publication_number} · ${item.consumer}`} status={item.status} detail={`图谱v${item.version_number} · 消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.manifest_hash.slice(0,16)}…`} action={item.status==="pending"?<Button size="sm" data-knowledge-publication-ack onClick={()=>void execute(()=>acknowledgeKnowledgePublication(projectId,item.id,ref(item.revision,"GEO-CONSUMER-ACK")),"下游已确认接收精确图谱清单")}>下游确认接收</Button>:null}/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>主数据不复制</Badge><Badge>来源修订与指纹固定</Badge><Badge>未验证事实禁止发布</Badge><Badge>关系异人验证</Badge><Badge>作者不能自发布</Badge><Badge>已发布版本不可改</Badge><Badge>不直接改写下游</Badge><Badge>证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
  </div></main></FactoryPage>
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-knowledge-record data-knowledge-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{STATUS[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
