import { useEffect, useMemo, useState, type ReactNode } from "react";
import { CheckCheck, Clock3, FileCheck2, GitBranch, RefreshCw, ShieldCheck, Smartphone, UserRoundCog } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FactoryPage } from "@/page-factory/FactoryPage";
import { acknowledgeApprovalHandoff, approveApprovalWorkflow, createApprovalDelegation, createApprovalRequest, createApprovalWorkflow, listApprovalWorkspace, reviewApprovalRequest, type ApprovalWorkspace } from "@/lib/factory-approval-api";

const EMPTY:ApprovalWorkspace={workflows:[],workflow_versions:[],requests:[],steps:[],actions:[],delegations:[],handoffs:[],eligible_sources:[],evidence:[],metrics:{active_workflows:0,pending_requests:0,median_approval_hours:0,overdue_rate_percent:0},contract:{domain_records_remain_authoritative:true,source_revision_pinned:true,requester_self_approval:false,ordered_steps:true,delegation_expands_permission:false,mobile_approval_lowers_assurance:false,final_approval_mutates_domain_record:false,domain_handoff_acknowledgement_required:true,supported_subject_types:[]}};
const SUBJECT:Record<string,string>={"cpq-quote":"报价单","purchase-order":"采购单","finance-document":"财务单据","people-contract":"员工合同","recruiting-offer":"招聘Offer","erp-posting":"ERP过账"};
const STATUS:Record<string,string>={draft:"草稿",active:"已启用","in-review":"审批中",approved:"已通过",rejected:"已拒绝",returned:"已退回",pending:"待审批",ready:"待业务确认",acknowledged:"业务已确认"};
const revision=(item:{revision:number})=>({expected_revision:item.revision,evidence_reference:`APPROVAL-EVIDENCE-${Date.now()}`});

export default function FactoryApprovalCenter(){
  const [projectText,setProjectText]=useState("1");const projectId=Number(projectText);const [mode,setMode]=useState<"loading"|"live"|"error">("loading");const [workspace,setWorkspace]=useState(EMPTY);
  const [subjectType,setSubjectType]=useState("cpq-quote");const [workflowName,setWorkflowName]=useState("高价值业务审批");const [firstApprover,setFirstApprover]=useState("commercial-approver");const [secondApprover,setSecondApprover]=useState("finance-approver");
  const [delegateFrom,setDelegateFrom]=useState("commercial-approver");const [delegateTo,setDelegateTo]=useState("commercial-delegate");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listApprovalWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"审批中心加载失败")}};
  useEffect(()=>{void load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"审批治理操作失败");await load(true)}};
  const activeWorkflows=workspace.workflows.filter(x=>x.status==="active");
  const source=workspace.eligible_sources.find(x=>activeWorkflows.some(w=>w.subject_type===x.subject_type));
  const sourceWorkflow=source?activeWorkflows.find(x=>x.subject_type===source.subject_type):undefined;
  const pending=workspace.requests.filter(x=>x.status==="in-review");
  const currentSteps=useMemo(()=>new Map(pending.map(request=>[request.id,workspace.steps.find(step=>step.request_id===request.id&&step.sequence===request.current_sequence)])),[pending,workspace.steps]);
  const createWorkflow=()=>execute(()=>createApprovalWorkflow(projectId,{workflow_code:`${subjectType.toUpperCase()}-${Date.now()}`,workflow_name:workflowName,subject_type:subjectType,steps:[{name:"业务负责人复核",assignee_reference:firstApprover,due_hours:8},{name:"独立终审",assignee_reference:secondApprover,due_hours:20}],sla_hours:24,allow_delegation:true}),"审批流程草稿已建立");
  const submit=()=>source&&sourceWorkflow&&execute(()=>createApprovalRequest(projectId,{workflow_id:sourceWorkflow.id,subject_id:source.id,subject_revision:source.revision,request_reference:`REQUEST-${Date.now()}`,business_reason:"业务单据达到治理阈值，需要按固定顺序完成独立审批。",evidence_reference:`SOURCE-PACK-${Date.now()}`}),"业务审批请求已提交");
  const delegation=()=>{const now=new Date();const end=new Date(now.getTime()+8*3600*1000);return execute(()=>createApprovalDelegation(projectId,{workflow_id:null,subject_type:null,delegator_reference:delegateFrom,delegate_reference:delegateTo,starts_at:now.toISOString(),ends_at:end.toISOString(),reason:"审批人在受控时间窗口内不可用，启用有限授权代理。",evidence_reference:`DELEGATION-${Date.now()}`}),"限时代理授权已登记")};
  return <FactoryPage pageId="client-approval-center" template="dashboard" sourceScope="client_source"><main data-page-factory-region="content" className="p-4 md:p-6" data-factory-approval-page data-approval-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div data-page-factory-region="title-2" className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><GitBranch className="h-5 w-5"/>审批中心</h1><p className="mt-1 text-sm opacity-70">统一编排报价、采购、财务、人事、招聘与ERP审批；固定来源版本、禁止自审，最终通过只交接业务系统确认。</p></div><div className="flex gap-2"><Input aria-label="审批项目ID" className="w-24" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入审批</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="启用流程" value={workspace.metrics.active_workflows}/><Metric label="待办审批" value={workspace.metrics.pending_requests}/><Metric label="审批中位时长" value={`${workspace.metrics.median_approval_hours}h`}/><Metric label="超时率" value={`${workspace.metrics.overdue_rate_percent}%`}/></div>
    <Card data-page-factory-region="large-card"><CardHeader><CardTitle className="text-base">流程设计与独立启用</CardTitle></CardHeader><CardContent data-page-factory-region="small-card" className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><Select value={subjectType} onValueChange={setSubjectType}><SelectTrigger aria-label="审批对象"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(SUBJECT).map(([key,label])=><SelectItem key={key} value={key}>{label}</SelectItem>)}</SelectContent></Select><Input aria-label="流程名称" value={workflowName} onChange={e=>setWorkflowName(e.target.value)}/><Button data-approval-workflow-create onClick={()=>void createWorkflow()}><FileCheck2 className="mr-1 h-4 w-4"/>建立两级流程</Button><Input aria-label="一级审批人" value={firstApprover} onChange={e=>setFirstApprover(e.target.value)}/><Input aria-label="二级审批人" value={secondApprover} onChange={e=>setSecondApprover(e.target.value)}/></div>{workspace.workflows.map(item=><Row key={item.id} title={`${item.workflow_number} · ${item.workflow_name}`} status={item.status} detail={`${SUBJECT[item.subject_type]??item.subject_type} · 版本 ${item.current_version} · 作者 ${item.authored_by}`} data="workflow" action={item.status==="draft"?<Button size="sm" data-approval-workflow-approve onClick={()=>void execute(()=>approveApprovalWorkflow(projectId,item.id,revision(item)),"审批流程已由独立治理人启用")}><ShieldCheck className="mr-1 h-4 w-4"/>独立启用</Button>:null}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">业务来源与审批待办</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap items-center gap-2"><Button disabled={!source||!sourceWorkflow} data-approval-request-create onClick={()=>void submit()}><Clock3 className="mr-1 h-4 w-4"/>提交首个可审批单据</Button><span className="text-xs opacity-70">{source?`${SUBJECT[source.subject_type]} ${source.number} · 来源版本 ${source.revision}`:"暂无与已启用流程匹配的待审批业务单据"}</span></div>{workspace.requests.map(item=>{const step=currentSteps.get(item.id);return <Row key={item.id} title={`${item.request_number} · ${item.subject_number}`} status={item.status} detail={`${SUBJECT[item.subject_type]??item.subject_type} · 固定版本 ${item.subject_revision} · 当前第 ${item.current_sequence} 级${step?` · ${step.step_name} / ${step.assignee_reference}`:""}`} data="request" action={item.status==="in-review"?<div className="flex flex-wrap gap-2"><Button size="sm" data-approval-request-approve onClick={()=>void execute(()=>reviewApprovalRequest(projectId,item.id,{expected_revision:item.revision,decision:"approve",reason:"审批人已复核来源版本、业务原因和证据，确认通过。",evidence_reference:`REVIEW-${Date.now()}`,channel:"web"}),"当前审批步骤已通过")}><CheckCheck className="mr-1 h-4 w-4"/>通过当前级</Button><Button size="sm" variant="outline" data-approval-request-return onClick={()=>void execute(()=>reviewApprovalRequest(projectId,item.id,{expected_revision:item.revision,decision:"return",reason:"现有证据不足，需要补充业务依据后重新提交。",evidence_reference:`RETURN-${Date.now()}`,channel:"web"}),"审批已退回补充")}>退回补充</Button></div>:null}/>})}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">限时代理与业务交接</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><Input aria-label="原审批人" value={delegateFrom} onChange={e=>setDelegateFrom(e.target.value)}/><Input aria-label="代理审批人" value={delegateTo} onChange={e=>setDelegateTo(e.target.value)}/><Button data-approval-delegation-create onClick={()=>void delegation()}><UserRoundCog className="mr-1 h-4 w-4"/>登记8小时代理</Button></div>{workspace.delegations.map(item=><Row key={item.id} title={`${item.delegation_number} · ${item.delegator_reference} → ${item.delegate_reference}`} status={item.status} detail={`${new Date(item.starts_at).toLocaleString()} 至 ${new Date(item.ends_at).toLocaleString()} · 权限不扩张`} data="delegation"/>)}{workspace.handoffs.map(item=><Row key={item.id} title={`${item.handoff_number} · ${item.subject_number}`} status={item.status} detail={`${SUBJECT[item.subject_type]??item.subject_type} · 来源仍保持版本 ${item.subject_revision}`} data="handoff" action={item.status==="ready"?<Button size="sm" data-approval-handoff-acknowledge onClick={()=>void execute(()=>acknowledgeApprovalHandoff(projectId,item.id,revision(item)),"业务系统已确认收到审批结果")}><Smartphone className="mr-1 h-4 w-4"/>业务确认接收</Button>:null}/>)}</CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge>来源版本固定</Badge><Badge>发起人自审：禁止</Badge><Badge>审批顺序：强制</Badge><Badge>移动端权限降级：禁止</Badge><Badge>审批直接改业务数据：禁止</Badge><Badge>业务确认交接：强制</Badge><Badge>审计证据：{workspace.evidence.length}条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action,data}:{title:string;status:string;detail:string;action?:ReactNode;data:string}){return <div className="rounded-lg border p-3" data-approval-record={data} data-approval-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{STATUS[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
