import {useEffect,useMemo,useState,type ReactNode} from "react";
import {BadgeCheck,Building2,GitBranch,Network,RefreshCw,Send,ShieldCheck} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";import {Button} from "@/components/ui/button";import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";import {Input} from "@/components/ui/input";
import {acknowledgeAccountGraphPublication,addAccountGraphEdge,addAccountGraphNode,createAccountGraph,listAccountGraphWorkspace,publishAccountGraph,verifyAccountGraphEdge,verifyAccountGraphNode,type AccountGraphNode,type AccountGraphWorkspace} from "@/lib/factory-account-graph-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:AccountGraphWorkspace={graphs:[],nodes:[],edges:[],versions:[],publications:[],evidence:[],sources:[],metrics:{verified_nodes:0,source_type_coverage_percent:0,verified_edges:0,relation_verification_percent:0,published_versions:0,handoff_acknowledgement_percent:0},contract:{}};
const STATUS:Record<string,string>={draft:"草稿",pending:"待核验",verified:"已核验",published:"已发布",acknowledged:"已回执"};const NODE_LABEL:Record<string,string>={enterprise:"法务主体",account:"黄金账户",contact:"同意联系人",opportunity:"商机报价",order:"履约订单"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});
export default function FactoryAccountGraph(){
 const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
 const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listAccountGraphWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"企业关系图加载失败")}};useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const execute=async(op:()=>Promise<unknown>,message:string)=>{try{await op();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"企业关系操作失败");await load(true)}};
 const graph=workspace.graphs[0];const nodes=useMemo(()=>graph?workspace.nodes.filter(x=>x.graph_id===graph.id):[],[graph,workspace.nodes]);const edges=useMemo(()=>graph?workspace.edges.filter(x=>x.graph_id===graph.id):[],[graph,workspace.edges]);
 const addSources=async()=>{if(!graph)return;for(const source of workspace.sources){if(nodes.some(x=>x.source_type===source.source_type&&x.source_id===source.source_id))continue;await addAccountGraphNode(projectId,graph.id,{source_type:source.source_type,source_id:source.source_id})}};
 const verifyNodes=async()=>{for(const item of nodes.filter(x=>x.status==="pending"))await verifyAccountGraphNode(projectId,item.id,ref(item.revision,"ACCOUNT-NODE-VERIFY"))};
 const createEdges=async()=>{if(!graph)return;const verified=nodes.filter(x=>x.status==="verified");const candidates:Array<{left:AccountGraphNode;right:AccountGraphNode;relation:string}>=[];for(const left of verified)for(const right of verified){if(left.id===right.id)continue;if(left.node_type==="enterprise"&&right.node_type==="opportunity"&&left.account_reference===right.account_reference)candidates.push({left,right,relation:"has-opportunity"});if(left.node_type==="account"&&right.node_type==="contact"&&left.account_reference===right.account_reference)candidates.push({left,right,relation:"contact-at"});if(left.node_type==="opportunity"&&right.node_type==="order"&&left.account_reference===right.account_reference&&workspace.sources.find(x=>x.source_id===right.source_id)?.related_source_id===left.source_id)candidates.push({left,right,relation:"fulfills"})}for(const item of candidates){if(edges.some(x=>x.from_node_id===item.left.id&&x.to_node_id===item.right.id&&x.relation_type===item.relation))continue;await addAccountGraphEdge(projectId,graph.id,{from_node_id:item.left.id,to_node_id:item.right.id,relation_type:item.relation,strength:"strong",evidence_reference:`ACCOUNT-RELATION-${item.relation}-${Date.now()}`})}};
 const verifyEdges=async()=>{for(const item of edges.filter(x=>x.status==="pending"))await verifyAccountGraphEdge(projectId,item.id,ref(item.revision,"ACCOUNT-RELATION-VERIFY"))};const acknowledgeAll=async()=>{for(const item of workspace.publications.filter(x=>x.status==="pending"))await acknowledgeAccountGraphPublication(projectId,item.id,ref(item.revision,"ACCOUNT-GRAPH-CONSUMER-ACK"))};
 return <FactoryPage pageId="client-account-graph" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-account-graph-page data-account-graph-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Network className="h-5 w-5"/>B2B企业关系图谱</h1><p className="mt-1 text-sm opacity-70">把法务主体、黄金账户、已同意联系人、CPQ商机和履约订单连接为可审计关系；节点固定权威来源，关系异人核验，发布不改写CRM/CDP。</p></div><div className="flex gap-2"><Input aria-label="企业关系项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入关系图</Button></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="核验节点" value={workspace.metrics.verified_nodes}/><Metric label="来源覆盖" value={`${workspace.metrics.source_type_coverage_percent}%`}/><Metric label="核验关系" value={workspace.metrics.verified_edges}/><Metric label="关系通过率" value={`${workspace.metrics.relation_verification_percent}%`}/><Metric label="发布版本" value={workspace.metrics.published_versions}/><Metric label="下游回执" value={`${workspace.metrics.handoff_acknowledgement_percent}%`}/></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Building2 className="h-4 w-4"/>权威节点与来源固定</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!graph} data-account-graph-create onClick={()=>void execute(()=>createAccountGraph(projectId,{graph_code:`ACCOUNT-360-${Date.now()}`,graph_name:"全球B2B企业关系图",scope:"account-360"}),"企业关系图草稿已建立")}>建立关系图</Button><Button disabled={!graph||graph.status!=="draft"||workspace.sources.every(s=>nodes.some(n=>n.source_type===s.source_type&&n.source_id===s.source_id))} data-account-nodes-ingest onClick={()=>void execute(addSources,"权威来源节点已固定")}>导入权威节点</Button><Button disabled={!nodes.some(x=>x.status==="pending")} data-account-nodes-verify onClick={()=>void execute(verifyNodes,"节点已由独立角色核验")}>独立核验节点</Button></div>{workspace.graphs.map(item=><Row key={item.id} title={`${item.graph_number} · ${item.graph_name}`} status={item.status} detail={`${item.scope} · 修订${item.revision}`}/>) }<div className="grid gap-2 md:grid-cols-2">{nodes.map(item=><Row key={item.id} title={`${NODE_LABEL[item.node_type]??item.node_type} · ${item.display_name}`} status={item.status} detail={`${item.source_type}/${item.source_number}@v${item.source_revision} · ${item.source_fingerprint.slice(0,14)}…`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GitBranch className="h-4 w-4"/>账户层级、联系人、商机与订单关系</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!graph||nodes.filter(x=>x.status==="verified").length<2||graph.status!=="draft"} data-account-edges-create onClick={()=>void execute(createEdges,"满足语义与账户一致性的关系已提交")}>生成受控关系</Button><Button disabled={!edges.some(x=>x.status==="pending")} data-account-edges-verify onClick={()=>void execute(verifyEdges,"企业关系已独立核验")}>独立核验关系</Button></div><div className="grid gap-2 md:grid-cols-2">{edges.map(item=><Row key={item.id} title={`${item.from_node_number} → ${item.relation_type} → ${item.to_node_number}`} status={item.status} detail={`${item.strength} · ${item.endpoint_manifest_hash.slice(0,16)}… · ${item.evidence_reference}`}/>)}</div></CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Send className="h-4 w-4"/>不可变版本与业务系统回执</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!graph||graph.status!=="draft"||!edges.length||workspace.metrics.relation_verification_percent<100} data-account-graph-publish onClick={()=>graph&&void execute(()=>publishAccountGraph(projectId,graph.id,{expected_revision:graph.revision,consumers:["crm","cdp","sales","service"],delivery_reference_prefix:`ACCOUNT-GRAPH-${Date.now()}`}),"不可变企业关系图已独立发布")}>独立发布关系图</Button><Button disabled={!workspace.publications.some(x=>x.status==="pending")} data-account-publications-ack onClick={()=>void execute(acknowledgeAll,"全部下游已确认关系图哈希")}>下游批量回执</Button></div>{workspace.versions.map(item=><Row key={item.id} title={`${item.version_reference} · 关系图v${item.version_number}`} status={item.status} detail={`${item.node_count}节点/${item.edge_count}关系 · ${item.manifest_hash.slice(0,20)}…`}/>) }<div className="grid gap-2 md:grid-cols-2">{workspace.publications.map(item=><Row key={item.id} title={`${item.consumer.toUpperCase()} · ${item.publication_number}`} status={item.status} detail={`消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.delivery_reference}`}/>)}</div></CardContent></Card>
  <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>不复制上游主数据</Badge><Badge>来源版本与指纹固定</Badge><Badge>节点异人核验</Badge><Badge>关系语义强校验</Badge><Badge>关系异人核验</Badge><Badge>未核验关系禁止发布</Badge><Badge>不可变版本</Badge><Badge>不直接改写CRM/CDP</Badge><Badge>证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
 </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-account-graph-record data-account-graph-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge><BadgeCheck className="mr-1 h-3 w-3"/>{STATUS[status]??status}</Badge></div><p className="mt-1 break-all text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
