import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { BriefcaseBusiness, Clock3, GraduationCap, RefreshCw, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  activatePeopleEmployee, approvePeopleContract, approvePeopleOrgUnit, approvePeopleTimeRecord,
  assignPeopleTraining, calibratePeoplePerformanceReview, completePeopleTraining, createPeopleContract,
  createPeopleEmployee, createPeopleOrgUnit, createPeoplePerformanceReview, createPeoplePosition,
  createPeopleTimeRecord, listPeopleWorkspace, submitPeopleContract, submitPeopleTimeRecord,
  verifyPeopleTraining, type PeopleWorkspace,
} from "@/lib/factory-people-api";

const EMPTY:PeopleWorkspace={org_units:[],positions:[],employees:[],contracts:[],time_records:[],performance_reviews:[],training_records:[],evidence:[],eligible_erp_units:[],metrics:{active_headcount:0,planned_headcount:0,critical_role_fill_rate:"100.00",mandatory_training_compliance:"100.00"},contract:{system_of_record:"hr-people-master",marketing_contact_import:false,customer_profile_import:false,raw_bank_tax_health_data_stored:false,payroll_amount_authority:false,employment_lifecycle_authority:true,independent_master_activation:true,independent_contract_approval:true,independent_time_approval:true,independent_performance_calibration:true,independent_training_verification:true}};
const LABEL:Record<string,string>={draft:"草稿",active:"生效",submitted:"待审批","pending-approval":"待审批",approved:"已审批",assigned:"已分配",completed:"待核验",verified:"已核验",calibrated:"已校准"};
const today=()=>new Date().toISOString().slice(0,10);
const future=(days:number)=>{const value=new Date();value.setDate(value.getDate()+days);return value.toISOString().slice(0,10);};
const rev=(item:{revision:number})=>({expected_revision:item.revision,evidence_reference:`HR-EVIDENCE-${Date.now()}`});

export default function FactoryPeople(){
  const [projectText,setProjectText]=useState("1"); const projectId=Number(projectText);
  const [mode,setMode]=useState<"loading"|"live"|"error">("loading"); const [workspace,setWorkspace]=useState<PeopleWorkspace>(EMPTY);
  const [unitCode,setUnitCode]=useState("PEOPLE-HQ"); const [unitName,setUnitName]=useState("全球人才运营中心");
  const [positionCode,setPositionCode]=useState("EXPORT-SALES"); const [positionTitle,setPositionTitle]=useState("外贸销售经理");
  const [employeeRef,setEmployeeRef]=useState("EMP-AUTO"); const [employeeName,setEmployeeName]=useState("新员工"); const [employeeEmail,setEmployeeEmail]=useState("employee-auto@factory.example");
  const [periodCode,setPeriodCode]=useState(new Date().toISOString().slice(0,7));
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listPeopleWorkspace(projectId));setMode("live");}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"HR人事中心加载失败");}};
  useEffect(()=>{void load();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true);}catch(error){toast.error(error instanceof Error?error.message:"HR治理操作失败");await load(true);}};
  const activeOrg=workspace.org_units.find(x=>x.status==="active"); const activePosition=workspace.positions.find(x=>x.status==="active"); const activeEmployee=workspace.employees.find(x=>x.status==="active");
  const createOrg=()=>execute(()=>createPeopleOrgUnit(projectId,{unit_reference:`HR-ORG-${Date.now()}`,unit_code:unitCode,unit_name:unitName,unit_type:"company",parent_unit_id:null,erp_operating_unit_id:workspace.eligible_erp_units[0]?.id??null,country_code:"CN",timezone_name:"Asia/Shanghai"}),"HR组织草稿已建立");
  const createPosition=()=>activeOrg&&execute(()=>createPeoplePosition(projectId,{org_unit_id:activeOrg.id,position_reference:`HR-POS-${Date.now()}`,position_code:positionCode,position_title:positionTitle,job_family:"Commercial",employment_level:"L5",planned_headcount:2,weekly_capacity_hours:"40",critical_role:true}),"岗位编制已建立");
  const createEmployee=()=>execute(()=>createPeopleEmployee(projectId,{employee_reference:employeeRef==="EMP-AUTO"?`EMP-${Date.now().toString().slice(-6)}`:employeeRef,preferred_name:employeeName,work_email:employeeEmail==="employee-auto@factory.example"?`employee-${Date.now().toString().slice(-6)}@factory.example`:employeeEmail,country_code:"CN",source_type:"hr-direct",source_reference:`HR-ONBOARD-${Date.now()}`,privacy_notice_reference:"PRIVACY-NOTICE-V1"}),"员工主数据草稿已建立");
  const createContract=()=>activeEmployee&&activePosition&&execute(()=>createPeopleContract(projectId,{contract_reference:`HR-CONTRACT-${Date.now()}`,employee_id:activeEmployee.id,position_id:activePosition.id,employment_type:"full-time",work_location:"Shanghai",start_date:today(),end_date:null,weekly_hours:"40",compensation_band:"CN-L5-BAND",payroll_reference:`PAYROLL-${activeEmployee.employee_number}`,signed_document_reference:`SIGNED-${Date.now()}`}),"劳动合同草稿已建立");
  const createTime=()=>activeEmployee&&execute(()=>createPeopleTimeRecord(projectId,{employee_id:activeEmployee.id,period_code:periodCode,scheduled_hours:"160",worked_hours:"160",approved_absence_hours:"0",overtime_hours:"0",source_reference:`TIMECLOCK-${periodCode}`}),"月度工时草稿已建立");
  const createReview=()=>activeEmployee&&execute(()=>createPeoplePerformanceReview(projectId,{employee_id:activeEmployee.id,cycle_code:`${new Date().getFullYear()}-H2`,goals_score:"90",competency_score:"88",evidence_reference:`OKR-${Date.now()}`,manager_comment:"基于已确认目标与经营结果形成的经理评价。"}),"绩效评价草稿已建立");
  const assignTraining=()=>activeEmployee&&execute(()=>assignPeopleTraining(projectId,{employee_id:activeEmployee.id,course_code:"EXPORT-COMPLIANCE",course_title:"出口合规必修课",mandatory:true,due_date:future(180)}),"必修培训已分配");
  return <FactoryPage pageId="client-people" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-people-page data-people-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><UsersRound className="h-5 w-5"/>HR人事中心</h1><p className="mt-1 text-sm opacity-70">以最小必要数据治理组织、岗位、员工、合同、工时、绩效与培训；不把营销联系人当员工，不保存原始银行卡、税务、健康或工资金额。</p></div><div className="flex gap-2"><Input aria-label="人事项目ID" className="w-24" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入人事</Button></div></div>

    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="在职人数" value={workspace.metrics.active_headcount}/><Metric label="规划编制" value={workspace.metrics.planned_headcount}/><Metric label="关键岗到位率" value={`${workspace.metrics.critical_role_fill_rate}%`}/><Metric label="必修合规率" value={`${workspace.metrics.mandatory_training_compliance}%`}/></div>

    <Card><CardHeader><CardTitle className="text-base">组织、岗位与员工主数据</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><Input aria-label="HR组织代码" value={unitCode} onChange={e=>setUnitCode(e.target.value)}/><Input aria-label="HR组织名称" value={unitName} onChange={e=>setUnitName(e.target.value)}/><Button data-people-org-create onClick={()=>void createOrg()}><UsersRound className="mr-1 h-4 w-4"/>建立组织草稿</Button></div>{workspace.org_units.map(item=><Row key={item.id} title={`${item.unit_number} · ${item.unit_code} · ${item.unit_name}`} status={item.status} detail={`${item.unit_type} · ${item.country_code} · ${item.timezone_name} · 修订 ${item.revision}`} data="people-org" action={item.status==="draft"?<Button size="sm" data-people-org-approve onClick={()=>void execute(()=>approvePeopleOrgUnit(projectId,item.id,rev(item)),"HR组织已独立审批启用")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批启用</Button>:null}/>)}<div className="grid gap-2 md:grid-cols-3"><Input aria-label="岗位代码" value={positionCode} onChange={e=>setPositionCode(e.target.value)}/><Input aria-label="岗位名称" value={positionTitle} onChange={e=>setPositionTitle(e.target.value)}/><Button disabled={!activeOrg} data-people-position-create onClick={()=>void createPosition()}><BriefcaseBusiness className="mr-1 h-4 w-4"/>建立岗位编制</Button></div>{workspace.positions.map(item=><Row key={item.id} title={`${item.position_number} · ${item.position_title}`} status={item.status} detail={`${item.position_code} · ${item.job_family}/${item.employment_level} · 编制 ${item.planned_headcount} · ${item.critical_role?"关键岗位":"普通岗位"}`} data="people-position"/>)}<div className="grid gap-2 md:grid-cols-4"><Input aria-label="员工编号参考" value={employeeRef} onChange={e=>setEmployeeRef(e.target.value)}/><Input aria-label="员工姓名" value={employeeName} onChange={e=>setEmployeeName(e.target.value)}/><Input aria-label="员工工作邮箱" value={employeeEmail} onChange={e=>setEmployeeEmail(e.target.value)}/><Button data-people-employee-create onClick={()=>void createEmployee()}><UserRoundCheck className="mr-1 h-4 w-4"/>建立员工草稿</Button></div>{workspace.employees.map(item=><Row key={item.id} title={`${item.employee_number} · ${item.preferred_name}`} status={item.status} detail={`${item.work_email} · ${item.source_type} · 修订 ${item.revision}`} data="people-employee" action={item.status==="draft"?<Button size="sm" data-people-employee-activate onClick={()=>void execute(()=>activatePeopleEmployee(projectId,item.id,rev(item)),"员工主数据已独立激活")}><ShieldCheck className="mr-1 h-4 w-4"/>独立核验激活</Button>:null}/>)}</CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">劳动合同与岗位任用</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!activeEmployee||!activePosition} data-people-contract-create onClick={()=>void createContract()}><BriefcaseBusiness className="mr-1 h-4 w-4"/>建立劳动合同</Button>{workspace.contracts.map(item=><Row key={item.id} title={`${item.contract_number} · ${item.employee_number}`} status={item.status} detail={`${item.position_number} · ${item.employment_type} · ${item.weekly_hours}小时/周 · ${item.compensation_band}`} data="people-contract" action={<div className="flex gap-2">{item.status==="draft"?<Button size="sm" data-people-contract-submit onClick={()=>void execute(()=>submitPeopleContract(projectId,item.id,rev(item)),"合同已提交独立审批")}>提交审批</Button>:null}{item.status==="pending-approval"?<Button size="sm" data-people-contract-approve onClick={()=>void execute(()=>approvePeopleContract(projectId,item.id,rev(item)),"劳动合同已独立审批生效")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批</Button>:null}</div>}/>)}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">工时与出勤</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input aria-label="人事工时月份" className="w-40" value={periodCode} onChange={e=>setPeriodCode(e.target.value)}/><Button disabled={!activeEmployee} data-people-time-create onClick={()=>void createTime()}><Clock3 className="mr-1 h-4 w-4"/>建立工时</Button></div>{workspace.time_records.map(item=><Row key={item.id} title={`${item.time_number} · ${item.period_code}`} status={item.status} detail={`${item.worked_hours}工时 + ${item.approved_absence_hours}请假 / ${item.scheduled_hours}计划 · 加班 ${item.overtime_hours}`} data="people-time" action={<div className="flex gap-2">{item.status==="draft"?<Button size="sm" data-people-time-submit onClick={()=>void execute(()=>submitPeopleTimeRecord(projectId,item.id,rev(item)),"工时已提交独立审批")}>提交</Button>:null}{item.status==="submitted"?<Button size="sm" data-people-time-approve onClick={()=>void execute(()=>approvePeopleTimeRecord(projectId,item.id,rev(item)),"工时已独立审批")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批</Button>:null}</div>}/>)}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-base">绩效校准</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!activeEmployee||!workspace.contracts.some(x=>x.employee_id===activeEmployee.id&&x.status==="active")} data-people-review-create onClick={()=>void createReview()}>建立绩效评价</Button>{workspace.performance_reviews.map(item=><Row key={item.id} title={`${item.review_number} · ${item.cycle_code}`} status={item.status} detail={`目标 ${item.goals_score} / 能力 ${item.competency_score} / 综合 ${item.overall_score}`} data="people-review" action={item.status==="draft"?<Button size="sm" data-people-review-calibrate onClick={()=>void execute(()=>calibratePeoplePerformanceReview(projectId,item.id,rev(item)),"绩效结果已独立校准")}><ShieldCheck className="mr-1 h-4 w-4"/>独立校准</Button>:null}/>)}</CardContent></Card></div>

    <Card><CardHeader><CardTitle className="text-base">培训、证照与合规能力</CardTitle></CardHeader><CardContent className="space-y-3"><Button disabled={!activeEmployee} data-people-training-assign onClick={()=>void assignTraining()}><GraduationCap className="mr-1 h-4 w-4"/>分配必修培训</Button>{workspace.training_records.map(item=><Row key={item.id} title={`${item.training_number} · ${item.course_title}`} status={item.status} detail={`${item.course_code} · 截止 ${item.due_date} · ${item.mandatory?"必修":"选修"}`} data="people-training" action={<div className="flex gap-2">{item.status==="assigned"?<Button size="sm" data-people-training-complete onClick={()=>void execute(()=>completePeopleTraining(projectId,item.id,{expected_revision:item.revision,completion_evidence_reference:`LMS-CERT-${Date.now()}`,expires_at:future(730)}),"培训完成证据已登记")}>登记完成</Button>:null}{item.status==="completed"?<Button size="sm" data-people-training-verify onClick={()=>void execute(()=>verifyPeopleTraining(projectId,item.id,rev(item)),"培训证据已独立核验")}><ShieldCheck className="mr-1 h-4 w-4"/>独立核验</Button>:null}</div>}/>)}</CardContent></Card>

    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge>员工主档权威：HR</Badge><Badge>营销联系人导入：禁止</Badge><Badge>客户画像导入：禁止</Badge><Badge>原始敏感财税健康数据：不保存</Badge><Badge>工资金额权威：财务/薪酬系统</Badge><Badge>审计证据：{workspace.evidence.length}条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>;}
function Row({title,status,detail,action,data}:{title:string;status:string;detail:string;action?:ReactNode;data:string}){return <div className="rounded-lg border p-3" data-people-record={data} data-people-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge>{LABEL[status]??status}</Badge></div><p className="mt-1 text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>;}
