import {useEffect,useState,type ReactNode} from "react";
import {BadgeCheck,Fingerprint,GitMerge,RefreshCw,Send,ShieldCheck,UserRoundCheck} from "lucide-react";
import {toast} from "sonner";
import {Badge} from "@/components/ui/badge";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {acknowledgeIdentityPublication,approveIdentityConsent,createGoldenProfile,createIdentityConsent,createIdentitySignal,decideIdentityMatch,listIdentityWorkspace,proposeIdentityMatch,publishGoldenProfile,verifyIdentitySignal,type IdentityWorkspace} from "@/lib/factory-identity-resolution-api";
import {FactoryPage} from "@/page-factory/FactoryPage";

const EMPTY:IdentityWorkspace={consents:[],signals:[],match_cases:[],profiles:[],versions:[],publications:[],evidence:[],metrics:{active_consents:0,verified_signals:0,identity_match_percent:0,approved_matches:0,published_profiles:0,handoff_acknowledgement_percent:0},contract:{}};
const STATUS:Record<string,string>={pending:"待处理",active:"有效",verified:"已核验",proposed:"待裁决",approved:"已批准",rejected:"已拒绝",draft:"草稿",published:"已发布",acknowledged:"已回执",revoked:"已撤回"};
const ref=(revision:number,prefix:string)=>({expected_revision:revision,reference:`${prefix}-${Date.now()}`});
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,"0")).join("")}

export default function FactoryIdentityResolution(){
 const[projectText,setProjectText]=useState("1");const projectId=Number(projectText);const[workspace,setWorkspace]=useState(EMPTY);const[mode,setMode]=useState<"loading"|"live"|"error">("loading");
 const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listIdentityWorkspace(projectId));setMode("live")}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"身份合并工作区加载失败")}};useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 const execute=async(op:()=>Promise<unknown>,message:string)=>{try{await op();toast.success(message);await load(true)}catch(error){toast.error(error instanceof Error?error.message:"身份合并操作失败");await load(true)}};
 const consent=workspace.consents[0];const signals=consent?workspace.signals.filter(x=>x.consent_id===consent.id):[];const match=workspace.match_cases[0];const profile=workspace.profiles[0];
 const createConsent=()=>createIdentityConsent(projectId,{subject_reference:`CONTACT-${Date.now()}`,account_reference:`ACCOUNT-${projectId}`,consent_reference:`CMP-CONSENT-${Date.now()}`,lawful_basis:"consent",purposes:["customer-identity","service-personalization"],expires_at:new Date(Date.now()+365*24*3600*1000).toISOString()});
 const captureSignals=async()=>{if(!consent)return;for(const spec of [{type:"account",raw:`ACCOUNT-${projectId}`,hint:"acct"},{type:"email",raw:`buyer-${projectId}@consented.example`,hint:"mail"},{type:"device",raw:`device-${projectId}-${consent.id}`,hint:"dev"}]){if(signals.some(x=>x.signal_type===spec.type))continue;await createIdentitySignal(projectId,{consent_id:consent.id,signal_type:spec.type,identifier_hash:await sha256(spec.raw),display_hint:spec.hint,source_type:"consent-event",source_reference:consent.consent_reference,source_revision:consent.revision,source_fingerprint:consent.source_event_hash})}};
 const verifySignals=async()=>{for(const item of signals.filter(x=>x.status==="pending"))await verifyIdentitySignal(projectId,item.id,ref(item.revision,"IDENTITY-SIGNAL-VERIFY"))};
 const acknowledgeAll=async()=>{for(const item of workspace.publications.filter(x=>x.status==="pending"))await acknowledgeIdentityPublication(projectId,item.id,ref(item.revision,"IDENTITY-CONSUMER-ACK"))};
 return <FactoryPage pageId="client-identity-resolution" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-identity-resolution-page data-identity-resolution-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Fingerprint className="h-5 w-5"/>身份合并与黄金档案</h1><p className="mt-1 text-sm opacity-70">在明确同意与用途边界内，把账户、联系人、邮箱和设备的不可逆哈希合并为可审计客户身份；原始标识不入库，概率结果不自动合并。</p></div><div className="flex gap-2"><Input aria-label="身份合并项目ID" className="w-24 !bg-white !text-slate-900" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入身份链</Button></div></div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Metric label="有效同意" value={workspace.metrics.active_consents}/><Metric label="已核验信号" value={workspace.metrics.verified_signals}/><Metric label="身份匹配率" value={`${workspace.metrics.identity_match_percent}%`}/><Metric label="批准匹配" value={workspace.metrics.approved_matches}/><Metric label="黄金档案" value={workspace.metrics.published_profiles}/><Metric label="下游回执" value={`${workspace.metrics.handoff_acknowledgement_percent}%`}/></div>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-4 w-4"/>同意、用途与隐私边界</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!consent} data-identity-consent-create onClick={()=>void execute(createConsent,"用途限定的身份同意已登记")}>登记身份同意</Button><Button disabled={!consent||consent.status!=="pending"} data-identity-consent-approve onClick={()=>consent&&void execute(()=>approveIdentityConsent(projectId,consent.id,ref(consent.revision,"DPO-CONSENT-APPROVAL")),"同意已由独立角色批准")}>独立批准同意</Button></div>{workspace.consents.map(item=><Row key={item.id} title={`${item.consent_number} · ${item.account_reference}`} status={item.status} detail={`${item.lawful_basis} · ${item.purposes_json.join(" / ")} · ${item.source_event_hash.slice(0,16)}…`}/>)}</CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GitMerge className="h-4 w-4"/>哈希信号、核验与人工裁决</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!consent||consent.status!=="active"||signals.length>=3} data-identity-signals-create onClick={()=>void execute(captureSignals,"三个不可逆身份哈希已采集")}>采集哈希信号</Button><Button disabled={!signals.some(x=>x.status==="pending")} data-identity-signals-verify onClick={()=>void execute(verifySignals,"身份信号已独立核验")}>独立核验信号</Button><Button disabled={!!match||signals.filter(x=>x.status==="verified").length<2} data-identity-match-propose onClick={()=>consent&&void execute(()=>proposeIdentityMatch(projectId,{account_reference:consent.account_reference,signal_ids:signals.filter(x=>x.status==="verified").map(x=>x.id),match_method:"deterministic",match_score:100,reasons:["同一受控账户","同意事件与来源指纹一致"]}),"可解释匹配已提交，尚未自动合并")}>提交匹配</Button><Button disabled={!match||match.status!=="proposed"} data-identity-match-decide onClick={()=>match&&void execute(()=>decideIdentityMatch(projectId,match.id,{expected_revision:match.revision,decision:"approved",reference:`IDENTITY-STEWARD-${Date.now()}`}),"匹配已由独立数据管家裁决")}>独立裁决</Button></div><div className="grid gap-2 md:grid-cols-2">{signals.map(item=><Row key={item.id} title={`${item.signal_type} · ${item.display_hint||"受保护"}`} status={item.status} detail={`${item.identifier_hash.slice(0,16)}… · 来源v${item.source_revision} · 未保存原值`}/>)}</div>{workspace.match_cases.map(item=><Row key={item.id} title={`${item.case_number} · ${item.match_method}`} status={item.status} detail={`评分 ${item.match_score} · ${item.signal_ids_json.length}个信号 · ${item.signal_manifest_hash.slice(0,16)}…`}/>)}</CardContent></Card>
  <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UserRoundCheck className="h-4 w-4"/>黄金档案、不可变版本与下游回执</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Button disabled={!!profile||!match||match.status!=="approved"} data-identity-profile-create onClick={()=>match&&void execute(()=>createGoldenProfile(projectId,match.id),"黄金档案草稿已建立")}>生成黄金档案</Button><Button disabled={!profile||profile.status!=="draft"} data-identity-profile-publish onClick={()=>profile&&void execute(()=>publishGoldenProfile(projectId,profile.id,{expected_revision:profile.revision,consumers:["cdp","crm","ads","service"],remote_reference_prefix:`GOLDEN-PROFILE-${Date.now()}`}),"不可变黄金档案已独立发布")}>独立发布档案</Button><Button disabled={!workspace.publications.some(x=>x.status==="pending")} data-identity-publications-ack onClick={()=>void execute(acknowledgeAll,"全部下游已确认精确档案哈希")}>下游批量回执</Button></div>{workspace.profiles.map(item=><Row key={item.id} title={`${item.profile_number} · ${item.account_reference}`} status={item.status} detail={`${item.member_signal_ids_json.length}个成员 · ${item.source_manifest_hash.slice(0,16)}…`}/>) }{workspace.versions.map(item=><Row key={item.id} title={`${item.version_number_ref} · 档案v${item.version_number}`} status={item.status} detail={`${item.manifest_hash.slice(0,20)}…`}/>) }<div className="grid gap-2 md:grid-cols-2">{workspace.publications.map(item=><Row key={item.id} title={`${item.consumer_system.toUpperCase()} · ${item.publication_number}`} status={item.status} detail={`消费者改写 ${item.consumer_mutated?"是":"否"} · ${item.remote_reference}`}/>)}</div></CardContent></Card>
  <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3"/>不保存原始标识</Badge><Badge>无有效同意禁止匹配</Badge><Badge>撤回后立即停用</Badge><Badge>来源版本与指纹固定</Badge><Badge>信号异人核验</Badge><Badge>匹配异人裁决</Badge><Badge>概率结果不自动合并</Badge><Badge>黄金档案异人发布</Badge><Badge>不直接改写下游</Badge><Badge>证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
 </div></main></FactoryPage>;
}
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="py-4"><p className="text-xs opacity-70">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></CardContent></Card>}
function Row({title,status,detail,action}:{title:string;status:string;detail:string;action?:ReactNode}){return <div className="rounded-lg border p-3" data-identity-record data-identity-status={status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{title}</b><Badge><BadgeCheck className="mr-1 h-3 w-3"/>{STATUS[status]??status}</Badge></div><p className="mt-1 break-all text-xs opacity-75">{detail}</p>{action?<div className="mt-2">{action}</div>:null}</div>}
