import { useEffect, useMemo, useState } from "react";
import { BookOpenCheck, Calculator, Landmark, RefreshCw, ShieldCheck, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FactoryPage } from "@/page-factory/FactoryPage";
import {
  approveFinanceBook, approveFinanceDocument, closeFinancePeriod, createFinanceBook,
  createFinanceDocument, listFinanceWorkspace, openFinancePeriod, submitFinancePeriodClose,
  type FinanceDocument, type FinancePeriod, type FinanceWorkspace,
} from "@/lib/factory-finance-api";

const EMPTY:FinanceWorkspace={books:[],accounts:[],periods:[],documents:[],journals:[],journal_lines:[],balances:[],operating_units:[],eligible_ar_sources:[],eligible_ap_sources:[],contract:{ledger_classification:"formal-accrual-ledger",double_entry_required:true,posted_journals_mutable:false,oms_order_authority:true,procurement_authority:true,engineering_standard_cost_authority:false,period_close_independent:true}};
const LABEL:Record<string,string>={draft:"草稿",active:"已启用",open:"开放",closing:"待独立关账",closed:"已关账",approved:"预算已批准",posted:"已过账","partially-settled":"部分结清",settled:"已结清","ar-invoice":"应收发票","ap-bill":"应付账单","cash-receipt":"收款","cash-payment":"付款",budget:"预算"};
const rev=(item:{revision:number})=>({expected_revision:item.revision,evidence_reference:`FIN-EVIDENCE-${Date.now()}`});

export default function FactoryFinance(){
  const [projectText,setProjectText]=useState("1"); const projectId=Number(projectText);
  const [mode,setMode]=useState<"loading"|"live"|"error">("loading"); const [workspace,setWorkspace]=useState<FinanceWorkspace>(EMPTY);
  const [bookCode,setBookCode]=useState("MAIN-BOOK"); const [bookName,setBookName]=useState("主权责发生制账簿");
  const [periodCode,setPeriodCode]=useState(new Date().toISOString().slice(0,7));
  const [documentType,setDocumentType]=useState<FinanceDocument["document_type"]>("ar-invoice");
  const [amount,setAmount]=useState("1000"); const [description,setDescription]=useState("确认订单正式应收发票过账");
  const load=async(silent=false)=>{if(!Number.isInteger(projectId)||projectId<=0)return;if(!silent)setMode("loading");try{setWorkspace(await listFinanceWorkspace(projectId));setMode("live");}catch(error){setMode("error");toast.error(error instanceof Error?error.message:"财务资金中心加载失败");}};
  useEffect(()=>{void load();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const execute=async(operation:()=>Promise<unknown>,message:string)=>{try{await operation();toast.success(message);await load(true);}catch(error){toast.error(error instanceof Error?error.message:"财务治理操作失败");await load(true);}};
  const unit=workspace.operating_units[0]; const book=workspace.books.find(x=>x.status==="active"); const period=workspace.periods.find(x=>x.status==="open");
  const arSource=workspace.eligible_ar_sources[0]; const apSource=workspace.eligible_ap_sources[0];
  const settlementSource=workspace.documents.find(x=>(documentType==="cash-receipt"?x.document_type==="ar-invoice":x.document_type==="ap-bill")&&["posted","partially-settled"].includes(x.status));
  const documentsByPeriod=useMemo(()=>new Map(workspace.periods.map(x=>[x.id,workspace.documents.filter(item=>item.period_id===x.id)])),[workspace.periods,workspace.documents]);
  const balancesByPeriod=useMemo(()=>new Map(workspace.periods.map(x=>[x.id,workspace.balances.filter(item=>item.period_id===x.id)])),[workspace.periods,workspace.balances]);
  const source=documentType==="ar-invoice"?arSource:documentType==="ap-bill"?apSource:null;
  const createBook=()=>unit&&execute(()=>createFinanceBook(projectId,{operating_unit_id:unit.id,book_reference:`FIN-BOOK-${Date.now()}`,book_code:bookCode,book_name:bookName}),"正式财务账簿草稿已建立");
  const openPeriod=()=>book&&execute(()=>openFinancePeriod(projectId,{book_id:book.id,period_reference:`FIN-PERIOD-${periodCode}-${Date.now()}`,period_code:periodCode}),"正式财务期间已开放");
  const createDocument=()=>book&&period&&execute(()=>createFinanceDocument(projectId,{book_id:book.id,period_id:period.id,document_reference:`FIN-DOC-${Date.now()}`,document_type:documentType,document_date:`${periodCode}-01`,due_date:["ar-invoice","ap-bill"].includes(documentType)?`${periodCode}-28`:null,source_id:source?.id??null,settlement_of_document_id:["cash-receipt","cash-payment"].includes(documentType)?settlementSource?.id??null:null,amount,description,source_evidence_reference:`FIN-SOURCE-${Date.now()}`}),"财务单据草稿已建立");
  return <FactoryPage pageId="client-finance" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-finance-page data-finance-mode={mode}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Landmark className="h-5 w-5"/>财务资金中心</h1><p className="mt-1 text-sm opacity-70">正式权责发生制账簿、应收应付、收付款、预算、平衡复式分录与独立关账；订单与采购事实仍由OMS、ERP和SRM负责。</p></div><div className="flex gap-2"><Input aria-label="财务项目ID" className="w-24" value={projectText} onChange={e=>setProjectText(e.target.value)}/><Button variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>载入财务</Button></div></div>

    <Card><CardHeader><CardTitle className="text-base">正式账簿与受控科目表</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><Input aria-label="财务账簿代码" value={bookCode} onChange={e=>setBookCode(e.target.value)}/><Input aria-label="财务账簿名称" value={bookName} onChange={e=>setBookName(e.target.value)}/><Button disabled={!unit} data-finance-book-create onClick={()=>void createBook()}><BookOpenCheck className="mr-1 h-4 w-4"/>建立账簿</Button></div>{!unit?<p className="text-sm text-amber-700">请先在ERP经营总台启用经营组织。</p>:null}{workspace.books.map(item=><div key={item.id} className="rounded-lg border p-3" data-finance-book-status={item.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.book_number} · {item.book_code} · {item.book_name}</b><Badge>{LABEL[item.status]??item.status}</Badge></div><p className="mt-1 text-xs">{item.unit_number} · {item.base_currency} · {item.accounting_basis} · 修订 {item.revision}</p>{item.status==="draft"?<Button className="mt-2" size="sm" data-finance-book-approve onClick={()=>void execute(()=>approveFinanceBook(projectId,item.id,rev(item)),"账簿已独立审批并生成基础科目表")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批启用</Button>:null}</div>)}<div className="grid gap-2 md:grid-cols-5">{workspace.accounts.map(account=><div key={account.id} className="rounded bg-muted/40 p-2 text-xs" data-finance-account><b>{account.account_code} {account.account_name}</b><p>{account.account_type} · 正常{account.normal_side==="debit"?"借方":"贷方"}</p></div>)}</div></CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">应收、应付、收付款与预算</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex flex-wrap gap-2"><Input aria-label="财务期间" className="w-40" value={periodCode} onChange={e=>setPeriodCode(e.target.value)}/><Button disabled={!book} data-finance-period-open onClick={()=>void openPeriod()}><Calculator className="mr-1 h-4 w-4"/>开放期间</Button></div>{period?<div className="grid gap-2 md:grid-cols-4"><select aria-label="财务单据类型" className="h-10 rounded-md border bg-background px-3 text-sm" value={documentType} onChange={e=>setDocumentType(e.target.value as FinanceDocument["document_type"])}><option value="ar-invoice">应收发票</option><option value="ap-bill">应付账单</option><option value="cash-receipt">收款</option><option value="cash-payment">付款</option><option value="budget">预算</option></select><Input aria-label="财务单据金额" value={amount} onChange={e=>setAmount(e.target.value)}/><Input aria-label="财务单据说明" value={description} onChange={e=>setDescription(e.target.value)}/><Button data-finance-document-create onClick={()=>void createDocument()}><WalletCards className="mr-1 h-4 w-4"/>建立单据</Button></div>:null}{workspace.periods.map(item=><FinancePeriodCard key={item.id} period={item} documents={documentsByPeriod.get(item.id)??[]} balances={balancesByPeriod.get(item.id)??[]} execute={execute} projectId={projectId}/>)}</CardContent></Card>

    <Card><CardHeader><CardTitle className="text-base">不可变复式分录</CardTitle></CardHeader><CardContent className="space-y-2">{workspace.journals.map(journal=><div key={journal.id} className="rounded-lg border p-3" data-finance-journal><div className="flex flex-wrap items-center justify-between gap-2"><b>{journal.journal_number} · {journal.document_number}</b><Badge>{journal.status}</Badge></div><p className="text-sm">借方 {journal.total_debit} / 贷方 {journal.total_credit} {journal.currency} · 编制 {journal.prepared_by} · 审批 {journal.approved_by}</p><div className="mt-2 grid gap-1 md:grid-cols-2">{workspace.journal_lines.filter(x=>x.journal_id===journal.id).map(line=><p key={line.id} className="rounded bg-muted/40 p-2 text-xs" data-finance-journal-line>{line.line_sequence}. {line.account_code} · {line.side==="debit"?"借":"贷"} {line.amount} · {line.counterparty_reference}</p>)}</div></div>)}</CardContent></Card>

    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge>{workspace.contract.ledger_classification}</Badge><Badge>复式记账：{workspace.contract.double_entry_required?"强制":"否"}</Badge><Badge>已过账可改：{workspace.contract.posted_journals_mutable?"允许":"禁止"}</Badge><Badge>订单权威：OMS</Badge><Badge>采购权威：SRM</Badge><Badge>工程标准成本权威：{workspace.contract.engineering_standard_cost_authority?"财务":"PLM/MES"}</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}

function FinancePeriodCard({period,documents,balances,execute,projectId}:{period:FinancePeriod;documents:FinanceDocument[];balances:FinanceWorkspace["balances"];execute:(operation:()=>Promise<unknown>,message:string)=>Promise<void>;projectId:number}){
  return <div className="rounded-lg border p-3" data-finance-period-status={period.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{period.period_number} · {period.period_code}</b><Badge>{LABEL[period.status]??period.status}</Badge></div><div className="mt-2 grid gap-2 sm:grid-cols-3 text-sm"><p>借方 <b data-finance-period-debit>{period.total_debit}</b></p><p>贷方 <b data-finance-period-credit>{period.total_credit}</b></p><p>正式分录 {period.journal_count} 张</p></div><div className="mt-2 space-y-2">{documents.map(item=><div key={item.id} className="rounded bg-muted/40 p-2" data-finance-document-status={item.status}><div className="flex flex-wrap items-center justify-between gap-2"><b>{item.document_number} · {LABEL[item.document_type]}</b><Badge variant="secondary">{LABEL[item.status]??item.status}</Badge></div><p className="text-xs">{item.counterparty_reference} · {item.amount} {item.currency} · 已结 {item.settled_amount} · 来源 {item.source_number??item.source_type}</p>{item.status==="draft"?<Button className="mt-1" size="sm" data-finance-document-approve onClick={()=>void execute(()=>approveFinanceDocument(projectId,item.id,rev(item)),item.document_type==="budget"?"预算已独立审批":"单据已独立审批并形成平衡分录")}><ShieldCheck className="mr-1 h-4 w-4"/>独立审批过账</Button>:null}</div>)}</div><div className="mt-2 flex gap-2">{period.status==="open"&&documents.some(x=>x.status!=="draft"&&x.document_type!=="budget")?<Button size="sm" data-finance-period-submit-close onClick={()=>void execute(()=>submitFinancePeriodClose(projectId,period.id,rev(period)),"试算平衡完成，等待独立关账")}>提交关账</Button>:null}{period.status==="closing"?<Button size="sm" data-finance-period-close onClick={()=>void execute(()=>closeFinancePeriod(projectId,period.id,rev(period)),"正式财务期间已独立关账冻结")}><ShieldCheck className="mr-1 h-4 w-4"/>独立关账</Button>:null}</div>{balances.map(item=><p key={item.id} className="mt-2 text-xs font-semibold" data-finance-account-balance>{item.account_code} · 借 {item.debit} / 贷 {item.credit} / 余额 {item.net_balance}</p>)}</div>;
}
