import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Inbox, RefreshCw, Route, ShieldCheck, Send } from "lucide-react";
import { toast } from "sonner";
import { authApi, isLocalDemoAuthEnabled, type LocalDemoScope } from "@/lib/auth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { acknowledgeInquiryAssignment, activateInquiryRule, approveInquiryRule, createInquiry, createInquiryRule, handoffInquiryToRevenue, listInquiryWorkspace, qualifyInquiry, routeInquiry, type Inquiry, type InquiryRule, type InquiryWorkspace } from "@/lib/factory-inquiry-api";
import { FactoryPage } from "@/page-factory/FactoryPage";

const EMPTY: InquiryWorkspace = { inquiries: [], rules: [], assignments: [], evidence: [], metrics: { received_inquiries: 0, qualified_inquiries: 0, routing_receipt_percent: 0 }, contract: {} };
const ref = (revision: number, prefix: string) => ({ expected_revision: revision, reference: `${prefix}-${Date.now()}` });
const statusLabel: Record<string, string> = { received: "待审核", qualified: "已审核", routed: "已分配", "handed-off": "已交接收入链路", draft: "草稿", approved: "已审批", active: "已启用", pending: "待回执", acknowledged: "已回执" };

export default function Inquiries() {
  const [projectText, setProjectText] = useState("1"); const projectId = Number(projectText);
  const [workspace, setWorkspace] = useState(EMPTY); const [mode, setMode] = useState("loading"); const [scope, setScope] = useState<LocalDemoScope>("hq");
  const [selectedInquiryId, setSelectedInquiryId] = useState(""); const [selectedRuleId, setSelectedRuleId] = useState("");
  const [form, setForm] = useState({ source_channel: "website", source_reference: "", account_reference: "", product_reference: "", country_code: "US", requested_quantity: "1", payload_summary: "", score: "70" });
  const [ruleForm, setRuleForm] = useState({ rule_key: "", rule_name: "", priority: "100", country_code: "US", product_reference: "", min_score: "70", assignee_reference: "sales-owner" });
  const load = async (silent = false) => { if (!Number.isInteger(projectId) || projectId < 1) return; if (!silent) setMode("loading"); try { const next = await listInquiryWorkspace(projectId); setWorkspace(next); setSelectedInquiryId(current => next.inquiries.some(item => item.id === current) ? current : next.inquiries[0]?.id || ""); setSelectedRuleId(current => next.rules.some(item => item.id === current) ? current : next.rules[0]?.id || ""); setMode("live"); } catch (error) { setMode("error"); toast.error(error instanceof Error ? error.message : "询盘工作台加载失败"); } };
  useEffect(() => { void (async () => { if (!authApi.getStoredToken() && isLocalDemoAuthEnabled()) await authApi.restoreLocalDemoSession("hq"); await load(); })(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const run = async (action: () => Promise<unknown>, message: string) => { try { await action(); toast.success(message); await load(true); } catch (error) { toast.error(error instanceof Error ? error.message : "操作失败"); await load(true); } };
  const inquiry = workspace.inquiries.find(item => item.id === selectedInquiryId); const rule = workspace.rules.find(item => item.id === selectedRuleId); const assignment = useMemo(() => workspace.assignments.find(item => item.inquiry_id === selectedInquiryId), [workspace.assignments, selectedInquiryId]);
  const switchScope = async (next: LocalDemoScope) => { if (!isLocalDemoAuthEnabled()) return; if (!await authApi.restoreLocalDemoSession(next)) return toast.error("本地三端演示会话不可用"); setScope(next); toast.success(`已切换到 ${next.toUpperCase()} 端演示身份`); await load(true); };
  const updateForm = (key: keyof typeof form, value: string) => setForm(current => ({ ...current, [key]: value })); const updateRule = (key: keyof typeof ruleForm, value: string) => setRuleForm(current => ({ ...current, [key]: value }));

  return <FactoryPage pageId="client-inquiries" template="dashboard" sourceScope="client_source" autoRegions><main className="p-4 md:p-6" data-factory-inquiry-page data-inquiry-mode={mode} data-three-end-scope={scope}><div className="mx-auto max-w-7xl space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="flex items-center gap-2 text-xl font-bold"><Inbox className="h-5 w-5" />全渠道询盘与线索分配</h1><p className="mt-1 text-sm opacity-70">同一来源只登记一次；先独立审核，再用已启用规则分配并取得接收回执，最后才交给收入黄金链路。</p></div><div className="flex flex-wrap gap-2"><Input aria-label="询盘项目编号" className="w-24" value={projectText} onChange={event => setProjectText(event.target.value)} /><Button variant="outline" onClick={() => void load()}><RefreshCw className="mr-1 h-4 w-4" />载入</Button>{isLocalDemoAuthEnabled() ? <select aria-label="三端演示身份" className="rounded-md border bg-background px-2 text-sm" value={scope} onChange={event => void switchScope(event.target.value as LocalDemoScope)}><option value="hq">总部</option><option value="agency">服务商</option><option value="client">客户</option></select> : null}</div></div>
    <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="py-4"><p className="text-xs opacity-70">已登记询盘</p><b className="text-2xl">{workspace.metrics.received_inquiries}</b></CardContent></Card><Card><CardContent className="py-4"><p className="text-xs opacity-70">已审核询盘</p><b className="text-2xl">{workspace.metrics.qualified_inquiries}</b></CardContent></Card><Card><CardContent className="py-4"><p className="text-xs opacity-70">分配回执率</p><b className="text-2xl">{workspace.metrics.routing_receipt_percent}%</b></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">1. 采集并去重</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><select data-inquiry-channel className="rounded-md border bg-background p-2 text-sm" value={form.source_channel} onChange={event => updateForm("source_channel", event.target.value)}>{["website", "email", "social", "marketplace", "commerce", "manual"].map(item => <option key={item} value={item}>{item}</option>)}</select><Input aria-label="来源编号" value={form.source_reference} onChange={event => updateForm("source_reference", event.target.value)} placeholder="来源编号（仅哈希去重）" /><Input aria-label="客户账号" value={form.account_reference} onChange={event => updateForm("account_reference", event.target.value)} placeholder="客户账号" /><Input aria-label="产品编号" value={form.product_reference} onChange={event => updateForm("product_reference", event.target.value)} placeholder="产品编号" /><Input aria-label="国家代码" value={form.country_code} onChange={event => updateForm("country_code", event.target.value.toUpperCase())} maxLength={2} placeholder="国家代码" /><Input aria-label="需求数量" type="number" min="1" value={form.requested_quantity} onChange={event => updateForm("requested_quantity", event.target.value)} placeholder="需求数量" /><Input aria-label="意向评分" type="number" value={form.score} onChange={event => updateForm("score", event.target.value)} placeholder="意向评分 0-100" /><Textarea aria-label="询盘摘要" className="sm:col-span-2" value={form.payload_summary} onChange={event => updateForm("payload_summary", event.target.value)} placeholder="只保存必要摘要，不保存原始载荷" /><Button data-inquiry-create className="sm:col-span-2" onClick={() => void run(() => createInquiry(projectId, { ...form, requested_quantity: Number(form.requested_quantity) }), "询盘已登记并完成来源去重")}>登记真实询盘</Button></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">2. 规则审核、启用与分配</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><Input aria-label="路由规则键" value={ruleForm.rule_key} onChange={event => updateRule("rule_key", event.target.value)} placeholder="规则键" /><Input aria-label="路由规则名称" value={ruleForm.rule_name} onChange={event => updateRule("rule_name", event.target.value)} placeholder="规则名称" /><Input aria-label="规则国家" value={ruleForm.country_code} onChange={event => updateRule("country_code", event.target.value.toUpperCase())} maxLength={2} placeholder="国家" /><Input aria-label="规则产品" value={ruleForm.product_reference} onChange={event => updateRule("product_reference", event.target.value)} placeholder="产品编号" /><Input aria-label="规则最低分" type="number" value={ruleForm.min_score} onChange={event => updateRule("min_score", event.target.value)} placeholder="最低评分" /><Input aria-label="接收负责人" value={ruleForm.assignee_reference} onChange={event => updateRule("assignee_reference", event.target.value)} placeholder="接收负责人引用" /><Button data-inquiry-rule-create className="sm:col-span-2" variant="outline" onClick={() => void run(() => createInquiryRule(projectId, { ...ruleForm, priority: Number(ruleForm.priority), conditions: { country_code: ruleForm.country_code, product_reference: ruleForm.product_reference, min_score: Number(ruleForm.min_score) } }), "路由规则已创建，等待独立审批")}>创建路由规则</Button></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="text-base">3. 可审计的业务交接</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 lg:grid-cols-2"><select data-inquiry-select className="rounded-md border bg-background p-2 text-sm" value={selectedInquiryId} onChange={event => setSelectedInquiryId(event.target.value)}><option value="">选择询盘</option>{workspace.inquiries.map(item => <option key={item.id} value={item.id}>{item.inquiry_number} · {item.account_reference} · {statusLabel[item.status]}</option>)}</select><select data-inquiry-rule-select className="rounded-md border bg-background p-2 text-sm" value={selectedRuleId} onChange={event => setSelectedRuleId(event.target.value)}><option value="">选择规则</option>{workspace.rules.map(item => <option key={item.id} value={item.id}>{item.rule_number} · {item.rule_name} · {statusLabel[item.status]}</option>)}</select></div><div className="flex flex-wrap gap-2"><Button data-inquiry-qualify disabled={!inquiry || inquiry.status !== "received"} onClick={() => inquiry && void run(() => qualifyInquiry(projectId, inquiry.id, ref(inquiry.revision, "INQ-QUALIFY")), "询盘已由独立身份审核")}>独立审核</Button><Button data-inquiry-rule-approve disabled={!rule || rule.status !== "draft"} onClick={() => rule && void run(() => approveInquiryRule(projectId, rule.id, ref(rule.revision, "ROUTE-APPROVE")), "规则已独立审批")}>审批规则</Button><Button data-inquiry-rule-activate disabled={!rule || rule.status !== "approved"} onClick={() => rule && void run(() => activateInquiryRule(projectId, rule.id, { expected_revision: rule.revision }), "规则已独立启用")}>启用规则</Button><Button data-inquiry-route disabled={!inquiry || inquiry.status !== "qualified"} onClick={() => inquiry && void run(() => routeInquiry(projectId, inquiry.id, { expected_revision: inquiry.revision }), "询盘已按已启用规则分配")}><Route className="mr-1 h-4 w-4" />执行分配</Button><Button data-inquiry-assignment-ack disabled={!assignment || assignment.status !== "pending"} onClick={() => assignment && void run(() => acknowledgeInquiryAssignment(projectId, assignment.id, ref(assignment.revision, "INQ-RECEIPT")), "负责人已确认接收")}>登记接收回执</Button><Button data-inquiry-handoff disabled={!inquiry || inquiry.status !== "routed" || assignment?.status !== "acknowledged"} onClick={() => inquiry && void run(() => handoffInquiryToRevenue(projectId, inquiry.id, { expected_revision: inquiry.revision, currency: "USD" }), "已交接收入黄金链路")}><Send className="mr-1 h-4 w-4" />交接收入链路</Button></div>
      <div className="grid gap-2 lg:grid-cols-2">{workspace.inquiries.map((item: Inquiry) => <div key={item.id} data-inquiry-record data-inquiry-status={item.status} className="rounded border p-3 text-sm"><b>{item.inquiry_number}</b><Badge className="ml-2">{statusLabel[item.status]}</Badge><p className="mt-1 opacity-70">{item.source_channel} · {item.country_code} · 评分 {item.score} · {item.product_reference}</p></div>)}{workspace.rules.map((item: InquiryRule) => <div key={item.id} data-inquiry-rule data-inquiry-rule-status={item.status} className="rounded border p-3 text-sm"><b>{item.rule_number}</b><Badge className="ml-2">{statusLabel[item.status]}</Badge><p className="mt-1 opacity-70">{item.assignee_reference} · 优先级 {item.priority}</p></div>)}</div></CardContent></Card>
    <Card><CardContent className="flex flex-wrap gap-2 py-4 text-xs"><Badge><ShieldCheck className="mr-1 h-3 w-3" />原始载荷不入库</Badge><Badge>来源指纹去重</Badge><Badge>审核、启用、回执均要求不同身份</Badge><Badge>收入交接固定询盘修订</Badge><Badge><CheckCircle2 className="mr-1 h-3 w-3" />审计证据 {workspace.evidence.length} 条</Badge></CardContent></Card>
  </div></main></FactoryPage>;
}
