"""Governed advocacy briefs and internal release receipts; no influencer or customer personal profiles."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Column,DateTime,Integer,String,Text,UniqueConstraint
class FactoryInfluenceBrief(Base):
 __tablename__="factory_influence_briefs";__table_args__=(UniqueConstraint("project_id","brief_key",name="uq_factory_influence_brief_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);brief_number=Column(String(100),nullable=False,unique=True,index=True);brief_key=Column(String(100),nullable=False,index=True);activation_id=Column(String(100),nullable=False,index=True);activation_number=Column(String(100),nullable=False);activation_fingerprint=Column(String(64),nullable=False);advocate_role=Column(String(32),nullable=False);topic=Column(String(255),nullable=False);status=Column(String(32),nullable=False,default="draft",server_default="draft",index=True);created_by=Column(String(255),nullable=False,index=True);verified_by=Column(String(255),index=True);verification_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);updated_at=Column(DateTime(timezone=True),default=datetime.now,onupdate=datetime.now)
class FactoryInfluenceRelease(Base):
 __tablename__="factory_influence_releases";__table_args__=(UniqueConstraint("brief_id","destination",name="uq_factory_influence_release_destination"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);release_number=Column(String(100),nullable=False,unique=True,index=True);brief_id=Column(String(100),nullable=False,index=True);brief_number=Column(String(100),nullable=False);destination=Column(String(32),nullable=False);release_manifest_json=Column(Text,nullable=False);manifest_fingerprint=Column(String(64),nullable=False);status=Column(String(32),nullable=False,default="authorized",server_default="authorized",index=True);authorized_by=Column(String(255),nullable=False,index=True);authorization_reference=Column(String(255),nullable=False);acknowledged_by=Column(String(255),index=True);acknowledgement_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);acknowledged_at=Column(DateTime(timezone=True))
