"""Tenant-scoped RFQ clarification and sample lifecycle records."""
from datetime import date,datetime
from decimal import Decimal
from core.database import Base
from sqlalchemy import Boolean,Date,DateTime,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class RfqTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryRfqCase(RfqTenantMixin,Base):
 __tablename__="factory_rfq_cases";__table_args__=(UniqueConstraint("project_id","source_flow_id",name="uq_factory_rfq_project_flow"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);rfq_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);source_flow_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);source_correlation_id:Mapped[str]=mapped_column(String(100),nullable=False);source_revision:Mapped[int]=mapped_column(Integer,nullable=False);source_stage:Mapped[str]=mapped_column(String(50),nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False);source_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);account_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);product_reference:Mapped[str]=mapped_column(String(255),nullable=False);objective:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="clarifying",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryRfqRequirement(RfqTenantMixin,Base):
 __tablename__="factory_rfq_requirements";__table_args__=(UniqueConstraint("case_id","requirement_code",name="uq_factory_rfq_case_requirement"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);requirement_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);case_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);rfq_number:Mapped[str]=mapped_column(String(96),nullable=False);requirement_code:Mapped[str]=mapped_column(String(64),nullable=False);requirement_name:Mapped[str]=mapped_column(String(180),nullable=False);specification:Mapped[str]=mapped_column(Text,nullable=False);quantity:Mapped[int]=mapped_column(Integer,nullable=False);target_date:Mapped[date]=mapped_column(Date,nullable=False);critical:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending-review",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approval_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactorySampleTask(RfqTenantMixin,Base):
 __tablename__="factory_sample_tasks";__table_args__=(UniqueConstraint("case_id","sample_code",name="uq_factory_rfq_case_sample"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);sample_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);case_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);rfq_number:Mapped[str]=mapped_column(String(96),nullable=False);sample_code:Mapped[str]=mapped_column(String(64),nullable=False);requirement_ids_json:Mapped[list]=mapped_column(JSON,nullable=False);quantity:Mapped[int]=mapped_column(Integer,nullable=False);unit_cost:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False);currency:Mapped[str]=mapped_column(String(8),nullable=False);promised_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending-approval",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approval_reference:Mapped[str|None]=mapped_column(String(255));shipping_reference:Mapped[str|None]=mapped_column(String(255));dispatched_by:Mapped[str|None]=mapped_column(String(128));dispatched_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));received_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactorySampleFeedback(RfqTenantMixin,Base):
 __tablename__="factory_sample_feedback";__table_args__=(UniqueConstraint("sample_id",name="uq_factory_sample_feedback_task"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);feedback_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);case_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);sample_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);sample_number:Mapped[str]=mapped_column(String(96),nullable=False);outcome:Mapped[str]=mapped_column(String(24),nullable=False);quality_score:Mapped[int]=mapped_column(Integer,nullable=False);feedback_note:Mapped[str]=mapped_column(Text,nullable=False);conversion_intent:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);feedback_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending-acknowledgement",index=True);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryRfqEvidence(RfqTenantMixin,Base):
 __tablename__="factory_rfq_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
