"""Governed social distribution plans pinned to approved content and country packs."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Column,DateTime,Integer,String,Text,UniqueConstraint
class FactoryLocalizedDistribution(Base):
 __tablename__="factory_localized_distributions";__table_args__=(UniqueConstraint("project_id","distribution_key",name="uq_factory_localized_distribution_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);distribution_number=Column(String(100),nullable=False,unique=True,index=True);distribution_key=Column(String(100),nullable=False,index=True);review_id=Column(String(100),nullable=False,index=True);review_fingerprint=Column(String(64),nullable=False);pack_id=Column(String(100),nullable=False,index=True);pack_number=Column(String(100),nullable=False);pack_manifest_hash=Column(String(64),nullable=False);target_market=Column(String(64),nullable=False);target_locale=Column(String(16),nullable=False);channel=Column(String(80),nullable=False);status=Column(String(32),nullable=False,default="draft",server_default="draft",index=True);created_by=Column(String(255),nullable=False,index=True);verified_by=Column(String(255),index=True);released_by=Column(String(255),index=True);revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);updated_at=Column(DateTime(timezone=True),default=datetime.now,onupdate=datetime.now)
class FactoryLocalizedDistributionRelease(Base):
 __tablename__="factory_localized_distribution_releases";__table_args__=(UniqueConstraint("distribution_id","version_number",name="uq_factory_localized_distribution_version"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);release_number=Column(String(100),nullable=False,unique=True,index=True);distribution_id=Column(String(100),nullable=False,index=True);version_number=Column(Integer,nullable=False);manifest_json=Column(Text,nullable=False);manifest_fingerprint=Column(String(64),nullable=False);status=Column(String(32),nullable=False,default="pending",server_default="pending",index=True);released_by=Column(String(255),nullable=False);delivery_reference=Column(String(255),nullable=False);acknowledged_by=Column(String(255),index=True);acknowledgement_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);acknowledged_at=Column(DateTime(timezone=True))
