"""Tenant-bound page-SEO source records, suggestion versions and handoffs."""
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from core.database import Base
class OnPageTenantMixin:
 project_id: Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path: Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryOnPageSeoPage(OnPageTenantMixin,Base):
 __tablename__="factory_onpage_seo_pages";__table_args__=(UniqueConstraint("project_id","page_reference","source_reference",name="uq_factory_onpage_seo_page"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);page_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);page_reference: Mapped[str]=mapped_column(String(255),nullable=False);source_reference: Mapped[str]=mapped_column(String(255),nullable=False);locale: Mapped[str]=mapped_column(String(32),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="active",index=True);created_by: Mapped[str]=mapped_column(String(128),nullable=False);created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryOnPageSeoVersion(OnPageTenantMixin,Base):
 __tablename__="factory_onpage_seo_versions";__table_args__=(UniqueConstraint("page_id","version_number",name="uq_factory_onpage_seo_version"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);version_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);page_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);page_number: Mapped[str]=mapped_column(String(96),nullable=False);suggestion_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="draft",index=True);authored_by: Mapped[str]=mapped_column(String(128),nullable=False);reviewed_by: Mapped[str|None]=mapped_column(String(128));review_reference: Mapped[str|None]=mapped_column(String(255));created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);reviewed_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryOnPageSeoRelease(OnPageTenantMixin,Base):
 __tablename__="factory_onpage_seo_releases";__table_args__=(UniqueConstraint("version_id","target",name="uq_factory_onpage_seo_release"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);release_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);page_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number: Mapped[str]=mapped_column(String(96),nullable=False);target: Mapped[str]=mapped_column(String(40),nullable=False);handoff_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);rollback_reference: Mapped[str]=mapped_column(String(255),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval",index=True);prepared_by: Mapped[str]=mapped_column(String(128),nullable=False);approved_by: Mapped[str|None]=mapped_column(String(128));approval_reference: Mapped[str|None]=mapped_column(String(255));consumer_receipt_reference: Mapped[str|None]=mapped_column(String(255));available: Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryOnPageSeoEvidence(OnPageTenantMixin,Base):
 __tablename__="factory_onpage_seo_evidence"
 id: Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_type: Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number: Mapped[str]=mapped_column(String(96),nullable=False);evidence_type: Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference: Mapped[str]=mapped_column(String(255),nullable=False);note: Mapped[str|None]=mapped_column(Text);recorded_by: Mapped[str]=mapped_column(String(128),nullable=False);recorded_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
