"""Governed enterprise targeting and account-based marketing records."""
from __future__ import annotations
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Float,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class AbmTenantMixin:
    project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryAbmProgram(AbmTenantMixin,Base):
    __tablename__="factory_abm_programs";__table_args__=(UniqueConstraint("project_id","program_code",name="uq_factory_abm_project_code"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);program_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);program_code:Mapped[str]=mapped_column(String(64),nullable=False,index=True);program_name:Mapped[str]=mapped_column(String(180),nullable=False);business_objective:Mapped[str]=mapped_column(String(255),nullable=False);allowed_consumers_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAbmTargetAccount(AbmTenantMixin,Base):
    __tablename__="factory_abm_target_accounts";__table_args__=(UniqueConstraint("program_id","account_reference",name="uq_factory_abm_program_account"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);target_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);program_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);program_number:Mapped[str]=mapped_column(String(96),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);priority_tier:Mapped[str]=mapped_column(String(16),nullable=False);fit_score:Mapped[float]=mapped_column(Float,nullable=False);audience_segment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);audience_version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);audience_version_reference:Mapped[str]=mapped_column(String(96),nullable=False);audience_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);consented_member_count:Mapped[int]=mapped_column(Integer,nullable=False);buying_committee_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);buying_version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);buying_version_reference:Mapped[str]=mapped_column(String(96),nullable=False);buying_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);opportunity_number:Mapped[str]=mapped_column(String(100),nullable=False);required_role_count:Mapped[int]=mapped_column(Integer,nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);source_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAbmRolePlay(AbmTenantMixin,Base):
    __tablename__="factory_abm_role_plays";__table_args__=(UniqueConstraint("target_id","committee_member_id",name="uq_factory_abm_target_member_play"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);play_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);program_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);target_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);target_number:Mapped[str]=mapped_column(String(96),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);committee_member_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);committee_member_number:Mapped[str]=mapped_column(String(96),nullable=False);role_code:Mapped[str]=mapped_column(String(64),nullable=False);role_name:Mapped[str]=mapped_column(String(128),nullable=False);contact_hash:Mapped[str]=mapped_column(String(64),nullable=False);member_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);owner_team:Mapped[str]=mapped_column(String(24),nullable=False);channel:Mapped[str]=mapped_column(String(32),nullable=False);action_code:Mapped[str]=mapped_column(String(64),nullable=False);message_intent:Mapped[str]=mapped_column(String(255),nullable=False);success_signal:Mapped[str]=mapped_column(String(180),nullable=False);sequence_order:Mapped[int]=mapped_column(Integer,nullable=False);definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approval_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAbmVersion(AbmTenantMixin,Base):
    __tablename__="factory_abm_versions";__table_args__=(UniqueConstraint("program_id","version_number",name="uq_factory_abm_program_version"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);program_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);program_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);target_count:Mapped[int]=mapped_column(Integer,nullable=False);role_play_count:Mapped[int]=mapped_column(Integer,nullable=False);role_coverage_percent:Mapped[float]=mapped_column(Float,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAbmActivation(AbmTenantMixin,Base):
    __tablename__="factory_abm_activations";__table_args__=(UniqueConstraint("version_id","consumer",name="uq_factory_abm_version_consumer"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);activation_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);program_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False,index=True);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryAbmEvidence(AbmTenantMixin,Base):
    __tablename__="factory_abm_evidence"
    id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
