"""Tenant-scoped B2B order and B2C checkout governance records."""
from datetime import datetime
from decimal import Decimal
from core.database import Base
from sqlalchemy import Boolean,DateTime,Integer,JSON,Numeric,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class CommerceTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryCommerceCheckout(CommerceTenantMixin,Base):
 __tablename__="factory_commerce_checkouts";__table_args__=(UniqueConstraint("project_id","source_type","source_id",name="uq_factory_commerce_project_source"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);checkout_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);commerce_mode:Mapped[str]=mapped_column(String(8),nullable=False,index=True);source_type:Mapped[str]=mapped_column(String(32),nullable=False);source_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);source_number:Mapped[str]=mapped_column(String(96),nullable=False);source_revision:Mapped[int]=mapped_column(Integer,nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False);source_hash:Mapped[str]=mapped_column(String(64),nullable=False);buyer_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);currency:Mapped[str]=mapped_column(String(8),nullable=False);subtotal:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False);quantity:Mapped[Decimal]=mapped_column(Numeric(18,4),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="draft",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCommerceAcceptance(CommerceTenantMixin,Base):
 __tablename__="factory_commerce_acceptances";__table_args__=(UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_acceptance"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);acceptance_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);checkout_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);checkout_number:Mapped[str]=mapped_column(String(96),nullable=False);terms_version:Mapped[str]=mapped_column(String(64),nullable=False);locale:Mapped[str]=mapped_column(String(16),nullable=False);destination_country:Mapped[str]=mapped_column(String(16),nullable=False);fulfillment_mode:Mapped[str]=mapped_column(String(32),nullable=False);purchase_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);acceptance_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);acceptance_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending-review",index=True);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);reviewed_by:Mapped[str|None]=mapped_column(String(128));reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));review_reference:Mapped[str|None]=mapped_column(String(255));review_note:Mapped[str|None]=mapped_column(Text);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCommercePayment(CommerceTenantMixin,Base):
 __tablename__="factory_commerce_payments";__table_args__=(UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_payment"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);payment_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);checkout_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);acceptance_id:Mapped[str]=mapped_column(String(100),nullable=False);method:Mapped[str]=mapped_column(String(32),nullable=False);amount:Mapped[Decimal]=mapped_column(Numeric(18,2),nullable=False);currency:Mapped[str]=mapped_column(String(8),nullable=False);processor_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-verification",index=True);initiated_by:Mapped[str]=mapped_column(String(128),nullable=False);initiated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCommerceHandoff(CommerceTenantMixin,Base):
 __tablename__="factory_commerce_handoffs";__table_args__=(UniqueConstraint("checkout_id",name="uq_factory_commerce_checkout_handoff"),UniqueConstraint("order_intent_id",name="uq_factory_commerce_order_intent"))
 id:Mapped[str]=mapped_column(String(100),primary_key=True);handoff_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);checkout_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);payment_id:Mapped[str]=mapped_column(String(100),nullable=False);order_intent_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-acknowledgement",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));decision:Mapped[str|None]=mapped_column(String(16));authority_system:Mapped[str|None]=mapped_column(String(64));authority_reference:Mapped[str|None]=mapped_column(String(255));authoritative_order_id:Mapped[str|None]=mapped_column(String(100));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCommerceEvidence(CommerceTenantMixin,Base):
 __tablename__="factory_commerce_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
