"""Tenant-scoped opportunity buying committees and influence paths."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Float,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column

class BuyingTenantMixin:
    project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryBuyingCommittee(BuyingTenantMixin,Base):
    __tablename__="factory_buying_committees";__table_args__=(UniqueConstraint("project_id","opportunity_source_type","opportunity_source_id",name="uq_factory_buying_project_opportunity"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);committee_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);committee_name:Mapped[str]=mapped_column(String(180),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);opportunity_source_type:Mapped[str]=mapped_column(String(40),nullable=False);opportunity_source_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);opportunity_source_number:Mapped[str]=mapped_column(String(100),nullable=False);opportunity_source_revision:Mapped[int]=mapped_column(Integer,nullable=False);opportunity_source_status:Mapped[str]=mapped_column(String(32),nullable=False);opportunity_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);opportunity_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);icp_profile_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);icp_profile_number:Mapped[str]=mapped_column(String(96),nullable=False);icp_profile_revision:Mapped[int]=mapped_column(Integer,nullable=False);icp_definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryBuyingCommitteeMember(BuyingTenantMixin,Base):
    __tablename__="factory_buying_committee_members";__table_args__=(UniqueConstraint("committee_id","role_id",name="uq_factory_buying_committee_role"),UniqueConstraint("committee_id","contact_signal_id",name="uq_factory_buying_committee_contact"))
    id:Mapped[str]=mapped_column(String(100),primary_key=True);member_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);committee_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);committee_number:Mapped[str]=mapped_column(String(96),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);role_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);role_number:Mapped[str]=mapped_column(String(96),nullable=False);role_code:Mapped[str]=mapped_column(String(64),nullable=False);role_name:Mapped[str]=mapped_column(String(128),nullable=False);influence_type:Mapped[str]=mapped_column(String(32),nullable=False);role_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);contact_signal_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);contact_signal_number:Mapped[str]=mapped_column(String(96),nullable=False);contact_hash:Mapped[str]=mapped_column(String(64),nullable=False);contact_hint:Mapped[str]=mapped_column(String(32),nullable=False);contact_source_revision:Mapped[int]=mapped_column(Integer,nullable=False);contact_source_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);influence_score:Mapped[float]=mapped_column(Float,nullable=False);relationship_strength:Mapped[str]=mapped_column(String(16),nullable=False);stance:Mapped[str]=mapped_column(String(16),nullable=False);preferred_channel:Mapped[str]=mapped_column(String(32),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryBuyingInfluenceEdge(BuyingTenantMixin,Base):
    __tablename__="factory_buying_influence_edges";__table_args__=(UniqueConstraint("committee_id","from_member_id","to_member_id",name="uq_factory_buying_influence_path"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);edge_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);committee_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);committee_number:Mapped[str]=mapped_column(String(96),nullable=False);from_member_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);from_member_number:Mapped[str]=mapped_column(String(96),nullable=False);to_member_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);to_member_number:Mapped[str]=mapped_column(String(96),nullable=False);influence_direction:Mapped[str]=mapped_column(String(24),nullable=False);strength:Mapped[str]=mapped_column(String(16),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);endpoint_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryBuyingCommitteeVersion(BuyingTenantMixin,Base):
    __tablename__="factory_buying_committee_versions";__table_args__=(UniqueConstraint("committee_id","version_number",name="uq_factory_buying_committee_version"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);committee_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);committee_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);required_role_count:Mapped[int]=mapped_column(Integer,nullable=False);member_count:Mapped[int]=mapped_column(Integer,nullable=False);influence_edge_count:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryBuyingCommitteePublication(BuyingTenantMixin,Base):
    __tablename__="factory_buying_committee_publications";__table_args__=(UniqueConstraint("version_id","consumer",name="uq_factory_buying_version_consumer"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);publication_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);committee_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False,index=True);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryBuyingCommitteeEvidence(BuyingTenantMixin,Base):
    __tablename__="factory_buying_committee_evidence"
    id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
