"""Tenant-bound verified trust evidence and controlled website handoffs."""
from datetime import datetime
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base
class ProofCenterTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryProofCenterAsset(ProofCenterTenantMixin,Base):
 __tablename__="factory_proof_center_assets";__table_args__=(UniqueConstraint("project_id","source_reference",name="uq_factory_proof_center_asset"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);asset_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);asset_type:Mapped[str]=mapped_column(String(40),nullable=False);source_reference:Mapped[str]=mapped_column(String(255),nullable=False);rights_reference:Mapped[str]=mapped_column(String(255),nullable=False);market_scope:Mapped[str]=mapped_column(String(80),nullable=False);valid_until:Mapped[str]=mapped_column(String(32),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="registered",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryProofCenterVersion(ProofCenterTenantMixin,Base):
 __tablename__="factory_proof_center_versions";__table_args__=(UniqueConstraint("asset_id","version_number",name="uq_factory_proof_center_version"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);version_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);asset_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);asset_number:Mapped[str]=mapped_column(String(96),nullable=False);claim_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verification_reference:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryProofCenterRelease(ProofCenterTenantMixin,Base):
 __tablename__="factory_proof_center_releases"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);release_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);asset_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number:Mapped[str]=mapped_column(String(96),nullable=False);target:Mapped[str]=mapped_column(String(40),nullable=False);handoff_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);rollback_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval",index=True);prepared_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approval_reference:Mapped[str|None]=mapped_column(String(255));consumer_receipt_reference:Mapped[str|None]=mapped_column(String(255));available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryProofCenterEvidence(ProofCenterTenantMixin,Base):
 __tablename__="factory_proof_center_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False);subject_id:Mapped[str]=mapped_column(String(100),nullable=False);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
