"""Tenant-scoped, human-governed AI sales-development records."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class AiSdrTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryAiSdrLead(AiSdrTenantMixin,Base):
 __tablename__="factory_ai_sdr_leads";__table_args__=(UniqueConstraint("project_id","assessment_id",name="uq_factory_ai_sdr_project_assessment"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);lead_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);assessment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);assessment_number:Mapped[str]=mapped_column(String(96),nullable=False);profile_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);profile_number:Mapped[str]=mapped_column(String(96),nullable=False);profile_version:Mapped[int]=mapped_column(Integer,nullable=False);definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);account_reference_hash:Mapped[str]=mapped_column(String(64),nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);fit_tier:Mapped[str]=mapped_column(String(16),nullable=False);fit_score:Mapped[str]=mapped_column(String(16),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryAiSdrRecommendation(AiSdrTenantMixin,Base):
 __tablename__="factory_ai_sdr_recommendations";__table_args__=(UniqueConstraint("lead_id","sequence_number",name="uq_factory_ai_sdr_lead_sequence"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);recommendation_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);lead_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);lead_number:Mapped[str]=mapped_column(String(96),nullable=False);sequence_number:Mapped[int]=mapped_column(Integer,nullable=False);model_reference:Mapped[str]=mapped_column(String(255),nullable=False);prompt_hash:Mapped[str]=mapped_column(String(64),nullable=False);enrichment_summary:Mapped[str]=mapped_column(Text,nullable=False);intent_score:Mapped[int]=mapped_column(Integer,nullable=False);qualification_proposal:Mapped[str]=mapped_column(String(24),nullable=False);reply_subject:Mapped[str]=mapped_column(String(180),nullable=False);reply_body:Mapped[str]=mapped_column(Text,nullable=False);next_action:Mapped[str]=mapped_column(String(255),nullable=False);output_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending-review",index=True);generated_by:Mapped[str]=mapped_column(String(128),nullable=False);reviewed_by:Mapped[str|None]=mapped_column(String(128));reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));review_reference:Mapped[str|None]=mapped_column(String(255));review_note:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryAiSdrHandoff(AiSdrTenantMixin,Base):
 __tablename__="factory_ai_sdr_handoffs";__table_args__=(UniqueConstraint("recommendation_id",name="uq_factory_ai_sdr_recommendation_handoff"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);handoff_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);lead_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);recommendation_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);recommendation_number:Mapped[str]=mapped_column(String(96),nullable=False);owner_team:Mapped[str]=mapped_column(String(64),nullable=False);sla_minutes:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);crm_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryAiSdrEvidence(AiSdrTenantMixin,Base):
 __tablename__="factory_ai_sdr_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
