"""Tenant-bound keyword evidence, topic-map versions and approved activations."""
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from core.database import Base
class KeywordMapTenantMixin:
 project_id: Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path: Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryKeywordMapStudy(KeywordMapTenantMixin,Base):
 __tablename__="factory_keyword_map_studies";__table_args__=(UniqueConstraint("project_id","market","source_reference",name="uq_factory_keyword_map_study"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);study_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);market: Mapped[str]=mapped_column(String(80),nullable=False);source_reference: Mapped[str]=mapped_column(String(255),nullable=False);observed_on: Mapped[str]=mapped_column(String(32),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="active",index=True);created_by: Mapped[str]=mapped_column(String(128),nullable=False);created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryKeywordMapVersion(KeywordMapTenantMixin,Base):
 __tablename__="factory_keyword_map_versions";__table_args__=(UniqueConstraint("study_id","version_number",name="uq_factory_keyword_map_version"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);version_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);study_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);study_number: Mapped[str]=mapped_column(String(96),nullable=False);topic_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="draft",index=True);authored_by: Mapped[str]=mapped_column(String(128),nullable=False);verified_by: Mapped[str|None]=mapped_column(String(128));verification_reference: Mapped[str|None]=mapped_column(String(255));created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryKeywordMapRelease(KeywordMapTenantMixin,Base):
 __tablename__="factory_keyword_map_releases";__table_args__=(UniqueConstraint("version_id","target",name="uq_factory_keyword_map_release"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);release_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);study_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number: Mapped[str]=mapped_column(String(96),nullable=False);target: Mapped[str]=mapped_column(String(40),nullable=False);activation_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);rollback_reference: Mapped[str]=mapped_column(String(255),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval",index=True);prepared_by: Mapped[str]=mapped_column(String(128),nullable=False);approved_by: Mapped[str|None]=mapped_column(String(128));approval_reference: Mapped[str|None]=mapped_column(String(255));consumer_receipt_reference: Mapped[str|None]=mapped_column(String(255));available: Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryKeywordMapEvidence(KeywordMapTenantMixin,Base):
 __tablename__="factory_keyword_map_evidence"
 id: Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_type: Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number: Mapped[str]=mapped_column(String(96),nullable=False);evidence_type: Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference: Mapped[str]=mapped_column(String(255),nullable=False);note: Mapped[str|None]=mapped_column(Text);recorded_by: Mapped[str]=mapped_column(String(128),nullable=False);recorded_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
