"""Tenant-scoped governed customer behavior timelines."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column

class TimelineTenantMixin:
    project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryCustomerTimeline(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timelines";__table_args__=(UniqueConstraint("project_id","account_reference",name="uq_factory_timeline_project_account"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);timeline_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);timeline_name:Mapped[str]=mapped_column(String(180),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);scope:Mapped[str]=mapped_column(String(40),nullable=False,default="customer-360");status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCustomerTimelineEvent(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timeline_events";__table_args__=(UniqueConstraint("timeline_id","source_type","source_id",name="uq_factory_timeline_source_event"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);event_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);timeline_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);timeline_number:Mapped[str]=mapped_column(String(96),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);event_type:Mapped[str]=mapped_column(String(48),nullable=False,index=True);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False,index=True);intent_level:Mapped[str]=mapped_column(String(16),nullable=False,index=True);source_type:Mapped[str]=mapped_column(String(48),nullable=False,index=True);source_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);source_number:Mapped[str]=mapped_column(String(100),nullable=False);source_revision:Mapped[int]=mapped_column(Integer,nullable=False);source_status:Mapped[str]=mapped_column(String(40),nullable=False);source_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCustomerTimelineVersion(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timeline_versions";__table_args__=(UniqueConstraint("timeline_id","version_number",name="uq_factory_timeline_version"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);timeline_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);timeline_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);event_count:Mapped[int]=mapped_column(Integer,nullable=False);source_type_count:Mapped[int]=mapped_column(Integer,nullable=False);high_intent_event_count:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCustomerTimelinePublication(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timeline_publications";__table_args__=(UniqueConstraint("version_id","consumer",name="uq_factory_timeline_version_consumer"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);publication_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);timeline_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False,index=True);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCustomerTimelineCheckpoint(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timeline_checkpoints";__table_args__=(UniqueConstraint("timeline_id","checkpoint_code",name="uq_factory_timeline_checkpoint"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);checkpoint_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);timeline_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);checkpoint_code:Mapped[str]=mapped_column(String(48),nullable=False);event_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);event_number:Mapped[str]=mapped_column(String(96),nullable=False);occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);note:Mapped[str|None]=mapped_column(Text);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCustomerTimelineEvidence(TimelineTenantMixin,Base):
    __tablename__="factory_customer_timeline_evidence"
    id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
