"""Tenant-bound public-mention records, verified assessments and response handoffs."""
from datetime import datetime
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base
class ReputationTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryReputationMention(ReputationTenantMixin,Base):
 __tablename__="factory_reputation_mentions";__table_args__=(UniqueConstraint("project_id","public_reference",name="uq_factory_reputation_mention"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);mention_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);public_reference:Mapped[str]=mapped_column(String(255),nullable=False);channel:Mapped[str]=mapped_column(String(48),nullable=False);sentiment:Mapped[str]=mapped_column(String(24),nullable=False);observed_on:Mapped[str]=mapped_column(String(32),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="registered",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryReputationAssessment(ReputationTenantMixin,Base):
 __tablename__="factory_reputation_assessments";__table_args__=(UniqueConstraint("mention_id","assessment_number",name="uq_factory_reputation_assessment"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);assessment_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);mention_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);mention_number:Mapped[str]=mapped_column(String(96),nullable=False);assessment_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verification_reference:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryReputationRelease(ReputationTenantMixin,Base):
 __tablename__="factory_reputation_releases";__table_args__=(UniqueConstraint("assessment_id","target",name="uq_factory_reputation_release"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);release_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);mention_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);assessment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);assessment_number:Mapped[str]=mapped_column(String(96),nullable=False);target:Mapped[str]=mapped_column(String(40),nullable=False);response_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);rollback_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval",index=True);prepared_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approval_reference:Mapped[str|None]=mapped_column(String(255));consumer_receipt_reference:Mapped[str|None]=mapped_column(String(255));available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryReputationEvidence(ReputationTenantMixin,Base):
 __tablename__="factory_reputation_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
