"""Tenant-scoped AI citation observation and controlled analysis records."""
from datetime import datetime
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base
class CitationTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryCitationMonitor(CitationTenantMixin,Base):
 __tablename__="factory_citation_monitors";__table_args__=(UniqueConstraint("project_id","monitor_key",name="uq_factory_citation_monitor"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);monitor_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);monitor_key:Mapped[str]=mapped_column(String(160),nullable=False);market:Mapped[str]=mapped_column(String(80),nullable=False);locale:Mapped[str]=mapped_column(String(32),nullable=False);model_provider:Mapped[str]=mapped_column(String(80),nullable=False);question_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="registered");created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCitationObservation(CitationTenantMixin,Base):
 __tablename__="factory_citation_observations"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);observation_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);monitor_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);monitor_number:Mapped[str]=mapped_column(String(96),nullable=False);observation_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="captured");captured_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verification_reference:Mapped[str|None]=mapped_column(String(255));observed_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCitationRelease(CitationTenantMixin,Base):
 __tablename__="factory_citation_releases"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);release_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);observation_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);observation_number:Mapped[str]=mapped_column(String(96),nullable=False);target:Mapped[str]=mapped_column(String(40),nullable=False);analysis_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval");prepared_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));consumer_receipt_reference:Mapped[str|None]=mapped_column(String(255));available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCitationEvidence(CitationTenantMixin,Base):
 __tablename__="factory_citation_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False);evidence_type:Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
