"""Tenant-bound GEO/AEO question sources and verified answer versions."""
from datetime import datetime
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base
class GeoTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryGeoAeoQuestion(GeoTenantMixin,Base):
 __tablename__="factory_geo_aeo_questions";__table_args__=(UniqueConstraint("project_id","question_reference",name="uq_factory_geo_aeo_question"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);question_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);question_reference:Mapped[str]=mapped_column(String(255),nullable=False);market:Mapped[str]=mapped_column(String(80),nullable=False);locale:Mapped[str]=mapped_column(String(32),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="registered");created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryGeoAeoAnswerVersion(GeoTenantMixin,Base):
 __tablename__="factory_geo_aeo_answer_versions"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);version_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);question_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);question_number:Mapped[str]=mapped_column(String(96),nullable=False);answer_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="draft");authored_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verification_reference:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryGeoAeoRelease(GeoTenantMixin,Base):
 __tablename__="factory_geo_aeo_releases"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);release_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number:Mapped[str]=mapped_column(String(96),nullable=False);target:Mapped[str]=mapped_column(String(40),nullable=False);handoff_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval");prepared_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));consumer_receipt_reference:Mapped[str|None]=mapped_column(String(255));available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryGeoAeoEvidence(GeoTenantMixin,Base):
 __tablename__="factory_geo_aeo_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False);evidence_type:Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
