"""Tenant-scoped governed enterprise knowledge graph records."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean, DateTime, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

class KnowledgeTenantMixin:
    project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)

class FactoryKnowledgeGraph(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_graphs";__table_args__=(UniqueConstraint("project_id","graph_code",name="uq_factory_knowledge_project_graph"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);graph_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);graph_code:Mapped[str]=mapped_column(String(64),nullable=False);graph_name:Mapped[str]=mapped_column(String(180),nullable=False);scope:Mapped[str]=mapped_column(String(32),nullable=False);default_locale:Mapped[str]=mapped_column(String(16),nullable=False);objective:Mapped[str]=mapped_column(Text,nullable=False);current_version:Mapped[int]=mapped_column(Integer,nullable=False,default=0);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FactoryKnowledgeEntity(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_entities";__table_args__=(UniqueConstraint("graph_id","entity_key",name="uq_factory_knowledge_graph_entity"),UniqueConstraint("graph_id","source_type","source_id","entity_type",name="uq_factory_knowledge_graph_source_entity"))
    id:Mapped[str]=mapped_column(String(100),primary_key=True);entity_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);graph_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);graph_number:Mapped[str]=mapped_column(String(96),nullable=False);entity_key:Mapped[str]=mapped_column(String(160),nullable=False);entity_type:Mapped[str]=mapped_column(String(32),nullable=False,index=True);canonical_name:Mapped[str]=mapped_column(String(255),nullable=False);aliases_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);properties_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);locale:Mapped[str]=mapped_column(String(16),nullable=False);source_type:Mapped[str]=mapped_column(String(48),nullable=False,index=True);source_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);source_number:Mapped[str]=mapped_column(String(100),nullable=False);source_revision:Mapped[int]=mapped_column(Integer,nullable=False);source_status:Mapped[str]=mapped_column(String(32),nullable=False);source_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);source_snapshot_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FactoryKnowledgeRelation(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_relations";__table_args__=(UniqueConstraint("graph_id","subject_entity_id","predicate","object_entity_id",name="uq_factory_knowledge_relation"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);relation_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);graph_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_entity_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_entity_number:Mapped[str]=mapped_column(String(96),nullable=False);predicate:Mapped[str]=mapped_column(String(100),nullable=False);object_entity_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);object_entity_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FactoryKnowledgeGraphVersion(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_graph_versions";__table_args__=(UniqueConstraint("graph_id","version_number",name="uq_factory_knowledge_graph_version"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);graph_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);graph_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);entity_manifest_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);relation_manifest_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);entity_type_coverage_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)

class FactoryKnowledgePublication(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_publications";__table_args__=(UniqueConstraint("graph_id","version_number","consumer",name="uq_factory_knowledge_publication"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);publication_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);graph_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);graph_number:Mapped[str]=mapped_column(String(96),nullable=False);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)

class FactoryKnowledgeEvidence(KnowledgeTenantMixin,Base):
    __tablename__="factory_knowledge_evidence"
    id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
