"""Public-signal listening triage projections; no private-message collection."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Column,DateTime,Integer,String,Text,UniqueConstraint
class FactorySocialListeningSignal(Base):
 __tablename__="factory_social_listening_signals";__table_args__=(UniqueConstraint("project_id","signal_key",name="uq_factory_social_listening_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);signal_number=Column(String(100),nullable=False,unique=True,index=True);signal_key=Column(String(100),nullable=False,index=True);assessment_id=Column(String(100),nullable=False,index=True);assessment_number=Column(String(100),nullable=False);assessment_fingerprint=Column(String(64),nullable=False);public_reference=Column(String(255),nullable=False);channel=Column(String(48),nullable=False);sentiment=Column(String(24),nullable=False);signal_type=Column(String(24),nullable=False);priority=Column(String(16),nullable=False);status=Column(String(32),nullable=False,default="captured",server_default="captured",index=True);created_by=Column(String(255),nullable=False,index=True);verified_by=Column(String(255),index=True);routed_by=Column(String(255),index=True);revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);updated_at=Column(DateTime(timezone=True),default=datetime.now,onupdate=datetime.now)
class FactorySocialListeningHandoff(Base):
 __tablename__="factory_social_listening_handoffs";__table_args__=(UniqueConstraint("signal_id","destination",name="uq_factory_social_listening_destination"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);handoff_number=Column(String(100),nullable=False,unique=True,index=True);signal_id=Column(String(100),nullable=False,index=True);signal_number=Column(String(100),nullable=False);destination=Column(String(32),nullable=False);triage_manifest_json=Column(Text,nullable=False);manifest_fingerprint=Column(String(64),nullable=False);status=Column(String(32),nullable=False,default="pending",server_default="pending",index=True);routed_by=Column(String(255),nullable=False);delivery_reference=Column(String(255),nullable=False);acknowledged_by=Column(String(255),index=True);acknowledgement_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);acknowledged_at=Column(DateTime(timezone=True))
