"""Governed B2B community spaces and internal activation handoffs; no member PII or channel credentials."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Column,DateTime,Integer,String,Text,UniqueConstraint
class FactoryCommunitySpace(Base):
 __tablename__="factory_community_spaces";__table_args__=(UniqueConstraint("project_id","community_key",name="uq_factory_community_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);community_number=Column(String(100),nullable=False,unique=True,index=True);community_key=Column(String(100),nullable=False,index=True);account_id=Column(String(100),nullable=False,index=True);account_number=Column(String(100),nullable=False);account_fingerprint=Column(String(64),nullable=False);community_name=Column(String(255),nullable=False);audience_kind=Column(String(32),nullable=False);status=Column(String(32),nullable=False,default="draft",server_default="draft",index=True);created_by=Column(String(255),nullable=False,index=True);verified_by=Column(String(255),index=True);verification_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);updated_at=Column(DateTime(timezone=True),default=datetime.now,onupdate=datetime.now)
class FactoryCommunityActivation(Base):
 __tablename__="factory_community_activations";__table_args__=(UniqueConstraint("project_id","activation_key",name="uq_factory_community_activation_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);activation_number=Column(String(100),nullable=False,unique=True,index=True);activation_key=Column(String(100),nullable=False,index=True);community_id=Column(String(100),nullable=False,index=True);community_number=Column(String(100),nullable=False);event_title=Column(String(255),nullable=False);event_type=Column(String(32),nullable=False);scheduled_on=Column(String(32),nullable=False);activation_manifest_json=Column(Text,nullable=False);manifest_fingerprint=Column(String(64),nullable=False);status=Column(String(32),nullable=False,default="planned",server_default="planned",index=True);planned_by=Column(String(255),nullable=False,index=True);approved_by=Column(String(255),index=True);approval_reference=Column(String(255));acknowledged_by=Column(String(255),index=True);acknowledgement_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);acknowledged_at=Column(DateTime(timezone=True))
