"""Tenant-scoped consent-bound audience segments and activations."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class SegmentTenantMixin:
    project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryAudienceSegment(SegmentTenantMixin,Base):
    __tablename__="factory_audience_segments";__table_args__=(UniqueConstraint("project_id","segment_code",name="uq_factory_segment_project_code"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);segment_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);segment_code:Mapped[str]=mapped_column(String(64),nullable=False);segment_name:Mapped[str]=mapped_column(String(180),nullable=False);business_purpose:Mapped[str]=mapped_column(String(255),nullable=False);allowed_channels_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAudienceSegmentRule(SegmentTenantMixin,Base):
    __tablename__="factory_audience_segment_rules";__table_args__=(UniqueConstraint("segment_id","rule_code",name="uq_factory_segment_rule_code"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);rule_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);segment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);segment_number:Mapped[str]=mapped_column(String(96),nullable=False);rule_code:Mapped[str]=mapped_column(String(64),nullable=False);rule_name:Mapped[str]=mapped_column(String(180),nullable=False);minimum_high_intent_events:Mapped[int]=mapped_column(Integer,nullable=False);required_source_types_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);required_consent_purposes_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approval_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAudienceMembership(SegmentTenantMixin,Base):
    __tablename__="factory_audience_memberships";__table_args__=(UniqueConstraint("segment_id","contact_signal_id",name="uq_factory_segment_contact"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);membership_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);segment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);segment_number:Mapped[str]=mapped_column(String(96),nullable=False);rule_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);rule_number:Mapped[str]=mapped_column(String(96),nullable=False);rule_definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);contact_signal_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);contact_signal_number:Mapped[str]=mapped_column(String(96),nullable=False);contact_hash:Mapped[str]=mapped_column(String(64),nullable=False);contact_hint:Mapped[str]=mapped_column(String(32),nullable=False);contact_revision:Mapped[int]=mapped_column(Integer,nullable=False);contact_fingerprint:Mapped[str]=mapped_column(String(64),nullable=False);consent_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);consent_number:Mapped[str]=mapped_column(String(96),nullable=False);consent_revision:Mapped[int]=mapped_column(Integer,nullable=False);consent_event_hash:Mapped[str]=mapped_column(String(64),nullable=False);consent_expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);timeline_version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);timeline_version_reference:Mapped[str]=mapped_column(String(96),nullable=False);timeline_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);high_intent_event_count:Mapped[int]=mapped_column(Integer,nullable=False);source_types_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);evaluation_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);evaluated_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));verification_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAudienceSegmentVersion(SegmentTenantMixin,Base):
    __tablename__="factory_audience_segment_versions";__table_args__=(UniqueConstraint("segment_id","version_number",name="uq_factory_segment_version"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);segment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);segment_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);member_count:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryAudienceActivation(SegmentTenantMixin,Base):
    __tablename__="factory_audience_activations";__table_args__=(UniqueConstraint("version_id","consumer",name="uq_factory_segment_version_consumer"),)
    id:Mapped[str]=mapped_column(String(100),primary_key=True);activation_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);segment_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False,index=True);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryAudienceEvidence(SegmentTenantMixin,Base):
    __tablename__="factory_audience_evidence"
    id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
