"""Tenant-scoped CDP data-product releases; source systems remain authoritative."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class CdpTenantMixin:
 project_id:Mapped[int]=mapped_column(nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryCdpDataProduct(CdpTenantMixin,Base):
 __tablename__="factory_cdp_data_products";__table_args__=(UniqueConstraint("project_id","product_key",name="uq_factory_cdp_product_key"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);product_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);product_key:Mapped[str]=mapped_column(String(96),nullable=False);account_reference:Mapped[str]=mapped_column(String(180),nullable=False,index=True);profile_version_id:Mapped[str]=mapped_column(String(100),nullable=False);timeline_version_id:Mapped[str]=mapped_column(String(100),nullable=False);segment_version_id:Mapped[str]=mapped_column(String(100),nullable=False);source_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);source_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approval_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class FactoryCdpPublication(CdpTenantMixin,Base):
 __tablename__="factory_cdp_publications";__table_args__=(UniqueConstraint("product_id","consumer",name="uq_factory_cdp_product_consumer"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);publication_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);product_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);product_number:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);created_by:Mapped[str]=mapped_column(String(128),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));receipt_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class FactoryCdpEvidence(CdpTenantMixin,Base):
 __tablename__="factory_cdp_evidence";id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);event_type:Mapped[str]=mapped_column(String(48),nullable=False);reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
