"""Tenant-scoped consent-first audiences; never stores raw customer identifiers."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Column,DateTime,Integer,String,Text,UniqueConstraint
class FactoryMarketingAudience(Base):
 __tablename__="factory_marketing_audiences";__table_args__=(UniqueConstraint("project_id","audience_key",name="uq_factory_marketing_audience_key"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);audience_number=Column(String(100),nullable=False,unique=True,index=True);audience_key=Column(String(120),nullable=False,index=True);source_reference=Column(String(255),nullable=False);consent_receipt=Column(String(255),nullable=False);market_scope=Column(String(32),nullable=False);status=Column(String(32),nullable=False,default="draft",server_default="draft",index=True);created_by=Column(String(255),nullable=False,index=True);verified_by=Column(String(255),index=True);verification_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);updated_at=Column(DateTime(timezone=True),default=datetime.now,onupdate=datetime.now)
class FactoryMarketingAudienceActivation(Base):
 __tablename__="factory_marketing_audience_activations";__table_args__=(UniqueConstraint("audience_id","destination",name="uq_factory_marketing_audience_activation_destination"),{"extend_existing":True})
 id=Column(String(100),primary_key=True);project_id=Column(Integer,nullable=False,index=True);agent_path=Column(String(500),nullable=False,index=True);tenant_id=Column(String(100),nullable=False,index=True);client_id=Column(String(100),nullable=False,index=True);plan_id=Column(String(100),nullable=False,index=True);activation_number=Column(String(100),nullable=False,unique=True,index=True);audience_id=Column(String(100),nullable=False,index=True);audience_number=Column(String(100),nullable=False);destination=Column(String(32),nullable=False);scope_manifest_json=Column(Text,nullable=False);manifest_fingerprint=Column(String(64),nullable=False);status=Column(String(32),nullable=False,default="pending",server_default="pending",index=True);activated_by=Column(String(255),nullable=False,index=True);acknowledged_by=Column(String(255),index=True);acknowledgement_reference=Column(String(255));revision=Column(Integer,nullable=False,default=1,server_default="1");created_at=Column(DateTime(timezone=True),default=datetime.now);acknowledged_at=Column(DateTime(timezone=True))
