"""Tenant-bound search-performance datasets, immutable snapshots and analysis handoffs."""
from datetime import datetime
from sqlalchemy import Boolean, DateTime, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column
from core.database import Base

class SearchShareTenantMixin:
 project_id: Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path: Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id: Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactorySearchShareDataset(SearchShareTenantMixin,Base):
 __tablename__="factory_search_share_datasets";__table_args__=(UniqueConstraint("project_id","source_reference","observed_from","observed_to",name="uq_factory_search_share_dataset"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);dataset_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);source_reference: Mapped[str]=mapped_column(String(255),nullable=False);market: Mapped[str]=mapped_column(String(80),nullable=False);search_engine: Mapped[str]=mapped_column(String(40),nullable=False);device: Mapped[str]=mapped_column(String(40),nullable=False);observed_from: Mapped[str]=mapped_column(String(32),nullable=False);observed_to: Mapped[str]=mapped_column(String(32),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="active",index=True);created_by: Mapped[str]=mapped_column(String(128),nullable=False);created_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactorySearchShareSnapshot(SearchShareTenantMixin,Base):
 __tablename__="factory_search_share_snapshots";__table_args__=(UniqueConstraint("dataset_id","snapshot_number",name="uq_factory_search_share_snapshot"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);snapshot_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);dataset_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);dataset_number: Mapped[str]=mapped_column(String(96),nullable=False);performance_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="captured",index=True);captured_by: Mapped[str]=mapped_column(String(128),nullable=False);verified_by: Mapped[str|None]=mapped_column(String(128));verification_reference: Mapped[str|None]=mapped_column(String(255));captured_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactorySearchShareRelease(SearchShareTenantMixin,Base):
 __tablename__="factory_search_share_releases";__table_args__=(UniqueConstraint("snapshot_id","target",name="uq_factory_search_share_release"),)
 id: Mapped[str]=mapped_column(String(100),primary_key=True);release_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);dataset_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);snapshot_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);snapshot_number: Mapped[str]=mapped_column(String(96),nullable=False);target: Mapped[str]=mapped_column(String(40),nullable=False);analysis_manifest_json: Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash: Mapped[str]=mapped_column(String(64),nullable=False);rollback_reference: Mapped[str]=mapped_column(String(255),nullable=False);status: Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval",index=True);prepared_by: Mapped[str]=mapped_column(String(128),nullable=False);approved_by: Mapped[str|None]=mapped_column(String(128));approval_reference: Mapped[str|None]=mapped_column(String(255));consumer_receipt_reference: Mapped[str|None]=mapped_column(String(255));available: Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_at: Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision: Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactorySearchShareEvidence(SearchShareTenantMixin,Base):
 __tablename__="factory_search_share_evidence"
 id: Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number: Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_type: Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id: Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number: Mapped[str]=mapped_column(String(96),nullable=False);evidence_type: Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference: Mapped[str]=mapped_column(String(255),nullable=False);note: Mapped[str|None]=mapped_column(Text);recorded_by: Mapped[str]=mapped_column(String(128),nullable=False);recorded_at: Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
