"""Tenant-bound AI-readable facts with source-bound versions and handoffs."""
from datetime import datetime
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from core.database import Base
class FactTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryFactLibraryFact(FactTenantMixin,Base):
 __tablename__="factory_fact_library_facts";__table_args__=(UniqueConstraint("project_id","fact_key",name="uq_factory_fact_library_fact"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);fact_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);fact_key:Mapped[str]=mapped_column(String(160),nullable=False);fact_type:Mapped[str]=mapped_column(String(40),nullable=False);source_reference:Mapped[str]=mapped_column(String(255),nullable=False);authority_reference:Mapped[str]=mapped_column(String(255),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="registered");created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryFactLibraryVersion(FactTenantMixin,Base):
 __tablename__="factory_fact_library_versions"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);version_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);fact_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);fact_number:Mapped[str]=mapped_column(String(96),nullable=False);fact_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="draft");authored_by:Mapped[str]=mapped_column(String(128),nullable=False);verified_by:Mapped[str|None]=mapped_column(String(128));verification_reference:Mapped[str|None]=mapped_column(String(255));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);verified_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryFactLibraryRelease(FactTenantMixin,Base):
 __tablename__="factory_fact_library_releases"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);release_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_number:Mapped[str]=mapped_column(String(96),nullable=False);target:Mapped[str]=mapped_column(String(40),nullable=False);handoff_manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(32),nullable=False,default="pending-approval");prepared_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));consumer_receipt_reference:Mapped[str|None]=mapped_column(String(255));available:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);prepared_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryFactLibraryEvidence(FactTenantMixin,Base):
 __tablename__="factory_fact_library_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),unique=True,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False);evidence_type:Mapped[str]=mapped_column(String(64),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
