"""Governed role-based creative center records."""
from datetime import datetime
from core.database import Base
from sqlalchemy import Boolean,DateTime,Integer,JSON,String,Text,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
class CreativeTenantMixin:
 project_id:Mapped[int]=mapped_column(Integer,nullable=False,index=True);agent_path:Mapped[str]=mapped_column(String(255),nullable=False,index=True);tenant_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);client_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True);plan_id:Mapped[str]=mapped_column(String(128),nullable=False,index=True)
class FactoryCreativeBrief(CreativeTenantMixin,Base):
 __tablename__="factory_creative_briefs";__table_args__=(UniqueConstraint("project_id","brief_code",name="uq_factory_creative_project_code"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);brief_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);brief_code:Mapped[str]=mapped_column(String(64),nullable=False,index=True);brief_name:Mapped[str]=mapped_column(String(180),nullable=False);objective:Mapped[str]=mapped_column(String(255),nullable=False);abm_program_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);abm_version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);abm_version_reference:Mapped[str]=mapped_column(String(96),nullable=False);abm_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);country_pack_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);country_pack_number:Mapped[str]=mapped_column(String(96),nullable=False);country_pack_manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);target_market:Mapped[str]=mapped_column(String(64),nullable=False);target_locale:Mapped[str]=mapped_column(String(16),nullable=False);allowed_consumers_json:Mapped[list]=mapped_column(JSON,nullable=False,default=list);status:Mapped[str]=mapped_column(String(24),nullable=False,default="draft",index=True);authored_by:Mapped[str]=mapped_column(String(128),nullable=False);published_by:Mapped[str|None]=mapped_column(String(128));published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCreativeVariant(CreativeTenantMixin,Base):
 __tablename__="factory_creative_variants";__table_args__=(UniqueConstraint("brief_id","abm_play_id",name="uq_factory_creative_brief_play"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);variant_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);brief_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);brief_number:Mapped[str]=mapped_column(String(96),nullable=False);abm_play_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);abm_play_number:Mapped[str]=mapped_column(String(96),nullable=False);role_code:Mapped[str]=mapped_column(String(64),nullable=False);role_name:Mapped[str]=mapped_column(String(128),nullable=False);channel:Mapped[str]=mapped_column(String(32),nullable=False);headline:Mapped[str]=mapped_column(String(180),nullable=False);message_body:Mapped[str]=mapped_column(Text,nullable=False);call_to_action:Mapped[str]=mapped_column(String(128),nullable=False);source_pack_hash:Mapped[str]=mapped_column(String(64),nullable=False);play_definition_hash:Mapped[str]=mapped_column(String(64),nullable=False);ai_assisted:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);model_reference:Mapped[str|None]=mapped_column(String(255));prompt_hash:Mapped[str|None]=mapped_column(String(64));content_hash:Mapped[str]=mapped_column(String(64),nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="review",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);approved_by:Mapped[str|None]=mapped_column(String(128));approved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));approval_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCreativeVersion(CreativeTenantMixin,Base):
 __tablename__="factory_creative_versions";__table_args__=(UniqueConstraint("brief_id","version_number",name="uq_factory_creative_brief_version"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);brief_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);brief_number:Mapped[str]=mapped_column(String(96),nullable=False);version_number:Mapped[int]=mapped_column(Integer,nullable=False);manifest_json:Mapped[dict]=mapped_column(JSON,nullable=False,default=dict);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);variant_count:Mapped[int]=mapped_column(Integer,nullable=False);role_coverage_percent:Mapped[int]=mapped_column(Integer,nullable=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="published",index=True);published_by:Mapped[str]=mapped_column(String(128),nullable=False);published_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
class FactoryCreativeActivation(CreativeTenantMixin,Base):
 __tablename__="factory_creative_activations";__table_args__=(UniqueConstraint("version_id","consumer",name="uq_factory_creative_version_consumer"),)
 id:Mapped[str]=mapped_column(String(100),primary_key=True);activation_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);brief_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);version_reference:Mapped[str]=mapped_column(String(96),nullable=False);consumer:Mapped[str]=mapped_column(String(32),nullable=False,index=True);manifest_hash:Mapped[str]=mapped_column(String(64),nullable=False);delivery_reference:Mapped[str]=mapped_column(String(255),nullable=False);consumer_mutated:Mapped[bool]=mapped_column(Boolean,nullable=False,default=False);status:Mapped[str]=mapped_column(String(24),nullable=False,default="pending",index=True);created_by:Mapped[str]=mapped_column(String(128),nullable=False);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False);acknowledged_by:Mapped[str|None]=mapped_column(String(128));acknowledged_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));acknowledgement_reference:Mapped[str|None]=mapped_column(String(255));revision:Mapped[int]=mapped_column(Integer,nullable=False,default=1)
class FactoryCreativeEvidence(CreativeTenantMixin,Base):
 __tablename__="factory_creative_evidence"
 id:Mapped[str]=mapped_column(String(100),primary_key=True);evidence_number:Mapped[str]=mapped_column(String(96),nullable=False,unique=True,index=True);subject_type:Mapped[str]=mapped_column(String(40),nullable=False,index=True);subject_id:Mapped[str]=mapped_column(String(100),nullable=False,index=True);subject_number:Mapped[str]=mapped_column(String(96),nullable=False);evidence_type:Mapped[str]=mapped_column(String(48),nullable=False);evidence_reference:Mapped[str]=mapped_column(String(255),nullable=False);note:Mapped[str|None]=mapped_column(Text);recorded_by:Mapped[str]=mapped_column(String(128),nullable=False);recorded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),nullable=False)
