"""Inspect the latest acknowledged B2B account graph and authoritative pins."""
import argparse,hashlib,json,sqlite3
from decimal import Decimal
def digest(payload):return hashlib.sha256(json.dumps(payload,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def same_number(left,right):return Decimal(str(left))==Decimal(str(right))
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--database",required=True);args=parser.parse_args();db=sqlite3.connect(args.database);db.row_factory=sqlite3.Row;query=lambda sql,values=():[dict(x) for x in db.execute(sql,values).fetchall()]
    rows=query("select v.* from factory_account_graph_versions v where not exists (select 1 from factory_account_graph_publications p where p.version_id=v.id and p.status!='acknowledged') and exists (select 1 from factory_account_graph_publications p where p.version_id=v.id) order by v.published_at desc limit 1")
    if not rows:raise SystemExit("No fully acknowledged B2B account graph found")
    version=rows[0];graph=query("select * from factory_account_graphs where id=? and status='published'",(version["graph_id"],))[0];nodes=query("select * from factory_account_graph_nodes where graph_id=?",(graph["id"],));edges=query("select * from factory_account_graph_edges where graph_id=?",(graph["id"],));publications=query("select * from factory_account_graph_publications where version_id=?",(version["id"],));assert len(nodes)==6 and len(edges)==3 and {x["source_type"] for x in nodes}=={"legal-party","golden-profile","identity-signal","cpq-quote","fulfillment-order"};assert all(x["status"]=="verified" and x["created_by"]!=x["verified_by"] for x in nodes);assert all(x["status"]=="verified" and x["created_by"]!=x["verified_by"] for x in edges);assert {x["relation_type"] for x in edges}=={"has-opportunity","contact-at","fulfills"};assert graph["authored_by"]!=graph["published_by"]
    for node in nodes:
        snap=json.loads(node["source_snapshot_json"]);assert digest(snap)==node["source_fingerprint"] and int(snap["revision"])==node["source_revision"] and snap["status"]==node["source_status"]
        if node["source_type"]=="legal-party":current=query("select * from factory_legal_parties where id=?",(node["source_id"],))[0];assert current["party_number"]==snap["party_number"] and current["party_reference"]==snap["party_reference"] and current["legal_name"]==snap["legal_name"] and current["identity_fingerprint"]==snap["identity_fingerprint"] and current["revision"]==snap["revision"]
        elif node["source_type"]=="golden-profile":current=query("select * from factory_golden_profiles where id=?",(node["source_id"],))[0];assert current["profile_number"]==snap["profile_number"] and current["account_reference"]==snap["account_reference"] and current["source_manifest_hash"]==snap["source_manifest_hash"] and current["revision"]==snap["revision"]
        elif node["source_type"]=="identity-signal":current=query("select * from factory_identity_signals where id=?",(node["source_id"],))[0];consent=query("select * from factory_identity_consents where id=?",(current["consent_id"],))[0];assert current["signal_number"]==snap["signal_number"] and current["identifier_hash"]==snap["identifier_hash"] and current["revision"]==snap["revision"] and consent["status"]==snap["consent_status"] and consent["revision"]==snap["consent_revision"]
        elif node["source_type"]=="cpq-quote":current=query("select * from factory_cpq_quotes where id=?",(node["source_id"],))[0];assert current["quote_number"]==snap["quote_number"] and current["account_reference"]==snap["account_reference"] and same_number(current["subtotal"],snap["subtotal"]) and current["revision"]==snap["revision"]
        else:current=query("select * from factory_fulfillment_orders where id=?",(node["source_id"],))[0];assert current["order_number"]==snap["order_number"] and current["quote_id"]==snap["quote_id"] and current["account_reference"]==snap["account_reference"] and same_number(current["order_total"],snap["order_total"]) and current["revision"]==snap["revision"]
    manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"] and version["node_count"]==6 and version["edge_count"]==3;assert len(publications)==4 and {x["consumer"] for x in publications}=={"crm","cdp","sales","service"} and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] and x["manifest_hash"]==version["manifest_hash"] for x in publications)
    subject_ids=[graph["id"],*[x["id"] for x in nodes],*[x["id"] for x in edges],*[x["id"] for x in publications]];marks=",".join("?" for _ in subject_ids);evidence=query(f"select * from factory_account_graph_evidence where subject_id in ({marks})",tuple(subject_ids));types={x["evidence_type"] for x in evidence};assert {"graph-created","node-created","node-verified","edge-created","edge-verified","graph-published","handoff-created","handoff-acknowledged"}<=types;audits=query(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.account.%'",tuple(subject_ids));actions={x["action"] for x in audits};assert {"factory.account.graph.create","factory.account.node.create","factory.account.node.verify","factory.account.relation.create","factory.account.relation.verify","factory.account.graph.publish","factory.account.publication.acknowledge"}<=actions
    permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in query("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];required={"factory.portrait.account.graph.manage","factory.portrait.account.node.verify","factory.portrait.account.relation.manage","factory.portrait.account.relation.verify","factory.portrait.account.publish","factory.portrait.account.handoff.acknowledge"};assert required<=permissions
    print(json.dumps({"project_id":graph["project_id"],"graph_number":graph["graph_number"],"version_reference":version["version_reference"],"manifest_hash":version["manifest_hash"],"node_count":len(nodes),"edge_count":len(edges),"source_records_unchanged":True,"source_records_copied":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
