"""Inspect the latest fully acknowledged consent-bound audience segment."""
import argparse,hashlib,json,sqlite3
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--database",required=True);a=p.parse_args();db=sqlite3.connect(a.database);db.row_factory=sqlite3.Row;q=lambda sql,v=():[dict(x) for x in db.execute(sql,v).fetchall()]
 versions=q("select v.* from factory_audience_segment_versions v where exists(select 1 from factory_audience_activations a where a.version_id=v.id) and not exists(select 1 from factory_audience_activations a where a.version_id=v.id and a.status!='acknowledged') order by v.published_at desc limit 1")
 if not versions:raise SystemExit("No fully acknowledged consent-bound audience segment found")
 version=versions[0];segment=q("select * from factory_audience_segments where id=? and status='published'",(version["segment_id"],))[0];rules=q("select * from factory_audience_segment_rules where segment_id=?",(segment["id"],));members=q("select * from factory_audience_memberships where segment_id=?",(segment["id"],));acts=q("select * from factory_audience_activations where version_id=?",(version["id"],));assert segment["authored_by"]!=segment["published_by"] and rules and members;assert all(x["status"]=="approved" and x["authored_by"]!=x["approved_by"] for x in rules);assert all(x["status"]=="verified" and x["evaluated_by"]!=x["verified_by"] for x in members)
 for rule in rules:
  definition={"minimum_high_intent_events":rule["minimum_high_intent_events"],"required_source_types":json.loads(rule["required_source_types_json"]),"required_consent_purposes":json.loads(rule["required_consent_purposes_json"])};assert digest(definition)==rule["definition_hash"]
 for member in members:
  signal=q("select * from factory_identity_signals where id=?",(member["contact_signal_id"],))[0];consent=q("select * from factory_identity_consents where id=?",(member["consent_id"],))[0];timeline=q("select * from factory_customer_timeline_versions where id=?",(member["timeline_version_id"],))[0];assert signal["status"]=="verified" and signal["identifier_hash"]==member["contact_hash"] and signal["source_fingerprint"]==member["contact_fingerprint"] and signal["source_revision"]==member["contact_revision"] and signal["signal_type"] in ("contact","email","phone");assert consent["status"]=="active" and consent["source_event_hash"]==member["consent_event_hash"] and consent["revision"]==member["consent_revision"];assert timeline["status"]=="published" and timeline["manifest_hash"]==member["timeline_manifest_hash"] and digest(json.loads(timeline["manifest_json"]))==timeline["manifest_hash"]
 manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"] and version["member_count"]==len(members);assert len(acts)==4 and {x["consumer"] for x in acts}=={"crm","marketing","ads","service"} and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] and x["manifest_hash"]==version["manifest_hash"] for x in acts)
 ids=[segment["id"],*[x["id"] for x in rules],*[x["id"] for x in members],*[x["id"] for x in acts]];marks=",".join("?" for _ in ids);evidence=q(f"select * from factory_audience_evidence where subject_id in ({marks})",tuple(ids));assert {"segment-created","rule-created","rule-approved","membership-evaluated","membership-verified","segment-published","activation-created","activation-acknowledged"}<={x["evidence_type"] for x in evidence};audits=q(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.segment.%'",tuple(ids));assert {"factory.segment.create","factory.segment.rule.create","factory.segment.rule.approve","factory.segment.membership.evaluate","factory.segment.membership.verify","factory.segment.publish","factory.segment.activation.acknowledge"}<={x["action"] for x in audits}
 permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in q("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];assert {"factory.portrait.segment.manage","factory.portrait.segment.rule.approve","factory.portrait.segment.membership.evaluate","factory.portrait.segment.membership.verify","factory.portrait.segment.publish","factory.portrait.segment.activation.acknowledge"}<=permissions
 print(json.dumps({"project_id":segment["project_id"],"segment_number":segment["segment_number"],"version_reference":version["version_reference"],"manifest_hash":version["manifest_hash"],"member_count":len(members),"source_records_unchanged":True,"source_records_copied":False,"raw_identifier_stored":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
