"""Inspect the latest fully acknowledged enterprise targeting program."""
import argparse,hashlib,json,sqlite3
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--database",required=True);a=p.parse_args();db=sqlite3.connect(a.database);db.row_factory=sqlite3.Row;q=lambda sql,v=():[dict(x) for x in db.execute(sql,v).fetchall()]
 versions=q("select v.* from factory_abm_versions v where exists(select 1 from factory_abm_activations a where a.version_id=v.id) and not exists(select 1 from factory_abm_activations a where a.version_id=v.id and a.status!='acknowledged') order by v.published_at desc limit 1")
 if not versions:raise SystemExit("No fully acknowledged enterprise targeting program found")
 version=versions[0];program=q("select * from factory_abm_programs where id=? and status='published'",(version["program_id"],))[0];targets=q("select * from factory_abm_target_accounts where program_id=?",(program["id"],));plays=q("select * from factory_abm_role_plays where program_id=?",(program["id"],));acts=q("select * from factory_abm_activations where version_id=?",(version["id"],));assert program["authored_by"]!=program["published_by"] and targets and plays;assert all(x["status"]=="verified" and x["created_by"]!=x["verified_by"] for x in targets);assert all(x["status"]=="approved" and x["authored_by"]!=x["approved_by"] for x in plays)
 for target in targets:
  av=q("select * from factory_audience_segment_versions where id=?",(target["audience_version_id"],))[0];bv=q("select * from factory_buying_committee_versions where id=?",(target["buying_version_id"],))[0];committee=q("select * from factory_buying_committees where id=?",(target["buying_committee_id"],))[0];members=q("select * from factory_audience_memberships where segment_id=? and account_reference=? and status='verified'",(target["audience_segment_id"],target["account_reference"]));committee_members=q("select * from factory_buying_committee_members where committee_id=? and status='verified'",(target["buying_committee_id"],));assert digest(json.loads(av["manifest_json"]))==av["manifest_hash"]==target["audience_manifest_hash"] and digest(json.loads(bv["manifest_json"]))==bv["manifest_hash"]==target["buying_manifest_hash"];assert {x["contact_hash"] for x in committee_members}<={x["contact_hash"] for x in members} and len(committee_members)==target["required_role_count"]
  for m in members:
   consent=q("select * from factory_identity_consents where id=?",(m["consent_id"],))[0];assert consent["status"]=="active" and consent["source_event_hash"]==m["consent_event_hash"]
  snap={"account_reference":committee["account_reference"],"audience":{"segment_number":q("select segment_number from factory_audience_segments where id=?",(target["audience_segment_id"],))[0]["segment_number"],"version_reference":av["version_reference"],"manifest_hash":av["manifest_hash"],"consented_member_hashes":sorted(x["contact_hash"] for x in members)},"buying_committee":{"committee_number":committee["committee_number"],"version_reference":bv["version_reference"],"manifest_hash":bv["manifest_hash"],"opportunity_number":committee["opportunity_source_number"],"member_hashes":sorted(x["contact_hash"] for x in committee_members)}};assert json.loads(target["source_snapshot_json"])==snap and digest(snap)==target["source_fingerprint"]
  target_plays=[x for x in plays if x["target_id"]==target["id"]];assert {x["committee_member_id"] for x in target_plays}=={x["id"] for x in committee_members}
  by_id={x["id"]:x for x in committee_members}
  for play in target_plays:
   m=by_id[play["committee_member_id"]];member_manifest={"member_number":m["member_number"],"role_code":m["role_code"],"role_name":m["role_name"],"contact_hash":m["contact_hash"],"role_fingerprint":m["role_fingerprint"],"contact_source_revision":m["contact_source_revision"],"contact_source_fingerprint":m["contact_source_fingerprint"],"preferred_channel":m["preferred_channel"],"revision":m["revision"]};assert digest(member_manifest)==play["member_fingerprint"];definition={"member_fingerprint":play["member_fingerprint"],"owner_team":play["owner_team"],"channel":play["channel"],"action_code":play["action_code"],"message_intent":play["message_intent"],"success_signal":play["success_signal"],"sequence_order":play["sequence_order"]};assert digest(definition)==play["definition_hash"]
 manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"] and version["target_count"]==len(targets) and version["role_play_count"]==len(plays) and version["role_coverage_percent"]==100;assert len(acts)==4 and {x["consumer"] for x in acts}=={"crm","marketing","ads","sales"} and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] and x["manifest_hash"]==version["manifest_hash"] for x in acts)
 ids=[program["id"],*[x["id"] for x in targets],*[x["id"] for x in plays],*[x["id"] for x in acts]];marks=",".join("?" for _ in ids);evidence=q(f"select * from factory_abm_evidence where subject_id in ({marks})",tuple(ids));assert {"program-created","target-added","target-verified","role-play-created","role-play-approved","program-published","activation-created","activation-acknowledged"}<={x["evidence_type"] for x in evidence};audits=q(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.abm.%'",tuple(ids));assert {"factory.abm.program.create","factory.abm.target.add","factory.abm.target.verify","factory.abm.play.create","factory.abm.play.approve","factory.abm.program.publish","factory.abm.activation.acknowledge"}<={x["action"] for x in audits}
 permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in q("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];assert {"factory.lead.abm.manage","factory.lead.abm.target.verify","factory.lead.abm.play.approve","factory.lead.abm.publish","factory.lead.abm.activation.acknowledge"}<=permissions
 print(json.dumps({"project_id":program["project_id"],"program_number":program["program_number"],"version_reference":version["version_reference"],"manifest_hash":version["manifest_hash"],"target_count":len(targets),"role_play_count":len(plays),"role_coverage_percent":version["role_coverage_percent"],"source_records_unchanged":True,"source_records_copied":False,"raw_identifier_stored":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
