"""Inspect the latest fully acknowledged customer behavior timeline."""
import argparse,hashlib,json,sqlite3
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--database",required=True);a=p.parse_args();db=sqlite3.connect(a.database);db.row_factory=sqlite3.Row;q=lambda sql,v=():[dict(x) for x in db.execute(sql,v).fetchall()]
 versions=q("select v.* from factory_customer_timeline_versions v where exists(select 1 from factory_customer_timeline_publications p where p.version_id=v.id) and not exists(select 1 from factory_customer_timeline_publications p where p.version_id=v.id and p.status!='acknowledged') order by v.published_at desc limit 1")
 if not versions:raise SystemExit("No fully acknowledged customer timeline found")
 version=versions[0];timeline=q("select * from factory_customer_timelines where id=? and status='published'",(version["timeline_id"],))[0];events=q("select * from factory_customer_timeline_events where timeline_id=? order by occurred_at",(timeline["id"],));checkpoints=q("select * from factory_customer_timeline_checkpoints where timeline_id=?",(timeline["id"],));pubs=q("select * from factory_customer_timeline_publications where version_id=?",(version["id"],));assert {x["source_type"] for x in events}=={"marketing-touchpoint","inquiry-flow","cpq-quote","fulfillment-order","service-ticket"} and all(x["status"]=="verified" and x["created_by"]!=x["verified_by"] for x in events);assert timeline["authored_by"]!=timeline["published_by"] and len(checkpoints)>=1
 for e in events:
  snap=json.loads(e["source_snapshot_json"]);assert digest(snap)==e["source_fingerprint"] and snap["account_reference"]==timeline["account_reference"]
  if e["source_type"]=="marketing-touchpoint":x=q("select * from factory_attribution_touchpoints where id=?",(e["source_id"],))[0];assert x["touchpoint_number"]==e["source_number"] and x["evidence_fingerprint"]==snap["evidence_fingerprint"]
  elif e["source_type"]=="inquiry-flow":x=q("select * from factory_revenue_flow_runs where id=?",(e["source_id"],))[0];assert x["correlation_id"]==e["source_number"] and x["revision"]==e["source_revision"] and x["current_stage"]==e["source_status"]
  elif e["source_type"]=="cpq-quote":x=q("select * from factory_cpq_quotes where id=?",(e["source_id"],))[0];assert x["quote_number"]==e["source_number"] and x["revision"]==e["source_revision"] and x["status"]==e["source_status"]
  elif e["source_type"]=="fulfillment-order":x=q("select * from factory_fulfillment_orders where id=?",(e["source_id"],))[0];assert x["order_number"]==e["source_number"] and x["revision"]==e["source_revision"] and x["status"]==e["source_status"]
  else:x=q("select * from factory_asset_service_tickets where id=?",(e["source_id"],))[0];asset=q("select * from factory_customer_assets where id=?",(x["asset_id"],))[0];assert x["ticket_number"]==e["source_number"] and x["revision"]==e["source_revision"] and asset["account_reference"]==timeline["account_reference"]
 manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"] and version["event_count"]==5 and version["source_type_count"]==5;assert len(pubs)==4 and {x["consumer"] for x in pubs}=={"crm","cdp","sales","service"} and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] and x["manifest_hash"]==version["manifest_hash"] for x in pubs)
 ids=[timeline["id"],*[x["id"] for x in events],*[x["id"] for x in checkpoints],*[x["id"] for x in pubs]];marks=",".join("?" for _ in ids);evidence=q(f"select * from factory_customer_timeline_evidence where subject_id in ({marks})",tuple(ids));assert {"timeline-created","event-added","event-verified","checkpoint-created","timeline-published","handoff-created","handoff-acknowledged"}<={x["evidence_type"] for x in evidence};audits=q(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.timeline.%'",tuple(ids));assert {"factory.timeline.create","factory.timeline.event.add","factory.timeline.event.verify","factory.timeline.checkpoint.create","factory.timeline.publish","factory.timeline.publication.acknowledge"}<={x["action"] for x in audits}
 permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in q("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];assert {"factory.portrait.timeline.manage","factory.portrait.timeline.event.verify","factory.portrait.timeline.checkpoint.manage","factory.portrait.timeline.publish","factory.portrait.timeline.handoff.acknowledge"}<=permissions
 print(json.dumps({"project_id":timeline["project_id"],"timeline_number":timeline["timeline_number"],"version_reference":version["version_reference"],"manifest_hash":version["manifest_hash"],"event_count":len(events),"source_type_count":5,"source_records_unchanged":True,"source_records_copied":False,"raw_tracking_identifier_stored":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
