"""Inspect the latest fully acknowledged AI SDR sales handoff."""
import argparse,hashlib,json,sqlite3
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--database",required=True);a=p.parse_args();db=sqlite3.connect(a.database);db.row_factory=sqlite3.Row;q=lambda sql,v=():[dict(x) for x in db.execute(sql,v).fetchall()]
 handoffs=q("select * from factory_ai_sdr_handoffs where status='acknowledged' order by acknowledged_at desc limit 1")
 if not handoffs:raise SystemExit("No fully acknowledged AI SDR handoff found")
 h=handoffs[0];r=q("select * from factory_ai_sdr_recommendations where id=? and status='approved'",(h["recommendation_id"],))[0];lead=q("select * from factory_ai_sdr_leads where id=?",(h["lead_id"],))[0];assessment=q("select * from factory_icp_fit_assessments where id=? and status='verified'",(lead["assessment_id"],))[0];profile=q("select * from factory_icp_profiles where id=? and status='active'",(lead["profile_id"],))[0];version=q("select * from factory_icp_versions where profile_id=? and version_number=? and status='active'",(profile["id"],lead["profile_version"]))[0];evidence=q("select * from factory_icp_account_evidence where id=? and verification_status='verified'",(assessment["account_evidence_id"],))[0]
 assert assessment["definition_hash"]==version["definition_hash"]==lead["definition_hash"] and assessment["profile_version"]==lead["profile_version"] and not assessment["disqualified"];assert digest(assessment["account_reference"])==lead["account_reference_hash"]
 source_tables={"cpq-quote":("factory_cpq_quotes","quote_number"),"fulfillment-order":("factory_fulfillment_orders","order_number"),"customer-asset":("factory_customer_assets","asset_number"),"voice-of-customer":("factory_voice_cases","voice_number")};table,number=source_tables[evidence["source_type"]];source=q(f"select * from {table} where id=? and project_id=?",(evidence["source_id"],lead["project_id"]))[0];assert int(source["revision"])==int(evidence["source_revision"])
 assert float(lead["fit_score"])==float(assessment["total_score"])
 snapshot={"assessment_number":assessment["assessment_number"],"profile_number":profile["profile_number"],"profile_version":assessment["profile_version"],"definition_hash":assessment["definition_hash"],"fit_tier":assessment["fit_tier"],"fit_score":lead["fit_score"],"account_reference_hash":digest(assessment["account_reference"]),"evidence_number":evidence["evidence_number"],"source_type":evidence["source_type"],"source_number":evidence["source_number"],"source_revision":evidence["source_revision"]};assert json.loads(lead["source_snapshot_json"])==snapshot
 output={"lead_number":lead["lead_number"],"model_reference":r["model_reference"],"prompt_hash":r["prompt_hash"],"enrichment_summary":r["enrichment_summary"],"intent_score":r["intent_score"],"qualification_proposal":r["qualification_proposal"],"reply_subject":r["reply_subject"],"reply_body":r["reply_body"],"next_action":r["next_action"]};assert digest(output)==r["output_hash"] and r["generated_by"]!=r["reviewed_by"] and r["review_reference"] and r["review_note"]
 manifest=json.loads(h["manifest_json"]);assert digest(manifest)==h["manifest_hash"] and manifest["output_hash"]==r["output_hash"] and manifest["definition_hash"]==lead["definition_hash"] and h["created_by"]!=h["acknowledged_by"] and not h["crm_mutated"]
 ids=[lead["id"],r["id"],h["id"]];marks=",".join("?" for _ in ids);ev=q(f"select * from factory_ai_sdr_evidence where subject_id in ({marks})",tuple(ids));assert {"lead-created","recommendation-generated","recommendation-reviewed","handoff-created","handoff-acknowledged"}<={x["evidence_type"] for x in ev};audits=q(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.ai-sdr.%'",tuple(ids));assert {"factory.ai-sdr.lead.create","factory.ai-sdr.recommendation.generate","factory.ai-sdr.recommendation.review","factory.ai-sdr.handoff.create","factory.ai-sdr.handoff.acknowledge"}<={x["action"] for x in audits}
 permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in q("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];assert {"factory.convert.ai-sdr.manage","factory.convert.ai-sdr.review","factory.convert.ai-sdr.handoff","factory.convert.ai-sdr.handoff.acknowledge"}<=permissions
 print(json.dumps({"project_id":lead["project_id"],"lead_number":lead["lead_number"],"recommendation_number":r["recommendation_number"],"handoff_number":h["handoff_number"],"manifest_hash":h["manifest_hash"],"fit_tier":lead["fit_tier"],"intent_score":r["intent_score"],"human_review_percent":100,"handoff_acknowledgement_percent":100,"source_records_unchanged":True,"source_records_copied":False,"raw_contact_identifier_stored":False,"prompt_content_stored":False,"crm_mutated":False,"evidence_count":len(ev),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
