"""Inspect the latest acknowledged knowledge-graph publication and source pins."""
import argparse,hashlib,json,sqlite3
def digest(payload):return hashlib.sha256(json.dumps(payload,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--database",required=True);args=parser.parse_args();db=sqlite3.connect(args.database);db.row_factory=sqlite3.Row;query=lambda sql,values=():[dict(x) for x in db.execute(sql,values).fetchall()]
    rows=query("select * from factory_knowledge_publications where status='acknowledged' order by acknowledged_at desc limit 1")
    if not rows:raise SystemExit("No acknowledged enterprise knowledge graph publication found")
    publication=rows[0];version=query("select * from factory_knowledge_graph_versions where id=? and status='published'",(publication["version_id"],))[0];graph=query("select * from factory_knowledge_graphs where id=? and status='published'",(publication["graph_id"],))[0];assert graph["authored_by"]!=graph["published_by"] and publication["created_by"]!=publication["acknowledged_by"] and not publication["consumer_mutated"];assert version["manifest_hash"]==publication["manifest_hash"]
    entity_manifest=json.loads(version["entity_manifest_json"]);relation_manifest=json.loads(version["relation_manifest_json"]);assert set(json.loads(version["entity_type_coverage_json"]))=={"organization","product","capability","certificate","case","market"} and len(relation_manifest)>=5
    source_tables={"legal-party":("factory_legal_parties","party_number","status"),"product-passport":("factory_product_passports","passport_number","lifecycle_status"),"passport-certificate":("factory_product_passport_certificates","certificate_number","verification_status"),"dam-asset":("factory_dam_assets","asset_number","status"),"icp-profile":("factory_icp_profiles","profile_number","status")};subject_ids=[graph["id"],publication["id"]];source_records=[]
    for manifest in entity_manifest:
        entity=query("select * from factory_knowledge_entities where id=? and status='verified'",(manifest["id"],))[0];assert entity["created_by"]!=entity["verified_by"] and manifest["source"]==entity["source_fingerprint"] and manifest["properties"]==digest(json.loads(entity["properties_json"]));table,number_field,status_field=source_tables[entity["source_type"]];source=query(f"select id,{number_field} as number,{status_field} as status,revision from {table} where id=? and project_id=?",(entity["source_id"],entity["project_id"]))[0];assert source["revision"]==entity["source_revision"] and source["status"]==entity["source_status"];source_records.append({"source_type":entity["source_type"],"source_number":source["number"],"revision":source["revision"],"status":source["status"]});subject_ids.append(entity["id"])
    for manifest in relation_manifest:
        relation=query("select * from factory_knowledge_relations where id=? and status='verified'",(manifest["id"],))[0];assert relation["created_by"]!=relation["verified_by"] and manifest["subject"]==relation["subject_entity_id"] and manifest["predicate"]==relation["predicate"] and manifest["object"]==relation["object_entity_id"];subject_ids.append(relation["id"])
    assert digest({"entities":entity_manifest,"relations":relation_manifest})==version["manifest_hash"];marks=",".join("?" for _ in subject_ids);evidence=query(f"select * from factory_knowledge_evidence where subject_id in ({marks})",tuple(subject_ids));types={x["evidence_type"] for x in evidence};assert {"graph-created","entity-ingested","entity-verified","relation-created","relation-verified","graph-published","publication-created","publication-acknowledged"}<=types;audits=query(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.knowledge.%'",tuple(subject_ids));actions={x["action"] for x in audits};assert {"factory.knowledge.graph.create","factory.knowledge.entity.ingest","factory.knowledge.entity.verify","factory.knowledge.relation.create","factory.knowledge.relation.verify","factory.knowledge.graph.publish","factory.knowledge.publication.acknowledge"}<=actions
    permissions=set()
    for role in query("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')"):permissions.update(json.loads(role["permissions_json"] or "[]"))
    required={"factory.recommend.knowledge.graph.manage","factory.recommend.knowledge.entity.verify","factory.recommend.knowledge.relation.manage","factory.recommend.knowledge.relation.verify","factory.recommend.knowledge.publish","factory.recommend.knowledge.handoff.acknowledge"};assert required<=permissions
    print(json.dumps({"project_id":graph["project_id"],"graph_number":graph["graph_number"],"version_number":version["version_number"],"manifest_hash":version["manifest_hash"],"entity_type_coverage":json.loads(version["entity_type_coverage_json"]),"relation_count":len(relation_manifest),"publication_number":publication["publication_number"],"consumer":publication["consumer"],"source_records":source_records,"source_records_unchanged":True,"engineering_master_copied":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
