"""Inspect the latest acknowledged golden profile and its privacy/source pins."""
import argparse,hashlib,json,sqlite3
def digest(payload):return hashlib.sha256(json.dumps(payload,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--database",required=True);args=parser.parse_args();db=sqlite3.connect(args.database);db.row_factory=sqlite3.Row;query=lambda sql,values=():[dict(x) for x in db.execute(sql,values).fetchall()]
    rows=query("select v.* from factory_golden_profile_versions v where not exists (select 1 from factory_identity_publications p where p.version_id=v.id and p.status!='acknowledged') and exists (select 1 from factory_identity_publications p where p.version_id=v.id) order by v.published_at desc limit 1")
    if not rows:raise SystemExit("No fully acknowledged golden identity profile found")
    version=rows[0];profile=query("select * from factory_golden_profiles where id=? and status='published'",(version["profile_id"],))[0];case=query("select * from factory_identity_match_cases where id=? and status='approved'",(profile["match_case_id"],))[0];signal_ids=json.loads(profile["member_signal_ids_json"]);marks=",".join("?" for _ in signal_ids);signals=query(f"select * from factory_identity_signals where id in ({marks}) and status='verified'",tuple(signal_ids));consent_ids=sorted({x["consent_id"] for x in signals});cmarks=",".join("?" for _ in consent_ids);consents=query(f"select * from factory_identity_consents where id in ({cmarks}) and status='active'",tuple(consent_ids));publications=query("select * from factory_identity_publications where version_id=?",(version["id"],))
    assert len(signals)>=3 and len(consents)>=1 and len(publications)==4 and {x["consumer_system"] for x in publications}=={"cdp","crm","ads","service"};assert all(len(x["identifier_hash"])==64 and all(c in "0123456789abcdef" for c in x["identifier_hash"]) and x["captured_by"]!=x["verified_by"] for x in signals);assert all(x["source_revision"]==next(c["revision"] for c in consents if c["id"]==x["consent_id"]) and x["source_fingerprint"]==next(c["source_event_hash"] for c in consents if c["id"]==x["consent_id"]) for x in signals);assert case["proposed_by"]!=case["decided_by"] and profile["authored_by"]!=profile["published_by"];assert all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] for x in publications)
    manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"]==profile["source_manifest_hash"] and digest(json.loads(profile["source_manifest_json"]))==profile["source_manifest_hash"]
    sensitive=("@consented.example","browser-fingerprint-secret");corpus=" ".join(str(value) for row in [*signals,*consents,*publications] for value in row.values() if value is not None);assert not any(marker in corpus for marker in sensitive)
    subject_ids=[profile["id"],case["id"],*[x["id"] for x in signals],*[x["id"] for x in consents],*[x["id"] for x in publications]];allmarks=",".join("?" for _ in subject_ids);evidence=query(f"select * from factory_identity_evidence where subject_id in ({allmarks})",tuple(subject_ids));types={x["evidence_type"] for x in evidence};assert {"consent-requested","consent-approved","signal-captured","signal-verified","match-proposed","match-approved","profile-created","profile-published","handoff-created","handoff-acknowledged"}<=types;audits=query(f"select * from audit_logs_platform where target_id in ({allmarks}) and action like 'factory.identity.%'",tuple(subject_ids));actions={x["action"] for x in audits};assert {"factory.identity.consent.create","factory.identity.consent.approve","factory.identity.signal.create","factory.identity.signal.verify","factory.identity.match.propose","factory.identity.match.decide","factory.identity.profile.create","factory.identity.profile.publish","factory.identity.handoff.acknowledge"}<=actions
    permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in query("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];required={"factory.portrait.identity.consent.manage","factory.portrait.identity.consent.approve","factory.portrait.identity.signal.manage","factory.portrait.identity.signal.verify","factory.portrait.identity.match.propose","factory.portrait.identity.match.decide","factory.portrait.identity.profile.publish","factory.portrait.identity.handoff.acknowledge"};assert required<=permissions
    print(json.dumps({"project_id":profile["project_id"],"profile_number":profile["profile_number"],"version_number_ref":version["version_number_ref"],"manifest_hash":version["manifest_hash"],"verified_signal_count":len(signals),"consumer_count":len(publications),"raw_identifier_stored":False,"source_records_unchanged":True,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
