"""Inspect the latest fully confirmed commerce handoff."""
import argparse,hashlib,json,sqlite3
from decimal import Decimal
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument("--database",required=True);a=p.parse_args();db=sqlite3.connect(a.database);db.row_factory=sqlite3.Row;q=lambda sql,v=():[dict(x) for x in db.execute(sql,v).fetchall()]
 handoffs=q("select * from factory_commerce_handoffs where status='confirmed' order by acknowledged_at desc limit 1")
 if not handoffs:raise SystemExit("No fully confirmed commerce handoff found")
 h=handoffs[0];c=q("select * from factory_commerce_checkouts where id=?",(h["checkout_id"],))[0];accept=q("select * from factory_commerce_acceptances where checkout_id=? and status='approved'",(c["id"],))[0];pay=q("select * from factory_commerce_payments where checkout_id=? and status='verified'",(c["id"],))[0]
 assert accept["recorded_by"]!=accept["reviewed_by"] and pay["initiated_by"]!=pay["verified_by"] and h["created_by"]!=h["acknowledged_by"] and not h["consumer_mutated"]
 acceptance_payload={"checkout_number":c["checkout_number"],"source_hash":c["source_hash"],"terms_version":accept["terms_version"],"locale":accept["locale"],"destination_country":accept["destination_country"],"fulfillment_mode":accept["fulfillment_mode"],"purchase_reference_hash":accept["purchase_reference_hash"],"acceptance_reference_hash":accept["acceptance_reference_hash"]};assert digest(acceptance_payload)==accept["acceptance_hash"]
 if c["source_type"]=="cpq-quote":
  source=q("select * from factory_cpq_quotes where id=? and project_id=? and status='accepted'",(c["source_id"],c["project_id"]))[0];lines=[{k:v for k,v in x.items() if k!="unit_cost"} for x in json.loads(source["lines_json"])];quantity=sum(Decimal(str(x.get("quantity",0))) for x in lines);snapshot={"source_number":source["quote_number"],"status":source["status"],"order_intent_id":source["order_intent_id"],"currency":source["currency"],"subtotal":f'{Decimal(str(source["subtotal"])):.2f}',"quantity":str(quantity),"lines":lines,"revision":source["revision"]}
 else:raise AssertionError("Acceptance proof requires B2B authoritative OMS chain")
 assert int(source["revision"])==int(c["source_revision"]) and json.loads(c["source_snapshot_json"])==snapshot and digest(snapshot)==c["source_hash"]
 manifest=json.loads(h["manifest_json"]);assert digest(manifest)==h["manifest_hash"] and manifest["source_hash"]==c["source_hash"] and manifest["acceptance_hash"]==accept["acceptance_hash"] and manifest["payment_number"]==pay["payment_number"] and Decimal(manifest["amount"])==Decimal(pay["amount"])
 order=q("select * from factory_fulfillment_orders where id=? and project_id=? and status='confirmed'",(h["authoritative_order_id"],c["project_id"]))[0];assert order["order_intent_id"]==h["order_intent_id"]==source["order_intent_id"] and order["quote_id"]==source["id"] and Decimal(order["order_total"])==Decimal(c["subtotal"]) and order["currency"]==c["currency"]
 ids=[c["id"],accept["id"],pay["id"],h["id"]];marks=",".join("?" for _ in ids);ev=q(f"select * from factory_commerce_evidence where subject_id in ({marks})",tuple(ids));assert {"checkout-created","terms-accepted","terms-reviewed","payment-intent-created","payment-verified","order-intent-submitted","order-decision-acknowledged"}<={x["evidence_type"] for x in ev};aud=q(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.commerce.%'",tuple(ids));assert {"factory.commerce.checkout.create","factory.commerce.terms.accept","factory.commerce.terms.review","factory.commerce.payment.create","factory.commerce.payment.verify","factory.commerce.order.submit","factory.commerce.order.acknowledge"}<={x["action"] for x in aud}
 permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in q("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];assert {"factory.convert.commerce.manage","factory.convert.commerce.terms.review","factory.convert.commerce.payment.verify","factory.convert.commerce.order.submit","factory.convert.commerce.order.acknowledge"}<=permissions
 columns={x[1] for x in db.execute("pragma table_info(factory_commerce_checkouts)")};assert not ({"buyer_name","email","phone","address","card_number","payment_secret"}&columns)
 print(json.dumps({"project_id":c["project_id"],"checkout_number":c["checkout_number"],"handoff_number":h["handoff_number"],"order_number":order["order_number"],"manifest_hash":h["manifest_hash"],"source_records_unchanged":True,"raw_buyer_identifier_stored":False,"payment_charge_created":False,"checkout_direct_order_confirmation":False,"terms_review_percent":100,"payment_verification_percent":100,"order_confirmation_percent":100,"evidence_count":len(ev),"audit_count":len(aud)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
