"""Inspect the latest fully acknowledged buying committee and its authority pins."""
import argparse,hashlib,json,sqlite3
from decimal import Decimal
def digest(payload):return hashlib.sha256(json.dumps(payload,ensure_ascii=False,sort_keys=True,separators=(",",":"),default=str).encode()).hexdigest()
def same_number(left,right):return Decimal(str(left))==Decimal(str(right))
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--database",required=True);args=parser.parse_args();db=sqlite3.connect(args.database);db.row_factory=sqlite3.Row;query=lambda sql,values=():[dict(x) for x in db.execute(sql,values).fetchall()]
    rows=query("select v.* from factory_buying_committee_versions v where exists (select 1 from factory_buying_committee_publications p where p.version_id=v.id) and not exists (select 1 from factory_buying_committee_publications p where p.version_id=v.id and p.status!='acknowledged') order by v.published_at desc limit 1")
    if not rows:raise SystemExit("No fully acknowledged buying committee found")
    version=rows[0];committee=query("select * from factory_buying_committees where id=? and status='published'",(version["committee_id"],))[0];members=query("select * from factory_buying_committee_members where committee_id=?",(committee["id"],));edges=query("select * from factory_buying_influence_edges where committee_id=?",(committee["id"],));publications=query("select * from factory_buying_committee_publications where version_id=?",(version["id"],));assert len(members)==version["required_role_count"]==version["member_count"] and len(members)>=3 and len(edges)>=len(members)-1;assert all(x["status"]=="verified" and x["created_by"]!=x["verified_by"] for x in members+edges);assert committee["authored_by"]!=committee["published_by"]
    quote=query("select * from factory_cpq_quotes where id=?",(committee["opportunity_source_id"],))[0];snapshot=json.loads(committee["opportunity_snapshot_json"]);assert snapshot["quote_number"]==quote["quote_number"] and snapshot["account_reference"]==quote["account_reference"] and snapshot["currency"]==quote["currency"] and snapshot["status"]==quote["status"] and snapshot["revision"]==quote["revision"];assert digest(snapshot)==committee["opportunity_fingerprint"] and same_number(snapshot["subtotal"],quote["subtotal"])
    profile=query("select * from factory_icp_profiles where id=?",(committee["icp_profile_id"],))[0];icp_version=query("select * from factory_icp_versions where profile_id=? and version_number=? and status='active'",(profile["id"],profile["current_version"]))[0];roles=query("select * from factory_icp_buying_roles where profile_id=?",(profile["id"],));assert committee["icp_profile_revision"]==profile["revision"] and committee["icp_definition_hash"]==icp_version["definition_hash"] and {x["role_id"] for x in members}=={x["id"] for x in roles}
    for member in members:
        role=next(x for x in roles if x["id"]==member["role_id"]);role_snapshot={"role_number":role["role_number"],"role_code":role["role_code"],"role_name":role["role_name"],"influence_type":role["influence_type"],"pains":json.loads(role["pains_json"]),"proof_requirements":json.loads(role["proof_requirements_json"]),"preferred_channels":json.loads(role["preferred_channels_json"])};assert digest(role_snapshot)==member["role_fingerprint"]
        signal=query("select * from factory_identity_signals where id=?",(member["contact_signal_id"],))[0];consent=query("select * from factory_identity_consents where id=? and status='active'",(signal["consent_id"],))[0];assert signal["status"]=="verified" and signal["account_reference"]==committee["account_reference"] and member["contact_hash"]==signal["identifier_hash"] and member["contact_source_revision"]==signal["revision"] and member["contact_source_fingerprint"]==signal["source_fingerprint"] and signal["source_revision"]==consent["revision"] and signal["source_fingerprint"]==consent["source_event_hash"]
    connected={x for edge in edges for x in (edge["from_member_id"],edge["to_member_id"])};assert connected=={x["id"] for x in members};manifest=json.loads(version["manifest_json"]);assert digest(manifest)==version["manifest_hash"];assert len(publications)==4 and {x["consumer"] for x in publications}=={"crm","sales","marketing","service"} and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] and x["manifest_hash"]==version["manifest_hash"] for x in publications)
    subject_ids=[committee["id"],*[x["id"] for x in members],*[x["id"] for x in edges],*[x["id"] for x in publications]];marks=",".join("?" for _ in subject_ids);evidence=query(f"select * from factory_buying_committee_evidence where subject_id in ({marks})",tuple(subject_ids));types={x["evidence_type"] for x in evidence};assert {"committee-created","member-created","member-verified","influence-created","influence-verified","committee-published","handoff-created","handoff-acknowledged"}<=types;audits=query(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.buying.%'",tuple(subject_ids));actions={x["action"] for x in audits};assert {"factory.buying.committee.create","factory.buying.member.create","factory.buying.member.verify","factory.buying.influence.create","factory.buying.influence.verify","factory.buying.committee.publish","factory.buying.publication.acknowledge"}<=actions
    permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in query("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];required={"factory.portrait.buying.committee.manage","factory.portrait.buying.member.verify","factory.portrait.buying.influence.manage","factory.portrait.buying.influence.verify","factory.portrait.buying.publish","factory.portrait.buying.handoff.acknowledge"};assert required<=permissions
    print(json.dumps({"project_id":committee["project_id"],"committee_number":committee["committee_number"],"version_reference":version["version_reference"],"manifest_hash":version["manifest_hash"],"member_count":len(members),"role_coverage_percent":100,"influence_edge_count":len(edges),"source_records_unchanged":True,"source_records_copied":False,"raw_contact_identifiers_stored":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
