"""Inspect the latest acknowledged multi-channel feed and source pins."""
import argparse,hashlib,json,sqlite3
def digest(payload):return hashlib.sha256(json.dumps(payload,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def main():
    parser=argparse.ArgumentParser();parser.add_argument("--database",required=True);args=parser.parse_args();db=sqlite3.connect(args.database);db.row_factory=sqlite3.Row;query=lambda sql,values=():[dict(x) for x in db.execute(sql,values).fetchall()]
    rows=query("select r.* from factory_channel_feed_releases r where not exists (select 1 from factory_channel_publications p where p.release_id=r.id and p.status!='acknowledged') and exists (select 1 from factory_channel_publications p where p.release_id=r.id) order by r.published_at desc limit 1")
    if not rows:raise SystemExit("No fully acknowledged multi-channel feed release found")
    release=rows[0];catalog=query("select * from factory_channel_catalogs where id=? and status='published'",(release["catalog_id"],))[0];run=query("select * from factory_channel_feed_runs where id=? and status='passed'",(release["run_id"],))[0];source=query("select * from factory_structured_data_releases where id=? and status='published'",(catalog["source_release_id"],))[0];publications=query("select * from factory_channel_publications where release_id=?",(release["id"],));assert len(publications)==4 and all(x["status"]=="acknowledged" and x["created_by"]!=x["acknowledged_by"] and not x["consumer_mutated"] for x in publications);assert catalog["authored_by"]!=catalog["published_by"]
    payload=json.loads(release["payload_json"]);assert digest(payload)==release["payload_hash"]==run["payload_hash"] and run["error_count"]==0 and release["channel_count"]==4 and release["listing_count"]==4;assert source["release_number"]==catalog["source_release_number"] and source["version_number"]==catalog["source_release_version"] and source["document_hash"]==catalog["source_document_hash"]==run["source_document_hash"] and digest(json.loads(source["document_json"]))==source["document_hash"]
    listings=query("select * from factory_channel_listings where catalog_id=? and status='validated'",(catalog["id"],));accounts=query("select * from factory_channel_accounts where id in (select account_id from factory_channel_listings where catalog_id=?)",(catalog["id"],));assert len(listings)==4 and len(accounts)==4 and {x["platform"] for x in accounts}=={"google-merchant","amazon","alibaba","industry-marketplace"};assert all(x["requested_by"]!=x["approved_by"] and x["status"]=="approved" and x["credential_reference"].startswith("vault://") for x in accounts);assert all(x["created_by"]!=x["validated_by"] and x["price_mode"]=="catalog-only" and x["price_amount"] is None and x["price_reference"] is None and x["inventory_mode"]=="on-request" and x["inventory_reference"] is None for x in listings)
    product=next(x for x in json.loads(source["document_json"])["@graph"] if x.get("@type")=="Product");assert all(x["product_identifier"]==str(product["identifier"]) and x["source_product_hash"]==digest(product) for x in listings);subject_ids=[catalog["id"],run["id"],*[x["id"] for x in accounts],*[x["id"] for x in listings],*[x["id"] for x in publications]];marks=",".join("?" for _ in subject_ids);evidence=query(f"select * from factory_channel_evidence where subject_id in ({marks})",tuple(subject_ids));types={x["evidence_type"] for x in evidence};assert {"account-requested","account-approved","catalog-created","listing-created","listing-validated","feed-passed","catalog-published","publication-created","publication-acknowledged"}<=types;audits=query(f"select * from audit_logs_platform where target_id in ({marks}) and action like 'factory.channel.%'",tuple(subject_ids));actions={x["action"] for x in audits};assert {"factory.channel.account.create","factory.channel.account.approve","factory.channel.catalog.create","factory.channel.listing.create","factory.channel.listing.validate","factory.channel.feed.execute","factory.channel.catalog.publish","factory.channel.publication.acknowledge"}<=actions
    permissions=set();[permissions.update(json.loads(x["permissions_json"] or "[]")) for x in query("select permissions_json from roles_platform where is_system=1 and scope in ('client','project')")];required={"factory.recommend.channel.account.manage","factory.recommend.channel.account.approve","factory.recommend.channel.catalog.manage","factory.recommend.channel.listing.validate","factory.recommend.channel.feed.execute","factory.recommend.channel.publish","factory.recommend.channel.handoff.acknowledge"};assert required<=permissions
    print(json.dumps({"project_id":catalog["project_id"],"catalog_number":catalog["catalog_number"],"release_number":release["release_number"],"payload_hash":release["payload_hash"],"channel_count":release["channel_count"],"listing_count":release["listing_count"],"source_release_number":source["release_number"],"source_records_unchanged":True,"credential_secret_stored":False,"product_master_copied":False,"consumer_system_mutated":False,"evidence_count":len(evidence),"audit_count":len(audits)},ensure_ascii=False,indent=2));db.close()
if __name__=="__main__":main()
