param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function S([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function P([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=S "hq";$agency=S "agency";$client=S "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff"
$reputation="/api/v1/factory-platform/projects/$ProjectId/reputation";$mention=P "$reputation/mentions" @{public_reference="https://public.example/listening-$stamp";channel="media";sentiment="negative";observed_on="2026-08-08"} $hh;$assessment=P "$reputation/mentions/$($mention.id)/assessments" @{assessment_manifest=@{summary="public issue requires service triage";response_required=$false}} $hh;$assessment=P "$reputation/assessments/$($assessment.id)/verify" @{expected_revision=$assessment.revision;reference="LISTEN-SOURCE-VERIFY-$stamp"} $ah
$root="/api/v1/factory-platform/projects/$ProjectId/social-listening";$signal=P $root @{signal_key="listening-$stamp";assessment_id=$assessment.id;signal_type="issue";priority="high"} $hh;$signal=P "$root/$($signal.id)/verify" @{expected_revision=$signal.revision;reference="LISTEN-VERIFY-$stamp"} $ah;$routed=P "$root/$($signal.id)/route" @{expected_revision=$signal.revision;reference="LISTEN-ROUTE-$stamp";destination="service-owner"} $ch;$handoff=P "$root/handoffs/$($routed.handoff.id)/acknowledge" @{expected_revision=$routed.handoff.revision;reference="LISTEN-ACK-$stamp"} $hh
if($handoff.status -ne "acknowledged"){throw "Listening handoff was not acknowledged."}
[pscustomobject]@{project_id=$ProjectId;signal_number=$routed.signal.signal_number;signal_status=$routed.signal.status;handoff_status=$handoff.status;source_public_reference=$mention.public_reference;private_messages_collected=$false;automatic_public_reply=$false;roles="hq,agency,client"}|ConvertTo-Json -Depth 8
