param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function S([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function G([string]$path,[hashtable]$headers){Invoke-RestMethod -Method Get -Uri "$BaseUrl$path" -Headers $headers}
function P([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=S "hq";$agency=S "agency";$client=S "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$financeRoot="/api/v1/factory-platform/projects/$ProjectId/finance";$finance=G $financeRoot $hh;$book=$finance.books|Where-Object status -eq "active"|Select-Object -First 1;$period=$finance.periods|Where-Object { $_.status -eq "open" -and $_.book_id -eq $book.id -and $_.period_start -le (Get-Date).ToString("yyyy-MM-dd") -and $_.period_end -ge (Get-Date).ToString("yyyy-MM-dd") }|Select-Object -First 1
if(!$book -or !$period){throw "Budget attribution acceptance requires an active finance book and matching open finance period."}
$budget=P "$financeRoot/documents" @{book_id=$book.id;period_id=$period.id;document_reference="BUDGET-ATTR-$stamp";document_type="budget";document_date=(Get-Date).ToString("yyyy-MM-dd");amount="1000";description="Approved marketing budget for attribution acceptance";source_evidence_reference="finance-budget:$stamp"} $hh;$budget=P "$financeRoot/documents/$($budget.id)/approve" @{expected_revision=$budget.revision;evidence_reference="FIN-BUDGET-APPROVE-$stamp"} $ah
$profit=G "/api/v1/factory-platform/projects/$ProjectId/revenue-profit" $hh;$run=$profit.analysis_runs|Where-Object status -eq "published"|Select-Object -First 1;if(!$run){throw "Budget attribution acceptance requires a published attribution analysis."}
$root="/api/v1/factory-platform/projects/$ProjectId/budget-attribution";$allocation=P $root @{allocation_reference="BUDGET-ALLOC-$stamp";finance_document_reference=$budget.document_reference;attribution_run_id=$run.id;channel="google";campaign_reference="search-product";proposed_amount="250"} $hh;$allocation=P "$root/$($allocation.id)/verify" @{expected_revision=$allocation.revision;reference="BUDGET-VERIFY-$stamp"} $ah;$allocation=P "$root/$($allocation.id)/accept" @{expected_revision=$allocation.revision;reference="BUDGET-ACCEPT-$stamp"} $ch
if($allocation.status -ne "accepted"){throw "Budget allocation was not accepted."}
[pscustomobject]@{project_id=$ProjectId;budget_document_status=$budget.status;attribution_run_status=$run.status;allocation_status=$allocation.status;external_ad_budget_changed=$false;automatic_bid_changed=$false;roles="hq,agency,client"}|ConvertTo-Json -Depth 8
