param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$Scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$Scope}|ConvertTo-Json -Compress)}
function Post([string]$Path,[hashtable]$Payload,[hashtable]$Headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$Path" -Headers $Headers -ContentType "application/json" -Body ($Payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$h=@{Authorization="Bearer $($hq.token)"};$a=@{Authorization="Bearer $($agency.token)"};$c=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/competitive-pricing"
$watch=Post "$root/watches" @{product_reference="ROBOT-CELL-$stamp";product_name="Global flexible robot cell";market_country="US";channel="distributor";currency="USD";own_reference_price=100;scope_note="Compare like-for-like governed public offers; this workflow never creates a customer quote."} $h
foreach($price in @(90,100,110)){$offer=Post "$root/watches/$($watch.id)/offers" @{competitor_name="Competitor-$price";competitor_offer_reference="SKU-$price";offer_type="list";offer_price=$price;freight_price=5;feature_summary="Comparable published configuration and delivery scope";source_system="acceptance-price-connector";source_reference="SOURCE-$price-$stamp";source_revision="2026.08-$stamp";source_observed_at=(Get-Date).ToUniversalTime().ToString("o")} $h;$offer=Post "$root/offers/$($offer.id)/verify" @{expected_revision=$offer.revision;verification_reference="AGENCY-PRICE-QA-$price-$stamp"} $a}
$decision=Post "$root/watches/$($watch.id)/decisions" @{boundary_note="Price band is market intelligence only. CPQ and finance price masters remain independent authoritative systems."} $h
$decision=Post "$root/decisions/$($decision.id)/review" @{expected_revision=$decision.revision;decision="approve";review_reference="CLIENT-PRICE-QA-$stamp"} $c
$release=Post "$root/decisions/$($decision.id)/releases" @{release_version="2026.08.$stamp";support_owner="factory-growth-operations";support_until=(Get-Date).AddDays(180).ToUniversalTime().ToString("o");customer_trial_reference="CUSTOMER-TRIAL-$stamp";role_training_reference="TRAINING-$stamp";issue_closure_reference="ISSUES-CLOSED-$stamp";monitoring_reference="MONITOR-$stamp";rollback_reference="ROLLBACK-$stamp"} $h
$release=Post "$root/releases/$($release.id)/approve" @{expected_revision=$release.revision;approval_reference="AGENCY-GA-APPROVAL-$stamp"} $a
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $h
[pscustomobject]@{project_id=$ProjectId;watch_number=$watch.watch_number;decision_number=$decision.decision_number;release_number=$release.release_number;release_version=$release.release_version;release_status=$release.status;available=$release.available;price_index=$decision.price_index;recommendation=$decision.recommendation;manifest_hash=$release.manifest_hash;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;availability=$workspace.availability;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
