param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$Scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$Scope}|ConvertTo-Json -Compress)}
function Post([string]$Path,[hashtable]$Payload,[hashtable]$Headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$Path" -Headers $Headers -ContentType "application/json" -Body ($Payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$h=@{Authorization="Bearer $($hq.token)"};$a=@{Authorization="Bearer $($agency.token)"};$c=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/market-radar"
$scan=Post "$root/scans" @{product_reference="ROBOT-CELL-$stamp";product_name="Global flexible robot cell";target_country="US";target_channel="distributor";objective="Validate demand, growth, competition, entry barriers and channel fit before country entry."} $h
$scores=@{demand=88;growth=84;competition=72;"entry-barrier"=78;"channel-fit"=82}
foreach($type in @("demand","growth","competition","entry-barrier","channel-fit")){$signal=Post "$root/scans/$($scan.id)/signals" @{signal_type=$type;normalized_score=$scores[$type];raw_value=1000+$scores[$type];measurement_unit="governed-index";source_system="acceptance-market-connector";source_reference="SOURCE-$type-$stamp";source_revision="2026.08-$stamp";source_observed_at=(Get-Date).ToUniversalTime().ToString("o")} $h;$signal=Post "$root/signals/$($signal.id)/verify" @{expected_revision=$signal.revision;verification_reference="AGENCY-SOURCE-QA-$type-$stamp"} $a}
$decision=Post "$root/scans/$($scan.id)/decisions" @{entry_gate_note="Tariff, certification, service capacity, distributor obligations and exit gates verified."} $h
$decision=Post "$root/decisions/$($decision.id)/review" @{expected_revision=$decision.revision;decision="approve";review_reference="CLIENT-MARKET-QA-$stamp"} $c
$release=Post "$root/decisions/$($decision.id)/releases" @{release_version="2026.08.$stamp";support_owner="factory-growth-operations";support_until=(Get-Date).AddDays(180).ToUniversalTime().ToString("o");customer_trial_reference="CUSTOMER-TRIAL-$stamp";role_training_reference="TRAINING-$stamp";issue_closure_reference="ISSUES-CLOSED-$stamp";monitoring_reference="MONITOR-$stamp";rollback_reference="ROLLBACK-$stamp"} $h
$release=Post "$root/releases/$($release.id)/approve" @{expected_revision=$release.revision;approval_reference="AGENCY-GA-APPROVAL-$stamp"} $a
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $h
[pscustomobject]@{project_id=$ProjectId;scan_number=$scan.scan_number;decision_number=$decision.decision_number;release_number=$release.release_number;release_version=$release.release_version;release_status=$release.status;available=$release.available;opportunity_score=$decision.opportunity_score;manifest_hash=$release.manifest_hash;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;availability=$workspace.availability;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
