param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 10 -Compress)}
$hq=Session hq;$agency=Session agency;$client=Session client;$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/brand-studio"
$made=Post "$root/profiles" @{brand_name="ForgeFlow $stamp";market_scope="global";audience="Industrial automation decision makers";positioning="Reliable flexible automation partner";value_promise="Evidence-backed throughput and service delivery";tone="expert and practical";visual_tokens=@{primary="#0f766e";font="Inter";layout="evidence-first"};messaging=@{headline="Automation with evidence";cta="Review capability proof"}} $hh;$profile=$made.profile
foreach($index in 1..2){$claim=Post "$root/profiles/$($profile.id)/claims" @{claim_type="capability";claim_text="Verified factory capability $index";evidence_reference="BRAND-PROOF-$index-$stamp"} $hh;$claim=Post "$root/claims/$($claim.id)/verify" @{expected_revision=$claim.revision;reference="BRAND-QA-$index-$stamp"} $ah}
$profile=Post "$root/profiles/$($profile.id)/approve" @{expected_revision=$profile.revision;reference="BRAND-OWNER-$stamp"} $ah
$release=Post "$root/profiles/$($profile.id)/releases" @{release_version="2026.08.$stamp";support_owner="brand-ops";support_until=(Get-Date).AddDays(180).ToUniversalTime().ToString("o");customer_trial_reference="BRAND-TRIAL-$stamp";role_training_reference="BRAND-TRAIN-$stamp";issue_closure_reference="BRAND-ISSUES-$stamp";monitoring_reference="BRAND-MON-$stamp";rollback_reference="BRAND-ROLLBACK-$stamp"} $hh
$release=Post "$root/releases/$($release.id)/approve" @{expected_revision=$release.revision;reference="BRAND-GA-$stamp"} $ch
$w=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh;[pscustomobject]@{profile_number=$profile.profile_number;profile_status=$profile.status;release_number=$release.release_number;release_available=$release.available;availability=$w.availability.status;website_published=$w.contract.website_published;protected_brand_configuration_overwritten=$w.contract.protected_brand_configuration_overwritten;verified_claim_percent=$w.metrics.verified_claim_percent;evidence_count=$w.evidence.Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id}|ConvertTo-Json
