param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/account-graph";$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
$legal=$workspace.sources|Where-Object {$_.source_type -eq "legal-party"}|Select-Object -First 1;if(-not $legal){throw "Missing active legal party"};$legalQuote=$workspace.sources|Where-Object {$_.source_type -eq "cpq-quote" -and $_.account_reference -eq $legal.account_reference}|Select-Object -First 1;if(-not $legalQuote){throw "Missing legal-party CPQ opportunity"}
$profile=$workspace.sources|Where-Object {$_.source_type -eq "golden-profile"}|Select-Object -First 1;if(-not $profile){throw "Missing published golden profile"};$contact=$workspace.sources|Where-Object {$_.source_type -eq "identity-signal" -and $_.account_reference -eq $profile.account_reference}|Select-Object -First 1;if(-not $contact){throw "Missing consented contact signal"}
$order=$workspace.sources|Where-Object {$_.source_type -eq "fulfillment-order" -and $_.related_source_id}|Select-Object -First 1;if(-not $order){throw "Missing fulfillment order source"};$orderQuote=$workspace.sources|Where-Object {$_.source_type -eq "cpq-quote" -and $_.source_id -eq $order.related_source_id}|Select-Object -First 1;if(-not $orderQuote){throw "Missing source quote for fulfillment order"}
$graph=Post "$root/graphs" @{graph_code="ACCOUNT-360-$stamp";graph_name="Global governed B2B account graph";scope="account-360"} $hh;$nodes=@{}
foreach($spec in @(@{key="legal";source=$legal},@{key="legalQuote";source=$legalQuote},@{key="account";source=$profile},@{key="contact";source=$contact},@{key="orderQuote";source=$orderQuote},@{key="order";source=$order})){$node=Post "$root/graphs/$($graph.id)/nodes" @{source_type=$spec.source.source_type;source_id=$spec.source.source_id} $hh;$node=Post "$root/nodes/$($node.id)/verify" @{expected_revision=$node.revision;reference="ACCOUNT-NODE-VERIFY-$($spec.key)-$stamp"} $ah;$nodes[$spec.key]=$node}
$edges=@();foreach($spec in @(@{left="legal";right="legalQuote";relation="has-opportunity"},@{left="account";right="contact";relation="contact-at"},@{left="orderQuote";right="order";relation="fulfills"})){$edge=Post "$root/graphs/$($graph.id)/edges" @{from_node_id=$nodes[$spec.left].id;to_node_id=$nodes[$spec.right].id;relation_type=$spec.relation;strength="strong";evidence_reference="ACCOUNT-RELATION-$($spec.relation)-$stamp"} $hh;$edge=Post "$root/edges/$($edge.id)/verify" @{expected_revision=$edge.revision;reference="ACCOUNT-RELATION-VERIFY-$($spec.relation)-$stamp"} $ah;$edges+=$edge}
$published=Post "$root/graphs/$($graph.id)/publish" @{expected_revision=$graph.revision;consumers=@("crm","cdp","sales","service");delivery_reference_prefix="ACCOUNT-GRAPH-$stamp"} $ah;$publications=@();if($LeavePendingReceipt){$publications=$published.publications}else{foreach($publication in $published.publications){$publications+=Post "$root/publications/$($publication.id)/acknowledge" @{expected_revision=$publication.revision;reference="ACCOUNT-GRAPH-ACK-$($publication.consumer)-$stamp"} $ch}}
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;graph_number=$published.graph.graph_number;version_reference=$published.version.version_reference;manifest_hash=$published.version.manifest_hash;node_count=$published.version.node_count;edge_count=$published.version.edge_count;consumer_count=$publications.Count;acknowledged_publications=($publications|Where-Object {$_.status -eq "acknowledged"}).Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
