param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$kg="/api/v1/factory-platform/projects/$ProjectId/knowledge-graph"
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$kg" -Headers $hh;$graph=Post "$kg/graphs" @{graph_code="ENTERPRISE-$stamp";graph_name="Global enterprise truth graph";scope="enterprise";default_locale="zh-CN";objective="Publish source-pinned enterprise facts for GEO, structured data and AI retrieval."} $hh
$specs=@(@{type="organization";key="org";props=@{role="manufacturer"}},@{type="product";key="product";props=@{offering="robot-cell"}},@{type="capability";key="capability";props=@{capability="flexible-assembly"}},@{type="certificate";key="certificate";props=@{assurance="verified"}},@{type="case";key="case";props=@{proof="authorized-content"}},@{type="market";key="market";props=@{segment="evidence-backed-ICP"}});$entities=@{}
foreach($spec in $specs){$source=$workspace.source_candidates|Where-Object {$_.allowed_entity_types -contains $spec.type}|Select-Object -First 1;if(-not $source){throw "Missing authoritative source candidate for $($spec.type)"};$entity=Post "$kg/graphs/$($graph.id)/entities" @{entity_key="$($spec.key)-$stamp";entity_type=$spec.type;canonical_name=$source.suggested_name;aliases=@();properties=$spec.props;locale="en-US";source_type=$source.source_type;source_id=$source.source_id;evidence_reference="SOURCE-PIN-$($spec.type)-$stamp"} $hh;$entity=Post "$kg/entities/$($entity.id)/verify" @{expected_revision=$entity.revision;reference="ENTITY-VERIFY-$($spec.type)-$stamp"} $ah;$entities[$spec.type]=$entity}
$relationSpecs=@(@("organization","offers","product"),@("product","has-capability","capability"),@("product","certified-by","certificate"),@("product","proven-by","case"),@("market","demands","product"));$relations=@()
foreach($spec in $relationSpecs){$relation=Post "$kg/graphs/$($graph.id)/relations" @{subject_entity_id=$entities[$spec[0]].id;predicate=$spec[1];object_entity_id=$entities[$spec[2]].id;evidence_reference="RELATION-$($spec[1])-$stamp"} $hh;$relation=Post "$kg/relations/$($relation.id)/verify" @{expected_revision=$relation.revision;reference="RELATION-VERIFY-$($spec[1])-$stamp"} $ah;$relations+=$relation}
$published=Post "$kg/graphs/$($graph.id)/publish" @{expected_revision=$graph.revision;consumer="geo";delivery_reference="GEO-GRAPH-PAYLOAD-$stamp"} $ah;$publication=Post "$kg/publications/$($published.publication.id)/acknowledge" @{expected_revision=$published.publication.revision;reference="GEO-CONSUMER-ACK-$stamp"} $ch;$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$kg" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;graph_number=$published.graph.graph_number;graph_status=$published.graph.status;version_reference=$published.version.version_reference;version_number=$published.version.version_number;manifest_hash=$published.version.manifest_hash;entity_types=$published.version.entity_type_coverage_json;verified_relations=$relations.Count;publication_number=$publication.publication_number;publication_status=$publication.status;consumer=$publication.consumer;consumer_mutated=$publication.consumer_mutated;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
