param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 8 -Compress)}
$hq=Session "hq";$agency=Session "agency";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$suffix=$stamp.Substring($stamp.Length-8)
$people="/api/v1/factory-platform/projects/$ProjectId/people";$rec="/api/v1/factory-platform/projects/$ProjectId/recruiting"
$org=Post "$people/org-units" @{unit_reference="ACC-REC-ORG-$stamp";unit_code="REC-$suffix";unit_name="Recruiting acceptance $suffix";unit_type="company";parent_unit_id=$null;erp_operating_unit_id=$null;country_code="CN";timezone_name="Asia/Shanghai"} $hh
$org=Post "$people/org-units/$($org.id)/approve" @{expected_revision=$org.revision;evidence_reference="ACC-REC-ORG-APPROVAL-$stamp"} $ah
$position=Post "$people/positions" @{org_unit_id=$org.id;position_reference="ACC-REC-POS-$stamp";position_code="RPOS-$suffix";position_title="Export Solution Engineer";job_family="Engineering";employment_level="L5";planned_headcount=1;weekly_capacity_hours="40";critical_role=$true} $hh
$req=Post "$rec/requisitions" @{requisition_reference="ACC-REQ-$stamp";position_id=$position.id;opening_count=1;employment_type="full-time";work_location="Shanghai";target_start_date="2027-01-15";hiring_reason="Approved export engineering capacity requirement.";rubric_version="RUBRIC-2026-V1";rubric=@{skills="Technical depth";evidence="Cited evidence";communication="Buyer communication";integrity="Compliance judgment"}} $hh
$req=Post "$rec/requisitions/$($req.id)/approve" @{expected_revision=$req.revision;evidence_reference="ACC-REQ-APPROVAL-$stamp"} $ah
$candidate=Post "$rec/candidates" @{candidate_reference="ACC-CAN-$stamp";display_name="Acceptance Candidate";email="candidate-$stamp@example.com";country_code="CN";source_type="candidate-direct";source_reference="CAREERS-$stamp";consent_reference="CONSENT-$stamp";privacy_notice_reference="PRIVACY-2026-V1";retention_until="2027-12-31";profile_reference="ATS-PROFILE-$stamp"} $hh
$app=Post "$rec/applications" @{requisition_id=$req.id;candidate_id=$candidate.id;application_reference="ACC-APP-$stamp";submitted_evidence_reference="PORTAL-$stamp"} $hh
$scheduled=(Get-Date).AddDays(3).ToUniversalTime().ToString("o");$interview=Post "$rec/interviews" @{application_id=$app.id;interview_type="structured-ai-assisted";scheduled_at=$scheduled;interviewer_reference="PANEL-$stamp"} $hh
$result=Post "$rec/interviews/$($interview.id)/complete" @{expected_revision=$interview.revision;skills_score="92";evidence_score="88";communication_score="90";integrity_score="94";transcript_reference="TRANSCRIPT-$stamp";citation_references=@("ANSWER-2-$stamp","ANSWER-5-$stamp");assessor_comment="Evidence-backed structured assessment acceptance.";ai_assisted=$true;ai_model_reference="INTERVIEW-MODEL-2026-V1"} $hh
$ws=Invoke-RestMethod -Method Get -Uri "$BaseUrl$rec" -Headers $hh;$app=$ws.applications|Where-Object {$_.id -eq $app.id}|Select-Object -First 1
$app=Post "$rec/applications/$($app.id)/decide" @{expected_revision=$app.revision;decision="advance";decision_reason="Independent human committee approved evidence-based advancement.";decision_reference="COMMITTEE-$stamp"} $ah
$offer=Post "$rec/offers" @{application_id=$app.id;offer_reference="ACC-OFFER-$stamp";proposed_start_date="2027-02-01";compensation_band="CN-L5-BAND";offer_document_reference="OFFER-DOC-$stamp"} $hh
$offer=Post "$rec/offers/$($offer.id)/approve" @{expected_revision=$offer.revision;evidence_reference="OFFER-APPROVAL-$stamp"} $ah
$offer=Post "$rec/offers/$($offer.id)/send" @{expected_revision=$offer.revision;evidence_reference="OFFER-DELIVERY-$stamp"} $hh
$offer=Post "$rec/offers/$($offer.id)/respond" @{expected_revision=$offer.revision;response="accepted";response_reference="CANDIDATE-ACCEPT-$stamp"} $hh
$ws=Invoke-RestMethod -Method Get -Uri "$BaseUrl$rec" -Headers $hh;$handoff=$ws.onboarding_handoffs|Where-Object {$_.offer_id -eq $offer.id}|Select-Object -First 1
$employee=Post "$people/employees" @{employee_reference="ACC-EMP-$stamp";preferred_name="Acceptance Employee";work_email="employee-$stamp@factory.example";country_code="CN";source_type="recruiting-offer";source_reference=$handoff.source_reference;privacy_notice_reference="EMPLOYEE-PRIVACY-$stamp"} $hh
$employee=Post "$people/employees/$($employee.id)/activate" @{expected_revision=$employee.revision;evidence_reference="IDENTITY-$stamp"} $ah
[pscustomobject]@{project_id=$ProjectId;requisition_number=$req.requisition_number;candidate_number=$candidate.candidate_number;interview_number=$interview.interview_number;overall_score=$result.assessment.overall_score;offer_number=$offer.offer_number;offer_status=$offer.status;handoff_number=$handoff.handoff_number;employee_number=$employee.employee_number;employee_status=$employee.status;author=$hq.user.id;approver=$agency.user.id;independent_approval=($hq.user.id -ne $agency.user.id);ai_autonomous_decision=$result.assessment.ai_autonomous_decision}|ConvertTo-Json -Depth 6
