param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 10 -Compress)}
$hq=Session hq;$agency=Session agency;$client=Session client;$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/digital-assets"
$plan=Post "$root/plans" @{business_goal="Launch a verified industrial B2B site $stamp";target_market="Germany";target_audience="Industrial automation procurement teams";site_scope="Product proof and contact content"} $hh
$suggestion=Post "$root/plans/$($plan.id)/suggestions" @{suggestion_type="site-map";recommendation=@{pages=@("home","products","proof","contact")};source_reference="DIGITAL-RESEARCH-$stamp"} $hh
$suggestion=Post "$root/suggestions/$($suggestion.id)/review" @{expected_revision=$suggestion.revision;reference="DIGITAL-AI-QA-$stamp"} $ah
$asset=Post "$root/plans/$($plan.id)/assets" @{asset_kind="domain";asset_identifier="forgeflow-$stamp.example";ownership_reference="DIGITAL-DOMAIN-$stamp";rights_scope="Global industrial B2B marketing"} $hh
$asset=Post "$root/assets/$($asset.id)/approve" @{expected_revision=$asset.revision;reference="DIGITAL-RIGHTS-QA-$stamp"} $ah
$plan=Post "$root/plans/$($plan.id)/approve" @{expected_revision=$plan.revision;reference="DIGITAL-PLAN-QA-$stamp"} $ah
$handoff=Post "$root/plans/$($plan.id)/handoffs" @{release_version="2026.08.$stamp";support_owner="digital-ops";support_until=(Get-Date).AddDays(180).ToUniversalTime().ToString("o");customer_trial_reference="DIGITAL-TRIAL-$stamp";role_training_reference="DIGITAL-TRAIN-$stamp";issue_closure_reference="DIGITAL-ISSUES-$stamp";monitoring_reference="DIGITAL-MON-$stamp";rollback_reference="DIGITAL-ROLLBACK-$stamp"} $hh
$handoff=Post "$root/handoffs/$($handoff.id)/approve" @{expected_revision=$handoff.revision;reference="DIGITAL-GA-$stamp"} $ch
$w=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh;[pscustomobject]@{plan_number=$plan.plan_number;plan_status=$plan.status;suggestion_status=$suggestion.status;asset_status=$asset.status;handoff_number=$handoff.handoff_number;handoff_available=$handoff.available;availability=$w.availability.status;ai_can_approve=$w.contract.ai_can_approve;registrar_secret_stored=$w.contract.registrar_secret_stored;domain_purchase_or_transfer_automated=$w.contract.domain_purchase_or_transfer_automated;website_published=$w.contract.website_published;protected_site_configuration_overwritten=$w.contract.protected_site_configuration_overwritten;evidence_count=$w.evidence.Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id}|ConvertTo-Json
