param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"}
$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$cpq="/api/v1/factory-platform/projects/$ProjectId/cpq-quotes";$icp="/api/v1/factory-platform/projects/$ProjectId/icp-profiles";$valid=(Get-Date).AddDays(60).ToUniversalTime().ToString("o")
$quote=Post $cpq @{account_reference="ICP-BUYER-$stamp";currency="USD";exchange_rate=1;valid_until=$valid;lines=@(@{product_reference="ROBOT-CELL";sku_reference="ROBOT-CELL-01";quantity=10;moq=1;unit_price=35000;unit_cost=22000;lead_time_days=45})} $hh
$created=Post $icp @{profile_code="GLOBAL-AUTOMATION-$stamp";profile_name="Global automation factories";market_mode="global";customer_type="b2b";objective="Identify evidence-backed industrial automation accounts for coordinated growth.";countries=@("US","DE","CN");industries=@("industrial-automation");company_size_bands=@("500-5000");product_references=@("ROBOT-CELL");required_roles=@("CFO","CTO","plant-manager");buying_triggers=@("capacity-expansion");minimum_potential_value=200000;currency="USD";scoring_weights=@{country=10;industry=15;company_size=10;product=20;role=15;trigger=15;value=15}} $hh
$profile=$created.profile
foreach($role in @(@{code="CFO";name="Economic buyer";type="economic-buyer"},@{code="CTO";name="Technical buyer";type="technical-buyer"},@{code="plant-manager";name="Plant champion";type="champion"})){Post "$icp/$($profile.id)/roles" @{role_code=$role.code;role_name=$role.name;influence_type=$role.type;pains=@("Capacity constraint");proof_requirements=@("Verified ROI");preferred_channels=@("Account workshop")} $hh|Out-Null}
foreach($scenario in @(@{code="expansion";name="Capacity expansion";trigger="capacity-expansion"},@{code="renewal";name="Equipment renewal";trigger="equipment-renewal"})){Post "$icp/$($profile.id)/scenarios" @{scenario_code=$scenario.code;scenario_name=$scenario.name;job_to_be_done="Expand safe production capacity with measurable payback.";buying_trigger=$scenario.trigger;product_references=@("ROBOT-CELL");success_outcomes=@("Higher throughput");disqualifiers=@("No executive sponsor")} $hh|Out-Null}
$profile=Post "$icp/$($profile.id)/approve" @{expected_revision=$profile.revision;reference="ICP-COMMITTEE-$stamp"} $ah
$evidence=Post "$icp/$($profile.id)/account-evidence" @{source_type="cpq-quote";source_id=$quote.id;firmographic_country="US";firmographic_industry="industrial-automation";firmographic_company_size="500-5000";firmographic_evidence_reference="FIRMOGRAPHIC-$stamp";observed_roles=@("CFO","CTO");observed_triggers=@("capacity-expansion");observed_products=@("ROBOT-CELL")} $hh
$evidence=Post "$icp/account-evidence/$($evidence.id)/verify" @{expected_revision=$evidence.revision;reference="ICP-EVIDENCE-QA-$stamp"} $ah
$assessment=Post "$icp/$($profile.id)/assessments" @{account_evidence_id=$evidence.id} $hh
$assessment=Post "$icp/assessments/$($assessment.id)/verify" @{expected_revision=$assessment.revision;reference="ICP-FIT-QA-$stamp"} $ah
$activation=Post "$icp/$($profile.id)/activations" @{consumer="lead-routing";minimum_fit_tier="B";delivery_reference="ICP-ROUTING-PAYLOAD-$stamp"} $hh
$activation=Post "$icp/activations/$($activation.id)/acknowledge" @{expected_revision=$activation.revision;reference="ICP-CONSUMER-ACK-$stamp"} $ch
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$icp" -Headers $hh;$quotes=Invoke-RestMethod -Method Get -Uri "$BaseUrl$cpq" -Headers $hh;$source=$quotes.items|Where-Object {$_.id -eq $quote.id}|Select-Object -First 1
[pscustomobject]@{project_id=$ProjectId;profile_number=$profile.profile_number;profile_status=$profile.status;account_evidence_number=$evidence.evidence_number;evidence_status=$evidence.verification_status;assessment_number=$assessment.assessment_number;fit_score=$assessment.total_score;fit_tier=$assessment.fit_tier;assessment_status=$assessment.status;activation_number=$activation.activation_number;activation_status=$activation.status;consumer=$activation.consumer;source_number=$source.quote_number;source_status=$source.status;source_revision=$source.revision;source_record_unchanged=($source.status -eq "draft" -and $source.revision -eq $quote.revision);hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
