param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 8 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/cpq-quotes"
$quote=Post $root @{account_reference="CPQ-BUYER-$stamp";currency="USD";exchange_rate=1;valid_until=(Get-Date).ToUniversalTime().AddDays(30).ToString("o");lines=@(@{product_reference="PUMP-001";sku_reference="PUMP-001-380V";quantity=10;moq=5;unit_price=100;unit_cost=70;lead_time_days=30})} $hh
$quote=Post "$root/$($quote.id)/transition" @{expected_revision=$quote.revision;action="submit"} $hh;$quote=Post "$root/$($quote.id)/transition" @{expected_revision=$quote.revision;action="approve";note="Margin and lead time independently approved $stamp"} $ah;$quote=Post "$root/$($quote.id)/transition" @{expected_revision=$quote.revision;action="send"} $hh;$quote=Post "$root/$($quote.id)/transition" @{expected_revision=$quote.revision;action="accept"} $ch
if($quote.status -ne "accepted" -or -not $quote.order_intent_id -or (@($quote.emitted_events|ForEach-Object {$_.eventType}) -join ",") -ne "quote-submitted,quote-accepted"){throw "CPQ acceptance did not preserve the required event and order-intent contract"}
[pscustomobject]@{project_id=$ProjectId;quote_number=$quote.quote_number;status=$quote.status;order_intent_id=$quote.order_intent_id;events=@($quote.emitted_events|ForEach-Object {$_.eventType});hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id}|ConvertTo-Json -Depth 6
