param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
function Digest([string]$value){$sha=[System.Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($value)))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/identity-resolution";$account="ACCOUNT-$ProjectId-$stamp"
$consent=Post "$root/consents" @{subject_reference="CONTACT-$stamp";account_reference=$account;consent_reference="CMP-CONSENT-$stamp";lawful_basis="consent";purposes=@("customer-identity","service-personalization");expires_at=(Get-Date).ToUniversalTime().AddDays(365).ToString("o")} $hh
$consent=Post "$root/consents/$($consent.id)/approve" @{expected_revision=$consent.revision;reference="DPO-APPROVAL-$stamp"} $ah
$signals=@();foreach($spec in @(@{type="account";raw=$account;hint="acct"},@{type="email";raw="buyer-$stamp@consented.example";hint="mail"},@{type="device";raw="browser-fingerprint-secret-$stamp";hint="dev"})){$signal=Post "$root/signals" @{consent_id=$consent.id;signal_type=$spec.type;identifier_hash=(Digest $spec.raw);display_hint=$spec.hint;source_type="consent-event";source_reference=$consent.consent_reference;source_revision=$consent.revision;source_fingerprint=$consent.source_event_hash} $hh;$signal=Post "$root/signals/$($signal.id)/verify" @{expected_revision=$signal.revision;reference="IDENTITY-VERIFY-$($spec.type)-$stamp"} $ah;$signals+=$signal}
$case=Post "$root/matches" @{account_reference=$account;signal_ids=@($signals|ForEach-Object {$_.id});match_method="deterministic";match_score=100;reasons=@("same governed account","consent and source fingerprint match")} $hh
$case=Post "$root/matches/$($case.id)/decide" @{expected_revision=$case.revision;decision="approved";reference="IDENTITY-STEWARD-$stamp"} $ah
$profile=Post "$root/matches/$($case.id)/profiles" @{} $hh
$published=Post "$root/profiles/$($profile.id)/publish" @{expected_revision=$profile.revision;consumers=@("cdp","crm","ads","service");remote_reference_prefix="GOLDEN-PROFILE-$stamp"} $ah
$publications=@();if($LeavePendingReceipt){$publications=$published.publications}else{foreach($publication in $published.publications){$publications+=Post "$root/publications/$($publication.id)/acknowledge" @{expected_revision=$publication.revision;reference="IDENTITY-CONSUMER-ACK-$($publication.consumer_system)-$stamp"} $ch}}
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;consent_number=$consent.consent_number;case_number=$case.case_number;profile_number=$published.profile.profile_number;version_number_ref=$published.version.version_number_ref;manifest_hash=$published.version.manifest_hash;signal_count=$signals.Count;consumer_count=$publications.Count;acknowledged_publications=($publications|Where-Object {$_.status -eq "acknowledged"}).Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
