param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
function Digest([string]$value){$sha=[System.Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($value)))).Replace("-","").ToLowerInvariant()}finally{$sha.Dispose()}}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/buying-committee";$identity="/api/v1/factory-platform/projects/$ProjectId/identity-resolution"
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh;$used=@($workspace.committees|ForEach-Object {$_.opportunity_source_id});$opportunity=$workspace.sources.opportunities|Where-Object {$_.status -eq "accepted" -and $used -notcontains $_.id}|Select-Object -First 1;if(-not $opportunity){$opportunity=$workspace.sources.opportunities|Where-Object {$used -notcontains $_.id}|Select-Object -First 1};if(-not $opportunity){throw "Missing unused active CPQ opportunity"};$profile=$workspace.sources.profiles|Where-Object {$_.roles.Count -ge 3}|Select-Object -First 1;if(-not $profile){throw "Missing active ICP profile with at least three roles"}
$consent=Post "$identity/consents" @{subject_reference="BUYING-COMMITTEE-$stamp";account_reference=$opportunity.account_reference;consent_reference="BUYING-CONSENT-$stamp";lawful_basis="consent";purposes=@("sales-committee");expires_at=(Get-Date).ToUniversalTime().AddDays(365).ToString("o")} $hh;$consent=Post "$identity/consents/$($consent.id)/approve" @{expected_revision=$consent.revision;reference="BUYING-DPO-$stamp"} $ah
$signals=@();for($i=0;$i -lt $profile.roles.Count;$i++){$signal=Post "$identity/signals" @{consent_id=$consent.id;signal_type="contact";identifier_hash=(Digest "buying-contact-$stamp-$i");display_hint="buyer-$($i+1)";source_type="consent-event";source_reference=$consent.consent_reference;source_revision=$consent.revision;source_fingerprint=$consent.source_event_hash} $hh;$signals+=Post "$identity/signals/$($signal.id)/verify" @{expected_revision=$signal.revision;reference="BUYING-CONTACT-VERIFY-$i-$stamp"} $ah}
$committee=Post "$root/committees" @{committee_name="Governed buying committee $stamp";opportunity_source_id=$opportunity.id;icp_profile_id=$profile.id} $hh;$members=@();for($i=0;$i -lt $profile.roles.Count;$i++){$member=Post "$root/committees/$($committee.id)/members" @{role_id=$profile.roles[$i].id;contact_signal_id=$signals[$i].id;influence_score=(90-$i*5);relationship_strength="strong";stance="supportive";preferred_channel="meeting";evidence_reference="DISCOVERY-$i-$stamp"} $hh;$members+=Post "$root/members/$($member.id)/verify" @{expected_revision=$member.revision;reference="BUYING-MEMBER-VERIFY-$i-$stamp"} $ah}
$edges=@();for($i=0;$i -lt $members.Count-1;$i++){$edge=Post "$root/committees/$($committee.id)/influences" @{from_member_id=$members[$i].id;to_member_id=$members[$i+1].id;influence_direction="influences";strength="strong";evidence_reference="INFLUENCE-$i-$stamp"} $hh;$edges+=Post "$root/influences/$($edge.id)/verify" @{expected_revision=$edge.revision;reference="BUYING-INFLUENCE-VERIFY-$i-$stamp"} $ah}
$published=Post "$root/committees/$($committee.id)/publish" @{expected_revision=$committee.revision;consumers=@("crm","sales","marketing","service");delivery_reference_prefix="BUYING-COMMITTEE-$stamp"} $ah;$publications=@();if($LeavePendingReceipt){$publications=$published.publications}else{foreach($publication in $published.publications){$publications+=Post "$root/publications/$($publication.id)/acknowledge" @{expected_revision=$publication.revision;reference="BUYING-COMMITTEE-ACK-$($publication.consumer)-$stamp"} $ch}};$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;committee_number=$published.committee.committee_number;version_reference=$published.version.version_reference;manifest_hash=$published.version.manifest_hash;required_role_count=$published.version.required_role_count;member_count=$members.Count;influence_edge_count=$edges.Count;consumer_count=$publications.Count;acknowledged_publications=($publications|Where-Object {$_.status -eq "acknowledged"}).Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
