param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function S([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function P([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=S "hq";$agency=S "agency";$client=S "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff"
$crm="/api/v1/factory-platform/projects/$ProjectId/crm";$account=P "$crm/accounts" @{account_reference="COMMUNITY-ACCOUNT-$stamp";account_name="B2B Dealer $stamp";market="global"} $hh;$account=P "$crm/accounts/$($account.id)/verify" @{expected_revision=$account.revision;reference="COMMUNITY-CRM-VERIFY-$stamp";note="Independent B2B account eligibility verification"} $ah
$root="/api/v1/factory-platform/projects/$ProjectId/communities";$community=P $root @{community_key="community-$stamp";account_id=$account.id;community_name="Dealer Circle $stamp";audience_kind="dealer"} $hh;$community=P "$root/$($community.id)/verify" @{expected_revision=$community.revision;reference="COMMUNITY-VERIFY-$stamp"} $ah;$activation=P "$root/$($community.id)/activations" @{activation_key="activation-$stamp";event_title="Product education $stamp";event_type="education";scheduled_on="2026-09-01"} $ch;$activation=P "$root/activations/$($activation.id)/approve" @{expected_revision=$activation.revision;reference="COMMUNITY-APPROVE-$stamp"} $ah;$activation=P "$root/activations/$($activation.id)/acknowledge" @{expected_revision=$activation.revision;reference="COMMUNITY-ACK-$stamp"} $hh
if($activation.status -ne "acknowledged"){throw "Community activation was not acknowledged."}
[pscustomobject]@{project_id=$ProjectId;community_status=$community.status;activation_status=$activation.status;member_personal_data_stored=$false;automatic_member_contact_dispatched=$false;roles="hq,agency,client"}|ConvertTo-Json -Depth 8
