param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$feed="/api/v1/factory-platform/projects/$ProjectId/channel-feed"
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$feed" -Headers $hh;$source=$workspace.source_releases|Select-Object -First 1;if(-not $source){throw "Missing published structured-data release"};$product=$source.products|Select-Object -First 1;if(-not $product){throw "Missing Product JSON-LD node"}
$accounts=@();foreach($platform in @("google-merchant","amazon","alibaba","industry-marketplace")){$account=Post "$feed/accounts" @{platform=$platform;account_reference="$($platform.ToUpper())-$stamp";credential_reference="vault://factory-channel/$platform/$stamp";territory="GLOBAL";locale="en-US";currency="USD"} $hh;$account=Post "$feed/accounts/$($account.id)/approve" @{expected_revision=$account.revision;reference="CHANNEL-SECURITY-APPROVAL-$platform-$stamp"} $ah;$accounts+=$account}
$catalog=Post "$feed/catalogs" @{catalog_code="GLOBAL-FEED-$stamp";catalog_name="Global governed multi-channel feed";source_release_id=$source.id;default_locale="en-US"} $hh;$listings=@()
foreach($account in $accounts){$listing=Post "$feed/catalogs/$($catalog.id)/listings" @{account_id=$account.id;external_sku="ROBOT-$($account.platform.ToUpper())-$stamp";product_identifier=$product.identifier;price_mode="catalog-only";price_amount=$null;currency=$null;price_reference=$null;inventory_mode="on-request";availability_status="on_request";inventory_reference=$null;channel_attributes=@{category="industrial-automation";condition="new"}} $hh;$listing=Post "$feed/listings/$($listing.id)/validate" @{expected_revision=$listing.revision;reference="CHANNEL-LISTING-VALIDATE-$($account.platform)-$stamp"} $ah;$listings+=$listing}
$run=Post "$feed/catalogs/$($catalog.id)/feed-runs" @{expected_revision=$catalog.revision;reference="MULTI-CHANNEL-FEED-VALIDATOR-$stamp"} $ah;$published=Post "$feed/catalogs/$($catalog.id)/publish" @{expected_revision=$catalog.revision;run_id=$run.id;remote_reference_prefix="CHANNEL-DEPLOY-$stamp"} $ah;$publications=@()
if($LeavePendingReceipt){$publications=$published.publications}else{foreach($publication in $published.publications){$publications+=Post "$feed/publications/$($publication.id)/acknowledge" @{expected_revision=$publication.revision;reference="CHANNEL-CONSUMER-ACK-$($publication.account_number)-$stamp"} $ch}}
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$feed" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;catalog_number=$published.catalog.catalog_number;catalog_status=$published.catalog.status;release_number=$published.release.release_number;version_number=$published.release.version_number;payload_hash=$published.release.payload_hash;channel_count=$published.release.channel_count;listing_count=$published.release.listing_count;run_number=$run.run_number;run_status=$run.status;error_count=$run.error_count;acknowledged_publications=($publications|Where-Object {$_.status -eq "acknowledged"}).Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
