param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$sd="/api/v1/factory-platform/projects/$ProjectId/structured-data"
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$sd" -Headers $hh;$version=$workspace.graph_versions|Select-Object -First 1;if(-not $version){throw "Missing published knowledge graph version"}
$bundle=Post "$sd/bundles" @{bundle_code="GLOBAL-SCHEMA-$stamp";bundle_name="Global governed JSON-LD bundle";target_site_reference="CLIENT-SOURCE-WEBSITE";default_locale="en-US";graph_version_id=$version.id} $hh
$specs=@(@{schema="Organization";entity="organization";target="name"},@{schema="Product";entity="product";target="name"},@{schema="FAQPage";entity="capability";target="mainEntity"},@{schema="Review";entity="case";target="itemReviewed"},@{schema="Article";entity="market";target="headline"});$mappings=@()
foreach($spec in $specs){$entity=$workspace.graph_entities|Where-Object {$_.graph_id -eq $version.graph_id -and $_.entity_type -eq $spec.entity}|Select-Object -First 1;if(-not $entity){throw "Missing verified graph entity $($spec.entity)"};$fieldMap=@{identifier="entity_number"};$fieldMap[$spec.target]="canonical_name";$mapping=Post "$sd/bundles/$($bundle.id)/mappings" @{schema_type=$spec.schema;source_entity_id=$entity.id;field_map=$fieldMap;required_fields=@($spec.target)} $hh;$mapping=Post "$sd/mappings/$($mapping.id)/verify" @{expected_revision=$mapping.revision;reference="SCHEMA-MAPPING-VERIFY-$($spec.schema)-$stamp"} $ah;$mappings+=$mapping}
$validation=Post "$sd/bundles/$($bundle.id)/validate" @{expected_revision=$bundle.revision;validation_reference="SCHEMA-VALIDATOR-$stamp"} $ah
$published=Post "$sd/bundles/$($bundle.id)/publish" @{expected_revision=$bundle.revision;validation_id=$validation.id;consumer="website";deployment_reference="WEBSITE-SCHEMA-DEPLOY-$stamp"} $ah
$publication=if($LeavePendingReceipt){$published.publication}else{Post "$sd/publications/$($published.publication.id)/acknowledge" @{expected_revision=$published.publication.revision;reference="WEBSITE-SCHEMA-ACK-$stamp"} $ch}
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$sd" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;bundle_number=$published.bundle.bundle_number;bundle_status=$published.bundle.status;release_number=$published.release.release_number;version_number=$published.release.version_number;document_hash=$published.release.document_hash;schema_types=$published.release.schema_types_json;validation_number=$validation.validation_number;validation_status=$validation.status;error_count=$validation.error_count;publication_number=$publication.publication_number;publication_status=$publication.status;consumer=$publication.consumer;consumer_mutated=$publication.consumer_mutated;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
