param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff"
$revenueRoot="/api/v1/factory-platform/projects/$ProjectId/revenue-flow";$flow=Post $revenueRoot @{product_reference="RFQ-ROBOT-CELL-$stamp";account_reference="PRIVATE-BUYER-$stamp";currency="USD"} $hh;$flow=Post "$revenueRoot/$($flow.id)/transition" @{expected_revision=$flow.revision;event_type="inquiry-created"} $hh
$root="/api/v1/factory-platform/projects/$ProjectId/rfq-samples";$case=Post "$root/cases" @{source_flow_id=$flow.id;objective="Validate customer technical scope before commercial commitment"} $hh;$target=(Get-Date).AddDays(14).ToString("yyyy-MM-dd");$requirement=Post "$root/cases/$($case.id)/requirements" @{requirement_code="VALIDATION-$stamp";requirement_name="Customer validation scope";specification="480V three phase, IP67 enclosure and customer acceptance protocol";quantity=2;target_date=$target;critical=$true} $hh;$requirement=Post "$root/requirements/$($requirement.id)/approve" @{expected_revision=$requirement.revision;approval_reference="TECH-QA-$stamp"} $ah
$promise=(Get-Date).AddDays(7).ToUniversalTime().ToString("o");$sample=Post "$root/cases/$($case.id)/samples" @{sample_code="SAMPLE-$stamp";requirement_ids=@($requirement.id);quantity=2;unit_cost="125.50";currency="USD";promised_at=$promise} $ah;$sample=Post "$root/samples/$($sample.id)/approve" @{expected_revision=$sample.revision;approval_reference="SAMPLE-QA-$stamp"} $ch;$sample=Post "$root/samples/$($sample.id)/dispatch" @{expected_revision=$sample.revision;shipping_reference="SHIP-$stamp"} $hh
$feedback=Post "$root/samples/$($sample.id)/feedback" @{outcome="accepted";quality_score=96;feedback_note="Customer confirms the sample meets every approved requirement";conversion_intent=$true} $ah;$feedback=Post "$root/feedback/$($feedback.id)/acknowledge" @{expected_revision=$feedback.revision;acknowledgement_reference="SALES-ACK-$stamp"} $ch;$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;rfq_number=$case.rfq_number;requirement_number=$requirement.requirement_number;sample_number=$sample.sample_number;feedback_number=$feedback.feedback_number;feedback_hash=$feedback.feedback_hash;source_flow_id=$flow.id;source_revision=$flow.revision;source_stage=$flow.current_stage;requirement_review_percent=$workspace.metrics.requirement_review_percent;feedback_acknowledgement_percent=$workspace.metrics.feedback_acknowledgement_percent;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
