param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"}
$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$cpq="/api/v1/factory-platform/projects/$ProjectId/cpq-quotes";$approval="/api/v1/factory-platform/projects/$ProjectId/approval-center";$legal="/api/v1/factory-platform/projects/$ProjectId/contract-legal"
$valid=(Get-Date).AddDays(30).ToUniversalTime().ToString("o")
$quote=Post $cpq @{account_reference="LEGAL-BUYER-$stamp";currency="USD";exchange_rate=1;valid_until=$valid;lines=@(@{product_reference="LEGAL-PRODUCT-$stamp";sku_reference="LEGAL-SKU-$stamp";quantity=12;moq=1;unit_price=1800;unit_cost=1000;lead_time_days=30})} $hh
$created=Post "$approval/workflows" @{workflow_code="LEGAL-CPQ-$stamp";workflow_name="Contract source approval";subject_type="cpq-quote";steps=@(@{name="Commercial independent review";assignee_reference=$agency.user.id;due_hours=8},@{name="Finance independent review";assignee_reference=$client.user.id;due_hours=20});sla_hours=24;allow_delegation=$true} $hh
$workflow=Post "$approval/workflows/$($created.workflow.id)/approve" @{expected_revision=$created.workflow.revision;evidence_reference="LEGAL-WORKFLOW-APPROVAL-$stamp"} $ah
$approvalRequest=Post "$approval/requests" @{workflow_id=$workflow.id;subject_id=$quote.id;subject_revision=$quote.revision;request_reference="LEGAL-SOURCE-$stamp";business_reason="Customer contract source requires ordered commercial and finance approval.";evidence_reference="LEGAL-SOURCE-PACK-$stamp"} $hh
$approvalRequest=Post "$approval/requests/$($approvalRequest.id)/review" @{expected_revision=$approvalRequest.revision;decision="approve";reason="Commercial reviewer confirms customer, margin and source evidence.";evidence_reference="LEGAL-COMMERCIAL-$stamp";channel="web"} $ah
$approvalRequest=Post "$approval/requests/$($approvalRequest.id)/review" @{expected_revision=$approvalRequest.revision;decision="approve";reason="Finance reviewer independently confirms exposure and payment assumptions.";evidence_reference="LEGAL-FINANCE-$stamp";channel="web"} $ch
$approvalWorkspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$approval" -Headers $hh;$handoff=$approvalWorkspace.handoffs|Where-Object {$_.request_id -eq $approvalRequest.id}|Select-Object -First 1
$handoff=Post "$approval/handoffs/$($handoff.id)/acknowledge" @{expected_revision=$handoff.revision;evidence_reference="LEGAL-DOMAIN-ACK-$stamp"} $ah
$party=Post "$legal/parties" @{party_reference=$quote.account_reference;party_type="customer";legal_name="Legal buyer $stamp";country_code="CN";identity_key="REGISTRATION-$stamp";registration_reference="REGISTRY-EVIDENCE-$stamp";tax_profile_reference="TAX-EVIDENCE-$stamp";registered_address_reference="ADDRESS-EVIDENCE-$stamp";source_type="cpq-quote";source_id=$quote.id;kyb_evidence_reference="KYB-EVIDENCE-$stamp";sanctions_screening_reference="SCREENING-EVIDENCE-$stamp"} $hh
$party=Post "$legal/parties/$($party.id)/approve" @{expected_revision=$party.revision;evidence_reference="PARTY-APPROVAL-$stamp"} $ah
$templateCreated=Post "$legal/templates" @{template_code="CUSTOMER-SALES-$stamp";template_name="Governed international sales contract";contract_type="customer-sales";language_code="en";governing_law="PRC law";dispute_resolution="Negotiation followed by agreed institutional arbitration";clauses=@(@{title="Scope";body="Approved source defines goods, specifications, quantity and commercial scope."},@{title="Delivery";body="Delivery and acceptance require milestone evidence and customer confirmation."},@{title="Payment";body="Payment timing, default remedies and dispute handling follow this controlled contract."});document_reference="TEMPLATE-DOCUMENT-$stamp"} $hh
$template=Post "$legal/templates/$($templateCreated.template.id)/approve" @{expected_revision=$templateCreated.template.revision;evidence_reference="TEMPLATE-APPROVAL-$stamp"} $ah
$effective=(Get-Date).ToString("yyyy-MM-dd");$expiry=(Get-Date).AddYears(1).ToString("yyyy-MM-dd")
$contract=Post "$legal/contracts" @{contract_reference="LEGAL-CONTRACT-$stamp";party_id=$party.id;template_id=$template.id;source_type="cpq-quote";source_id=$quote.id;approval_handoff_id=$handoff.id;effective_date=$effective;expiry_date=$expiry;auto_renew=$false;notice_days=30;draft_document_reference="CONTRACT-DRAFT-$stamp"} $hh
$contract=Post "$legal/contracts/$($contract.id)/submit" @{expected_revision=$contract.revision;evidence_reference="CONTRACT-SUBMIT-$stamp"} $hh
$reviewed=Post "$legal/contracts/$($contract.id)/review" @{expected_revision=$contract.revision;risk_level="low";deviations=@(@{clause="Delivery";position="Customer requested staged acceptance";resolution="Staged acceptance milestones added to controlled schedule"});recommendation="approve";legal_comment="Independent legal review confirms party, authority, source, clauses and controlled deviations.";review_evidence_reference="LEGAL-REVIEW-$stamp"} $ah
$contract=$reviewed.contract
$seal=Post "$legal/seals" @{contract_id=$contract.id;seal_type="contract-seal";document_hash=("a"*64);purpose="Single-document seal use for independently reviewed customer contract."} $hh
$seal=Post "$legal/seals/$($seal.id)/approve" @{expected_revision=$seal.revision;evidence_reference="SEAL-APPROVAL-$stamp"} $ah
$seal=Post "$legal/seals/$($seal.id)/use" @{expected_revision=$seal.revision;evidence_reference="SEAL-USE-$stamp"} $hh
$envelope=Post "$legal/signatures" @{contract_id=$contract.id;seal_authorization_id=$seal.id;provider_reference="trusted-esign-provider";provider_envelope_reference="PROVIDER-ENVELOPE-$stamp";signers=@($agency.user.id,$client.user.id);signed_document_reference="SIGNED-DOCUMENT-$stamp"} $hh
$envelope=Post "$legal/signatures/$($envelope.id)/send" @{expected_revision=$envelope.revision;evidence_reference="SIGN-DELIVERY-$stamp"} $hh
$envelope=Post "$legal/signatures/$($envelope.id)/record" @{expected_revision=$envelope.revision;signer_reference=$agency.user.id;provider_event_reference="PROVIDER-EVENT-A-$stamp";signature_evidence_reference="SIGNATURE-A-$stamp"} $ah
$envelope=Post "$legal/signatures/$($envelope.id)/record" @{expected_revision=$envelope.revision;signer_reference=$client.user.id;provider_event_reference="PROVIDER-EVENT-C-$stamp";signature_evidence_reference="SIGNATURE-C-$stamp"} $ch
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$legal" -Headers $hh;$contract=$workspace.contracts|Where-Object {$_.id -eq $contract.id}|Select-Object -First 1
$due=(Get-Date).AddMonths(3).ToString("yyyy-MM-dd")
$delivery=Post "$legal/obligations" @{contract_id=$contract.id;obligation_reference="DELIVERY-$stamp";obligation_type="delivery";title="Delivery and acceptance";description="Complete delivery and preserve customer acceptance evidence.";owner_reference=$agency.user.id;due_date=$due} $hh
$payment=Post "$legal/obligations" @{contract_id=$contract.id;obligation_reference="PAYMENT-$stamp";obligation_type="payment";title="Payment collection";description="Collect the contract payment and preserve bank evidence.";owner_reference=$agency.user.id;due_date=$due} $hh
$delivery=Post "$legal/obligations/$($delivery.id)/complete" @{expected_revision=$delivery.revision;evidence_reference="DELIVERY-COMPLETE-$stamp"} $ah
$payment=Post "$legal/obligations/$($payment.id)/waive" @{expected_revision=$payment.revision;evidence_reference="PAYMENT-WAIVER-$stamp"} $ch
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$legal" -Headers $hh;$quotes=Invoke-RestMethod -Method Get -Uri "$BaseUrl$cpq" -Headers $hh;$source=$quotes.items|Where-Object {$_.id -eq $quote.id}|Select-Object -First 1
[pscustomobject]@{project_id=$ProjectId;contract_number=$contract.contract_number;contract_status=$contract.status;party_number=$party.party_number;template_number=$template.template_number;review_number=$reviewed.review.review_number;seal_number=$seal.seal_number;seal_status=$seal.status;envelope_number=$envelope.envelope_number;envelope_status=$envelope.status;obligation_fulfillment_percent=$workspace.metrics.obligation_fulfillment_percent;source_number=$source.quote_number;source_status=$source.status;source_revision=$source.revision;source_record_unchanged=($source.status -eq "draft" -and $source.revision -eq $quote.revision);hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id}|ConvertTo-Json -Depth 6
