param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function S([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function P([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=S "hq";$agency=S "agency";$client=S "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff"
$community="/api/v1/factory-platform/projects/$ProjectId/communities";$work=Invoke-RestMethod -Method Get -Uri "$BaseUrl$community" -Headers $hh;$activation=$work.activations|Where-Object {$_.status -eq "acknowledged"}|Select-Object -First 1;if(-not $activation){throw "An acknowledged community activation is required."}
$root="/api/v1/factory-platform/projects/$ProjectId/influence";$brief=P $root @{brief_key="influence-$stamp";activation_id=$activation.id;advocate_role="expert";topic="Product education $stamp"} $hh;$brief=P "$root/$($brief.id)/verify" @{expected_revision=$brief.revision;reference="INFLUENCE-VERIFY-$stamp"} $ah;$authorized=P "$root/$($brief.id)/authorize" @{expected_revision=$brief.revision;reference="INFLUENCE-AUTH-$stamp";destination="event-owner"} $ch;$release=P "$root/releases/$($authorized.release.id)/acknowledge" @{expected_revision=$authorized.release.revision;reference="INFLUENCE-ACK-$stamp"} $hh
if($release.status -ne "acknowledged"){throw "Influence release was not acknowledged."}
[pscustomobject]@{project_id=$ProjectId;brief_status=$authorized.brief.status;release_status=$release.status;advocate_personal_data_stored=$false;testimonial_or_endorsement_fabricated=$false;external_livestream_started=$false;roles="hq,agency,client"}|ConvertTo-Json -Depth 8
