param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1,[switch]$LeavePendingReceipt)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 12 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"};$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$root="/api/v1/factory-platform/projects/$ProjectId/segments-consent";$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh;$used=@($workspace.memberships|ForEach-Object {$_.contact_signal_id});$source=$workspace.sources|Where-Object {$used -notcontains $_.contact_signal_id -and $_.consent_purposes.Count -gt 0 -and $_.source_types.Count -eq 5}|Select-Object -First 1;if(-not $source){throw "Missing unused verified contact with active consent and published five-source timeline"}
$segment=Post "$root/segments" @{segment_code="CONSENT-HIGH-INTENT-$stamp";segment_name="Governed consented high-intent factories $stamp";business_purpose="Coordinate consented complex B2B sales and service";allowed_channels=@("crm","marketing","ads","service")} $hh;$rule=Post "$root/segments/$($segment.id)/rules" @{rule_code="CONSENTED-JOURNEY";rule_name="Consented verified high-intent journey";minimum_high_intent_events=1;required_source_types=@("marketing-touchpoint","inquiry-flow","cpq-quote","fulfillment-order","service-ticket");required_consent_purposes=@($source.consent_purposes[0])} $hh;$rule=Post "$root/rules/$($rule.id)/approve" @{expected_revision=$rule.revision;reference="SEGMENT-RULE-APPROVE-$stamp"} $ah
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh;$members=@();foreach($candidate in $workspace.sources){if($used -contains $candidate.contact_signal_id){continue};if(@($rule.required_consent_purposes_json|Where-Object {$candidate.consent_purposes -notcontains $_}).Count -gt 0){continue};$member=Post "$root/segments/$($segment.id)/memberships" @{rule_id=$rule.id;contact_signal_id=$candidate.contact_signal_id} $hh;$members+=Post "$root/memberships/$($member.id)/verify" @{expected_revision=$member.revision;reference="SEGMENT-MEMBER-VERIFY-$stamp"} $ah};if($members.Count -lt 1){throw "No consent-eligible member was evaluated"}
$published=Post "$root/segments/$($segment.id)/publish" @{expected_revision=$segment.revision;consumers=@("crm","marketing","ads","service");delivery_reference_prefix="CONSENT-SEGMENT-$stamp"} $ah;$acks=@();if($LeavePendingReceipt){$acks=$published.activations}else{foreach($activation in $published.activations){$acks+=Post "$root/activations/$($activation.id)/acknowledge" @{expected_revision=$activation.revision;reference="SEGMENT-ACTIVATION-ACK-$($activation.consumer)-$stamp"} $ch}};$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$root" -Headers $hh
[pscustomobject]@{project_id=$ProjectId;segment_number=$published.segment.segment_number;version_reference=$published.version.version_reference;manifest_hash=$published.version.manifest_hash;member_count=$published.version.member_count;consumer_count=$acks.Count;acknowledged_activations=($acks|Where-Object {$_.status -eq "acknowledged"}).Count;hq=$hq.user.id;agency=$agency.user.id;client=$client.user.id;contract=$workspace.contract;metrics=$workspace.metrics}|ConvertTo-Json -Depth 8
