param([string]$BaseUrl="http://127.0.0.1:8000",[int]$ProjectId=1)
$ErrorActionPreference="Stop"
function Session([string]$scope){Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/auth/local/demo-session" -ContentType "application/json" -Body (@{scope=$scope}|ConvertTo-Json -Compress)}
function Post([string]$path,[hashtable]$payload,[hashtable]$headers){Invoke-RestMethod -Method Post -Uri "$BaseUrl$path" -Headers $headers -ContentType "application/json" -Body ($payload|ConvertTo-Json -Depth 10 -Compress)}
$hq=Session "hq";$agency=Session "agency";$client=Session "client";$hh=@{Authorization="Bearer $($hq.token)"};$ah=@{Authorization="Bearer $($agency.token)"};$ch=@{Authorization="Bearer $($client.token)"}
$stamp=Get-Date -Format "yyyyMMddHHmmssfff";$cpq="/api/v1/factory-platform/projects/$ProjectId/cpq-quotes";$approval="/api/v1/factory-platform/projects/$ProjectId/approval-center"
$valid=(Get-Date).AddDays(30).ToUniversalTime().ToString("o")
$quote=Post $cpq @{account_reference="APPROVAL-BUYER-$stamp";currency="USD";exchange_rate=1;valid_until=$valid;lines=@(@{product_reference="APPROVAL-PRODUCT-$stamp";sku_reference="APPROVAL-SKU-$stamp";quantity=10;moq=1;unit_price=1500;unit_cost=900;lead_time_days=30})} $hh
$created=Post "$approval/workflows" @{workflow_code="CPQ-GOV-$stamp";workflow_name="High value CPQ governance";subject_type="cpq-quote";steps=@(@{name="Commercial independent review";assignee_reference=$agency.user.id;due_hours=8},@{name="Finance independent review";assignee_reference=$client.user.id;due_hours=20});sla_hours=24;allow_delegation=$true} $hh
$workflow=Post "$approval/workflows/$($created.workflow.id)/approve" @{expected_revision=$created.workflow.revision;evidence_reference="WORKFLOW-APPROVAL-$stamp"} $ah
$request=Post "$approval/requests" @{workflow_id=$workflow.id;subject_id=$quote.id;subject_revision=$quote.revision;request_reference="CPQ-REQUEST-$stamp";business_reason="High value customer quote requires ordered independent approval.";evidence_reference="CPQ-RISK-PACK-$stamp"} $hh
$request=Post "$approval/requests/$($request.id)/review" @{expected_revision=$request.revision;decision="approve";reason="Commercial reviewer confirms margin and customer evidence.";evidence_reference="COMMERCIAL-APPROVAL-$stamp";channel="mobile"} $ah
$request=Post "$approval/requests/$($request.id)/review" @{expected_revision=$request.revision;decision="approve";reason="Finance reviewer independently confirms exposure and margin.";evidence_reference="FINANCE-APPROVAL-$stamp";channel="web"} $ch
$workspace=Invoke-RestMethod -Method Get -Uri "$BaseUrl$approval" -Headers $hh;$handoff=$workspace.handoffs|Where-Object {$_.request_id -eq $request.id}|Select-Object -First 1
$handoff=Post "$approval/handoffs/$($handoff.id)/acknowledge" @{expected_revision=$handoff.revision;evidence_reference="CPQ-DOMAIN-ACK-$stamp"} $ah
$quotes=Invoke-RestMethod -Method Get -Uri "$BaseUrl$cpq" -Headers $hh;$source=$quotes.items|Where-Object {$_.id -eq $quote.id}|Select-Object -First 1
[pscustomobject]@{project_id=$ProjectId;workflow_number=$workflow.workflow_number;request_number=$request.request_number;request_status=$request.status;subject_number=$quote.quote_number;subject_revision=$quote.revision;domain_status=$source.status;domain_revision=$source.revision;handoff_number=$handoff.handoff_number;handoff_status=$handoff.status;workflow_author=$hq.user.id;workflow_approver=$agency.user.id;step_one=$agency.user.id;step_two=$client.user.id;ordered_steps=$true;domain_source_unchanged=($source.status -eq "draft" -and $source.revision -eq $quote.revision)}|ConvertTo-Json -Depth 6
