import { useEffect, useState } from "react";
import { CheckCircle2, RefreshCw, Send, Share2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { socialCredentialReferenceApi, type SocialCredentialReferenceRecord } from "@/lib/social-credential-reference-api";
import { socialPageAssetsApi, type SocialPageAssetRecord } from "@/lib/social-page-assets-api";
import { acknowledgeFactorySocialMatrix, bindFactorySocialMatrixPage, createFactorySocialMatrix, listFactorySocialMatrices, publishFactorySocialMatrix, verifyFactorySocialMatrix, type FactorySocialMatrix, type FactorySocialMatrixPublication } from "@/lib/factory-social-matrix-api";

export function SocialMatrixGovernance({projectId}:{projectId:number|null}){
 const [matrices,setMatrices]=useState<FactorySocialMatrix[]>([]);const [publications,setPublications]=useState<FactorySocialMatrixPublication[]>([]);const [pages,setPages]=useState<SocialPageAssetRecord[]>([]);const [credentials,setCredentials]=useState<SocialCredentialReferenceRecord[]>([]);const [key,setKey]=useState("global-social");const [name,setName]=useState("国内外社媒账号矩阵");const [scope,setScope]=useState<"china"|"overseas"|"dual">("dual");const [reference,setReference]=useState("SOCIAL-MATRIX-EVIDENCE-001");
 const load=async()=>{if(!projectId)return;try{const [workspace,pageData,credentialData]=await Promise.all([listFactorySocialMatrices(projectId),socialPageAssetsApi.list(projectId),socialCredentialReferenceApi.list(projectId)]);setMatrices(workspace.matrices);setPublications(workspace.publications);setPages(pageData.items);setCredentials(credentialData.items.filter((item)=>item.status==="active"));}catch(error){toast.error(error instanceof Error?error.message:"社媒矩阵载入失败")}};
 useEffect(()=>{void load()},[projectId]);
 const replace=(item:FactorySocialMatrix)=>setMatrices((rows)=>rows.map((row)=>row.id===item.id?item:row));
 const create=async()=>{if(!projectId)return;try{const item=await createFactorySocialMatrix(projectId,{matrix_key:key,matrix_name:name,market_scope:scope});setMatrices((rows)=>[item,...rows]);toast.success("社媒矩阵草稿已创建") }catch(error){toast.error(error instanceof Error?error.message:"创建失败")}};
 const bind=async(item:FactorySocialMatrix)=>{if(!projectId)return;const page=pages.find((value)=>credentials.some((credential)=>credential.provider===value.provider));const credential=page&&credentials.find((value)=>value.provider===page.provider);if(!page||!credential){toast.error("需先由总部登记同渠道凭据引用，并为主页写入官方或人工核验快照");return}try{await bindFactorySocialMatrixPage(projectId,item.id,{page_asset_id:page.id,credential_reference_id:credential.id});toast.success("已绑定受控主页、凭据引用和指标快照");await load()}catch(error){toast.error(error instanceof Error?error.message:"绑定失败")}};
 const advance=async(item:FactorySocialMatrix)=>{if(!projectId)return;try{if(item.status==="draft")replace(await verifyFactorySocialMatrix(projectId,item.id,{expected_revision:item.revision,reference}));else if(item.status==="verified"){const data=await publishFactorySocialMatrix(projectId,item.id,{expected_revision:item.revision,reference});replace(data.matrix);setPublications((rows)=>[data.publication,...rows])}}catch(error){toast.error(error instanceof Error?error.message:"推进失败");await load()}};
 const acknowledge=async(item:FactorySocialMatrixPublication)=>{if(!projectId)return;try{const value=await acknowledgeFactorySocialMatrix(projectId,item.id,{expected_revision:item.revision,reference});setPublications((rows)=>rows.map((row)=>row.id===item.id?value:row))}catch(error){toast.error(error instanceof Error?error.message:"签收失败")}};
 if(!projectId)return null;
 return <Card className="border-violet-200 bg-violet-50/35" data-social-matrix-page><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><Share2 className="h-4 w-4"/>平台共享社媒矩阵</CardTitle><p className="mt-1 text-sm text-slate-600">只引用主页、受控凭据引用和指标快照；不展示令牌，不发起第三方发布。</p></div><Button size="sm" variant="outline" onClick={()=>void load()}><RefreshCw className="mr-1 h-4 w-4"/>刷新</Button></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 md:grid-cols-4"><Input aria-label="社媒矩阵键" value={key} onChange={(e)=>setKey(e.target.value)}/><Input aria-label="社媒矩阵名称" value={name} onChange={(e)=>setName(e.target.value)}/><select aria-label="社媒矩阵市场范围" value={scope} onChange={(e)=>setScope(e.target.value as typeof scope)} className="h-10 rounded-md border bg-background px-3 text-sm"><option value="dual">国内与海外</option><option value="china">仅国内</option><option value="overseas">仅海外</option></select><Button data-social-matrix-create onClick={()=>void create()}>创建矩阵</Button></div><Input aria-label="社媒矩阵证据编号" value={reference} onChange={(e)=>setReference(e.target.value)}/><div className="grid gap-3 xl:grid-cols-2">{matrices.map((item)=><Card key={item.id} data-social-matrix={item.id} data-social-matrix-status={item.status}><CardHeader className="pb-2"><CardTitle className="flex items-center justify-between gap-2 text-sm"><span>{item.matrix_number} · {item.matrix_name}</span><Badge>{item.status}</Badge></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Button data-social-matrix-bind size="sm" variant="outline" disabled={item.status!=="draft"} onClick={()=>void bind(item)}>绑定主页</Button>{item.status!=="published"?<Button data-social-matrix-advance={item.status} size="sm" onClick={()=>void advance(item)}>{item.status==="verified"?<Send className="mr-1 h-4 w-4"/>:<CheckCircle2 className="mr-1 h-4 w-4"/>}{item.status==="draft"?"独立核验":"发布矩阵"}</Button>:null}</CardContent></Card>)}</div><div className="grid gap-2">{publications.map((item)=><div key={item.id} data-social-matrix-publication={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded border bg-white p-3 text-sm"><span>{item.publication_number} · {item.status}</span>{item.status==="pending"?<Button data-social-matrix-acknowledge size="sm" variant="outline" onClick={()=>void acknowledge(item)}>独立签收</Button>:<span className="text-emerald-700">已签收</span>}</div>)}</div></CardContent></Card>
}
