import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";
export type FactorySocialMatrix={id:string;matrix_number:string;matrix_key:string;matrix_name:string;market_scope:string;status:"draft"|"verified"|"published";revision:number;created_by:string;verified_by?:string|null;published_by?:string|null};
export type FactorySocialMatrixBinding={id:string;matrix_id:string;page_asset_id:string;provider:string;page_reference:string;credential_reference_id:string;latest_snapshot_id:string;created_by:string};
export type FactorySocialMatrixPublication={id:string;matrix_id:string;publication_number:string;version_number:number;status:"pending"|"acknowledged";revision:number;delivery_reference:string;acknowledgement_reference?:string|null};
export type FactorySocialMatrixWorkspace={matrices:FactorySocialMatrix[];bindings:FactorySocialMatrixBinding[];publications:FactorySocialMatrixPublication[];contract:{raw_credentials_stored:boolean;external_publish_dispatched:boolean;source_assets_mutated:boolean}};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`社媒矩阵请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(projectId:number)=>`/api/v1/factory-platform/projects/${projectId}/social-matrices`;
export const listFactorySocialMatrices=(projectId:number)=>request<FactorySocialMatrixWorkspace>(base(projectId));
export const createFactorySocialMatrix=(projectId:number,payload:{matrix_key:string;matrix_name:string;market_scope:"china"|"overseas"|"dual"})=>request<FactorySocialMatrix>(base(projectId),{method:"POST",body:JSON.stringify(payload)});
export const bindFactorySocialMatrixPage=(projectId:number,id:string,payload:{page_asset_id:string;credential_reference_id:string})=>request<FactorySocialMatrixBinding>(`${base(projectId)}/${encodeURIComponent(id)}/bindings`,{method:"POST",body:JSON.stringify(payload)});
export const verifyFactorySocialMatrix=(projectId:number,id:string,payload:{expected_revision:number;reference:string})=>request<FactorySocialMatrix>(`${base(projectId)}/${encodeURIComponent(id)}/verify`,{method:"POST",body:JSON.stringify(payload)});
export const publishFactorySocialMatrix=(projectId:number,id:string,payload:{expected_revision:number;reference:string})=>request<{matrix:FactorySocialMatrix;publication:FactorySocialMatrixPublication}>(`${base(projectId)}/${encodeURIComponent(id)}/publish`,{method:"POST",body:JSON.stringify(payload)});
export const acknowledgeFactorySocialMatrix=(projectId:number,id:string,payload:{expected_revision:number;reference:string})=>request<FactorySocialMatrixPublication>(`${base(projectId)}/publications/${encodeURIComponent(id)}/acknowledge`,{method:"POST",body:JSON.stringify(payload)});
