import {authApi} from "@/lib/auth";import {getAPIBaseURL} from "@/lib/config";
export type ChannelCatalog={id:string;catalog_number:string;catalog_code:string;catalog_name:string;source_release_id:string;source_release_number:string;source_release_version:number;source_document_hash:string;default_locale:string;status:string;authored_by:string;published_by?:string|null;revision:number};
export type ChannelAccount={id:string;account_number:string;platform:string;account_reference:string;credential_reference:string;territory:string;locale:string;currency:string;status:string;requested_by:string;approved_by?:string|null;revision:number};
export type ChannelListing={id:string;listing_number:string;catalog_id:string;account_id:string;account_number:string;external_sku:string;product_name:string;product_identifier:string;source_product_hash:string;price_mode:string;inventory_mode:string;availability_status:string;status:string;created_by:string;validated_by?:string|null;revision:number};
export type ChannelFeedRun={id:string;run_number:string;catalog_id:string;source_document_hash:string;listing_count:number;error_count:number;warning_count:number;payload_hash:string;status:string;executed_by:string};
export type ChannelFeedRelease={id:string;release_number:string;catalog_id:string;run_id:string;version_number:number;payload_hash:string;channel_count:number;listing_count:number;status:string;published_by:string};
export type ChannelPublication={id:string;publication_number:string;catalog_id:string;release_id:string;account_id:string;account_number:string;payload_hash:string;remote_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type ChannelSourceRelease={id:string;release_number:string;version_number:number;document_hash:string;products:Array<{identifier:string;name:string;source_product_hash:string}>};
export type ChannelWorkspace={catalogs:ChannelCatalog[];accounts:ChannelAccount[];listings:ChannelListing[];runs:ChannelFeedRun[];releases:ChannelFeedRelease[];publications:ChannelPublication[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;source_releases:ChannelSourceRelease[];metrics:{approved_channels:number;channel_coverage_percent:number;validated_listings:number;listing_validation_percent:number;passed_feed_runs:number;publication_acknowledgement_percent:number};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`商品Feed请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/channel-feed`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listChannelWorkspace=(p:number)=>request<ChannelWorkspace>(base(p));export const createChannelAccount=(p:number,x:Record<string,unknown>)=>post<ChannelAccount>(`${base(p)}/accounts`,x);export const approveChannelAccount=(p:number,id:string,x:Record<string,unknown>)=>post<ChannelAccount>(`${base(p)}/accounts/${encodeURIComponent(id)}/approve`,x);export const createChannelCatalog=(p:number,x:Record<string,unknown>)=>post<ChannelCatalog>(`${base(p)}/catalogs`,x);export const addChannelListing=(p:number,id:string,x:Record<string,unknown>)=>post<ChannelListing>(`${base(p)}/catalogs/${encodeURIComponent(id)}/listings`,x);export const validateChannelListing=(p:number,id:string,x:Record<string,unknown>)=>post<ChannelListing>(`${base(p)}/listings/${encodeURIComponent(id)}/validate`,x);export const runChannelFeed=(p:number,id:string,x:Record<string,unknown>)=>post<ChannelFeedRun>(`${base(p)}/catalogs/${encodeURIComponent(id)}/feed-runs`,x);export const publishChannelCatalog=(p:number,id:string,x:Record<string,unknown>)=>post<{catalog:ChannelCatalog;release:ChannelFeedRelease;publications:ChannelPublication[]}>(`${base(p)}/catalogs/${encodeURIComponent(id)}/publish`,x);export const acknowledgeChannelPublication=(p:number,id:string,x:Record<string,unknown>)=>post<ChannelPublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
