import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";

export type GeoAeoWorkspace={questions:Array<{id:string;question_number:string;question_reference:string;market:string;locale:string;status:string;revision:number}>;answers:Array<{id:string;version_number:string;question_id:string;question_number:string;manifest_hash:string;status:string;authored_by:string;verified_by:string|null;verification_reference:string|null;revision:number}>;releases:Array<{id:string;release_number:string;version_id:string;version_number:string;target:string;status:string;available:boolean;consumer_receipt_reference:string|null;revision:number}>;evidence:Array<{id:string;subject_id:string;evidence_type:string;evidence_reference:string}>;metrics:Record<string,number>;availability:{application_id:"recommend.geo-aeo";status:"pilot"|"available";release_version:string|null};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit){let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);const response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||`GEO/AEO 请求失败 (${response.status})`);return response.json()as Promise<T>}
const base=(project:number)=>`/api/v1/factory-platform/projects/${project}/geo-aeo`;const post=<T>(path:string,payload:object)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listGeoAeoWorkspace=(project:number)=>request<GeoAeoWorkspace>(base(project));
export const createGeoAeoQuestion=(project:number,payload:{question_reference:string;market:string;locale:string})=>post<GeoAeoWorkspace["questions"][number]>(`${base(project)}/questions`,payload);
export const draftGeoAeoAnswer=(project:number,questionId:string,payload:{answer_manifest:Record<string,unknown>})=>post<GeoAeoWorkspace["answers"][number]>(`${base(project)}/questions/${questionId}/answers`,payload);
export const verifyGeoAeoAnswer=(project:number,answerId:string,payload:{expected_revision:number;reference:string})=>post<GeoAeoWorkspace["answers"][number]>(`${base(project)}/answers/${answerId}/verify`,payload);
export const prepareGeoAeoRelease=(project:number,answerId:string,payload:{target:"content-owner"|"geo-owner"|"marketing-owner";handoff_manifest:Record<string,unknown>})=>post<GeoAeoWorkspace["releases"][number]>(`${base(project)}/answers/${answerId}/releases`,payload);
export const approveGeoAeoRelease=(project:number,releaseId:string,payload:{expected_revision:number;reference:string})=>post<GeoAeoWorkspace["releases"][number]>(`${base(project)}/releases/${releaseId}/approve`,payload);
export const acknowledgeGeoAeoRelease=(project:number,releaseId:string,payload:{expected_revision:number;reference:string})=>post<GeoAeoWorkspace["releases"][number]>(`${base(project)}/releases/${releaseId}/acknowledge`,payload);
