import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";

export type TechnicalSeoAudit={id:string;audit_number:string;site_reference:string;audit_reference:string;public_scope:string;status:string;revision:number};
export type TechnicalSeoSnapshot={id:string;snapshot_number:string;audit_id:string;audit_number:string;manifest_hash:string;status:string;captured_by:string;verified_by:string|null;revision:number};
export type TechnicalSeoRelease={id:string;release_number:string;audit_id:string;snapshot_id:string;snapshot_number:string;target:string;status:string;available:boolean;consumer_receipt_reference:string|null;revision:number};
export type TechnicalSeoWorkspace={audits:TechnicalSeoAudit[];snapshots:TechnicalSeoSnapshot[];releases:TechnicalSeoRelease[];evidence:Array<{id:string;evidence_type:string;evidence_reference:string}>;metrics:Record<string,number>;availability:{application_id:"trust.technical-seo";status:"pilot"|"available";release_version:string|null};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`Technical SEO request failed (${response.status})`);}return response.json() as Promise<T>}
const base=(projectId:number)=>`/api/v1/factory-platform/projects/${projectId}/technical-seo`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listTechnicalSeoWorkspace=(projectId:number)=>request<TechnicalSeoWorkspace>(base(projectId));export const createTechnicalSeoAudit=(projectId:number,payload:Record<string,unknown>)=>post<TechnicalSeoAudit>(`${base(projectId)}/audits`,payload);export const captureTechnicalSeoSnapshot=(projectId:number,auditId:string,payload:Record<string,unknown>)=>post<TechnicalSeoSnapshot>(`${base(projectId)}/audits/${auditId}/snapshots`,payload);export const verifyTechnicalSeoSnapshot=(projectId:number,snapshotId:string,payload:Record<string,unknown>)=>post<TechnicalSeoSnapshot>(`${base(projectId)}/snapshots/${snapshotId}/verify`,payload);export const prepareTechnicalSeoRelease=(projectId:number,snapshotId:string,payload:Record<string,unknown>)=>post<TechnicalSeoRelease>(`${base(projectId)}/snapshots/${snapshotId}/releases`,payload);export const approveTechnicalSeoRelease=(projectId:number,releaseId:string,payload:Record<string,unknown>)=>post<TechnicalSeoRelease>(`${base(projectId)}/releases/${releaseId}/approve`,payload);export const acknowledgeTechnicalSeoRelease=(projectId:number,releaseId:string,payload:Record<string,unknown>)=>post<TechnicalSeoRelease>(`${base(projectId)}/releases/${releaseId}/acknowledge`,payload);
