import {authApi} from "@/lib/auth";import {getAPIBaseURL} from "@/lib/config";
export type DamAsset={id:string;asset_number:string;asset_name:string;asset_type:string;source_asset_id:string;source_display_name:string;source_media_type:string;source_sha256:string;source_size_bytes:number;source_language:string;product_references_json:string[];brand_reference:string;rights_owner_reference:string;status:string;authored_by:string;activated_by?:string|null;revision:number};
export type DamRights={id:string;grant_number:string;grant_code:string;asset_id:string;asset_number:string;territories_json:string[];languages_json:string[];channels_json:string[];valid_from:string;valid_until:string;license_type:string;rights_evidence_reference:string;restrictions?:string|null;status:string;requested_by:string;approved_by?:string|null;revision:number};
export type DamGlossary={id:string;glossary_number:string;glossary_code:string;glossary_name:string;source_locale:string;target_locale:string;current_version:number;status:string;authored_by:string;approved_by?:string|null;revision:number};
export type DamJob={id:string;job_number:string;asset_id:string;asset_number:string;source_sha256:string;rights_grant_id:string;rights_grant_number:string;glossary_id:string;glossary_number:string;glossary_version:number;glossary_hash:string;target_market:string;target_locale:string;channel:string;brief:string;status:string;created_by:string;revision:number};
export type DamRendition={id:string;rendition_number:string;job_id:string;job_number:string;localized_storage_reference:string;localized_sha256:string;translator_reference:string;ai_assisted:boolean;status:string;submitted_by:string;approved_by?:string|null;revision:number};
export type DamPack={id:string;pack_number:string;pack_code:string;pack_name:string;version_number:number;target_market:string;target_locale:string;rendition_ids_json:string[];manifest_hash:string;compliance_assessment_reference:string;tax_reviewed:boolean;privacy_reviewed:boolean;market_access_reviewed:boolean;status:string;created_by:string;published_by?:string|null;revision:number};
export type DamHandoff={id:string;handoff_number:string;pack_id:string;pack_number:string;pack_version:number;manifest_hash:string;consumer:string;delivery_reference:string;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type DamSource={id:string;display_name:string;media_type:string;size_bytes:number;sha256:string;scan_status:string};
export type DamWorkspace={assets:DamAsset[];rights_grants:DamRights[];glossaries:DamGlossary[];glossary_versions:Array<{id:string;glossary_id:string;version_number:number;content_hash:string;status:string}>;jobs:DamJob[];renditions:DamRendition[];reviews:Array<{id:string;review_number:string;rendition_id:string;linguistic_score:number;terminology_score:number;brand_score:number;cultural_score:number;recommendation:string}>;country_packs:DamPack[];handoffs:DamHandoff[];eligible_sources:DamSource[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;metrics:{active_assets:number;rights_coverage_percent:number;approved_renditions:number;localization_approval_percent:number;published_country_packs:number;handoff_acknowledgement_percent:number};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`DAM本地化请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(projectId:number)=>`/api/v1/factory-platform/projects/${projectId}/dam-localization`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listDamWorkspace=(p:number)=>request<DamWorkspace>(base(p));export const adoptDamAsset=(p:number,x:Record<string,unknown>)=>post<DamAsset>(`${base(p)}/assets`,x);export const requestDamRights=(p:number,id:string,x:Record<string,unknown>)=>post<DamRights>(`${base(p)}/assets/${encodeURIComponent(id)}/rights`,x);export const approveDamRights=(p:number,id:string,x:Record<string,unknown>)=>post<{rights:DamRights;asset:DamAsset}>(`${base(p)}/rights/${encodeURIComponent(id)}/approve`,x);
export const createDamGlossary=(p:number,x:Record<string,unknown>)=>post<{glossary:DamGlossary}>(`${base(p)}/glossaries`,x);export const approveDamGlossary=(p:number,id:string,x:Record<string,unknown>)=>post<DamGlossary>(`${base(p)}/glossaries/${encodeURIComponent(id)}/approve`,x);export const createLocalizationJob=(p:number,x:Record<string,unknown>)=>post<DamJob>(`${base(p)}/jobs`,x);export const submitLocalizedRendition=(p:number,id:string,x:Record<string,unknown>)=>post<DamRendition>(`${base(p)}/jobs/${encodeURIComponent(id)}/renditions`,x);export const reviewLocalizedRendition=(p:number,id:string,x:Record<string,unknown>)=>post<{rendition:DamRendition}>(`${base(p)}/renditions/${encodeURIComponent(id)}/review`,x);export const createCountryPack=(p:number,x:Record<string,unknown>)=>post<DamPack>(`${base(p)}/country-packs`,x);export const publishCountryPack=(p:number,id:string,x:Record<string,unknown>)=>post<{pack:DamPack;handoff:DamHandoff}>(`${base(p)}/country-packs/${encodeURIComponent(id)}/publish`,x);export const acknowledgeDamHandoff=(p:number,id:string,x:Record<string,unknown>)=>post<DamHandoff>(`${base(p)}/handoffs/${encodeURIComponent(id)}/acknowledge`,x);
