import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";

export type BuyingCommittee={id:string;committee_number:string;committee_name:string;account_reference:string;opportunity_source_id:string;opportunity_source_number:string;opportunity_source_revision:number;icp_profile_id:string;icp_profile_number:string;status:string;authored_by:string;published_by?:string|null;revision:number};
export type BuyingCommitteeMember={id:string;member_number:string;committee_id:string;role_id:string;role_code:string;role_name:string;contact_signal_id:string;contact_signal_number:string;contact_hint:string;influence_score:number;relationship_strength:string;stance:string;preferred_channel:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type BuyingInfluenceEdge={id:string;edge_number:string;committee_id:string;from_member_id:string;from_member_number:string;to_member_id:string;to_member_number:string;influence_direction:string;strength:string;endpoint_manifest_hash:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type BuyingCommitteeVersion={id:string;version_reference:string;committee_id:string;version_number:number;manifest_hash:string;required_role_count:number;member_count:number;influence_edge_count:number;status:string;published_by:string};
export type BuyingCommitteePublication={id:string;publication_number:string;committee_id:string;version_id:string;version_reference:string;consumer:string;manifest_hash:string;delivery_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type BuyingCommitteeSources={opportunities:Array<{id:string;number:string;account_reference:string;revision:number;status:string;fingerprint:string}>;profiles:Array<{id:string;number:string;name:string;revision:number;definition_hash:string;roles:Array<{id:string;number:string;code:string;name:string;influence_type:string;fingerprint:string}>}>;contacts:Array<{id:string;number:string;account_reference:string;signal_type:string;hint:string;hash:string;revision:number}>};
export type BuyingCommitteeWorkspace={committees:BuyingCommittee[];members:BuyingCommitteeMember[];influence_edges:BuyingInfluenceEdge[];versions:BuyingCommitteeVersion[];publications:BuyingCommitteePublication[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;sources:BuyingCommitteeSources;metrics:{verified_members:number;role_coverage_percent:number;multi_threaded_opportunities:number;verified_influence_edges:number;published_versions:number;handoff_acknowledgement_percent:number};contract:Record<string,boolean>};

async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`采购画像请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/buying-committee`;const post=<T>(path:string,payload:Record<string,unknown>={})=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listBuyingCommitteeWorkspace=(p:number)=>request<BuyingCommitteeWorkspace>(base(p));
export const createBuyingCommittee=(p:number,x:Record<string,unknown>)=>post<BuyingCommittee>(`${base(p)}/committees`,x);
export const addBuyingCommitteeMember=(p:number,id:string,x:Record<string,unknown>)=>post<BuyingCommitteeMember>(`${base(p)}/committees/${encodeURIComponent(id)}/members`,x);
export const verifyBuyingCommitteeMember=(p:number,id:string,x:Record<string,unknown>)=>post<BuyingCommitteeMember>(`${base(p)}/members/${encodeURIComponent(id)}/verify`,x);
export const addBuyingInfluence=(p:number,id:string,x:Record<string,unknown>)=>post<BuyingInfluenceEdge>(`${base(p)}/committees/${encodeURIComponent(id)}/influences`,x);
export const verifyBuyingInfluence=(p:number,id:string,x:Record<string,unknown>)=>post<BuyingInfluenceEdge>(`${base(p)}/influences/${encodeURIComponent(id)}/verify`,x);
export const publishBuyingCommittee=(p:number,id:string,x:Record<string,unknown>)=>post<{committee:BuyingCommittee;version:BuyingCommitteeVersion;publications:BuyingCommitteePublication[]}>(`${base(p)}/committees/${encodeURIComponent(id)}/publish`,x);
export const acknowledgeBuyingPublication=(p:number,id:string,x:Record<string,unknown>)=>post<BuyingCommitteePublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
