import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";

export type RecruitingRequisition={id:string;requisition_number:string;requisition_reference:string;position_id:string;position_number:string;opening_count:number;employment_type:string;work_location:string;target_start_date:string;hiring_reason:string;rubric_version:string;rubric_json:string;status:"draft"|"open"|"closed";authored_by:string;approved_by?:string|null;revision:number};
export type RecruitingCandidate={id:string;candidate_number:string;candidate_reference:string;display_name:string;email:string;country_code:string;source_type:string;source_reference:string;consent_reference:string;privacy_notice_reference:string;retention_until:string;profile_reference:string;status:string;revision:number};
export type RecruitingApplication={id:string;application_number:string;requisition_id:string;requisition_number:string;candidate_id:string;candidate_number:string;application_reference:string;current_stage:string;status:string;submitted_by:string;final_decision?:string|null;decision_reason?:string|null;decided_by?:string|null;revision:number};
export type RecruitingInterview={id:string;interview_number:string;application_id:string;application_number:string;interview_type:string;scheduled_at:string;interviewer_reference:string;rubric_version:string;status:"scheduled"|"completed";scheduled_by:string;completed_by?:string|null;revision:number};
export type RecruitingAssessment={id:string;assessment_number:string;interview_id:string;application_id:string;skills_score:string;evidence_score:string;communication_score:string;integrity_score:string;overall_score:string;transcript_reference:string;citation_references_json:string;assessor_comment:string;ai_assisted:boolean;ai_model_reference?:string|null;ai_autonomous_decision:boolean;assessed_by:string};
export type RecruitingOffer={id:string;offer_number:string;application_id:string;application_number:string;position_id:string;candidate_id:string;offer_reference:string;proposed_start_date:string;compensation_band:string;offer_document_reference:string;status:"draft"|"approved"|"sent"|"accepted"|"declined";authored_by:string;approved_by?:string|null;sent_by?:string|null;responded_by?:string|null;revision:number};
export type RecruitingHandoff={id:string;handoff_number:string;offer_id:string;offer_number:string;candidate_id:string;candidate_number:string;position_id:string;position_number:string;source_reference:string;status:"ready"|"consumed";created_by:string;consumed_employee_id?:string|null;revision:number};
export type RecruitingWorkspace={requisitions:RecruitingRequisition[];candidates:RecruitingCandidate[];applications:RecruitingApplication[];interviews:RecruitingInterview[];assessments:RecruitingAssessment[];offers:RecruitingOffer[];onboarding_handoffs:RecruitingHandoff[];eligible_positions:Array<{id:string;position_number:string;position_code:string;position_title:string;planned_headcount:number;filled_headcount:number;available_openings:number}>;evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;metrics:{open_requisitions:number;active_candidates:number;interviews_completed:number;offers_accepted:number};contract:{system_of_record:string;candidate_consent_required:boolean;marketing_contact_import:boolean;resume_content_stored:boolean;ai_assistance_allowed:boolean;ai_autonomous_decision:boolean;structured_rubric_required:boolean;human_final_decision_required:boolean;accepted_offer_hr_handoff_only:boolean}};

async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`招聘面试中心请求失败（${response.status}）`);}return response.json() as Promise<T>}
const base=(projectId:number)=>`/api/v1/factory-platform/projects/${projectId}/recruiting`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listRecruitingWorkspace=(projectId:number)=>request<RecruitingWorkspace>(base(projectId));
export const createRecruitingRequisition=(projectId:number,payload:Record<string,unknown>)=>post<RecruitingRequisition>(`${base(projectId)}/requisitions`,payload);
export const approveRecruitingRequisition=(projectId:number,id:string,payload:Record<string,unknown>)=>post<RecruitingRequisition>(`${base(projectId)}/requisitions/${encodeURIComponent(id)}/approve`,payload);
export const createRecruitingCandidate=(projectId:number,payload:Record<string,unknown>)=>post<RecruitingCandidate>(`${base(projectId)}/candidates`,payload);
export const submitRecruitingApplication=(projectId:number,payload:Record<string,unknown>)=>post<RecruitingApplication>(`${base(projectId)}/applications`,payload);
export const scheduleRecruitingInterview=(projectId:number,payload:Record<string,unknown>)=>post<RecruitingInterview>(`${base(projectId)}/interviews`,payload);
export const completeRecruitingInterview=(projectId:number,id:string,payload:Record<string,unknown>)=>post<{interview:RecruitingInterview;assessment:RecruitingAssessment}>(`${base(projectId)}/interviews/${encodeURIComponent(id)}/complete`,payload);
export const decideRecruitingApplication=(projectId:number,id:string,payload:Record<string,unknown>)=>post<RecruitingApplication>(`${base(projectId)}/applications/${encodeURIComponent(id)}/decide`,payload);
export const createRecruitingOffer=(projectId:number,payload:Record<string,unknown>)=>post<RecruitingOffer>(`${base(projectId)}/offers`,payload);
export const approveRecruitingOffer=(projectId:number,id:string,payload:Record<string,unknown>)=>post<RecruitingOffer>(`${base(projectId)}/offers/${encodeURIComponent(id)}/approve`,payload);
export const sendRecruitingOffer=(projectId:number,id:string,payload:Record<string,unknown>)=>post<RecruitingOffer>(`${base(projectId)}/offers/${encodeURIComponent(id)}/send`,payload);
export const respondRecruitingOffer=(projectId:number,id:string,payload:Record<string,unknown>)=>post<RecruitingOffer>(`${base(projectId)}/offers/${encodeURIComponent(id)}/respond`,payload);
