import {authApi} from "@/lib/auth";import {getAPIBaseURL} from "@/lib/config";
export type CustomerTimeline={id:string;timeline_number:string;timeline_name:string;account_reference:string;scope:string;status:string;authored_by:string;published_by?:string|null;revision:number};
export type CustomerTimelineEvent={id:string;event_number:string;timeline_id:string;timeline_number:string;account_reference:string;event_type:string;occurred_at:string;intent_level:string;source_type:string;source_id:string;source_number:string;source_revision:number;source_status:string;source_fingerprint:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type CustomerTimelineVersion={id:string;version_reference:string;timeline_id:string;version_number:number;manifest_hash:string;event_count:number;source_type_count:number;high_intent_event_count:number;status:string;published_by:string};
export type CustomerTimelinePublication={id:string;publication_number:string;timeline_id:string;version_id:string;version_reference:string;consumer:string;manifest_hash:string;delivery_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type CustomerTimelineCheckpoint={id:string;checkpoint_number:string;timeline_id:string;checkpoint_code:string;event_id:string;event_number:string;occurred_at:string;note?:string|null;created_by:string};
export type CustomerTimelineSource={source_type:string;source_id:string;source_number:string;account_reference:string;event_type:string;occurred_at:string;intent_level:string;revision:number;status:string;fingerprint:string};
export type CustomerTimelineWorkspace={timelines:CustomerTimeline[];events:CustomerTimelineEvent[];versions:CustomerTimelineVersion[];publications:CustomerTimelinePublication[];checkpoints:CustomerTimelineCheckpoint[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;sources:CustomerTimelineSource[];metrics:{verified_events:number;source_coverage_percent:number;high_intent_events:number;journey_checkpoints:number;published_versions:number;handoff_acknowledgement_percent:number};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`行为时间线请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/customer-timeline`;const post=<T>(path:string,payload:Record<string,unknown>={})=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listCustomerTimelineWorkspace=(p:number)=>request<CustomerTimelineWorkspace>(base(p));export const createCustomerTimeline=(p:number,x:Record<string,unknown>)=>post<CustomerTimeline>(`${base(p)}/timelines`,x);export const addCustomerTimelineEvent=(p:number,id:string,x:Record<string,unknown>)=>post<CustomerTimelineEvent>(`${base(p)}/timelines/${encodeURIComponent(id)}/events`,x);export const verifyCustomerTimelineEvent=(p:number,id:string,x:Record<string,unknown>)=>post<CustomerTimelineEvent>(`${base(p)}/events/${encodeURIComponent(id)}/verify`,x);export const addCustomerTimelineCheckpoint=(p:number,id:string,x:Record<string,unknown>)=>post<CustomerTimelineCheckpoint>(`${base(p)}/timelines/${encodeURIComponent(id)}/checkpoints`,x);export const publishCustomerTimeline=(p:number,id:string,x:Record<string,unknown>)=>post<{timeline:CustomerTimeline;version:CustomerTimelineVersion;publications:CustomerTimelinePublication[]}>(`${base(p)}/timelines/${encodeURIComponent(id)}/publish`,x);export const acknowledgeCustomerTimelinePublication=(p:number,id:string,x:Record<string,unknown>)=>post<CustomerTimelinePublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
