import {authApi} from "@/lib/auth";import {getAPIBaseURL} from "@/lib/config";
export type KnowledgeGraph={id:string;graph_number:string;graph_code:string;graph_name:string;scope:string;default_locale:string;objective:string;current_version:number;status:string;authored_by:string;published_by?:string|null;revision:number};
export type KnowledgeEntity={id:string;entity_number:string;graph_id:string;entity_key:string;entity_type:string;canonical_name:string;aliases_json:string[];properties_json:Record<string,unknown>;locale:string;source_type:string;source_id:string;source_number:string;source_revision:number;source_status:string;source_fingerprint:string;evidence_reference:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type KnowledgeRelation={id:string;relation_number:string;graph_id:string;subject_entity_id:string;predicate:string;object_entity_id:string;evidence_reference:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type KnowledgeVersion={id:string;version_reference:string;graph_id:string;version_number:number;entity_manifest_json:Array<Record<string,string>>;relation_manifest_json:Array<Record<string,string>>;manifest_hash:string;entity_type_coverage_json:string[];status:string;published_by:string};
export type KnowledgePublication={id:string;publication_number:string;graph_id:string;version_id:string;version_number:number;manifest_hash:string;consumer:string;delivery_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type KnowledgeSource={source_type:string;source_id:string;source_number:string;source_status:string;source_fingerprint:string;suggested_name:string;allowed_entity_types:string[]};
export type KnowledgeWorkspace={graphs:KnowledgeGraph[];entities:KnowledgeEntity[];relations:KnowledgeRelation[];versions:KnowledgeVersion[];publications:KnowledgePublication[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;source_candidates:KnowledgeSource[];metrics:{verified_entities:number;entity_type_completeness_percent:number;verified_relations:number;relation_verification_percent:number;published_graph_versions:number;publication_acknowledgement_percent:number};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`知识图谱请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/knowledge-graph`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listKnowledgeWorkspace=(p:number)=>request<KnowledgeWorkspace>(base(p));export const createKnowledgeGraph=(p:number,x:Record<string,unknown>)=>post<KnowledgeGraph>(`${base(p)}/graphs`,x);export const addKnowledgeEntity=(p:number,id:string,x:Record<string,unknown>)=>post<KnowledgeEntity>(`${base(p)}/graphs/${encodeURIComponent(id)}/entities`,x);export const verifyKnowledgeEntity=(p:number,id:string,x:Record<string,unknown>)=>post<KnowledgeEntity>(`${base(p)}/entities/${encodeURIComponent(id)}/verify`,x);export const addKnowledgeRelation=(p:number,id:string,x:Record<string,unknown>)=>post<KnowledgeRelation>(`${base(p)}/graphs/${encodeURIComponent(id)}/relations`,x);export const verifyKnowledgeRelation=(p:number,id:string,x:Record<string,unknown>)=>post<KnowledgeRelation>(`${base(p)}/relations/${encodeURIComponent(id)}/verify`,x);export const publishKnowledgeGraph=(p:number,id:string,x:Record<string,unknown>)=>post<{graph:KnowledgeGraph;version:KnowledgeVersion;publication:KnowledgePublication}>(`${base(p)}/graphs/${encodeURIComponent(id)}/publish`,x);export const acknowledgeKnowledgePublication=(p:number,id:string,x:Record<string,unknown>)=>post<KnowledgePublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
