import {authApi} from "@/lib/auth";
import {getAPIBaseURL} from "@/lib/config";

export type IdentityConsent={id:string;consent_number:string;subject_reference:string;account_reference:string;consent_reference:string;lawful_basis:string;purposes_json:string[];source_event_hash:string;valid_from:string;expires_at:string;status:string;requested_by:string;approved_by?:string|null;revoked_by?:string|null;revision:number};
export type IdentitySignal={id:string;signal_number:string;consent_id:string;consent_number:string;account_reference:string;signal_type:string;identifier_hash:string;display_hint:string;source_type:string;source_reference:string;source_revision:number;source_fingerprint:string;status:string;captured_by:string;verified_by?:string|null;revision:number};
export type IdentityMatchCase={id:string;case_number:string;account_reference:string;signal_ids_json:string[];signal_manifest_hash:string;match_method:string;match_score:number;reasons_json:string[];status:string;proposed_by:string;decided_by?:string|null;revision:number};
export type GoldenProfile={id:string;profile_number:string;account_reference:string;match_case_id:string;match_case_number:string;member_signal_ids_json:string[];source_manifest_json:Record<string,unknown>;source_manifest_hash:string;status:string;authored_by:string;published_by?:string|null;revision:number};
export type GoldenProfileVersion={id:string;version_number_ref:string;profile_id:string;profile_number:string;version_number:number;manifest_json:Record<string,unknown>;manifest_hash:string;status:string;published_by:string};
export type IdentityPublication={id:string;publication_number:string;profile_id:string;version_id:string;version_number_ref:string;consumer_system:string;manifest_hash:string;remote_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type IdentityWorkspace={consents:IdentityConsent[];signals:IdentitySignal[];match_cases:IdentityMatchCase[];profiles:GoldenProfile[];versions:GoldenProfileVersion[];publications:IdentityPublication[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;metrics:{active_consents:number;verified_signals:number;identity_match_percent:number;approved_matches:number;published_profiles:number;handoff_acknowledgement_percent:number};contract:Record<string,boolean>};

async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`身份合并请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/identity-resolution`;const post=<T>(path:string,payload:Record<string,unknown>={})=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listIdentityWorkspace=(p:number)=>request<IdentityWorkspace>(base(p));
export const createIdentityConsent=(p:number,x:Record<string,unknown>)=>post<IdentityConsent>(`${base(p)}/consents`,x);
export const approveIdentityConsent=(p:number,id:string,x:Record<string,unknown>)=>post<IdentityConsent>(`${base(p)}/consents/${encodeURIComponent(id)}/approve`,x);
export const revokeIdentityConsent=(p:number,id:string,x:Record<string,unknown>)=>post<IdentityConsent>(`${base(p)}/consents/${encodeURIComponent(id)}/revoke`,x);
export const createIdentitySignal=(p:number,x:Record<string,unknown>)=>post<IdentitySignal>(`${base(p)}/signals`,x);
export const verifyIdentitySignal=(p:number,id:string,x:Record<string,unknown>)=>post<IdentitySignal>(`${base(p)}/signals/${encodeURIComponent(id)}/verify`,x);
export const proposeIdentityMatch=(p:number,x:Record<string,unknown>)=>post<IdentityMatchCase>(`${base(p)}/matches`,x);
export const decideIdentityMatch=(p:number,id:string,x:Record<string,unknown>)=>post<IdentityMatchCase>(`${base(p)}/matches/${encodeURIComponent(id)}/decide`,x);
export const createGoldenProfile=(p:number,id:string)=>post<GoldenProfile>(`${base(p)}/matches/${encodeURIComponent(id)}/profiles`);
export const publishGoldenProfile=(p:number,id:string,x:Record<string,unknown>)=>post<{profile:GoldenProfile;version:GoldenProfileVersion;publications:IdentityPublication[]}>(`${base(p)}/profiles/${encodeURIComponent(id)}/publish`,x);
export const acknowledgeIdentityPublication=(p:number,id:string,x:Record<string,unknown>)=>post<IdentityPublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
