import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";
export type PriceWatch={id:string;watch_number:string;product_reference:string;product_name:string;market_country:string;channel:string;currency:string;own_reference_price:string;scope_note:string;status:string;revision:number};
export type CompetitiveOffer={id:string;snapshot_number:string;watch_id:string;competitor_name:string;competitor_offer_reference:string;offer_type:string;offer_price:string;freight_price:string;landed_price:string;source_system:string;source_revision:string;status:string;revision:number};
export type PriceDecision={id:string;decision_number:string;watch_id:string;low_landed_price:string;median_landed_price:string;high_landed_price:string;price_index:string;recommendation:string;boundary_note:string;status:string;revision:number};
export type PriceRelease={id:string;release_number:string;release_version:string;decision_id:string;manifest_hash:string;support_until:string;status:string;available:boolean;revision:number};
export type CompetitivePricingWorkspace={watches:PriceWatch[];offers:CompetitiveOffer[];decisions:PriceDecision[];releases:PriceRelease[];evidence:Array<{id:string;subject_type:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;metrics:{price_watches:number;verified_offer_percent:number;approved_decisions:number;available_releases:number;latest_price_index:string|null};availability:{application_id:string;status:"pilot"|"available";release_version:string|null;support_until:string|null};contract:Record<string,unknown>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`竞价情报请求失败（${response.status}）`);}return response.json() as Promise<T>}
const base=(project:number)=>`/api/v1/factory-platform/projects/${project}/competitive-pricing`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listCompetitivePricing=(project:number)=>request<CompetitivePricingWorkspace>(base(project));export const createPriceWatch=(project:number,payload:Record<string,unknown>)=>post<PriceWatch>(`${base(project)}/watches`,payload);export const createCompetitiveOffer=(project:number,watch:string,payload:Record<string,unknown>)=>post<CompetitiveOffer>(`${base(project)}/watches/${encodeURIComponent(watch)}/offers`,payload);export const verifyCompetitiveOffer=(project:number,offer:string,payload:Record<string,unknown>)=>post<CompetitiveOffer>(`${base(project)}/offers/${encodeURIComponent(offer)}/verify`,payload);export const createPriceDecision=(project:number,watch:string,payload:Record<string,unknown>)=>post<PriceDecision>(`${base(project)}/watches/${encodeURIComponent(watch)}/decisions`,payload);export const reviewPriceDecision=(project:number,decision:string,payload:Record<string,unknown>)=>post<PriceDecision>(`${base(project)}/decisions/${encodeURIComponent(decision)}/review`,payload);export const preparePriceRelease=(project:number,decision:string,payload:Record<string,unknown>)=>post<PriceRelease>(`${base(project)}/decisions/${encodeURIComponent(decision)}/releases`,payload);export const approvePriceRelease=(project:number,release:string,payload:Record<string,unknown>)=>post<PriceRelease>(`${base(project)}/releases/${encodeURIComponent(release)}/approve`,payload);
