import {authApi} from "@/lib/auth";import {getAPIBaseURL} from "@/lib/config";
export type AccountGraph={id:string;graph_number:string;graph_code:string;graph_name:string;scope:string;status:string;authored_by:string;published_by?:string|null;revision:number};
export type AccountGraphNode={id:string;node_number:string;graph_id:string;node_type:string;display_name:string;account_reference:string;country_code?:string|null;source_type:string;source_id:string;source_number:string;source_revision:number;source_status:string;source_fingerprint:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type AccountGraphEdge={id:string;edge_number:string;graph_id:string;from_node_id:string;from_node_number:string;to_node_id:string;to_node_number:string;relation_type:string;strength:string;evidence_reference:string;endpoint_manifest_hash:string;status:string;created_by:string;verified_by?:string|null;revision:number};
export type AccountGraphVersion={id:string;version_reference:string;graph_id:string;version_number:number;manifest_hash:string;node_count:number;edge_count:number;status:string;published_by:string};
export type AccountGraphPublication={id:string;publication_number:string;graph_id:string;version_id:string;version_reference:string;consumer:string;manifest_hash:string;delivery_reference:string;consumer_mutated:boolean;status:string;created_by:string;acknowledged_by?:string|null;revision:number};
export type AccountGraphSource={source_type:string;source_id:string;source_number:string;node_type:string;display_name:string;account_reference:string;country_code?:string|null;revision:number;status:string;fingerprint:string;related_source_id?:string|null};
export type AccountGraphWorkspace={graphs:AccountGraph[];nodes:AccountGraphNode[];edges:AccountGraphEdge[];versions:AccountGraphVersion[];publications:AccountGraphPublication[];evidence:Array<{id:string;subject_type:string;subject_id:string;evidence_type:string;evidence_reference:string;recorded_by:string}>;sources:AccountGraphSource[];metrics:{verified_nodes:number;source_type_coverage_percent:number;verified_edges:number;relation_verification_percent:number;published_versions:number;handoff_acknowledgement_percent:number};contract:Record<string,boolean>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(response.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);response=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});}if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(typeof body.detail==="string"?body.detail:`企业关系请求失败（${response.status}）`)}return response.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/account-graph`;const post=<T>(path:string,payload:Record<string,unknown>={})=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listAccountGraphWorkspace=(p:number)=>request<AccountGraphWorkspace>(base(p));export const createAccountGraph=(p:number,x:Record<string,unknown>)=>post<AccountGraph>(`${base(p)}/graphs`,x);export const addAccountGraphNode=(p:number,id:string,x:Record<string,unknown>)=>post<AccountGraphNode>(`${base(p)}/graphs/${encodeURIComponent(id)}/nodes`,x);export const verifyAccountGraphNode=(p:number,id:string,x:Record<string,unknown>)=>post<AccountGraphNode>(`${base(p)}/nodes/${encodeURIComponent(id)}/verify`,x);export const addAccountGraphEdge=(p:number,id:string,x:Record<string,unknown>)=>post<AccountGraphEdge>(`${base(p)}/graphs/${encodeURIComponent(id)}/edges`,x);export const verifyAccountGraphEdge=(p:number,id:string,x:Record<string,unknown>)=>post<AccountGraphEdge>(`${base(p)}/edges/${encodeURIComponent(id)}/verify`,x);export const publishAccountGraph=(p:number,id:string,x:Record<string,unknown>)=>post<{graph:AccountGraph;version:AccountGraphVersion;publications:AccountGraphPublication[]}>(`${base(p)}/graphs/${encodeURIComponent(id)}/publish`,x);export const acknowledgeAccountGraphPublication=(p:number,id:string,x:Record<string,unknown>)=>post<AccountGraphPublication>(`${base(p)}/publications/${encodeURIComponent(id)}/acknowledge`,x);
