import { authApi } from "@/lib/auth";
import { getAPIBaseURL } from "@/lib/config";
export type BrandProfile={id:string;profile_number:string;brand_name:string;market_scope:string;audience:string;positioning:string;value_promise:string;tone:string;status:string;current_version:number;revision:number};
export type BrandClaim={id:string;claim_number:string;profile_id:string;claim_type:string;claim_text:string;evidence_reference:string;status:string;revision:number};
export type BrandRelease={id:string;release_number:string;profile_id:string;release_version:string;manifest_hash:string;support_until:string;status:string;available:boolean;revision:number};
export type BrandWorkspace={profiles:BrandProfile[];claims:BrandClaim[];versions:Array<{profile_id:string;definition_hash:string;status:string}>;releases:BrandRelease[];evidence:Array<{id:string;evidence_type:string}>;metrics:{brand_profiles:number;verified_claim_percent:number;active_profiles:number;available_releases:number};availability:{application_id:string;status:"pilot"|"available";release_version:string|null;support_until:string|null};contract:Record<string,boolean|number>};
async function request<T>(path:string,init?:RequestInit):Promise<T>{let token=authApi.getStoredToken();if(!token&&await authApi.restoreLocalDemoSession("hq"))token=authApi.getStoredToken();const headers=new Headers(init?.headers);headers.set("Content-Type","application/json");if(token)headers.set("Authorization",`Bearer ${token}`);let r=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers});if(r.status===401&&await authApi.restoreLocalDemoSession("hq")){const restored=authApi.getStoredToken();if(restored)headers.set("Authorization",`Bearer ${restored}`);r=await fetch(`${getAPIBaseURL()}${path}`,{...init,headers})}if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(typeof b.detail==="string"?b.detail:`Brand request failed (${r.status})`)}return r.json() as Promise<T>}
const base=(p:number)=>`/api/v1/factory-platform/projects/${p}/brand-studio`;const post=<T>(path:string,payload:Record<string,unknown>)=>request<T>(path,{method:"POST",body:JSON.stringify(payload)});
export const listBrandWorkspace=(p:number)=>request<BrandWorkspace>(base(p));export const createBrandProfile=(p:number,payload:Record<string,unknown>)=>post<{profile:BrandProfile}>(`${base(p)}/profiles`,payload);export const createBrandClaim=(p:number,id:string,payload:Record<string,unknown>)=>post<BrandClaim>(`${base(p)}/profiles/${id}/claims`,payload);export const verifyBrandClaim=(p:number,id:string,payload:Record<string,unknown>)=>post<BrandClaim>(`${base(p)}/claims/${id}/verify`,payload);export const approveBrandProfile=(p:number,id:string,payload:Record<string,unknown>)=>post<BrandProfile>(`${base(p)}/profiles/${id}/approve`,payload);export const prepareBrandRelease=(p:number,id:string,payload:Record<string,unknown>)=>post<BrandRelease>(`${base(p)}/profiles/${id}/releases`,payload);export const approveBrandRelease=(p:number,id:string,payload:Record<string,unknown>)=>post<BrandRelease>(`${base(p)}/releases/${id}/approve`,payload);
